"""Relance de recherche du 07/08/2026 - toutes sources CLAUDE.md."""

import add_offre

add_offre.COLS = add_offre.COLS + ['Date trouvée', 'Date publiée']

D = '07/08/2026'

OFFRES = [
    # ---------------- SIRH / SAP ----------------
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Global Tech HR Domain Manager (F/M/X)',
        'Entreprise': 'Sephora (LVMH)', 'Source': 'jobs.sephora.com / LinkedIn',
        'Contrat': 'CDI', 'Localisation': 'Neuilly-sur-Seine (92)', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Pilotage du domaine SI RH au niveau groupe, rattache au Corporate Domain Director de la DSI. Equipe de 2 chefs de projet internes et 2 consultants externes entre Neuilly et Casablanca. Contexte international grand compte beaute proche de L'Oreal ; le fit est eleve sur la partie gouvernance SI RH et pilotage d'equipes mixtes internes/externes.",
        'Lien': 'https://jobs.sephora.com/France/job/NEUILLY-SUR-SEINE-CDI-Global-Tech-HR-Domain-Manager-(FMX)/1341168455/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '90-110 K€',
        'Date trouvée': D, 'Date publiée': '04/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': "Consultant Confirme Integration SAP SuccessFactors (F/H) - France",
        'Entreprise': 'ACT-ON HRIS', 'Source': 'LinkedIn',
        'Contrat': 'CDI', 'Localisation': 'Neuilly-sur-Seine (92)', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Integration SAP SuccessFactors chez un pure player SIRH francais ; annonce publiee il y a moins de 24h. Gaetan a deja postule chez ACT-ON en juillet (poste HRIS) ; relance possible sur ce poste plus technique. Plusieurs autres postes ouverts chez eux (AMOA SIRH Lyon, Lille, Nantes, GTA, SAP HR confirme).",
        'Lien': 'https://fr.linkedin.com/jobs/successfactors-emplois-r%C3%A9gion-de-paris-france',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '06/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Consultant HR Digital & IA',
        'Entreprise': 'Sia (ex-Sia Partners)', 'Source': 'sia-partners.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Croisement exact des deux cibles de Gaetan : strategie SI RH, choix de solution SIRH, data et IA appliquees aux RH, pilotage de transformations digitales RH et gouvernance de la donnee RH. Sia recrute aussi des Manager HR Digital & IA a Paris et des consultants HR & Transformation a Lyon, Marseille et Paris.",
        'Lien': 'https://www.sia-partners.com/fr/career/consultant-hr-digital-ia',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '75-90 K€',
        'Date trouvée': D, 'Date publiée': '31/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef(fe) de projet SIRH F/H',
        'Entreprise': 'CGI', 'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': "Jusqu'a 3 j/semaine",
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Conseil amont aupres des DRH et DSI, animation d'ateliers de recueil de besoins, audit et choix de solution, redaction de cahiers des charges, definition de trajectoires SIRH et pilotage projet incluant budget et coordination MOA/MOE/editeurs. Correspond au coeur du parcours de Gaetan. Un poste equivalent est ouvert a Nantes.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/cgi/jobs/chef-fe-de-projet-sirh-f-h_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '06/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant(e) fonctionnel SIRH (F/H)',
        'Entreprise': 'CGI', 'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Conseil RH et metier aupres des directions generales de grands groupes et d'administrations, assistance a la mise en oeuvre SIRH, expertise fonctionnelle et applicative en phase de production, avec ouverture au developpement commercial et au management d'equipe.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/cgi/jobs/consultant-sirh-f-h-transport-secteur-public-et-hr_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '03/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': "Consultant(e) en Gestion des talents / SIRH a l'international H/F",
        'Entreprise': 'mc2i', 'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI', 'Localisation': 'Paris 8e', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Cabinet independant de 1000 personnes. Grands projets SIRH internationaux, gestion des talents, contribution au developpement de l'offre SIRH. Le deploiement multi-pays et la gestion des talents recouvrent directement les dix ans sur le compte L'Oreal mondial.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/mc2i/jobs/consultant-en-gestion-des-talents-sirh-a-l-international-h-f_paris-8e-arrondissement_MC2I_Z9qdR7o',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '05/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant Manager / Senior Manager Change - People Strategy & Transformation F/H',
        'Entreprise': 'KPMG France', 'Source': 'emplois.kpmg.fr',
        'Contrat': 'CDI', 'Localisation': 'Courbevoie (92)', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Transformation RH et conduite du changement avec exposition aux solutions SIRH dont SAP SuccessFactors. Niveau Manager ou Senior Manager coherent avec 15 ans d'experience. Le site de Courbevoie reste un frein depuis Anglet, a negocier.",
        'Lien': 'https://emplois.kpmg.fr/emploi/courbevoie/consultant-manager-senior-manager-change-people-strategy-and-transformation-f-h/2913/15249903232',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '85-100 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'HRIS Learning Solution Technical Project Director M/F',
        'Entreprise': 'CMA CGM', 'Source': 'jobs.cmacgm-group.com',
        'Contrat': 'CDI', 'Localisation': 'Paris (75)', 'Remote': 'NC',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Direction technique de projet sur la solution Learning du SIRH d'un groupe present dans 160 pays avec 155 000 collaborateurs. Le pilotage de projet SIRH a l'echelle mondiale est le coeur du parcours ; le module Learning fait partie du perimetre SuccessFactors connu.",
        'Lien': 'https://jobs.cmacgm-group.com/job/paris-75-hris-learning-solution-technical-project-director-mf/1290488301',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'HRIS Technical Manager',
        'Entreprise': 'CMA CGM', 'Source': 'jobs.cmacgm-group.com',
        'Contrat': 'CDI', 'Localisation': 'Marseille (13)', 'Remote': 'NC',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Supervision des aspects techniques du portefeuille de solutions RH, integration, maintenance et performance. Marseille reste eloigne d'Anglet ; le profil de Gaetan est plus fonctionnel que technique.",
        'Lien': 'https://jobs.cmacgm-group.com/job/Marseille-HRIS-Technical-Manager/1248665101/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '75-90 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Global SAP HRIS Manager (SuccessFactors) - Allemagne',
        'Entreprise': 'Eursap (client confidentiel)', 'Source': 'eursap.eu',
        'Contrat': 'CDI', 'Localisation': 'Allemagne', 'Remote': 'Sur site',
        'Salaire / TJM': "Jusqu'a 145 000 €/an + bonus", 'Durée mission': 'NC',
        'Fit / Notes': "Reference 34522-DE, prise de poste au 01/09/2026. Intitule quasi identique a la cible Group HRIS Manager et remuneration tres au-dessus de la fourchette visee. Le frein est la presence sur site en Allemagne ; a tester en demandant un arrangement remote depuis la France.",
        'Lien': 'https://eursap.eu/jobs/global-sap-hris-manager-successfactors-34522-de',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.pdf', 'Prétention': '120-145 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Global SAP HRIS Manager (SuccessFactors) - Tchequie',
        'Entreprise': 'Eursap (client confidentiel)', 'Source': 'eursap.eu',
        'Contrat': 'CDI', 'Localisation': 'Tchequie', 'Remote': 'Sur site',
        'Salaire / TJM': "Jusqu'a 200 000 CZK/mois", 'Durée mission': 'NC',
        'Fit / Notes': "Reference 34522-CZ, meme poste que la version allemande sur un autre site. Le contenu correspond a la cible Group HRIS Manager ; la localisation est le seul obstacle serieux.",
        'Lien': 'https://eursap.eu/jobs/global-sap-hris-manager-successfactors-34522-cz',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.pdf', 'Prétention': 'NC',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant SAP HCM Paie senior',
        'Entreprise': 'Strada (ex-Alight / ex-NGA)', 'Source': 'careers.alight.com/strada',
        'Contrat': 'CDI', 'Localisation': 'Colombes (92)', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Premier partenaire mondial SAP HR, 8000 experts et 1400 clients dans 33 pays. Poste senior sur SAP HCM Paie ; la paie francaise reste un angle moins couvert par Gaetan que le core HR, a assumer en entretien.",
        'Lien': 'https://careers.alight.com/strada/us/en/job/ALIGUSR32021STRADAENUS/Consultant-SAP-HCM-Paie-senior',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '24/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Manager SIRH',
        'Entreprise': 'HR DNA', 'Source': 'free-work.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Partiel',
        'Salaire / TJM': '60-110 K€/an', 'Durée mission': 'NC',
        'Fit / Notes': "Poste a dominante developpement commercial : prospection de comptes, construction d'offres de services, management de consultants et participation aux decisions strategiques. Dix ans d'experience minimum demandes. La fourchette haute depasse la cible ; l'angle commercial rejoint le profil Account Manager.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/manager-sirh-11',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '85-100 K€',
        'Date trouvée': D, 'Date publiée': '06/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Consultant Transformation RH - Target Operating Model & Core HR',
        'Entreprise': 'NOVAMINDS', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'Île-de-France', 'Remote': 'Partiel',
        'Salaire / TJM': '650 €/j', 'Durée mission': '4 mois renouvelables',
        'Fit / Notes': "Definition et mise en oeuvre d'un Target Operating Model pour un CSP RH, avec coordination du deploiement local d'un Core HR dans un environnement multi-entites aux conventions collectives variees. Le pilotage multi-entites correspond au perimetre 40 pays gere chez L'Oreal.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant/senior-consultant-transformation-rh-target-operating-model-core-hr',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '03/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant Transformation RH - Core HR',
        'Entreprise': 'VISIAN', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': 'Partiel',
        'Salaire / TJM': 'NC', 'Durée mission': '1 an renouvelable',
        'Fit / Notes': "Mise en place d'un modele operationnel cible pour le CSP RH d'un grand groupe bancaire couvrant 60 000 collaborateurs et 23 entites : definition de la gouvernance, analyse de scenarios d'organisation et harmonisation des processus. Demarrage des que possible.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant/consultant-transformation-rh-core-hr',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '04/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Technico-Fonctionnel SAP HCM French Payroll',
        'Entreprise': 'Apps IT Limited', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'France', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': '6 mois',
        'Fit / Notes': "Une des rares missions SAP HCM annoncees en 100% remote, ce qui leve la contrainte geographique depuis Anglet. Perimetre paie francaise, moins central dans le parcours de Gaetan que le core HR et le deploiement international.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/technico-fonctionnel-sap-hcm-french-payroll',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '17/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de Projet SIRH (H/F)',
        'Entreprise': 'HAYS France', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'Bordeaux (33)', 'Remote': 'Partiel',
        'Salaire / TJM': 'NC', 'Durée mission': '6 mois',
        'Fit / Notes': "Bordeaux est la grande ville la plus accessible depuis Anglet, ce qui rend un rythme hybride realiste sur cette mission. Chef de projet SIRH correspond directement a la cible.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/autre/chef-de-projet-sirh-h-f-79',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '04/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chef de projet MOE SIRH H/F',
        'Entreprise': 'HAYS France', 'Source': 'free-work.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'NC',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Chef de projet cote MOE, donc plus proche de la realisation technique que de la MOA ou Gaetan est le plus a l'aise. Poste publie le 06/08/2026.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/chef-de-projet-moe-sirh-h-f-1',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '06/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': "Gestionnaire d'Application SIRH",
        'Entreprise': 'Montreal Associates', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'Bretagne', 'Remote': 'Partiel',
        'Salaire / TJM': '400-600 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "Gestion applicative SIRH, poste plus run que projet. Publie le 05/08/2026. Le TJM est en dessous de la fourchette habituelle mais reste a considerer.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/gestionnaire-dapplication-sirh',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '600 €/j',
        'Date trouvée': D, 'Date publiée': '05/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager SIRH / Chef de Projet (Oracle HCM) (H/F)',
        'Entreprise': 'Freelance.com', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'Île-de-France', 'Remote': 'Partiel',
        'Salaire / TJM': 'NC', 'Durée mission': '3 ans',
        'Fit / Notes': "Duree de trois ans, rare et interessante pour la stabilite. Le socle est Oracle HCM plutot que SAP, ce qui demande un transfert de competences ; la posture Product Owner SIRH correspond en revanche a une des cibles.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/administrateur-de-base-de-donnee-oracle-sybase/product-manager-sirh-chef-de-projet-sirh-oracle-hcm-h-f',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '05/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP ECC HCM Time Management Senior (H/F)',
        'Entreprise': 'PREREQUIS', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'La Garenne-Colombes (92)', 'Remote': 'Partiel',
        'Salaire / TJM': '600-650 €/j', 'Durée mission': '4 mois',
        'Fit / Notes': "Gestion des temps SAP ECC HCM, module deja pratique sur le compte L'Oreal. Mission courte en region parisienne.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-ecc-hcm-time-management-senior-h-f',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '01/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Expert Technico-Fonctionnel SAP HCM',
        'Entreprise': 'INFOTEL CONSEIL', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'Roissy-en-France (95)', 'Remote': 'Partiel',
        'Salaire / TJM': '540-750 €/j', 'Durée mission': '3 mois',
        'Fit / Notes': "Expertise SAP HCM technico-fonctionnelle, fourchette de TJM alignee sur la cible freelance. Mission courte.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/expert-technico-fonctionnel-sap-hcm',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '24/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'SAP SuccessFactors Senior/Lead Consultant',
        'Entreprise': 'INVESTIGO', 'Source': 'free-work.com',
        'Contrat': 'CDI', 'Localisation': 'Angleterre', 'Remote': 'NC',
        'Salaire / TJM': '80-90 k£/an', 'Durée mission': 'NC',
        'Fit / Notes': "Poste senior SuccessFactors au Royaume-Uni. Meme question de droit au travail UK que sur l'offre Qurated ; a clarifier avant d'investir dans une candidature.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/sap-successfactors-senior-lead-consultant-permanent-ps80-000-ps90-000-per-annum-benefits',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.pdf', 'Prétention': '90-100 k£',
        'Date trouvée': D, 'Date publiée': '08/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant AMOA SIRH / Recette fonctionnelle',
        'Entreprise': 'Signe +', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'Marseille (13)', 'Remote': 'Partiel',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Assistance a maitrise d'ouvrage sur la recette fonctionnelle d'une solution SIRH pour un organisme public : analyse des besoins, ateliers de parametrage et de tests, redaction des plans de test et organisation des phases de recette. La recette et les TNR font partie des cibles declarees.",
        'Lien': 'https://www.free-work.com/fr/tech-it/consultant-moa-amoa/job-mission/consultant-amoa-sirh-recette-fonctionnelle',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '15/02/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant AMOA GTA SIRH',
        'Entreprise': 'Tenth Revolution Group', 'Source': 'free-work.com',
        'Contrat': 'CDI', 'Localisation': 'Paris (75)', 'Remote': 'NC',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "AMOA sur la gestion des temps et activites. Tenth Revolution Group est la maison mere de Washington Frank, tres actif sur le marche SAP.",
        'Lien': 'https://www.free-work.com/fr/tech-it/consultant-moa-amoa/job-mission/consultant-amoa-gta-sirh',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SIRH - F/H',
        'Entreprise': 'Onepoint', 'Source': 'groupeonepoint.cvcatcher.io',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Onepoint recrute aussi un Leader SIRH a Paris. Cabinet de transformation reconnu ; le poste de consultant est un cran en dessous du niveau vise, le poste de Leader serait plus adapte.",
        'Lien': 'https://groupeonepoint.cvcatcher.io/offer/10528-SlIxMDE1NTM',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '31/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chef de Projet SIRH (H/F)',
        'Entreprise': 'diptyque paris', 'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Maison de parfum et cosmetique, secteur proche de L'Oreal. Poste interne de chef de projet SIRH ; Paris reste un frein pour un projet 100% remote.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/diptyque-paris/jobs/cdi-chef-de-projet-sirh-h-f_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chef de projet IT SIRH',
        'Entreprise': 'Objectware', 'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "ESN parisienne, poste de chef de projet IT sur le domaine SIRH. Profil aligne mais positionnement plus IT que metier.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/objectware/jobs/chef-de-projet-it-sirh_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SIRH H/F',
        'Entreprise': 'Septeo', 'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI', 'Localisation': 'Lyon', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Editeur logiciel, accompagnement des clients dans le parametrage et l'optimisation de solutions SIRH. Lyon est eloigne d'Anglet.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/septeo/jobs/consultant-sirh-h-f_lyon_SEPTE_MjlzpK8',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chef de projet SIRH',
        'Entreprise': 'Silae', 'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Editeur de paie francais en forte croissance. Nantes est eloigne d'Anglet ; a considerer seulement si un rythme tres remote est accepte.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/silae/jobs/chef-de-projet-sirh_nantes',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },

    # ---------------- CSM ----------------
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Customer Success Manager, Mid-Market, EMEA',
        'Entreprise': 'Harvey', 'Source': 'AshbyHQ / LinkedIn',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Editeur d'IA juridique tres bien finance, clients cabinets d'avocats et directions juridiques de grands groupes. Le poste couvre l'integration du produit dans les workflows clients, l'accompagnement des administrateurs et le travail avec les Account Executives sur les renouvellements et expansions. Croisement CSM enterprise et IA, les deux cibles de Gaetan.",
        'Lien': 'https://jobs.ashbyhq.com/harvey/b7398afc-09c5-45c9-bbc1-1d00f722b798',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': '85-95 K€',
        'Date trouvée': D, 'Date publiée': '31/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Customer Success Manager (Remote from France)',
        'Entreprise': 'Jobgether (client confidentiel)', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Poste base en France en full remote avec un portefeuille clients EMEA, sur un produit cybersecurite. Le 100% remote depuis la France correspond exactement a la contrainte d'Anglet.",
        'Lien': 'https://jobs.lever.co/jobgether/2cfe2bb1-31f9-4afa-adaf-41a8a45a0e05',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager EMEA',
        'Entreprise': 'RemoFirst', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Plateforme d'employer of record et de paie internationale, donc croisement direct entre le metier CSM et le domaine RH/paie multi-pays. L'entreprise est 100% remote par construction. Le portefeuille est decrit comme tech-touch et low-touch, donc plus volumique que strategique.",
        'Lien': 'https://jobs.lever.co/remofirst/99b6bcf0-c14b-4806-aadc-b27d41119445',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Strategic Customer Success Manager, EMEA - Remote',
        'Entreprise': 'Jobgether (client confidentiel)', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Portefeuille des clients les plus larges et les plus complexes de la zone EMEA, ce qui correspond au positionnement grands comptes de Gaetan.",
        'Lien': 'https://jobs.lever.co/jobgether/2846e701-bee8-45c2-b746-4e12251c4cae',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '85-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Remote Enterprise Customer Success Manager',
        'Entreprise': 'Jobgether (client confidentiel)', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'Europe', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Segment enterprise en full remote. Jobgether agrege des offres pour le compte de ses clients ; verifier le pays d'embauche reel avant de candidater.",
        'Lien': 'https://jobs.lever.co/jobgether/6dd14b05-54c3-4382-92f1-a7e49add19d7',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '85-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Customer Success Manager (Remote)',
        'Entreprise': 'Notabene', 'Source': 'AshbyHQ',
        'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Editeur de conformite pour les acteurs crypto ; l'experience de co-fondateur de WallOfTraders.com donne une legitimite immediate sur le domaine. Poste senior en full remote.",
        'Lien': 'https://jobs.ashbyhq.com/notabene/8fa82c0c-c65b-4af5-bbb5-f624c5e0f3a5',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '85-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Strategic Customer Success Manager, South Europe',
        'Entreprise': 'GitLab', 'Source': 'boards.greenhouse.io',
        'Contrat': 'CDI', 'Localisation': 'Europe du Sud', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "GitLab fonctionne en all-remote, ce qui rend Anglet sans objet. Segment strategique sur l'Europe du Sud. Verifier que l'annonce est toujours ouverte, l'identifiant Greenhouse semble ancien.",
        'Lien': 'https://boards.greenhouse.io/gitlab/jobs/6305872002',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '85-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager, Europe',
        'Entreprise': 'Vercel', 'Source': 'boards.greenhouse.io',
        'Contrat': 'CDI', 'Localisation': 'Europe', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Portefeuille de comptes enterprise sur l'Europe. Produit tres technique destine aux equipes de developpement, ce qui eloigne du terrain RH habituel. Annonce a verifier.",
        'Lien': 'https://boards.greenhouse.io/vercel/jobs/5015211004',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '85-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager EMEA (f/m/d)',
        'Entreprise': 'LeanIX (SAP)', 'Source': 'boards.greenhouse.io',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "LeanIX a ete rachete par SAP, ce qui cree une passerelle naturelle avec les 14 ans d'experience SAP. Le territoire France demande un anglais et un francais courants, tous deux acquis. Annonce a verifier.",
        'Lien': 'https://boards.greenhouse.io/leanixjobs/jobs/5839115003',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '85-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Senior Client Success Manager (Together)',
        'Entreprise': 'Absorb LMS', 'Source': 'AshbyHQ',
        'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Editeur de LMS, avec manipulation de donnees collaborateurs et de fichiers issus de SIRH. Croisement CSM et SIRH interessant, sur un produit adjacent au module Learning de SuccessFactors.",
        'Lien': 'https://jobs.ashbyhq.com/absorblms/93dcf31c-fe2e-4b2d-99a4-bd69b4a5ae67',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-90 K€',
        'Date trouvée': D, 'Date publiée': '04/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager (Europe)',
        'Entreprise': 'Whitecollars', 'Source': 'himalayas.app',
        'Contrat': 'CDI', 'Localisation': 'Europe', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Poste CSM ouvert a toute l'Europe en full remote. Cabinet de recrutement intermediaire, le client final reste a identifier.",
        'Lien': 'https://himalayas.app/companies/whitecollars/jobs/customer-success-manager-europe',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-90 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Enterprise Customer Success Manager (Remote)',
        'Entreprise': 'Vendavo', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Editeur de solutions de pricing B2B pour grands comptes industriels. Segment enterprise coherent avec le parcours ; domaine metier eloigne des RH.",
        'Lien': 'https://jobs.lever.co/vendavo/6beb7c2b-96eb-40ac-84a0-6d241b384ce7',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '85-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager - Remote',
        'Entreprise': 'Nevis Wealth', 'Source': 'AshbyHQ',
        'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Startup IA pour conseillers financiers, financee par Sequoia, ICONIQ et Ribbit Capital. Croisement IA et finance qui rejoint l'experience WallOfTraders.com ; verifier si le poste est ouvert hors Etats-Unis.",
        'Lien': 'https://jobs.ashbyhq.com/nevis/d7f67a70-2956-41b2-a015-e3f127b36d2c/application',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '85-95 K€',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager - UK or Germany (Remote)',
        'Entreprise': 'Zilliant', 'Source': 'himalayas.app',
        'Contrat': 'CDI', 'Localisation': 'Royaume-Uni / Allemagne', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Poste restreint au Royaume-Uni ou a l'Allemagne, ce qui pose la meme question de droit au travail que les offres UK. A garder en veille.",
        'Lien': 'https://himalayas.app/companies/zilliant/jobs/customer-success-manager-uk-or-germany',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': 'NC',
        'Date trouvée': D, 'Date publiée': 'NC',
    },

    # ---------------- IA ----------------
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Formateur / Consultant IA et IA générative (freelance)',
        'Entreprise': 'Mantra (ex-GrowthMakers)', 'Source': 'Welcome to the Jungle',
        'Contrat': 'Freelance', 'Localisation': 'France', 'Remote': '100% remote',
        'Salaire / TJM': 'NC', 'Durée mission': 'Recurrent',
        'Fit / Notes': "Conception et animation de formations de un a deux jours aupres de dirigeants de TPE et PME, en 100% remote avec des horaires flexibles. C'est le profil formateur IA le plus proche de ce que Gaetan vise : acculturation et conduite du changement, sans data science. Le format freelance recurrent se combine avec d'autres missions.",
        'Lien': 'https://www.welcometothejungle.com/en/companies/growthmakers/jobs/formateur-ia-et-ia-generative_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': 'A definir (jour de formation)',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Consultant IA Générative & Conduite du changement',
        'Entreprise': 'Client via Mission Freelances', 'Source': 'mission-freelances.fr',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': 'Sur site',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Deploiement d'outils d'IA generative dans l'organisation : animation d'ateliers d'adoption, demonstrations de ChatGPT et Adobe Firefly, identification d'opportunites d'automatisation et pilotage en agile. Le profil demande combine gestion de projet, conduite du changement et pratique reelle des outils IA, ce qui decrit le positionnement de Gaetan. Le presentiel parisien est le seul frein.",
        'Lien': 'https://www.mission-freelances.fr/missions/consultant-ia-generative-conduite-du-changement-paris-87a17202/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '17/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Consultant Assurance IARD - Change Management & Intelligence Artificielle',
        'Entreprise': 'YGL consulting', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'France (multi-sites)', 'Remote': 'Partiel',
        'Salaire / TJM': '600-700 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "Le client dispose des outils IA mais l'usage reste tres faible ; le sujet est explicitement de la conduite du changement, pas de la technique. Perimetre de plus de 2000 souscripteurs repartis sur Toulouse, Bordeaux, Angers, l'Alsace, la Lorraine et Lille, avec une pyramide des ages agee et une resistance a l'IA. Mission d'analyse du dispositif, de priorisation d'une vingtaine de cas d'usage et de plan de deploiement. C'est exactement le profil acculturation IA vise.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/project-management-officer/consultant-assurance-iard-change-management-intelligence-artificielle',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '30/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Formateur / Formatrice en Intelligence Artificielle Générative',
        'Entreprise': 'Client via Mission Freelances', 'Source': 'mission-freelances.fr',
        'Contrat': 'Mission freelance', 'Localisation': 'Île-de-France', 'Remote': 'NC',
        'Salaire / TJM': 'NC', 'Durée mission': 'NC',
        'Fit / Notes': "Transmission des bonnes pratiques d'usage de l'IA, accompagnement des apprenants dans la definition d'une strategie d'implementation et formation a la creation de contenus redactionnels et visuels avec des outils d'IA generative. Poste de formateur pur, sans exigence de data science.",
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-formatrice-en-intelligence-artificielle-generative-ile-de-france-a5471a52/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': 'A definir (jour de formation)',
        'Date trouvée': D, 'Date publiée': 'NC',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chef de Produit Plateforme IA (AI Platform Product Manager)',
        'Entreprise': 'JCW Search Ltd', 'Source': 'free-work.com',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': 'Partiel',
        'Salaire / TJM': '610-1110 £/j', 'Durée mission': '12 mois',
        'Fit / Notes': "Vision et strategie d'une plateforme IA d'entreprise, avec industrialisation LLMOps. Le TJM est le plus eleve rencontre sur cette relance. La composante LLMOps est technique et sort du perimetre non-data-science vise ; a tenter si l'angle produit domine.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/responsable-produit/chef-de-produit-plateforme-ia-ai-platform-product-manager',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': '750-900 €/j',
        'Date trouvée': D, 'Date publiée': '05/08/2026',
    },
]

def _liens_existants():
    import openpyxl
    wb = openpyxl.load_workbook(add_offre.FICHIER)
    lien_idx = add_offre._col_index(wb['Offres SIRH'], 'Lien')
    liens = set()
    for ws in (wb['Offres SIRH'], wb['Offres CSM'], wb['Offres IA'], wb['Fait']):
        for row in ws.iter_rows(min_row=2):
            v = row[lien_idx].value
            if v:
                liens.add(str(v).strip())
    return liens


if __name__ == '__main__':
    connus = _liens_existants()
    nouvelles = [o for o in OFFRES if o['Lien'] not in connus]
    doublons = len(OFFRES) - len(nouvelles)
    print(f"{len(OFFRES)} offres collectees, {doublons} deja presentes, {len(nouvelles)} a ajouter\n")
    add_offre.ajouter_offres(nouvelles)
