"""
Ajout des offres trouvées lors de la recherche exhaustive du 2026-08-03.
Sources couvertes : free-work.com (SIRH, SAP SuccessFactors, IA), welcometothejungle.com,
Strada (Alight), Cegid, CGI, Accenture, Jobgether, Dashlane, Pacvue, Glean, Culture Amp,
Himalayas, Employment Hero, Customer.io, LumApps, Mindquest, SPIE ICS, Groupe Artemys,
mission-freelances.fr, Huron Consulting, Ayming, Talentia Software.
Recherche menée en parallèle sur toutes les sources CLAUDE.md (cabinets de conseil,
cabinets RH, éditeurs HRIS, boards SAP/SIRH, boards généralistes, boards remote/VC/ATS,
LinkedIn, IA). La grande majorité des résultats remontés étaient déjà présents dans le
tableur (ACT-ON, HR Path, EY, KPMG, Sopra Steria, Deel, Sitetracker, Brevo, Okta, Lucca,
LeanIX, Cornerstone, etc.) ; seules les offres réellement nouvelles sont ajoutées ici.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from add_offre import ajouter_offres

offres = [

    # ── ONGLET OFFRES SIRH ─────────────────────────────────────────────────────

    # Apps IT Limited (via free-work) — Technico-Fonctionnel SAP HCM French Payroll — full remote
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Technico-Fonctionnel SAP HCM French Payroll',
        'Entreprise': 'Apps IT Limited',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'France',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Mission 100% remote sur SAP HCM paie française, correspond exactement aux 14 ans d\'expertise SAP HR de Gaëtan. Peu de missions SAP HCM affichent un remote total ; à prioriser.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sap-hcm',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '600-700€/j',
    },

    # SPIE ICS — Chef de projet SIRH — Bordeaux (proche Anglet)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de projet SIRH (H/F)',
        'Entreprise': 'SPIE ICS',
        'Source': 'free-work.com',
        'Contrat': 'Freelance ou CDI',
        'Localisation': 'Bordeaux (33)',
        'Remote': 'Partiel',
        'Salaire / TJM': '450-600€/j ou 40-45K€/an',
        'Durée mission': '6 mois',
        'Fit / Notes': 'Localisation Bordeaux proche d\'Anglet, ce qui facilite les déplacements ponctuels sur site. Salaire CDI un peu bas pour le profil mais TJM freelance correct ; à négocier.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '600€/j',
    },

    # NOVAMINDS / Mon Consultant Indépendant (via free-work) — Senior Consultant Transformation RH
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Consultant Transformation RH - Target Operating Model & Core HR',
        'Entreprise': 'NOVAMINDS / Mon Consultant Indépendant',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris / Île-de-France',
        'Remote': 'Partiel',
        'Salaire / TJM': '500-650€/j',
        'Durée mission': '4 mois renouvelable',
        'Fit / Notes': 'Correspond très bien au profil : transformation RH, Core HR multi-pays, anglais courant, 10 ans d\'expérience. Deux recruteurs postent la même mission (500-550€/j et 650€/j selon l\'annonce), à négocier vers le haut.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '650€/j',
    },

    # HR DNA (pour TalHenT, via free-work) — Manager SIRH
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Manager SIRH',
        'Entreprise': 'TalHenT (via HR DNA)',
        'Source': 'free-work.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '60-110K€/an',
        'Durée mission': '',
        'Fit / Notes': 'Poste hybride management + business development, correspond à la cible "Account Manager HR Tech" ; fourchette salariale large, à clarifier le niveau exact du poste en entretien.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '90K€',
    },

    # Mindquest (via free-work) — SAP PMO SuccessFactors
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'SAP PMO SuccessFactors (H/F)',
        'Entreprise': 'Mindquest',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '3 mois',
        'Fit / Notes': 'Mission courte PMO SuccessFactors, bon complément entre deux missions plus longues ; correspond à l\'expérience de pilotage de projets SIRH multi-pays.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '600€/j',
    },

    # Groupe Artemys (via free-work) — Chef de projet SIRH
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de projet SIRH (H/F)',
        'Entreprise': 'Groupe Artemys',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris 15e',
        'Remote': 'Partiel',
        'Salaire / TJM': '550-650€/j',
        'Durée mission': '9 mois',
        'Fit / Notes': 'Mission longue (9 mois) de chef de projet SIRH, correspond bien au profil de pilotage de projets SIRH mondiaux de Gaëtan.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '600€/j',
    },

    # Strada (ex-Alight) — Senior SAP HCM Payroll — Lyon
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior SAP HCM Payroll',
        'Entreprise': 'Strada (ex-Alight/NGA)',
        'Source': 'careers.alight.com',
        'Contrat': 'CDI',
        'Localisation': 'Lyon',
        'Remote': 'Non précisé',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Nouveau poste ouvert à Lyon chez Strada (1er partenaire mondial SAP HR), en complément des postes Colombes déjà identifiés. Correspondance quasi parfaite avec les 14 ans SAP HR de Gaëtan.',
        'Lien': 'https://careers.alight.com/strada/us/en/job/ALIGUSR30184STRADAENUS/Senior-SAP-HCM-Payroll',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '80-90K€',
    },

    # Cegid — Directeur/Directrice de projets SIRH — Nantes
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Directeur / Directrice de projets SIRH F/H/NB',
        'Entreprise': 'Cegid',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Nantes',
        'Remote': 'Non précisé',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste de pilotage simultané de plusieurs projets de déploiement Talent Management chez un éditeur SIRH français reconnu ; correspond très bien à la cible "Chef de projet SIRH" senior.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/cegid/jobs/directeur-directrice-de-projets-sirh-f-h-nb_nantes',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75-85K€',
    },

    # Cegid — Consultant SIRH Grands Comptes — Boulogne-Billancourt
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH Grands Comptes F/H/NB',
        'Entreprise': 'Cegid',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Boulogne-Billancourt',
        'Remote': 'Non précisé',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Même type de poste que la version Lyon déjà identifiée, publié ici pour Boulogne-Billancourt ; grands comptes = profil senior avec expérience L\'Oréal valorisable.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/cegid/jobs/consultant-sirh-grands-comptes-f-h-nb_boulogne-billancourt_CEGID_Kp678y8',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75K€',
    },

    # CGI — Chef(fe) de projet SIRH — Nantes
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef(fe) de projet SIRH F/H',
        'Entreprise': 'CGI',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Nantes',
        'Remote': 'Hybride (jusqu\'à 3j télétravail/semaine)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste équivalent à celui déjà identifié à Paris chez CGI, ouvert également à Nantes ; intégrateur SAP majeur, hybride mais flexible.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/cgi/jobs/chef-fe-de-projet-sirh-f-h_nantes',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # Accenture — Consultant digital RH
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant digital RH - F/H',
        'Entreprise': 'Accenture',
        'Source': 'accenture.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Non confirmé (une source mentionne remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Exige 5+ ans sur Workday/SuccessFactors/Oracle HCM et transformation digitale RH incluant IA ; correspond au profil SAP + acculturation IA de Gaëtan.',
        'Lien': 'https://www.accenture.com/fr-fr/careers/jobdetails?id=R00270940_fr-fr',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75-85K€',
    },

    # Huron Consulting Group — HCM Solution Architect (full remote)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'HCM Solution Architect',
        'Entreprise': 'Huron Consulting Group',
        'Source': 'jobgether.com',
        'Contrat': 'Non précisé',
        'Localisation': 'Non précisée',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste HCM senior full remote, plutôt orienté Workday/Oracle HCM que SAP mais compétences largement transférables. Lien à vérifier manuellement (page bloquée en fetch automatisé).',
        'Lien': 'https://jobgether.com/offer/69eab9adc646310ee39997f9-hcm-solution-architect',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-90K€',
    },

    # Ayming — Chef de projet SIRH / Consultant Paie et SIRH (statut incertain)
    {
        'Priorité': '⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de projet SIRH (H/F) / Consultant Paie et SIRH (H/F)',
        'Entreprise': 'Ayming',
        'Source': 'ayming.fr / Glassdoor',
        'Contrat': 'CDI',
        'Localisation': 'France / Lyon',
        'Remote': 'Non précisé',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Postes trouvés via recherche mais absents de la liste actuelle des offres ouvertes sur le site ; statut incertain (probablement pourvus). À vérifier manuellement avant de postuler.',
        'Lien': 'https://www.ayming.fr/jobs/chef-de-projet-sirh-hf/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # Talentia Software — Consultant paramétrage SIRH paie
    {
        'Priorité': '⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant paramétrage SIRH paie (H/F)',
        'Entreprise': 'Talentia Software',
        'Source': 'engagement-jeunes.com',
        'Contrat': 'CDI',
        'Localisation': 'Puteaux (92)',
        'Remote': 'Non précisé',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Éditeur RH/Finance français, poste paramétrage paie SIRH ; source secondaire peu détaillée, à vérifier directement sur le site de l\'éditeur.',
        'Lien': 'https://www.engagement-jeunes.com/fr/detail-offre/37016104/cdi-talentia-software-consultant-parametrage-sirh-paie-h-f.html',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '65-75K€',
    },

    # ── ONGLET OFFRES CSM ──────────────────────────────────────────────────────

    # Glean (via Sequoia portfolio) — Enterprise Customer Success Manager EMEA
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Enterprise Customer Success Manager, EMEA',
        'Entreprise': 'Glean',
        'Source': 'LinkedIn / Sequoia portfolio',
        'Contrat': 'CDI',
        'Localisation': 'Remote EMEA',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': '5-7 ans de CSM SaaS enterprise requis, gestion de book of business, français apprécié ; bon fit avec l\'expérience grands comptes de Gaëtan chez L\'Oréal.',
        'Lien': 'https://www.linkedin.com/jobs/view/enterprise-customer-success-manager-at-glean-3867298616',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '85-95K€',
    },

    # Jobgether (agence) — Strategic Customer Success Manager EMEA
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Strategic Customer Success Manager, EMEA',
        'Entreprise': 'Jobgether (client non identifié)',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDI',
        'Localisation': 'Remote EMEA',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Portefeuille d\'environ 20 comptes enterprise à plus de 2M$ ARR ; niveau senior correspondant à l\'expérience grands comptes de Gaëtan. Jobgether republie régulièrement des postes similaires sous agence.',
        'Lien': 'https://jobs.lever.co/jobgether/707812db-31e1-4fa7-82f5-2fb18b90bba6',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '85-95K€',
    },

    # Dashlane — Customer Support Operations Manager
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Support Operations Manager',
        'Entreprise': 'Dashlane',
        'Source': 'boards.greenhouse.io',
        'Contrat': 'CDI',
        'Localisation': 'Remote France (ou bureau Paris)',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste opérations support/CS chez un éditeur SaaS reconnu, remote France flexible ; bon complément aux candidatures CSM pures.',
        'Lien': 'https://boards.greenhouse.io/dashlane/jobs/3507159',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '75-85K€',
    },

    # Pacvue — Customer Success Manager, EU
    {
        'Priorité': '⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager, EU',
        'Entreprise': 'Pacvue',
        'Source': 'job-boards.greenhouse.io',
        'Contrat': 'CDI',
        'Localisation': 'Remote UK ou Allemagne',
        'Remote': 'Oui (zone EU, France non listée explicitement)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Zone EU correspond au profil mais la France n\'est pas explicitement listée comme éligible ; à vérifier en candidatant.',
        'Lien': 'https://job-boards.greenhouse.io/pacvue/jobs/4712905004',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '75-85K€',
    },

    # Culture Amp — Customer Success Manager (Commercial/Scaled)
    {
        'Priorité': '⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager (Commercial / Scaled)',
        'Entreprise': 'Culture Amp',
        'Source': 'indexventures.com (portfolio)',
        'Contrat': 'CDI',
        'Localisation': 'Bureaux US/UK/Allemagne/Australie',
        'Remote': 'Éligibilité France incertaine',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Éditeur RH/People Analytics reconnu mais éligibilité remote depuis la France non confirmée ; à clarifier avant de postuler.',
        'Lien': 'https://www.indexventures.com/startup-jobs/culture-amp/customer-success-manager-commercial-4/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '75-85K€',
    },

    # Customer.io — Customer Success Manager, EMEA
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager, EMEA',
        'Entreprise': 'Customer.io',
        'Source': 'weworkremotely.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote EMEA',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Portefeuille mid-market de 50 à 60 clients, zone EMEA ; éditeur SaaS marketing automation reconnu, bon fit avec l\'expérience CSM senior de Gaëtan.',
        'Lien': 'https://weworkremotely.com/remote-jobs/customer-io-customer-success-manager-emea',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-90K€',
    },

    # LumApps — Enterprise Customer Success Manager (Paris/Lyon)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Enterprise Customer Success Manager (F/M)',
        'Entreprise': 'LumApps',
        'Source': 'job.lumapps.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris / Lyon / Tassin-la-Demi-Lune',
        'Remote': 'Hybride (2j bureau / 3j remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'CSM Enterprise grands comptes, 4-5 ans SaaS requis ; Gaëtan largement qualifié mais poste hybride, pas full remote.',
        'Lien': 'https://job.lumapps.com/jobs/8149701-enterprise-customer-success-manager-f-m-paris-lyon',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75-85K€',
    },

    # Employment Hero — HR Implementation Consultant (Guided)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'HR Implementation Consultant (Guided)',
        'Entreprise': 'Employment Hero',
        'Source': 'himalayas.app',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste implementation consultant HRIS full remote, correspond bien au profil chef de projet SIRH/consultant en migration de données.',
        'Lien': 'https://himalayas.app/companies/employment-hero/jobs/hr-implementation-consultant-guided',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '75-85K€',
    },

    # Imnoo AG — Senior Customer Success Manager (freelance/remote flexible)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager (50-100% Remote/Freelance)',
        'Entreprise': 'Imnoo AG',
        'Source': 'himalayas.app',
        'Contrat': 'Freelance ou CDI flexible',
        'Localisation': 'Remote flexible',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Format mixte freelance/CDI intéressant pour une transition en douceur ; flexibilité de charge (50 à 100%) qui peut convenir en complément d\'une autre mission.',
        'Lien': 'https://himalayas.app/companies/imnoo-ag',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '600-700€/j ou 80K€',
    },

    # ── ONGLET OFFRES IA ───────────────────────────────────────────────────────

    # mission-freelances.fr — Formateur·rice·s freelances en IA (télétravail)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur·rice·s freelances en IA',
        'Entreprise': 'mission-freelances.fr (client non identifié)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Télétravail',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Match direct avec le profil formateur IA 100% remote recherché par Gaëtan ; usage quotidien des outils IA générative valorisable directement.',
        'Lien': 'https://mission-freelances.fr/missions/formateur-rice-s-freelances-en-ia-teletravail-9cc97c82/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500-600€/j',
    },

    # mission-freelances.fr — Formateur IA appliquée à l'acquisition client (télétravail)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur IA appliquée à l\'acquisition client',
        'Entreprise': 'mission-freelances.fr (client non identifié)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Télétravail',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Formation IA orientée usage commercial ; nécessite SIRET/inscription directe sur la plateforme, pas de data science pure.',
        'Lien': 'https://mission-freelances.fr/missions/formateur-ia-appliquee-a-l-acquisition-client-teletravail-68ec066a/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500€/j',
    },

    # mission-freelances.fr — Consultant indépendant en IA pour PME (Gironde)
    {
        'Priorité': '⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant indépendant en intelligence artificielle pour PME',
        'Entreprise': 'mission-freelances.fr (client non identifié)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Gironde',
        'Remote': 'Non précisé',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Proximité géographique Sud-Ouest intéressante (Gironde proche d\'Anglet) ; offre peu détaillée, à creuser manuellement.',
        'Lien': 'https://mission-freelances.fr/missions/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500-600€/j',
    },

]

if __name__ == '__main__':
    ajouter_offres(offres, verbose=True)
    print("\nTerminé. Offres ajoutées dans offres_emploi.xlsx")
