"""Relance de recherche exhaustive du 10/08/2026 - toutes sources CLAUDE.md (5 agents paralleles)."""

import add_offre

add_offre.COLS = add_offre.COLS + ['Date trouvée', 'Date publiée']

D = '10/08/2026'

OFFRES = [
    # ---------------- SIRH / SAP ----------------
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'HRIS Manager - SAP SuccessFactors',
        'Entreprise': 'QIMA', 'Source': 'careers.ta.com',
        'Contrat': 'CDI', 'Localisation': 'Paris (siège France)', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Group HRIS Manager, redesign du HR operating model sur 120+ pays. Fit parfait avec le parcours L'Oréal/SAP HR mondial de Gaëtan.",
        'Lien': 'https://careers.ta.com/companies/qima-2-dcae509c-009b-43d7-baf2-d4362febeafe/jobs/77395774-hris-manager-sap-successfactors',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.pdf', 'Prétention': '90-110 K€',
        'Date trouvée': D, 'Date publiée': '05/05/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de Projet HR Access',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Chef de projet SIRH ciblé, HR Access est un cœur de compétence SIRH généraliste chez ce cabinet très ciblé.",
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Chef-de-Projet-HR-Access-Paris-La-D%C3%A9fense-75-92042/904222801/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de Projet Expert HR Access (H/F)',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Lyon', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Chef de projet SIRH niveau expert, HR Access, bon fit.",
        'Lien': 'https://jobs.hr-path.com/job/Lyon-Chef-de-Projet-Expert-HR-Access-%28HF%29-69-69002/1412852433/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant SIRH Paie HR Access - Paris La Défense (H/F)',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Consultant SIRH paie HR Access, bon fit avec le profil senior SIRH.",
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SIRH-Paie-HR-Access-Paris-La-D%C3%A9fense-%28HF%29-75-92042/888056701/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Product Owner HRIS - Technical',
        'Entreprise': 'CMA CGM', 'Source': 'jobs.cmacgm-group.com',
        'Contrat': 'CDI', 'Localisation': 'Marseille', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Product Owner SIRH chez un grand compte, cohérent avec la cible Product Owner SIRH.",
        'Lien': 'https://jobs.cmacgm-group.com/job/Marseille-Product-Owner-HRIS-Technical/1416631133/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Workday HCM Specialist',
        'Entreprise': 'Client confidentiel (via Keylime Consultants)', 'Source': 'keylime.co.uk',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride (3j/semaine bureau)',
        'Salaire / TJM': "jusqu'à ~85 K€ + bonus", 'Durée mission': None,
        'Fit / Notes': "Client parisien venant d'implémenter Workday, configuration Core HCM + module, forte dimension stakeholder management.",
        'Lien': 'https://keylime.co.uk/vacancy/senior-specialist-workday-jobs-in-france/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Implementation Project Manager SaaS (HRSD/PeopleDoc)',
        'Entreprise': 'UKG', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Oui (full remote possible en France)',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Implementation Consultant HRIS chez l'éditeur UKG (ex-PeopleDoc), 3-6 ans requis en implémentation SaaS RH, remote total possible.",
        'Lien': 'https://www.welcometothejungle.com/en/companies/ukg/jobs/implementation-project-manager_paris_UKG_bV5YrOq',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'PMO HR Digital Team',
        'Entreprise': 'CMA CGM', 'Source': 'jobs.cmacgm-group.com',
        'Contrat': 'CDI', 'Localisation': 'Marseille', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "PMO transformation SIRH grand compte, complémentaire au poste Product Owner HRIS chez le même employeur.",
        'Lien': 'https://jobs.cmacgm-group.com/job/Marseille-PMO-HR-Digital-Team/1412376133/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Workday HCM Analyst',
        'Entreprise': 'Client confidentiel (via Keylime Consultants)', 'Source': 'keylime.co.uk',
        'Contrat': 'CDI', 'Localisation': 'Paris ou Bruxelles', 'Remote': 'Hybride',
        'Salaire / TJM': '~70 K€ + bonus', 'Durée mission': None,
        'Fit / Notes': "Poste Workday HCM légèrement plus junior, même cabinet/vivier de clients que le poste Senior Workday HCM Specialist.",
        'Lien': 'https://keylime.co.uk/vacancy/hcm-analyst-hybrid-workday-jobs-in-france/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Consultant SIRH / Oracle HCM Cloud F/H',
        'Entreprise': 'n.c. (via APEC)', 'Source': 'apec.fr',
        'Contrat': None, 'Localisation': 'Paris 09', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "SIRH mais spécifiquement Oracle HCM (pas SAP, cœur d'expertise) ; APEC bloque le fetch direct, détails à confirmer.",
        'Lien': 'https://www.apec.fr/candidat/recherche-emploi.html/emploi/detail-offre/177777863W',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Workday Intégration Consultant (H/F)',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Bègles (33)', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "SIRH mais Workday, pas d'expérience directe de Gaëtan sur cet outil.",
        'Lien': 'https://jobs.hr-path.com/job/B%C3%A8gles-Workday-Int%C3%A9gration-Consultant-%28HF%29-33-33130/1171326601/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Consultant Workday HCM - France (H/F)',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Idem, Workday hors cœur SAP.",
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-Workday-HCM-France-%28HF%29-75-92042/772919601/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Oracle HCM Cloud Consultant (H/F)',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "SIRH mais Oracle HCM, hors cœur SAP.",
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Oracle-HCM-Cloud-Consultant-%28HF%29-75-92042/768696101/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Consultant sénior SIRH paie Silae (H/F)',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Ifs (14)', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "SIRH paie mais outil Silae, localisation Calvados peu adaptée au remote.",
        'Lien': 'https://jobs.hr-path.com/job/Ifs-Consultant-s%C3%A9nior-SIRH-paie-Silae-%28HF%29-14-14123/1401970133/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Workday Solution Architect - France',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Architecte solution, hors cœur SAP.",
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Workday-Solution-Architect-France-75-92042/768697301/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Workday Lead Consultant (H/F)',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Idem, Workday hors cœur SAP.",
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Workday-Lead-Consultant-%28HF%29-75-92042/1079681201/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Workday Talent Lead Consultant',
        'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Idem, Workday hors cœur SAP.",
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Workday-Talent-Lead-Consultant-75-92042/1079691701/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    # ---------------- CSM ----------------
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success - Scale - Western Europe',
        'Entreprise': 'ElevenLabs', 'Source': 'Ashby (site carrière)',
        'Contrat': 'CDI', 'Localisation': 'Remote France/Italie/Pologne/Espagne/UK', 'Remote': 'Oui',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Remote confirmé éligible France, portefeuille ~80 comptes, éditeur IA en forte croissance ; bon croisement avec l'appétence IA de Gaëtan.",
        'Lien': 'https://elevenlabs.io/careers/f330bd23-f909-4e50-bf58-9974aee85fc8/customer-success-scale-western-europe',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager - SMB & Mid-market',
        'Entreprise': 'HeyTeam (Onboarding Facile)', 'Source': 'LinkedIn',
        'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Éditeur SaaS RH (onboarding), portefeuille ~40 comptes SMB/mid-market, secteur HR Tech proche du profil SIRH.",
        'Lien': 'https://fr.linkedin.com/jobs/view/customer-success-manager-smb-mid-market-at-heyteam-onboarding-facile-4431921444',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '30/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant(e) Customer Success spé. Grands Comptes - Marseille',
        'Entreprise': 'Lucca', 'Source': 'welcometothejungle.com / jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'Marseille', 'Remote': 'Hybride (2j télétravail/sem)',
        'Salaire / TJM': '44-54 K€ fixe', 'Durée mission': None,
        'Fit / Notes': "CSM SIRH grands comptes (Accor, Pernod Ricard...) chez Lucca ; 2 ans d'XP visés, en dessous du niveau senior de Gaëtan, hybride Marseille.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/lucca/jobs/consultant-customer-success-spe-grands-comptes-marseille_marseille_LUCCA_VYMmMDp',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '44-54 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant Customer Success Partenariat - Équipe intégrateurs',
        'Entreprise': 'Lucca', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Marseille', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM Lucca dédié aux intégrateurs partenaires (SI/cabinets), angle différent des autres postes CSM Lucca déjà trackés.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/lucca/jobs/consultant-customer-success-partenariat-equipe-integrateurs_marseille',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '60-75 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager',
        'Entreprise': 'StrangeBee', 'Source': 'LinkedIn',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Structuration de l'organisation Customer Success chez cet éditeur cybersécurité (TheHive Project), poste à fort impact.",
        'Lien': 'https://fr.linkedin.com/jobs/view/customer-success-manager-at-strangebee-4450359654',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '08/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager (F/H)',
        'Entreprise': 'Worklife', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris 11e', 'Remote': 'Hybride (8-10j/mois bureau)',
        'Salaire / TJM': '44-48 K€ fixe + variable', 'Durée mission': None,
        'Fit / Notes': "Fin/HR tech (avantages salariés), déploiement de la solution auprès de clients mid-market 100-1500 salariés.",
        'Lien': 'https://www.welcometothejungle.com/en/companies/worklife/jobs/customer-success-manager-f-h-44-a-48k-fixe-variable_paris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '44-48 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Manager, Customer Success EMEA Scale',
        'Entreprise': 'Samsara', 'Source': 'Greenhouse (site carrière direct)',
        'Contrat': 'CDI', 'Localisation': 'Remote UK', 'Remote': 'Oui (UK)',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Management d'équipe CS scale EMEA, distinct des CSM Samsara déjà trackés ; base remote UK affichée, à vérifier si ouvert à la France.",
        'Lien': 'https://www.samsara.com/company/careers/roles/7682030',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '90-110 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Onboarding - Formateur H/F',
        'Entreprise': 'Organilog', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Pontchâteau (siège)', 'Remote': 'Oui (télétravail total)',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM avec volet formation client intégré, full remote ; bon croisement CS/formation avec le profil.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/organilog/jobs/custome-success-manager-specialite-formateur-h-f-teletravail_pontchateau',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '60-75 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager (English-Spanish)',
        'Entreprise': 'Landbot', 'Source': 'Himalayas',
        'Contrat': None, 'Localisation': 'Espagne (éligibilité travail Espagne requise)', 'Remote': 'Oui',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "SaaS IA (agents conversationnels), portefeuille de 400€ à 20k+/mois ; espagnol courant requis (profil ES intermédiaire, à évaluer).",
        'Lien': 'https://himalayas.app/companies/landbot/jobs/customer-success-manager-english-spanish',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': 'Avril 2026',
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager - EMEA',
        'Entreprise': 'Tilla', 'Source': 'Ashby',
        'Contrat': 'CDI', 'Localisation': '"Basé en Grèce" (remote)', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Maritime tech (gestion des changements d'équipage) ; l'annonce précise une base en Grèce, éligibilité France incertaine.",
        'Lien': 'https://jobs.ashbyhq.com/tilla/823e58d1-e986-42d9-9441-47f31bb77a52',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager',
        'Entreprise': 'Alcumus', 'Source': 'Himalayas',
        'Contrat': None, 'Localisation': None, 'Remote': 'Oui',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Éditeur SaaS risk/compliance management ; détails non vérifiables (fetch direct bloqué), à confirmer avant candidature.",
        'Lien': 'https://himalayas.app/companies/alcumus/jobs/customer-success-manager',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': '2026',
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager',
        'Entreprise': 'BrandBastion', 'Source': 'Himalayas',
        'Contrat': None, 'Localisation': 'Portugal (zone)', 'Remote': 'Oui',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "SaaS IA modération réseaux sociaux, poste mid-level 3 ans min ; détails non vérifiables en fetch direct.",
        'Lien': 'https://himalayas.app/companies/brandbastion/jobs/customer-success-manager',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': 'Mars 2026',
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager (Tech Startup)',
        'Entreprise': 'Rankbreeze', 'Source': 'weworkremotely.com',
        'Contrat': 'Freelance/contractor long terme', 'Localisation': 'Remote monde entier', 'Remote': 'Oui',
        'Salaire / TJM': '2000-2500 $/mois', 'Durée mission': None,
        'Fit / Notes': "Startup SaaS proptech (vacation rental) ; salaire modeste mais le TJM n'est jamais un critère d'exclusion.",
        'Lien': 'https://weworkremotely.com/remote-jobs/rankbreeze-customer-success-manager-tech-startup',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '2000-2500 $/mois',
        'Date trouvée': D, 'Date publiée': '2026',
    },
    {
        'Priorité': '⭐', 'Poste': 'Customer Success Agent',
        'Entreprise': 'Breezy HR', 'Source': 'weworkremotely.com',
        'Contrat': 'CDI', 'Localisation': 'USA (horaires 9h-18h EST)', 'Remote': 'Oui mais zone US',
        'Salaire / TJM': '~45 K$', 'Durée mission': None,
        'Fit / Notes': "Éditeur ATS/HR tech (fit sectoriel) mais niveau 'Agent' junior et horaires calés sur l'Est américain (15h-minuit heure FR), peu compatible.",
        'Lien': 'https://weworkremotely.com/remote-jobs/breezy-hr-customer-success-agent-5',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': '2026',
    },
    # ---------------- IA ----------------
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'AI Trainer (Formateur/rice IA Généraliste & Certifiante)',
        'Entreprise': 'Focus Cloud Group', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Hauts-de-Seine (92)', 'Remote': 'Non (présentiel obligatoire)',
        'Salaire / TJM': None, 'Durée mission': '5 jours (renouvelable long terme, début 24/08/2026)',
        'Fit / Notes': "Formation IA généraliste certifiante (ML, deep learning, NLP, éthique/conformité IA) pour public professionnel ; bon fit formateur IA mais mission en présentiel dans le 92.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/autre/ai-trainer',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': '10/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'PMO IA',
        'Entreprise': 'Craftman data', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Lyon', 'Remote': 'Hybride (télétravail partiel)',
        'Salaire / TJM': '460-480 €/j', 'Durée mission': '3 mois renouvelable',
        'Fit / Notes': "Pilotage d'initiatives IA générative (Copilot, Gemini), gouvernance, comités de pilotage, conduite du changement et adoption ; bon fit PMO/chef de projet IA différenciant SAP/SIRH.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/project-management-officer/pmo-ia-1',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': '460-480€/j',
        'Date trouvée': D, 'Date publiée': '06/08/2026',
    },
]


def _liens_existants():
    import openpyxl
    wb = openpyxl.load_workbook(add_offre.FICHIER)
    lien_idx = add_offre._col_index(wb['Offres SIRH'], 'Lien')
    liens = set()
    for ws in (wb['Offres SIRH'], wb['Offres CSM'], wb['Offres IA'], wb['Fait']):
        for row in ws.iter_rows(min_row=2):
            v = row[lien_idx].value
            if v:
                liens.add(str(v).strip())
    return liens


if __name__ == '__main__':
    connus = _liens_existants()
    nouvelles = [o for o in OFFRES if o['Lien'] not in connus]
    doublons = len(OFFRES) - len(nouvelles)
    print(f"{len(OFFRES)} offres collectees, {doublons} deja presentes, {len(nouvelles)} a ajouter\n")
    add_offre.ajouter_offres(nouvelles)
