"""
Ajout des offres trouvées lors de la recherche du 2026-07-27.
Sources couvertes : LinkedIn, HR Path, Strada/Alight, SD Worx, Samsara, Spendesk, OpenAI,
Brevo, Pigment, Inetum, EY, CLAP Partners, ACT-ON HRIS, Lucca, Movement Group,
mission-freelances.fr, Michael Page, Sia Partners, free-work.com IA.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from add_offre import ajouter_offres

offres = [

    # ── ONGLET OFFRES SIRH ─────────────────────────────────────────────────────

    # HR Path - France
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP HCM (H/F)',
        'Entreprise': 'HR Path',
        'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI',
        'Localisation': 'Villeneuve-d\'Ascq (59)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'HR Path spécialiste SAP HCM/SF, posté 19/07/2026',
        'Lien': 'https://jobs.hr-path.com/job/Villeneuve-d\'Ascq-Consultant-SAP-HCM-(HF)-59-59650/770170201/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP SuccessFactors (H/F)',
        'Entreprise': 'HR Path',
        'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris La Défense',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'HR Path leader SAP HCM/SF, posté 16/07/2026',
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SAP-SuccessFactors-(HF)-75-92042/818651901/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH (H/F) - Workday / Oracle HCM / SAP SuccessFactors',
        'Entreprise': 'HR Path',
        'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris La Défense',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Multi-SIRH, posté 27/07/2026 - très récent',
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SIRH-(HF)-Workday-%E2%80%A2-Oracle-HCM-%E2%80%A2-SAP-SuccessFactors-75-92042/1419350533/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j ou 70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Solution Architect SuccessFactors (H/F)',
        'Entreprise': 'HR Path',
        'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris La Défense',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Architecte SF - profil très senior, posté 14/07/2026',
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Solution-Architect-SuccessFactors-(HF)-75-92042/1079264001/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '90-110K€',
    },

    # Strada (ex-Alight) - France
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP HCM Paie Senior',
        'Entreprise': 'Strada (ex-Alight)',
        'Source': 'careers.alight.com',
        'Contrat': 'CDI',
        'Localisation': 'Colombes, France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Strada = 1er partenaire SAP HR monde, 8000+ experts. Posté 2026. Parfait fit expertise L\'Oréal/SAP HCM paie',
        'Lien': 'https://careers.alight.com/strada/us/en/job/ALIGUSR27911STRADAENUS/Consultant-SAP-HCM-Paie-senior',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j ou 70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP HCM Time Senior',
        'Entreprise': 'Strada (ex-Alight)',
        'Source': 'careers.alight.com',
        'Contrat': 'CDI',
        'Localisation': 'Colombes, France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Strada expert SAP HCM Time, posté 2026',
        'Lien': 'https://careers.alight.com/strada/us/en/job/ALIGUSR27913STRADAENUS/Consultant-SAP-HCM-Time-senior',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j ou 70-85K€',
    },

    # EY - Paris La Défense
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant expérimenté Transformation RH/Change Management/SIRH - secteur financier (H/F)',
        'Entreprise': 'EY',
        'Source': 'careers.ey.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris La Défense',
        'Remote': 'Partiel',
        'Salaire / TJM': 'Compétitif',
        'Durée mission': '',
        'Fit / Notes': 'Profil transformation RH + SIRH + Change Management. 4 ans exp requis. Posté 21/07/2026',
        'Lien': 'https://careers.ey.com/ey/job/Paris-La-D%C3%A9fense-Consultant-exp%C3%A9riment%C3%A9-en-Transformation-RHChange-ManagementSIRH-secteur-financier-%28HF%29-92037/1220008001/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Manager/Senior Manager Transformation RH (H/F)',
        'Entreprise': 'EY',
        'Source': 'careers.ey.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris La Défense',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Niveau Manager/Senior Manager RH - très senior',
        'Lien': 'https://careers.ey.com/ey/job/Paris-La-D%C3%A9fense-ManagerSenior-Manager-en-Transformation-RH-HF-%28Paris%29-92037/1404311033/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '90-110K€',
    },

    # CLAP Partners
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH AMOA',
        'Entreprise': 'CLAP Partners',
        'Source': 'careers.clap-partners.com',
        'Contrat': 'CDI',
        'Localisation': 'Montrouge (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': '130+ consultants, spécialiste SAP SuccessFactors, AMOA + déploiement pays + change management. Posté 08/07/2026. 2-5 ans requis.',
        'Lien': 'https://careers.clap-partners.com/job/MONTROUGE-Consultant-SIRH-AMOA-92120/770441902/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # ACT-ON HRIS
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) AMOA SIRH (F/H)',
        'Entreprise': 'ACT-ON HRIS',
        'Source': 'actongroup.com / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Lyon / Nantes / Lille / Neuilly-sur-Seine',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': '200+ consultants AMOA, missions grands comptes CAC 40 / SBF 120 / public. Multiples ouvertures. Posté juillet 2026.',
        'Lien': 'https://actongroup.com/offre/consultante-amoa-sirh-f-h/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Inetum
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Fonctionnel Confirmé HR Access (H/F)',
        'Entreprise': 'Inetum',
        'Source': 'inetum.com',
        'Contrat': 'CDI',
        'Localisation': 'Saint-Ouen (93)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'HR Access - moins pertinent que SAP HCM/SF mais SIRH confirmé. 4 ans HR Access requis.',
        'Lien': 'https://www.inetum.com/fr/accueil/carrieres/4fb67a0a-5fa6-48b8-9c1a-0df7767ee7e3.html',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Movement Group
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'SAP HCM Consultant (French Payroll)',
        'Entreprise': 'Movement Group',
        'Source': 'movementgroup.uk',
        'Contrat': 'Freelance (12 mois + extension)',
        'Localisation': 'Remote (100%)',
        'Remote': '100%',
        'Salaire / TJM': 'TJM Outside IR35',
        'Durée mission': '12 mois',
        'Fit / Notes': 'Mission freelance remote, paie française SAP HCM. 3 ans expérience requis. Fit parfait.',
        'Lien': 'https://movementgroup.uk/job/sap-hcm-consultant-time-management/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },

    # SD Worx
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Implémentation SIRH',
        'Entreprise': 'SD Worx',
        'Source': 'welcometothejungle.com / careers.sdworx.com',
        'Contrat': 'CDI',
        'Localisation': 'France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Implémentation HRIS, French speaker. Posté mai/juin 2026.',
        'Lien': 'https://careers.sdworx.com/jobs/7673069-implementation-consultant-french-speaking',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '70-85K€',
    },

    # Sia Partners
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant HR Digital & IA',
        'Entreprise': 'Sia Partners',
        'Source': 'sia-partners.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'BU HR & Change Management, croisement SIRH + IA. Postes ouverts actuellement.',
        'Lien': 'https://www.sia-partners.com/en/career/consultant-digital-hris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Consultant HR & Transformation',
        'Entreprise': 'Sia Partners',
        'Source': 'sia-partners.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Transformation RH, stratégie HR',
        'Lien': 'https://www.sia-partners.com/en/career',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '80-95K€',
    },

    # LinkedIn SIRH/SAP trouvés
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) Senior SAP HCM Paie & Time',
        'Entreprise': 'Strada',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Strada LinkedIn, posté il y a 5 jours',
        'Lien': 'https://fr.linkedin.com/jobs/sap-hcm-emplois',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j ou 70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH – F/H',
        'Entreprise': 'Onepoint',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '60-80K€',
        'Durée mission': '',
        'Fit / Notes': 'Onepoint cabinet conseil digital, posté il y a 2 semaines',
        'Lien': 'https://fr.linkedin.com/jobs/consultant-sirh-emplois',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) AMOA SIRH (F/H)',
        'Entreprise': 'Hey Hr !',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Île-de-France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Cabinet SIRH, posté il y a 1 semaine',
        'Lien': 'https://fr.linkedin.com/jobs/consultant-sirh-emplois',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) fonctionnel SIRH (F/H)',
        'Entreprise': 'CGI',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'CGI grande ESN, posté il y a 2 semaines',
        'Lien': 'https://fr.linkedin.com/jobs/consultant-sirh-emplois',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Talentia Software
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Technico-Fonctionnel SIRH HCM (H/F)',
        'Entreprise': 'Talentia Software',
        'Source': 'WebSearch / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Puteaux (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Éditeur SIRH FR, déploiement HCM - paie, talent, formation. Poste ouvert.',
        'Lien': 'https://www.talentia-software.com/en/careers/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # ── ONGLET OFFRES CSM ──────────────────────────────────────────────────────

    # Samsara
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Enterprise Customer Success Manager (Remote France)',
        'Entreprise': 'Samsara',
        'Source': 'samsara.com / boards.greenhouse.io',
        'Contrat': 'CDI',
        'Localisation': 'Paris / Remote',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Fleet ops IoT, remote Paris, partenaire clients grands comptes, 20% déplacements France/UK.',
        'Lien': 'https://www.samsara.com/company/careers/roles/7613787?gh_jid=7613787',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Strategic Customer Success Manager - French Fluency (Remote France)',
        'Entreprise': 'Samsara',
        'Source': 'samsara.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris / Remote',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Niveau stratégique, comptes clés France, remote. Posté déc. 2025 - vérifier disponibilité.',
        'Lien': 'https://www.samsara.com/company/careers/roles/7495947?gh_jid=7495947',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Spendesk
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Team Lead Customer Success - Southern Europe',
        'Entreprise': 'Spendesk',
        'Source': 'career.spendesk.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste lead CSM Europe du Sud, Spendesk plateforme gestion dépenses SaaS. Posté 25/06/2026. 4+ ans requis. À vérifier si toujours actif.',
        'Lien': 'https://career.spendesk.com/jobs/7973782-team-lead-customer-success-southern-europe',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Brevo
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager - French Speaker',
        'Entreprise': 'Brevo',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Brevo (ex-Sendinblue) 800+ employés, 500k clients. Portfolio grands comptes, onboarding → renouvellement. 4 ans CSM requis.',
        'Lien': 'https://jobs.lever.co/brevo/8cba557a-b2f5-4652-bd86-5e000940239b',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # OpenAI
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager - Ads Solutions',
        'Entreprise': 'OpenAI',
        'Source': 'jobs.ashbyhq.com / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris (Hybride)',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'OpenAI équipe Ads Paris - poste très visible, posté 03/07/2026. Onboarding annonceurs ChatGPT Ads. Profil CSM + IA = parfait pour Gaëtan.',
        'Lien': 'https://jobs.ashbyhq.com/openai/3a2b9078-f4ac-4d97-89b2-2bbf59919796/application',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '95-115K€',
    },

    # Pigment
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager',
        'Entreprise': 'Pigment',
        'Source': 'welcometothejungle.com / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Pigment SaaS FP&A, scale-up $400M levés, clients Unilever/Snowflake/Siemens. CSM adoption + expansion. Posté juillet 2026.',
        'Lien': 'https://www.welcometothejungle.com/en/companies/pigment/jobs/customer-success-manager_paris_PIGME_VGbjy9',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Lucca
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success SIRH Grands Comptes',
        'Entreprise': 'Lucca',
        'Source': 'jobs.world.luccasoftware.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride (2j/sem)',
        'Salaire / TJM': '45-55K€',
        'Durée mission': '',
        'Fit / Notes': 'SIRH SaaS FR, clients Accor/Pernod Ricard/Deezer. Portfolio 2-3 grands comptes. 2 ans requis, C1/C2 EN. Posté 19/06/2026. Salaire en dessous de cible.',
        'Lien': 'https://jobs.world.luccasoftware.com/lucca/customer-success-sirh-grands-comptes-8d12e285-9f5c-4dcd-ba4c-661c80abe25c',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '60-70K€ (fourchette affichée basse)',
    },

    # Pleo
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager - France',
        'Entreprise': 'Pleo',
        'Source': 'boards.greenhouse.io',
        'Contrat': 'CDI',
        'Localisation': 'France (Remote)',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Pleo gestion dépenses B2B SaaS, marché France.',
        'Lien': 'https://boards.greenhouse.io/pleo/jobs/6339991003',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Temenos
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager',
        'Entreprise': 'Temenos',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Temenos éditeur banking core, posté il y a 6 heures (27/07/2026). Très récent.',
        'Lien': 'https://fr.linkedin.com/jobs/customer-success-manager-emplois-france',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # LinkedIn Lever Greenhouse CSM divers
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager (Remote from France)',
        'Entreprise': 'Jobgether',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDI',
        'Localisation': 'France (Remote)',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Plateforme matching emplois remote, rôle CSM B2B EMEA. Posté récemment.',
        'Lien': 'https://jobs.lever.co/jobgether/2cfe2bb1-31f9-4afa-adaf-41a8a45a0e05',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager - French Speaker',
        'Entreprise': 'Sitetracker',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDI',
        'Localisation': 'France/Benelux (Remote)',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Sitetracker gestion projets infrastructure, marché FR + Benelux. Senior CSM.',
        'Lien': 'https://jobs.lever.co/sitetracker/3d537233-47b4-4f8c-b393-6479ecabe968',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager - French, German or Dutch Fluency',
        'Entreprise': 'Samsara',
        'Source': 'boards.greenhouse.io',
        'Contrat': 'CDI',
        'Localisation': 'France (Remote)',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Fleet ops IoT, French speaker.',
        'Lien': 'https://boards.greenhouse.io/samsara/jobs/4141069?gh_jid=4141069',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Learning Customer Success Manager',
        'Entreprise': 'LumApps',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Valbonne',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'LumApps intranet social, CSM formation/adoption, posté il y a 6 jours',
        'Lien': 'https://fr.linkedin.com/jobs/customer-success-manager-emplois-france',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager (12 Month Fixed Term)',
        'Entreprise': 'LinkedIn',
        'Source': 'LinkedIn (fr.linkedin.com)',
        'Contrat': 'CDD 12 mois',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '12 mois',
        'Fit / Notes': 'LinkedIn interne, CDD - posté il y a 4 jours',
        'Lien': 'https://fr.linkedin.com/jobs/customer-success-manager-emplois-france',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # ── ONGLET OFFRES IA ────────────────────────────────────────────────────────

    # Mission Freelances
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant IA Générative & Conduite du changement',
        'Entreprise': 'Client non divulgué',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': 'Non précisée',
        'Fit / Notes': 'Accompagnement déploiement IA générative (ChatGPT/Gemini), ateliers acculturation, lien stratégie-métiers, mode Agile. Posté 17/06/2026. Fit parfait profil non-technique IA.',
        'Lien': 'https://www.mission-freelances.fr/missions/consultant-ia-generative-conduite-du-changement-paris-87a17202/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500-700€/j',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur / Formatrice en Intelligence Artificielle Générative',
        'Entreprise': 'Client non divulgué',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Île-de-France',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': 'Non précisée',
        'Fit / Notes': 'Formation certifiante IA générative, usage responsable IA. Outils ChatGPT/Gemini/Copilot. Certification RS6776 souhaitée. Posté 25/06/2026.',
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-formatrice-en-intelligence-artificielle-generative-ile-de-france-a5471a52/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '400-600€/j',
    },

    # Free-work.com IA
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur IA H/F',
        'Entreprise': 'OUICODING',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Formation IA freelance via OUICODING. Posté 2026.',
        'Lien': 'https://www.free-work.com/fr/tech-it/formateur/job-mission/formateur-ia-h-f',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '400-600€/j',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de projet SI – Support & Adoption Solution IA Conversationnelle (H/F)',
        'Entreprise': 'AVA2I',
        'Source': 'free-work.com',
        'Contrat': 'Freelance/CDI',
        'Localisation': 'Île-de-France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '3 ans',
        'Fit / Notes': 'Chef de projet adoption IA conversationnelle. Longue durée. Posté 20/07/2026. Croisement IA x SIRH.',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/assistant-chef-de-projet/chef-de-projet-si-support-adoption-dune-solution-dia-conversationnelle-h-f',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500-650€/j',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de projet IT Gouvernance des Données, RGPD & IA Act',
        'Entreprise': 'Deodis',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Île-de-France',
        'Remote': 'Partiel',
        'Salaire / TJM': '500€/j',
        'Durée mission': '1 an',
        'Fit / Notes': 'Chef de projet IA Act + RGPD, gouvernance données. TJM 500€/j. Posté 20/07/2026.',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/expert-e-protection-donnees/chef-de-projet-it-gouvernance-des-donnees-rgpd-ia-act',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500-600€/j',
    },
    {
        'Priorité': '⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de projet IA',
        'Entreprise': 'HN SERVICES',
        'Source': 'free-work.com',
        'Contrat': 'Freelance/CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '400-710€/j',
        'Durée mission': '6 mois',
        'Fit / Notes': 'Chef de projet IA généraliste. TJM 400-710€/j ou 40-70K€/an. Posté 15/07/2026.',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/assistant-chef-de-projet/ingenieur-ia-16',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500-650€/j',
    },

    # Michael Page
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Formateur IA & Management (H/F)',
        'Entreprise': 'Cabinet conseil (via Michael Page)',
        'Source': 'michaelpage.fr',
        'Contrat': 'CDI',
        'Localisation': 'Lille',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Concevoir et animer formations IA + management, expert IA interne, création offres RH innovantes. PME formation B2B. Fit excellent profil Gaëtan. Ref JN-032026-6962869.',
        'Lien': 'https://www.michaelpage.fr/job-detail/consultant-formateur-ia-management-hf/ref/jn-032026-6962869',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '70-85K€',
    },
]

if __name__ == '__main__':
    ajouter_offres(offres, verbose=True)
    print("\nTerminé. Offres ajoutées dans offres_emploi.xlsx")
