"""
Ajout des offres trouvées lors de la recherche exhaustive du 2026-08-05.

Sources couvertes : LinkedIn (catégories SuccessFactors Paris, CSM France, CSM monde,
consultant SIRH, SAP HCM, HRIS, formateur IA), free-work.com (SIRH, SAP SuccessFactors,
IA, IA générative), mission-freelances.fr, welcometothejungle.com, jobs.ashbyhq.com,
jobs.lever.co, boards.greenhouse.io, wellfound.com, whitehallresources.com, eursap.eu,
jobs.sap.com, careers.ey.com, apply.deloitte.com, careers.soprasteria.fr, wavestone.com,
jobs.hr-path.com, careers.alight.com/strada, careers.servicenow.com, opusresourcing.com,
himalayas.app, weworkremotely.com, euremotejobs.com, apec.fr, freelance-informatique.fr.

La très grande majorité des résultats remontés étaient déjà présents dans le tableur
(ACT-ON, HR Path, Deloitte, EY, SAP, Eramet, DXC, SQORUS, Washington Frank, LINKWAY,
Mindquest, Tenth Revolution, Camunda, Owkin, Brevo, Sitetracker, Harvey, Trustpair,
Jobgether CSM, OUICODING, Walter Learning, Groupe MDA, Experteam, Cherry Pick...).
Seules les offres réellement nouvelles sont ajoutées ici.

Sites en erreur ce jour : zalaris.com (404), himalayas.app (403), weworkremotely.com (429),
euremotejobs.com (403), hansonregan.com (404), freelance-informatique.fr (404),
careers.soprasteria.fr et wavestone.com (aucune offre RH/SIRH), apply.deloitte.com
(ne renvoie que des postes US), jobs.ashbyhq.com/deel (page JS vide).
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
import add_offre
from add_offre import ajouter_offres

# Routage explicite vers l'onglet "Offres IA" : plusieurs titres anglais
# ("AI Enablement Trainer", "AI Adoption Manager"...) ne matchent pas les
# mots-clés par défaut de add_offre.
POSTES_IA = {
    'AI Enablement Trainer - Claude Enterprise Adoption',
    'AI Enablement Lead',
    'AI Adoption & Training Manager',
    'AI Adoption Manager',
    'AI Enablement Specialist',
    'AI Strategy & Enablement Lead',
    'AI Transformation Engineer',
    'Responsable Augmentation IA des Métiers',
    'Responsable Pilotage IA de la Performance Commerciale H/F',
}
_is_ia_orig = add_offre._is_ia
add_offre._is_ia = lambda poste: poste in POSTES_IA or _is_ia_orig(poste)


offres = [

    # ── ONGLET OFFRES IA ───────────────────────────────────────────────────────

    # Neurons Lab — AI Enablement Trainer, adoption Claude Enterprise, freelance remote
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'AI Enablement Trainer - Claude Enterprise Adoption',
        'Entreprise': 'Neurons Lab',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'Freelance',
        'Localisation': 'Remote (Europe)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '6-12 semaines à partir de sept. 2026',
        'Fit / Notes': "Mission freelance 100% remote de formation à l'adoption de Claude Enterprise en entreprise, niveau senior face client. C'est exactement le croisement recherché : usage quotidien des outils IA générative, 15 ans de posture conseil face à des grands comptes, aucune exigence de data science. La mission cible le secteur BFSI, où l'expérience L'Oréal et grands comptes se transpose bien. Format court, donc cumulable avec une autre mission.",
        'Lien': 'https://jobs.ashbyhq.com/neurons-lab.com/89f15831-fbcc-48ce-bb4b-20655e16e10e',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '900-1100€/j',
    },

    # Multiverse — AI Enablement Lead
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'AI Enablement Lead',
        'Entreprise': 'Multiverse',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Europe (remote)',
        'Remote': 'Remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Multiverse est une plateforme d'upskilling IA travaillant avec plus de 1500 entreprises ; le poste consiste à piloter l'adoption de l'IA chez les clients. Le profil attendu combine conduite du changement, formation et relation client grands comptes, sans compétence data science. Le passé Customer Success sert directement la partie adoption et rétention.",
        'Lien': 'https://jobs.ashbyhq.com/multiverse/228b1670-2201-44a4-99a9-62f837864e49',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '85-100K€',
    },

    # Jobgether — AI Adoption Manager
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'AI Adoption Manager',
        'Entreprise': 'n.c. (via Jobgether)',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste centré sur l'accélération de l'adoption des solutions IA : conception de stratégies d'enablement et animation de programmes de formation. Jobgether publie en 100% remote, ce qui lève la contrainte géographique depuis Anglet. Le mélange formation + conduite du changement + suivi d'adoption reprend la mécanique du Customer Success appliquée à l'IA.",
        'Lien': 'https://jobs.lever.co/jobgether/e7ee624a-7e8d-48b4-a682-788b0eaea5ce',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '85-95K€',
    },

    # Jobgether — AI Enablement Specialist
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'AI Enablement Specialist',
        'Entreprise': 'n.c. (via Jobgether)',
        'Source': 'jobs.lever.co',
        'Contrat': 'Freelance / Consulting',
        'Localisation': 'Remote',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Mission de conseil en enablement IA, 100% remote et à horaires flexibles, publiée il y a une semaine. Le périmètre reste généraliste (acculturation, montée en compétence des équipes) plutôt que technique. À traiter comme un complément de la même famille que l'AI Adoption Manager du même diffuseur ; postuler aux deux.",
        'Lien': 'https://jobs.lever.co/jobgether/e436352e-751e-45f9-a2e3-072587338814',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '700-850€/j',
    },

    # Jobgether — AI Strategy & Enablement Lead
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'AI Strategy & Enablement Lead',
        'Entreprise': 'n.c. (via Jobgether)',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDI',
        'Localisation': 'Remote (monde)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste de lead sur la stratégie et l'enablement IA dans une organisation entièrement distribuée. Le niveau attendu est plus stratégique que les deux autres postes Jobgether ; l'expérience de co-fondateur de WallOfTraders.com et le pilotage de programmes mondiaux chez L'Oréal donnent la hauteur demandée. Publié en mai 2026, donc vérifier que l'offre reste ouverte avant de rédiger la LM.",
        'Lien': 'https://jobs.lever.co/jobgether/4c52dc4b-a501-4cc2-8907-e92704c02367',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '95-110K€',
    },

    # Vocal Media — AI Adoption & Training Manager
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'AI Adoption & Training Manager',
        'Entreprise': 'Vocal Media',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDD (jusqu\'à déc. 2026, extension possible)',
        'Localisation': 'Remote',
        'Remote': 'Remote',
        'Salaire / TJM': '',
        'Durée mission': "Jusqu'à décembre 2026",
        'Fit / Notes': "Poste dédié à la formation interne et à l'adoption de l'IA, en contrat jusqu'à fin 2026 avec extension possible. Le format temps plein limité dans le temps ressemble à une mission ; il conviendrait bien en attendant un CDI. Vérifier si l'entreprise accepte un contractant basé en France.",
        'Lien': 'https://jobs.lever.co/get-vocal-pbc/7e94f2ae-2749-402a-b94a-cbe7cb2ee9d2',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '80-90K€',
    },

    # Insider One — AI Transformation Engineer (Remote)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'AI Transformation Engineer',
        'Entreprise': 'Insider One',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Le poste consiste à coacher les équipes sur l'adoption de l'IA et à ancrer les changements de comportement, ce qui relève de la conduite du changement plus que de l'ingénierie. L'intitulé « Engineer » risque toutefois de cacher des attendus techniques ; lire la fiche complète avant de postuler.",
        'Lien': 'https://jobs.lever.co/insiderone/49f7e3c9-2a0e-4f45-99bd-1af880b7615b',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '80-95K€',
    },

    # Formateurs IA freelance — annonce LinkedIn relayée par mission-freelances.fr
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur IA freelance (vivier)',
        'Entreprise': 'n.c. (via LinkedIn / mission-freelances.fr)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Télétravail',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Appel à candidatures pour constituer un vivier de formateurs IA freelances en télétravail. Le TJM du marché formateur IA se situe entre 700 et 1300€/j selon les données collectées ce jour. Candidature à faible coût qui peut générer un flux de missions récurrentes.",
        'Lien': 'https://www.mission-freelances.fr/missions/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '800-1000€/j',
    },

    # Expert IA / Consultant en transformation — télétravail
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Expert IA / Consultant en transformation',
        'Entreprise': 'n.c. (via LinkedIn / mission-freelances.fr)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Télétravail',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Mission d'expertise IA orientée transformation, en télétravail intégral. Le libellé reste vague ; il faut ouvrir l'annonce LinkedIn pour vérifier qu'il ne s'agit pas d'un poste data science. Si le périmètre est bien conduite du changement, le fit est fort.",
        'Lien': 'https://www.mission-freelances.fr/missions/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '700-900€/j',
    },

    # Responsable Augmentation IA des Métiers — Paris
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Responsable Augmentation IA des Métiers',
        'Entreprise': 'n.c. (via HelloWork / mission-freelances.fr)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Le poste porte sur l'augmentation des métiers par l'IA, donc sur l'acculturation et l'outillage des équipes opérationnelles. C'est le type de rôle transverse où l'expérience SIRH mondiale sert de terrain d'application concret. Localisation Paris affichée ; négocier le remote dès le premier échange.",
        'Lien': 'https://www.mission-freelances.fr/missions/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '85-100K€',
    },

    # Responsable Pilotage IA de la Performance Commerciale — Paris
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Responsable Pilotage IA de la Performance Commerciale H/F',
        'Entreprise': 'n.c. (via HelloWork / mission-freelances.fr)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste à l'intersection IA et performance commerciale, donc proche du suivi de portefeuille et des indicateurs de rétention pratiqués en Customer Success. La dimension analytique risque d'être plus forte que sur les postes formateur IA ; à confirmer.",
        'Lien': 'https://www.mission-freelances.fr/missions/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '80-95K€',
    },

    # Formateur IA appliquée à l'acquisition client — télétravail
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': "Formateur IA appliquée à l'acquisition client",
        'Entreprise': 'n.c. (via Indeed / mission-freelances.fr)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Télétravail',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Formation à l'usage de l'IA sur les sujets d'acquisition client, en télétravail. Le sujet commercial reste dans la zone de confort après quinze ans de relation client ; le format formation correspond au transfert de connaissances déjà pratiqué sur les projets SIRH. Annonce publiée il y a trois semaines, vérifier qu'elle est toujours active.",
        'Lien': 'https://www.mission-freelances.fr/missions/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '700-850€/j',
    },

    # ── ONGLET OFFRES CSM ──────────────────────────────────────────────────────

    # Linear — Customer Success Manager, Europe
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager, Europe',
        'Entreprise': 'Linear',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Europe (remote)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Linear recrute un CSM Europe en remote ; l'entreprise est réputée pour ses standards produit élevés et sa culture distribuée. Le portefeuille est composé d'équipes tech exigeantes, ce qui rejoint le profil technico-fonctionnel construit sur quatorze ans de SAP. Concurrence forte sur ce poste ; soigner particulièrement la lettre.",
        'Lien': 'https://jobs.ashbyhq.com/Linear/c3457e89-9ac2-4017-93d5-d1a7935782a0',
        'CV à envoyer': 'Resume_GaetanFRANCOIS.html',
        'Prétention': '85-95K€',
    },

    # Stora — Multilingual CSM EU Markets
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager - EU Markets (multilingue)',
        'Entreprise': 'Stora',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Europe (remote)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste CSM multilingue sur les marchés européens, en remote. Le français, l'anglais, l'espagnol et le portugais couvrent une large partie des marchés visés, ce qui constitue un vrai différenciant sur cette annonce précise. Startup de taille modeste, donc rémunération probablement sous la fourchette cible.",
        'Lien': 'https://jobs.ashbyhq.com/stora/25c5499a-e52f-4466-9f25-3efbe9451345',
        'CV à envoyer': 'Resume_GaetanFRANCOIS.html',
        'Prétention': '75-85K€',
    },

    # voize — Founding Onboarding Manager & CSM France
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Founding Onboarding Manager & Customer Success Manager (France)',
        'Entreprise': 'voize',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'France',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Rôle fondateur du Customer Success sur le marché français d'une scale-up allemande de santé numérique. Le mandat couvre l'onboarding et la réussite client de bout en bout, ce qui correspond au parcours WallOfTraders.com additionné des quinze ans de CSM. Un poste fondateur laisse de la latitude pour imposer le 100% remote.",
        'Lien': 'https://jobs.ashbyhq.com/voize/61a799c2-7cbd-4829-8619-dec6ce647653',
        'CV à envoyer': 'Resume_GaetanFRANCOIS.html',
        'Prétention': '80-90K€',
    },

    # Modash.io — CSM Europe remote
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager, Europe',
        'Entreprise': 'Modash.io',
        'Source': 'wellfound.com',
        'Contrat': 'CDI',
        'Localisation': 'Europe (remote)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Équipe remote-first basée à Tallinn, portefeuille clients européen. Le fonctionnement entièrement distribué correspond à la contrainte géographique d'Anglet. Secteur influence marketing, donc éloigné du SIRH ; c'est le savoir-faire CSM pur qui est vendu ici.",
        'Lien': 'https://wellfound.com/jobs/4121641-customer-success-manager-europe',
        'CV à envoyer': 'Resume_GaetanFRANCOIS.html',
        'Prétention': '75-85K€',
    },

    # Amperon — Solutions Consultant & CSM remote
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Solutions Consultant & Customer Success Manager',
        'Entreprise': 'Amperon',
        'Source': 'wellfound.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste hybride avant-vente et Customer Success sur les comptes européens : onboarding, adoption, renouvellements et croissance. Ce double rôle correspond exactement à la cible pre-sales + CSM identifiée dans le projet. Le secteur énergie demande un effort d'acculturation métier.",
        'Lien': 'https://wellfound.com/jobs/4015331-solutions-consultant-customer-success-manager',
        'CV à envoyer': 'Resume_GaetanFRANCOIS.html',
        'Prétention': '85-95K€',
    },

    # Mento — Customer Success Coach (Director/VP+) UK/IE/Europe Remote
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Coach (Director/VP+)',
        'Entreprise': 'Mento',
        'Source': 'boards.greenhouse.io',
        'Contrat': 'CDI',
        'Localisation': 'UK / Irlande / Europe (remote)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Mento cherche des coachs de niveau directeur pour accompagner des professionnels du Customer Success. Le poste valorise l'ancienneté plutôt qu'un domaine produit ; quinze ans de CSM y répondent. Le format coaching reste éloigné d'un poste CSM classique, d'où la priorité intermédiaire.",
        'Lien': 'https://job-boards.greenhouse.io/mento/jobs/4687441005',
        'CV à envoyer': 'Resume_GaetanFRANCOIS.html',
        'Prétention': '80-95K€',
    },

    # XXII — CSM Puteaux
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager (F/H)',
        'Entreprise': 'XXII',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Puteaux (92)',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Scale-up française de vision par ordinateur, offre publiée il y a quatre jours. Le produit est technique et le client grand compte, ce qui joue en faveur du profil. Poste affiché à Puteaux ; le remote total sera à négocier et reste incertain sur ce type de structure.",
        'Lien': 'https://fr.linkedin.com/jobs/customer-success-manager-emplois-france',
        'CV à envoyer': 'Resume_GaetanFRANCOIS.html',
        'Prétention': '75-85K€',
    },

    # Figen AI — CSM Paris
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager',
        'Entreprise': 'Figen AI',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Offre publiée il y a moins de vingt-quatre heures, sur un éditeur IA parisien. Le croisement CSM et IA générative correspond à la double cible du projet ; c'est un des rares postes qui permet de valoriser les deux d'un coup. Structure jeune, donc vérifier le niveau de séniorité attendu et le budget.",
        'Lien': 'https://fr.linkedin.com/jobs/customer-success-manager-emplois-france',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '75-90K€',
    },

    # ── ONGLET OFFRES SIRH ─────────────────────────────────────────────────────

    # Whitehall Resources — SAP SuccessFactors ESM Consultant, remote total
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'SAP SuccessFactors ESM Consultant',
        'Entreprise': 'n.c. (via Whitehall Resources)',
        'Source': 'whitehallresources.com',
        'Contrat': 'Freelance',
        'Localisation': 'Anywhere (remote)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Mission SuccessFactors annoncée en remote total sans contrainte de pays, ce qui est rare sur ce marché. Whitehall place régulièrement des consultants SAP HR en Europe et le contact se fait directement avec un recruteur spécialisé. Référence BBBH67445 à citer lors de la prise de contact.",
        'Lien': 'https://www.whitehallresources.com/jobs/?search=SuccessFactors',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '650-750€/j',
    },

    # Collabora — People Operations Partner HRIS & Automation, remote France
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'People Operations Partner - HRIS & Automation',
        'Entreprise': 'Collabora',
        'Source': 'himalayas.app',
        'Contrat': 'CDI',
        'Localisation': 'Remote (France / UK / Canada)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste explicitement ouvert en remote depuis la France, centré sur la migration de données RH et l'implémentation SIRH avec du français exigé. La migration de données est précisément la spécialité construite sur les dix ans L'Oréal. Annonce publiée en janvier 2026 puis mise à jour en mars ; vérifier qu'elle est encore ouverte avant d'investir sur la LM.",
        'Lien': 'https://himalayas.app/companies/collabora/jobs/people-operations-partner-hris-automation-remote-france-uk-canada',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '80-95K€',
    },

    # HR Path — Consultant SAP SuccessFactors CoreHR (freelance)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP SuccessFactors CoreHR (freelance)',
        'Entreprise': 'HR Path',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '450-600€/j',
        'Durée mission': '',
        'Fit / Notes': "Mission Core HR SuccessFactors publiée le 04/08/2026, donc très fraîche. HR Path est déjà bien identifié dans le tableur et reste le meilleur point d'entrée français sur le SIRH. Le TJM affiché se situe sous la fourchette cible ; négocier vers le haut de la fourchette au vu des quatorze ans SAP.",
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sap-successfactors',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '600-650€/j',
    },

    # Freelance.com — Product Manager SIRH (Oracle HCM)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Product Manager SIRH (Oracle HCM)',
        'Entreprise': 'Freelance.com',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Île-de-France',
        'Remote': 'Partiel',
        'Salaire / TJM': '700€/j',
        'Durée mission': '',
        'Fit / Notes': "TJM de 700€ au-dessus de la fourchette cible freelance, sur un rôle de Product Manager SIRH. La partie produit rejoint l'expérience de co-fondateur ; l'environnement Oracle HCM demande en revanche un transfert depuis SAP à assumer honnêtement en entretien. Publiée le 30/07/2026.",
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '700€/j',
    },

    # VISIAN — Consultant Transformation RH Core HR
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Transformation RH - Core HR',
        'Entreprise': 'VISIAN',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Mission de transformation RH sur le Core HR publiée le 04/08/2026. Le périmètre correspond au cœur de l'expertise SIRH ; le TJM reste à négocier puisqu'il n'est pas affiché. VISIAN place régulièrement sur des programmes RH de grands comptes.",
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '650-750€/j',
    },

    # HAYS France — Chef de Projet SIRH Bordeaux
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de Projet SIRH (Bordeaux)',
        'Entreprise': 'HAYS France',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Bordeaux',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Mission de chef de projet SIRH à Bordeaux, publiée le 04/08/2026. Bordeaux est à environ deux heures d'Anglet, ce qui rend un rythme hybride tenable même sans remote total. Correspond directement à la cible chef de projet SIRH du projet.",
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '650-750€/j',
    },

    # Byrongroup — Support SIRH/Paie Bordeaux
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Support SIRH / Paie',
        'Entreprise': 'Byrongroup',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Bordeaux',
        'Remote': 'Partiel',
        'Salaire / TJM': '600-700€/j',
        'Durée mission': '',
        'Fit / Notes': "TJM de 600 à 700€ dans la fourchette cible, mission basée à Bordeaux donc accessible depuis Anglet. Le support applicatif SIRH et paie reprend une part importante du quotidien sur le compte L'Oréal. Publiée le 16/07/2026, donc à contacter rapidement.",
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '650-700€/j',
    },

    # Montreal Associates — Gestionnaire d'Application SIRH Bretagne
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': "Gestionnaire d'Application SIRH",
        'Entreprise': 'Montreal Associates',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Bretagne',
        'Remote': 'Partiel',
        'Salaire / TJM': '400-600€/j',
        'Durée mission': '',
        'Fit / Notes': "Mission d'administration applicative SIRH en Bretagne, publiée le 30/07/2026. Le TJM plafonne à 600€, sous la fourchette cible, et la localisation impose des déplacements longs depuis Anglet. À retenir seulement si le remote est largement ouvert.",
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '600€/j',
    },

    # Lùkla — Product Manager/Owner SIRH Rouen
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Product Manager / Product Owner SIRH',
        'Entreprise': 'Lùkla',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Rouen',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste de Product Owner SIRH, l'une des cibles explicites du projet, croisant expérience startup et spécifications fonctionnelles. Publiée le 14/07/2026 et localisée à Rouen, ce qui suppose un remote large pour être viable. TJM non affiché.",
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sirh',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '650-700€/j',
    },

    # Peppermint Company — AMOA SIRH Paris (CDI)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'AMOA SIRH',
        'Entreprise': 'Peppermint Company',
        'Source': 'free-work.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Offre en CDI sur un poste AMOA SIRH, qui fait partie des cibles listées dans le projet. Le rôle couvre les spécifications fonctionnelles et la recette, terrain maîtrisé depuis les projets L'Oréal quarante pays. Poste parisien ; le remote total sera le point de négociation principal.",
        'Lien': 'https://www.free-work.com/fr/tech-it/administrateur-applicatif-erp-crm-sirh/job-mission/amoa-sirh-30',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '70-85K€',
    },

    # STHREE / Computer Futures — Test Lead Workday HCM
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Test Lead Workday HCM (SIRH)',
        'Entreprise': 'STHREE SAS pour Computer Futures',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris (75)',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Mission de pilotage des phases de test sur des projets SIRH internationaux, avec Workday, SuccessFactors et Oracle HCM cités. La recette et les TNR en contexte international sont une compétence directement transposable. L'outil principal reste Workday, ce qui affaiblit un peu l'argumentaire SAP.",
        'Lien': 'https://www.free-work.com/fr/tech-it/administrateur-applicatif-erp-crm-sirh/job-mission/test-lead-workday-hcm-sirh',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '650-700€/j',
    },

    # HR Path — Consultant Oracle HCM freelance IDF
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Oracle HCM (H/F)',
        'Entreprise': 'HR Path',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Île-de-France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Mission Oracle HCM chez HR Path, acteur déjà identifié comme prioritaire. L'écart technologique avec SAP est réel et sera le principal obstacle ; l'argument à porter est la maîtrise des processus RH et de la migration de données plutôt que l'outil. Utile aussi pour entretenir la relation avec HR Path.",
        'Lien': 'https://www.free-work.com/fr/tech-it/consultant-erp-ms-dynamics-oracle-sage-sap/job-mission/consultant-oracle-hcm-h-f',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '600-700€/j',
    },

    # N2jsoft — Consultant SIRH N2F 100% remote
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH (H/F) - N2F',
        'Entreprise': 'N2jsoft',
        'Source': 'welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'Montagnat (remote)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste en CDI intégralement remote chez l'éditeur de N2F, avec formation interne sur le produit. Le remote total lève la contrainte principale ; le chef de projet SIRH du même éditeur est déjà suivi dans le tableur. Éditeur de taille moyenne, donc rémunération probablement sous la fourchette cible.",
        'Lien': 'https://www.welcometothejungle.com/en/companies/n2jsoft-fr/jobs/consultant-logiciel-rh-h-f-n2f_montagnat_N2JSO_M2lVjoW',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '65-75K€',
    },

    # N2jsoft — Consultant SIRH bilingue FR/IT 100% remote
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH bilingue Français/Italien (H/F)',
        'Entreprise': 'N2jsoft',
        'Source': 'welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'Montagnat (remote)',
        'Remote': '100% remote',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Même éditeur et même format 100% remote, avec l'italien exigé en plus. L'italien ne figure pas dans les langues maîtrisées, ce qui rend cette variante moins accessible que le poste généraliste. À garder comme porte d'entrée secondaire chez N2jsoft.",
        'Lien': 'https://www.welcometothejungle.com/en/companies/n2jsoft-fr/jobs/consultant-sirh-bilingue-francais-italien-h-f_montagnat',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '65-75K€',
    },

    # Mantu — Consultant SIRH Talentsoft Paris
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH Talentsoft (H/F)',
        'Entreprise': 'Mantu',
        'Source': 'welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste d'implémentation Talentsoft chez Mantu, en CDI parisien. Le déploiement d'une solution RH SaaS chez des clients variés correspond au parcours de conseil SIRH ; Talentsoft reste toutefois une solution non pratiquée. Ni remote ni salaire précisés dans l'annonce.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/mantu/jobs/consultant-sirh-talentsoft_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '70-80K€',
    },

    # Back Market — Global HRIS Specialist
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Global HRIS Specialist',
        'Entreprise': 'Back Market',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris / Bordeaux',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste HRIS global publié il y a quatre jours et ouvert sur Bordeaux, ce qui est rare et exploitable depuis Anglet. Back Market est une licorne française avec une dimension internationale réelle, terrain proche du périmètre mondial L'Oréal. À traiter en priorité sur l'antenne bordelaise.",
        'Lien': 'https://fr.linkedin.com/jobs/hris-emplois',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '75-90K€',
    },

    # Valeo — HR Technology Specialist
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'HR Technology Specialist H/F',
        'Entreprise': 'Valeo',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Cergy-Pontoise (95)',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Équipementier automobile mondial, poste republié il y a trois jours donc actif. Le contexte industriel multi-pays reprend la configuration L'Oréal quarante pays. Un poste AI Adoption Leader chez Valeo est déjà suivi dans le tableur ; une seule candidature bien ciblée vaut mieux que deux dispersées.",
        'Lien': 'https://fr.linkedin.com/jobs/hris-emplois',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '75-90K€',
    },

    # IT MATES — Consultant RH SAP
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant RH SAP',
        'Entreprise': 'IT MATES',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Seine-Saint-Denis (93)',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste de consultant SAP RH publié il y a une semaine, au cœur exact des quatorze ans d'expertise SAP HR. La structure est une ESN de taille modeste, ce qui plafonne souvent la rémunération. La candidature demande peu d'effort puisque le fit technique se démontre en quelques lignes.",
        'Lien': 'https://fr.linkedin.com/jobs/sap-hcm-emplois',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '70-85K€',
    },

    # L-Acoustics — Workday HRIS Specialist
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Workday HRIS Specialist',
        'Entreprise': 'L-Acoustics',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Massy (91)',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Entreprise française reconnue mondialement sur l'audio professionnel, poste HRIS interne. L'outil est Workday et non SAP, ce qui impose de vendre la logique SIRH plutôt que l'outil. Localisation Massy sans remote confirmé, à clarifier dès le premier échange.",
        'Lien': 'https://fr.linkedin.com/jobs/hris-emplois',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '70-85K€',
    },

    # EFOR — Workday Specialist
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Workday Specialist',
        'Entreprise': 'EFOR',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Champagne',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste Workday chez un groupe de conseil en sciences de la vie, publié il y a une semaine. L'écart d'outil et l'éloignement géographique en font une option secondaire. À conserver pour élargir le vivier Workday si les pistes SAP ralentissent.",
        'Lien': 'https://fr.linkedin.com/jobs/hris-emplois',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.html',
        'Prétention': '70-80K€',
    },

    # Skechers — Workday HRIS Senior Analyst
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Workday HRIS Senior Analyst',
        'Entreprise': 'Skechers',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste senior HRIS chez une marque internationale de grande consommation, publié il y a quatre jours. Le contexte retail mondial rappelle L'Oréal et le niveau senior correspond ; l'environnement Workday reste le point faible. Le CV visuel HRIS en anglais convient bien à cette annonce.",
        'Lien': 'https://fr.linkedin.com/jobs/hris-emplois',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '75-90K€',
    },

    # Whitehall Resources — SAP SuccessFactors Architect (hybride Angleterre)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'SAP SuccessFactors Architect',
        'Entreprise': 'n.c. (via Whitehall Resources)',
        'Source': 'whitehallresources.com',
        'Contrat': 'CDI',
        'Localisation': 'Angleterre (hybride)',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': "Poste d'architecte SuccessFactors en CDI, en hybride depuis l'Angleterre. La question du visa et de la présence sur site rend l'option compliquée depuis Anglet, comme pour SAP Taulia Londres. À tenter uniquement si le recruteur confirme un remote depuis la France. Référence BBBH67575.",
        'Lien': 'https://www.whitehallresources.com/jobs/?search=SuccessFactors',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.html',
        'Prétention': '95-110K€',
    },
]

ajouter_offres(offres)
