# -*- coding: utf-8 -*-
"""Première relance de l'onglet Offres UX, créé le 10/09/2026."""

from add_offre import ajouter_offres

AUJOURDHUI = "2026-09-10"
CV_UX = "Resume_GaetanFRANCOIS_UXLead.pdf"

offres = [
    # ───────────── Offres UX — 100% remote confirmé ─────────────
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Senior/Staff Product Designer',
        'Entreprise': 'n8n', 'Source': 'Ashby',
        'Lien': 'https://jobs.ashbyhq.com/n8n/fe05c209-8069-4a88-aeba-8da23488cd30',
        'Contrat': 'CDI', 'Localisation': 'Allemagne (siège) + France en localisation secondaire remote', 'Remote': 'Oui (Remote EU, France incluse)',
        'Fit / Notes': "Éditeur no-code/agentique ; le profil de fondateur qui vibe-code avec Claude Code (Lifaia.com, ArchiKK.com) parle directement à ce type de produit.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Head of Product Design',
        'Entreprise': 'n8n', 'Source': 'Ashby',
        'Lien': 'https://jobs.ashbyhq.com/n8n/eee6e2dc-c565-4cef-adee-a054b59b1c28',
        'Contrat': 'CDI', 'Localisation': 'Berlin (siège) + France en localisation secondaire remote', 'Remote': 'Oui (Remote EU, France incluse)',
        'Fit / Notes': "Poste de lead ; valorise le rôle réel de responsable UX solo chez WallOfTraders.com (structurer une démarche UX de zéro).",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Senior Product Designer (Full Remote - France)',
        'Entreprise': 'EverAI', 'Source': 'Ashby',
        'Lien': 'https://jobs.ashbyhq.com/everai/7ab9cf04-5fe3-4d7b-83de-4b069046b9ab',
        'Contrat': 'CDI', 'Localisation': 'France explicite', 'Remote': 'Oui',
        'Fit / Notes': "Éditeur IA (compagnon IA, 50M utilisateurs) ; double fit produit IA + UX, France nommée explicitement.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Senior Product Designer - Remote Europe',
        'Entreprise': 'Reedsy', 'Source': 'Ashby',
        'Lien': 'https://jobs.ashbyhq.com/reedsy/5b054faf-e032-44d2-90f4-60a6b1241937',
        'Contrat': 'CDI', 'Localisation': 'UK (siège) + France en localisation secondaire remote', 'Remote': 'Oui (Remote Europe, France incluse)',
        'Fit / Notes': "Plateforme SaaS édition/auteurs, produit B2B/B2C proche de la taille de WallOfTraders.com.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'UX Designer - Environnement Complexe Systèmes Multiples',
        'Entreprise': 'SILKHOM (client anonymisé)', 'Source': 'free-work.com',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/chef-de-projet-systemes-et-reseaux/ux-designer-environnement-complexe-systemes-multiples',
        'Contrat': 'Freelance', 'Localisation': 'Toulouse', 'Remote': 'Oui (100% télétravail)',
        'Durée mission': '3 mois',
        'Fit / Notes': "Mission UX pure, écosystème multi-outils (D365/ServiceNow), proche de la polyvalence technique du profil.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Designer - Figma - Loyalty',
        'Entreprise': 'KUBE Partners / Pixie Services', 'Source': 'free-work.com',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/product-owner/product-designer-figma-loyalty',
        'Contrat': 'Freelance', 'Localisation': 'France', 'Remote': 'Oui (100% télétravail)',
        'Durée mission': '3 ans',
        'Fit / Notes': "Produit loyalty/Figma, format mission longue compatible avec le profil consultant.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Designer UX/UI - SaaS B2B / IA Générative / Agentique',
        'Entreprise': 'KatchMe Consulting', 'Source': 'free-work.com',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/product-owner/product-designer-ux-ui-saas-b2b-ia-generative-agentique',
        'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Oui (100% télétravail)',
        'Durée mission': '6 mois',
        'Fit / Notes': "SaaS B2B + IA générative/agentique, très proche du double profil PM/UX + pratique IA de Gaëtan.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },

    # ───────────── Offres UX — Jobgether (remote France confirmé, employeur anonymisé) ─────────────
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Designer - Editor',
        'Entreprise': 'Client anonymisé (Jobgether, plateforme IA création contenu publicitaire)', 'Source': 'Lever (Jobgether)',
        'Lien': 'https://jobs.lever.co/jobgether/8f5eb23c-0c82-41a5-a5cf-b8bcafb8bf00',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui',
        'Fit / Notes': "Employeur non révélé avant candidature (pratique Jobgether standard) ; produit IA de création de contenu publicitaire.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Lead Product Designer',
        'Entreprise': 'Client anonymisé (Jobgether, produit de paiement)', 'Source': 'Lever (Jobgether)',
        'Lien': 'https://jobs.lever.co/jobgether/c3646619-19f0-449e-9b2a-9adb1b61fbd4',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui',
        'Fit / Notes': "Poste de lead, Design System mentionné ; employeur non révélé avant candidature.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Senior Product Designer - Mobile',
        'Entreprise': 'Client anonymisé (Jobgether)', 'Source': 'Lever (Jobgether)',
        'Lien': 'https://jobs.lever.co/jobgether/6afa235b-0579-4991-bcd5-16ed2f499d93',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui',
        'Fit / Notes': "Produit mobile iOS/Android B2B+B2C ; employeur non révélé avant candidature.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },

    # ───────────── Offres UX — télétravail non précisé (reste onglet métier, règle du 18/08) ─────────────
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Head Of UX-UI H/F',
        'Entreprise': 'Veepee', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/73262873.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': "Grand groupe e-commerce, poste de lead UX/UI.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Ux Designer B2e H/F',
        'Entreprise': 'Nexton', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/81120558.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': "UX Designer générique.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'CDI Ui-Ux Designer H/F',
        'Entreprise': 'Shiro Games', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82077672.html',
        'Contrat': 'CDI', 'Localisation': 'Bordeaux', 'Remote': 'Non précisé',
        'Fit / Notes': "Studio de jeux vidéo, UI/UX Designer.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Ux-Ui Designer H/F',
        'Entreprise': 'European Dynamics', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82113830.html',
        'Contrat': 'CDI', 'Localisation': 'Strasbourg', 'Remote': 'Non précisé',
        'Fit / Notes': "UX/UI Designer générique.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Designer Ux Expérimenté H/F',
        'Entreprise': 'Klanik', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82886358.html',
        'Contrat': 'CDI', 'Localisation': 'Montpellier', 'Remote': 'Non précisé',
        'Fit / Notes': "UX Designer expérimenté.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Senior Ux-Ui Designer H/F',
        'Entreprise': 'Geser Best', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82903810.html',
        'Contrat': 'CDI', 'Localisation': 'Strasbourg', 'Remote': 'Non précisé',
        'Fit / Notes': "UX/UI Designer senior.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'User Experience-User Interface Designer 3B-23 H/F',
        'Entreprise': 'SSA', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82943744.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': "UX/UI Designer générique.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Ux Designer',
        'Entreprise': 'Smile Group', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83067935.html',
        'Contrat': 'CDI', 'Localisation': 'Montpellier', 'Remote': 'Non précisé',
        'Fit / Notes': "UX Designer générique, ESN.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Ux Designer',
        'Entreprise': 'Smile Group', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83067937.html',
        'Contrat': 'CDI', 'Localisation': 'Lyon', 'Remote': 'Non précisé',
        'Fit / Notes': "UX Designer générique, ESN, poste jumeau (ville différente).",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Ux Designer - Vannes',
        'Entreprise': 'Smile Group', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83067938.html',
        'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': 'Non précisé',
        'Fit / Notes': "UX Designer générique, ESN, poste jumeau (ville différente).",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Ux & Digital Product Specialist - Iot',
        'Entreprise': 'Airbus Defense and Space', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83128631.html',
        'Contrat': 'CDI', 'Localisation': 'Toulouse', 'Remote': 'Non précisé',
        'Fit / Notes': "Grand groupe aéronautique/défense, croisement UX + produit IoT.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Ux-Ui Designer H/F',
        'Entreprise': 'Nexton', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83161482.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': "UX/UI Designer générique.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Designer Senior H/F',
        'Entreprise': 'Menlog', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83173826.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': "Product Designer senior.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Designer H/F',
        'Entreprise': 'eXalt Company', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83203686.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': "Product Designer générique.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Ui-Ux Designer - Produits B2B Electronique',
        'Entreprise': 'Client confidentiel (via Michael Page)', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82779637.html',
        'Contrat': 'CDI', 'Localisation': 'Levallois-Perret', 'Remote': 'Non précisé (mention "Télétravail" sans fréquence précisée)',
        'Fit / Notes': "Produits B2B électroniques, UI/UX.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },

    # ───────────── NoRemote (télétravail exclu ou partiel confirmé) ─────────────
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'UX-UI Designer Confirmé',
        'Entreprise': 'Sopra Steria', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/71907314.html',
        'Contrat': 'CDI', 'Localisation': 'Courbevoie', 'Remote': 'Hybride (2j/sem)',
        'Fit / Notes': "UX/UI Designer confirmé.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'UX Designer',
        'Entreprise': 'Scalian', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/78439793.html',
        'Contrat': 'CDI', 'Localisation': 'Montpellier', 'Remote': 'Hybride (2j/sem)',
        'Fit / Notes': "UX Designer, ESN.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'UX Designer Senior',
        'Entreprise': 'Scalian', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/80785943.html',
        'Contrat': 'CDI', 'Localisation': 'Neuilly', 'Remote': 'Hybride (2-3j/sem + présence régulière)',
        'Fit / Notes': "UX Designer senior, ESN.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Designer Cadrage & UX-UI',
        'Entreprise': 'Suricatsold', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/80894764.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride (télétravail conditionnel)',
        'Fit / Notes': "Cadrage & UX/UI.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': "Pilote d'Activité Design UX",
        'Entreprise': 'EDF', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/81051832.html',
        'Contrat': 'CDI', 'Localisation': 'Lyon', 'Remote': 'Hybride (2j/sem)',
        'Fit / Notes': "Grand groupe énergie, pilotage d'activité design UX.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'UX-UI Designer',
        'Entreprise': 'Atol Conseils', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82106759.html',
        'Contrat': 'CDI', 'Localisation': 'Dijon', 'Remote': 'Hybride (2j/sem)',
        'Fit / Notes': "UX/UI Designer, ESN.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐', 'Statut': AUJOURDHUI, 'Poste': 'Chef de Projets Junior UX-UI',
        'Entreprise': 'ACRELEC', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82176800.html',
        'Contrat': 'CDI', 'Localisation': 'Saint-Thibault-des-Vignes', 'Remote': 'Hybride (2j/sem après 3 mois)',
        'Fit / Notes': "Poste junior, moins aligné avec le niveau senior du profil.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Designer UX',
        'Entreprise': 'MONAPP', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83026077.html',
        'Contrat': 'CDI', 'Localisation': 'Marseille', 'Remote': 'Présentiel ("pas de télétravail" explicite)',
        'Fit / Notes': "UX Designer générique.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'UX Researcher Confirmé',
        'Entreprise': 'Caboost', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83048544.html',
        'Contrat': 'CDI', 'Localisation': 'Lille', 'Remote': 'Hybride (partiel sur site)',
        'Fit / Notes': "UX Researcher confirmé.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'UX Designer Senior',
        'Entreprise': 'Selfing', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83192657.html',
        'Contrat': 'CDI', 'Localisation': 'Saint-Rémy-lès-Chevreuse', 'Remote': 'Hybride (présentiel + partiel occasionnel)',
        'Fit / Notes': "UX Designer senior.",
        'CV à envoyer': CV_UX, 'Date trouvée': AUJOURDHUI,
    },
]

if __name__ == '__main__':
    ajouter_offres(offres, verbose=True)
