"""Relance de recherche exhaustive du 13/08/2026 - toutes sources CLAUDE.md."""

import add_offre

add_offre.COLS = add_offre.COLS + ['Date trouvée', 'Date publiée']

D = '13/08/2026'
FW = 'https://www.free-work.com'

CV_SIRH_FR = 'Resume_GaetanFRANCOIS_SIRH.pdf'
CV_SIRH_EN = 'Resume_GaetanFRANCOIS_SIRH_EN.pdf'
CV_CSM_EN = 'CV_GaetanFRANCOIS_CSM_EN.pdf'
CV_IA = 'Resume_GaetanFRANCOIS_IA.pdf'

OFFRES = [

    # ================= SIRH / SAP - free-work.com/jobs/sirh =================
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Consultant SAP SuccessFactors CoreHR (H/F)',
        'Entreprise': 'HR Path', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '450-600 €/j', 'Durée mission': '3 mois',
        'Fit / Notes': "SuccessFactors Core HR chez le cabinet SIRH le plus ciblé du marché français ; cœur de compétence de Gaëtan.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-corehr-h-f',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '10/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Expert SAP SuccessFactors',
        'Entreprise': 'LeHibou', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Saint-Ouen-sur-Seine', 'Remote': None,
        'Salaire / TJM': '575 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "Poste d'expert SuccessFactors sur mission longue via LeHibou ; correspond directement aux 14 ans SAP HR.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/expert-sap-successfactors-1',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '05/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de projet IT / Responsable SIRH (H/F)',
        'Entreprise': 'LeHibou', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Bordeaux', 'Remote': None,
        'Salaire / TJM': '675 €/j', 'Durée mission': '9 mois',
        'Fit / Notes': "Mission publiée aujourd'hui, Nouvelle-Aquitaine donc proche d'Anglet ; pilotage SIRH complet.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/chef-de-projet-it-responsable-sirh-h-f',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '675 €/j',
        'Date trouvée': D, 'Date publiée': '13/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Manager SIRH',
        'Entreprise': 'HR DNA', 'Source': 'free-work',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '60-110 K€', 'Durée mission': None,
        'Fit / Notes': "Poste de manager SIRH avec fourchette haute ; niveau de séniorité cohérent avec le parcours.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/manager-sirh-11',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '90-110 K€',
        'Date trouvée': D, 'Date publiée': '12/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de projet MOE SIRH H/F',
        'Entreprise': 'HAYS France', 'Source': 'free-work',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Chef de projet SIRH côté MOE, une des cibles explicites du profil.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/chef-de-projet-moe-sirh-h-f-1',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '12/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant Transformation RH - Core HR',
        'Entreprise': 'VISIAN', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': '1 an',
        'Fit / Notes': "Transformation RH sur périmètre Core HR, mission longue ; profil consultant senior attendu.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant/consultant-transformation-rh-core-hr',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '04/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Consultant Transformation RH - Target Operating Model & Core HR',
        'Entreprise': 'NOVAMINDS', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Île-de-France', 'Remote': None,
        'Salaire / TJM': '650 €/j', 'Durée mission': '4 mois',
        'Fit / Notes': "Mission senior sur le modèle opérationnel RH et le Core HR ; TJM aligné sur la cible freelance.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant/senior-consultant-transformation-rh-target-operating-model-core-hr',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650 €/j',
        'Date trouvée': D, 'Date publiée': '03/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Consultant Transformation RH - TOM & Core HR',
        'Entreprise': 'Mon Consultant Indépendant', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '500-550 €/j', 'Durée mission': '4 mois',
        'Fit / Notes': "Même famille de mission que NOVAMINDS, client différent ; transformation RH senior.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant/senior-consultant-transformation-rh-target-operating-model-core-hr-1',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '550 €/j',
        'Date trouvée': D, 'Date publiée': '03/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de Projet SIRH (H/F)',
        'Entreprise': 'HAYS France', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Bordeaux', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': '6 mois',
        'Fit / Notes': "Chef de projet SIRH en Nouvelle-Aquitaine, région proche d'Anglet.",
        'Lien': FW + '/fr/tech-it/job-mission/autre/chef-de-projet-sirh-h-f-79',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '04/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Project Manager SIRH',
        'Entreprise': 'DSI group', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Luxembourg', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': '5 mois',
        'Fit / Notes': "Chef de projet SIRH au Luxembourg ; contexte international, anglais courant utile.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/project-manager-sirh-2',
        'CV à envoyer': CV_SIRH_EN, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '11/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': "Gestionnaire d'Application SIRH",
        'Entreprise': 'Montreal Associates', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Bretagne', 'Remote': None,
        'Salaire / TJM': '400-600 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "Gestion applicative SIRH ; poste plus run que projet mais dans le périmètre.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/gestionnaire-dapplication-sirh',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '600 €/j',
        'Date trouvée': D, 'Date publiée': '05/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chargé de missions SIRH N2 - Workday HCM (H/F)',
        'Entreprise': 'HR DNA', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Neuilly-sur-Marne', 'Remote': None,
        'Salaire / TJM': '250-500 €/j', 'Durée mission': '24 mois',
        'Fit / Notes': "Mission SIRH de 2 ans sur Workday ; outil différent de SAP mais logique fonctionnelle transférable.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/charge-de-missions-sirh-n2-workday-hcm-h-f-25',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '500 €/j',
        'Date trouvée': D, 'Date publiée': '10/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant AMOA Workday HCM (H/F)',
        'Entreprise': 'HR Path', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Lyon', 'Remote': None,
        'Salaire / TJM': '550-600 €/j', 'Durée mission': '3 mois',
        'Fit / Notes': "AMOA SIRH chez HR Path ; la posture MOA est une cible du profil, Workday à monter en compétence.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant-moa-amoa/consultant-amoa-workday-hcm-h-f',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '600 €/j',
        'Date trouvée': D, 'Date publiée': '10/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Expert Workday HCM N2/N3',
        'Entreprise': 'HR DNA', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Saint-Ouen-sur-Seine', 'Remote': None,
        'Salaire / TJM': '325-650 €/j', 'Durée mission': '24 mois',
        'Fit / Notes': "Mission longue Workday, niveau expert ; hors SAP mais SIRH pur.",
        'Lien': FW + '/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-workday-hcm-n2-n3-3',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650 €/j',
        'Date trouvée': D, 'Date publiée': '05/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager SIRH / Chef de Projet SIRH (Oracle HCM) H/F',
        'Entreprise': 'Freelance.com', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Île-de-France', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': '3 ans',
        'Fit / Notes': "Mission de 3 ans mêlant Product Manager et chef de projet SIRH ; deux cibles du profil réunies.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-de-base-de-donnee-oracle-sybase/product-manager-sirh-chef-de-projet-sirh-oracle-hcm-h-f',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '05/08/2026',
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Consultant Technico-Fonctionnel HR Access Paie (H/F)',
        'Entreprise': 'HR DNA', 'Source': 'free-work',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '60-65 K€', 'Durée mission': None,
        'Fit / Notes': "Poste HR Access orienté paie ; périmètre SIRH mais outil non maîtrisé.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant-fonctionnel/consultant-technico-fonctionnel-hr-access-paie-h-f-6',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '12/08/2026',
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Adjoint(e) Responsable Paie (H/F)',
        'Entreprise': 'HR Path', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '650-700 €/j', 'Durée mission': '3 mois',
        'Fit / Notes': "Poste paie opérationnelle ; TJM correct mais métier éloigné du pilotage SIRH.",
        'Lien': FW + '/fr/tech-it/job-mission/directeur-de-la-data-cdo/adjoint-e-responsable-paie-h-f',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '700 €/j',
        'Date trouvée': D, 'Date publiée': '04/08/2026',
    },

    # ================= SIRH - free-work pages 2 et 3 =================
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'PMO SIRH H/F',
        'Entreprise': 'HAYS France', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Guyancourt', 'Remote': None,
        'Salaire / TJM': '450-540 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "PMO sur programme SIRH ; correspond au rôle tenu sur les déploiements L'Oréal multi-pays.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/pmo-sirh-h-f',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '540 €/j',
        'Date trouvée': D, 'Date publiée': '06/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Directeur de Projet SIRH',
        'Entreprise': 'EXteam', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Île-de-France', 'Remote': None,
        'Salaire / TJM': '630-730 €/j', 'Durée mission': '3 ans',
        'Fit / Notes': "Direction de projet SIRH sur 3 ans ; séniorité et TJM cohérents avec la cible.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/directeur-de-projet-sirh-7',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '730 €/j',
        'Date trouvée': D, 'Date publiée': '15/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Architecte Solution / Opérationnel SIRH (H/F)',
        'Entreprise': 'Insitoo Freelances', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Lyon', 'Remote': None,
        'Salaire / TJM': '500-590 €/j', 'Durée mission': '2 ans',
        'Fit / Notes': "Architecture de solution SIRH sur mission longue ; volet plus technique que le cœur du profil.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/architecte-solution-operationnel-sirh-h-f',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '590 €/j',
        'Date trouvée': D, 'Date publiée': '09/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Business product owner SIRH',
        'Entreprise': 'Mon Consultant Indépendant', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '500-550 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "Product Owner SIRH côté métier ; croise l'expérience startup et le lien métier/dev.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/business-product-owner-sirh',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '550 €/j',
        'Date trouvée': D, 'Date publiée': '23/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chef de projet fonctionnel SIRH - secteur immobilier',
        'Entreprise': 'Mon Consultant Indépendant', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '550-590 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "Chef de projet SIRH fonctionnel, secteur immobilier ; profil MOA attendu.",
        'Lien': FW + '/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/chef-de-projet-fonctionnel-sirh-secteur-de-limmobilier',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '590 €/j',
        'Date trouvée': D, 'Date publiée': '23/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Directeur de Projet Data - Refonte Décisionnel RH (H/F)',
        'Entreprise': 'Cherry Pick', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Orly', 'Remote': None,
        'Salaire / TJM': '760 €/j', 'Durée mission': '12 mois',
        'Fit / Notes': "Direction de projet sur le décisionnel RH ; croise data RH et pilotage de programme.",
        'Lien': FW + '/fr/tech-it/job-mission/directeur-de-la-data-cdo/directeur-de-projet-data-refonte-decisionnel-rh-h-f',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '760 €/j',
        'Date trouvée': D, 'Date publiée': '16/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Business Analyst SIRH Technico-Fonctionnel - TalentSoft / HR Access (F/H)',
        'Entreprise': 'CELAD', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '450-500 €/j', 'Durée mission': '1 an',
        'Fit / Notes': "Business Analyst SIRH, une des cibles MOA du profil ; outils TalentSoft et HR Access.",
        'Lien': FW + '/fr/tech-it/job-mission/business-analyst/business-analyst-sirh-technico-fonctionnel-talentsoft-hr-access-f-h',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '500 €/j',
        'Date trouvée': D, 'Date publiée': '08/07/2026',
    },

    # ================= SAP HCM - free-work.com/jobs/sap-hcm =================
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Expert Technico-Fonctionnel SAP HCM',
        'Entreprise': 'INFOTEL CONSEIL', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Roissy-en-France', 'Remote': None,
        'Salaire / TJM': '540-750 €/j', 'Durée mission': '3 mois',
        'Fit / Notes': "Expertise SAP HCM technico-fonctionnelle ; TJM haut de fourchette, cœur de compétence.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/expert-technico-fonctionnel-sap-hcm',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '750 €/j',
        'Date trouvée': D, 'Date publiée': '24/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP Paie (HCM Payroll)',
        'Entreprise': 'DUONEXT', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': '6 mois',
        'Fit / Notes': "SAP HCM Payroll ; module connu via les déploiements L'Oréal mais métier paie plus étroit.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-paie-hcm-payroll',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '22/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Expert SAP HCM en gestion des temps',
        'Entreprise': 'RED Commerce', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'La Garenne-Colombes', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': '3 mois',
        'Fit / Notes': "SAP HCM Time Management ; module déjà pratiqué sur le compte L'Oréal.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/expert-sap-hcm-en-gestion-des-temps',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '16/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'SAP SuccessFactors Senior/Lead Consultant',
        'Entreprise': 'INVESTIGO', 'Source': 'free-work',
        'Contrat': 'CDI', 'Localisation': 'Angleterre (UK)', 'Remote': None,
        'Salaire / TJM': '80-90 K£', 'Durée mission': None,
        'Fit / Notes': "Poste lead SuccessFactors au Royaume-Uni ; question visa UK à clarifier comme pour Taulia.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/sap-successfactors-senior-lead-consultant-permanent-ps80-000-ps90-000-per-annum-benefits',
        'CV à envoyer': CV_SIRH_EN, 'Prétention': '85-90 K£',
        'Date trouvée': D, 'Date publiée': '08/07/2026',
    },

    # ================= SIRH - entreprises et cabinets (LinkedIn -> site direct) =================
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Global HRIS Europe & Core HR Lead',
        'Entreprise': 'Nexans', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'La Défense / Puteaux', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Pilotage de la plateforme SuccessFactors groupe sur 22 pays et 14 000 dossiers, plus l'identification de cas d'usage IA sur le Core HR ; le croisement SAP HR mondial et IA que Gaëtan vise.",
        'Lien': 'https://www.welcometothejungle.com/en/companies/nexans/jobs/global-hris-europe-core-hr-lead_la-defense',
        'CV à envoyer': CV_SIRH_EN, 'Prétention': '90-110 K€',
        'Date trouvée': D, 'Date publiée': '12/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'HRIS & AI Tech Pre-Sales Specialist',
        'Entreprise': 'Arago', 'Source': 'jobs.smartrecruiters.com',
        'Contrat': 'CDI', 'Localisation': 'Paris ou Bordeaux', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Avant-vente SIRH avec une orientation IA explicite ; réunit les deux axes du profil, et Bordeaux reste accessible depuis Anglet.",
        'Lien': 'https://jobs.smartrecruiters.com/Arago/744000139094386-hris-ai-tech-pre-sales-specialist',
        'CV à envoyer': CV_SIRH_EN, 'Prétention': '95-115 K€',
        'Date trouvée': D, 'Date publiée': '23/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'HRIS Pre-Sales Specialist France H/F',
        'Entreprise': 'Arago', 'Source': 'careers.flatchr.io',
        'Contrat': 'CDI', 'Localisation': 'Paris / Bordeaux', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Second canal de publication du poste avant-vente SIRH chez Arago ; postuler par le canal le plus direct.",
        'Lien': 'https://careers.flatchr.io/fr/company/aragoconsulting/vacancy/bmqj09zllvedxorl-hris-pre-sales-manager-france-h-f/',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '95-115 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Global SAP HRIS Manager (SuccessFactors)',
        'Entreprise': 'n.c. (via Eursap)', 'Source': 'eursap.eu',
        'Contrat': 'CDI', 'Localisation': 'Allemagne', 'Remote': None,
        'Salaire / TJM': "jusqu'à 145 K€ + bonus", 'Durée mission': None,
        'Fit / Notes': "Poste de Group HRIS Manager sur SuccessFactors, réf. 34522-DE, démarrage septembre 2026 ; rémunération très au-dessus de la cible.",
        'Lien': 'https://eursap.eu/jobs/global-sap-hris-manager-successfactors-34522-de',
        'CV à envoyer': CV_SIRH_EN, 'Prétention': '110-145 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'CDI - Global Tech HR Domain Manager (F/M/X)',
        'Entreprise': 'SEPHORA', 'Source': 'jobs.sephora.com',
        'Contrat': 'CDI', 'Localisation': 'Neuilly-sur-Seine', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Pilotage des projets d'intégration SuccessFactors sur périmètre mondial (EME, Chine, Asie du Sud-Est, Amérique latine) avec équipe interne et prestataires ; très proche du rôle tenu sur L'Oréal.",
        'Lien': 'https://jobs.sephora.com/France/job/NEUILLY-SUR-SEINE-CDI-Global-Tech-HR-Domain-Manager-(FMX)/1341168455/',
        'CV à envoyer': CV_SIRH_EN, 'Prétention': '90-110 K€',
        'Date trouvée': D, 'Date publiée': '06/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Consultant Manager - SIRH - HR Transformation - Île-de-France',
        'Entreprise': 'Sopra Steria', 'Source': 'careers.soprasteria.com',
        'Contrat': 'CDI', 'Localisation': 'Courbevoie', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Niveau manager dans l'activité conseil transformation RH de Sopra HR (une centaine de consultants) ; séniorité alignée sur 15 ans d'expérience.",
        'Lien': 'https://careers.soprasteria.com/job/consultant-manager-sirh-hr-transformation-ile-de-france-in-courbevoie-france-jid-792',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '85-100 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Consultant Senior HR Transformation - SAP SuccessFactors (F/H)',
        'Entreprise': 'Deloitte', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Human Capital de Deloitte Consulting, équipe SuccessFactors, avec plan de certification SAP ; Deloitte est sept fois partenaire SuccessFactors de l'année.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/deloitte/jobs/consultant-hr-transformation-sap-successfactors-h-f_paris-la-defense_DELOI_z1JZMVL',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '75-90 K€',
        'Date trouvée': D, 'Date publiée': '07/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Consultant SAP HCM SF (H/F)',
        'Entreprise': 'Inetum', 'Source': 'inetum.com',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Déploiement des modules SuccessFactors (Employee Central, Performance & Goals, Learning, Recruiting) chez un acteur SAP majeur en France.",
        'Lien': 'https://www.inetum.com/fr/emploi/consultant-sap-hcm-sf-hf',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Consultant SAP SuccessFactors H/F',
        'Entreprise': 'Inetum', 'Source': 'inetum.com',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Analyse des besoins RH, paramétrage, formation utilisateurs et accompagnement de bout en bout ; le volet formation rejoint l'expérience de transfert de connaissances.",
        'Lien': 'https://www.inetum.com/fr/accueil/carrieres/d726923c-1981-42ba-89d3-b4d0355b578d.html',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'HRIS Implementation Project Manager',
        'Entreprise': 'Yassir', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'Paris (et autres sites)', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Implémentation SIRH de bout en bout, du cadrage au post-go-live, avec conduite du changement ; scale-up en croissance rapide.",
        'Lien': 'https://jobs.lever.co/Yassir/0c61130f-8b15-4366-b253-5662b6ba4c0c',
        'CV à envoyer': CV_SIRH_EN, 'Prétention': '75-90 K€',
        'Date trouvée': D, 'Date publiée': '30/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de projet IT SIRH',
        'Entreprise': 'Objectware', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Chef de projet SIRH en ESN parisienne ; cible directe du profil.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/objectware/jobs/chef-de-projet-it-sirh_paris',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de projet SIRH',
        'Entreprise': 'Clap Partners', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Montrouge', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Cabinet de 90 personnes entièrement spécialisé sur l'intégration SuccessFactors ; structure à taille humaine et périmètre pile dans la compétence.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/clap-partners-fr/jobs/chef-de-projet-sirh_montrouge_CP_JGZ0Yy6',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef(fe) de projet SIRH F/H',
        'Entreprise': 'CGI', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Accompagnement des transformations RH clients ; CGI publie régulièrement sur ce périmètre.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/cgi/jobs/chef-fe-de-projet-sirh-f-h_paris',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chef(fe) de projet SIRH F/H',
        'Entreprise': 'CGI', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Même poste que Paris, antenne nantaise.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/cgi/jobs/chef-fe-de-projet-sirh-f-h_nantes_CGI_oVZJzWp',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': "Consultant.e Confirmé.e Intégration SAP SuccessFactors (F/H)",
        'Entreprise': 'ACT-ON GROUP', 'Source': 'actongroup.com',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Intégration SuccessFactors chez ACT-ON, cabinet déjà identifié et déjà approché via LinkedIn ; le site direct fonctionne à nouveau.",
        'Lien': 'https://actongroup.com/offre/consultant-e-confirme-e-integration-sap-successfactors-f-h-france/',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant(e) Senior SAP HCM Paie & Time',
        'Entreprise': 'Strada', 'Source': 'careers.alight.com',
        'Contrat': 'CDI', 'Localisation': 'Colombes', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Strada est le premier partenaire mondial SAP HR ; poste senior sur les modules paie et temps, publié il y a moins de 24 h.",
        'Lien': 'https://careers.alight.com/strada/us/en/job/ALIGUSR32021STRADAENUS/Consultant-SAP-HCM-Paie-senior',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '75-90 K€',
        'Date trouvée': D, 'Date publiée': '12/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP HCM Time senior',
        'Entreprise': 'Strada', 'Source': 'careers.alight.com',
        'Contrat': 'CDI', 'Localisation': 'Colombes', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Volet gestion des temps chez Strada ; périmètre plus étroit que la paie mais même employeur cible.",
        'Lien': 'https://careers.alight.com/strada/us/en/job/ALIGUSR27913STRADAENUS/Consultant-SAP-HCM-Time-senior',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '75-90 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'SAP SF LMS Consultant',
        'Entreprise': 'n.c. (via Hanson Regan)', 'Source': 'hansonregan.com',
        'Contrat': 'Mission freelance', 'Localisation': 'Portugal', 'Remote': None,
        'Salaire / TJM': 'À négocier', 'Durée mission': None,
        'Fit / Notes': "Module LMS de SuccessFactors, trois implémentations de bout en bout demandées ; le volet formation rejoint la cible formateur SIRH.",
        'Lien': 'https://hansonregan.com/job/sap-sf-lms-consultant/',
        'CV à envoyer': CV_SIRH_EN, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SIRH H/F',
        'Entreprise': 'Septeo', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Lyon', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Accompagnement client sur toutes les phases du projet SIRH jusqu'au déploiement ; éditeur français.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/septeo/jobs/consultant-sirh-h-f_lyon_SEPTE_MjlzpK8',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '05/06/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant(e) senior SIRH/Paie H/F',
        'Entreprise': 'mc2i', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "mc2i compte 250 consultants dédiés au SIRH (SuccessFactors, Workday, HR Access, Oracle HCM, ADP) ; poste senior.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/mc2i/jobs/consultant-senior-sirh-paie-h-f_paris_MC2I_mP6gq3V',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant.e projets RH/SIRH',
        'Entreprise': 'LABBE LAURELLI', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Pilotage de projets RH et SIRH avec conduite du changement ; cabinet de petite taille.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/labbe-laurelli/jobs/consultant-projet-rh-sirh_paris',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant Salesforce Freelance - Projet SIRH / RH - Full Remote (H/F)',
        'Entreprise': 'n.c. (via Collective.work)', 'Source': 'collective.work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': 'Full remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Mission SIRH en full remote, critère prioritaire de Gaëtan ; la partie Salesforce reste à évaluer.",
        'Lien': 'https://www.collective.work/job/consultant-salesforce-freelance-projet-sirh-rh-full-remote-hf-b4np',
        'CV à envoyer': CV_SIRH_FR, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': None,
    },

    # ================= CSM =================
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager, Mid-Market, EMEA',
        'Entreprise': 'Harvey', 'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM mid-market EMEA chez un acteur IA juridique en forte croissance ; croise CSM et IA.",
        'Lien': 'https://jobs.ashbyhq.com/harvey/e8ed59d5-798c-49d3-a6ab-9e628d5dc221',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': '30/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager, EMEA',
        'Entreprise': 'HackerOne', 'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM EMEA remote chez un éditeur cybersécurité ; comptes enterprise, anglais courant requis.",
        'Lien': 'https://jobs.ashbyhq.com/hackerone/29422a55-bd09-4095-81d2-6ce7f4543a4f',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager, EMEA',
        'Entreprise': 'Ironclad', 'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM EMEA chez un éditeur SaaS contract management ; comptes grands comptes.",
        'Lien': 'https://jobs.ashbyhq.com/ironcladhq/9904557d-c48c-4a0a-86a1-4b259a12c611',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Scaled Customer Success - EMEA',
        'Entreprise': 'ElevenLabs', 'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Customer Success chez un laboratoire IA audio ; croisement CSM et IA générative très cohérent avec la cible.",
        'Lien': 'https://jobs.ashbyhq.com/elevenlabs/76e76881-32d9-494a-a187-460672680f41',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Strategic Customer Success Manager - EMEA',
        'Entreprise': 'Ashby', 'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM stratégique chez un éditeur ATS, donc secteur HR Tech ; le fond métier RH est un vrai avantage ici.",
        'Lien': 'https://jobs.ashbyhq.com/ashby/1cf7c730-caba-4fc3-8b98-52a0735ef14b',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'High Touch Customer Success Manager - EMEA',
        'Entreprise': 'Ashby', 'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Variante mid-market du poste CSM chez Ashby, éditeur HR Tech.",
        'Lien': 'https://jobs.ashbyhq.com/ashby/62d4f71e-f56c-447a-a965-a9c2ea8eac5e',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager - EMEA',
        'Entreprise': 'Tilla', 'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM EMEA dans une jeune structure ; à qualifier sur la taille des comptes.",
        'Lien': 'https://jobs.ashbyhq.com/tilla/823e58d1-e986-42d9-9441-47f31bb77a52',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager (Remote from France)',
        'Entreprise': 'n.c. (via Jobgether)', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Full remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Poste 100% remote depuis la France avec portefeuille EMEA ; correspond exactement à la contrainte géographique.",
        'Lien': 'https://jobs.lever.co/jobgether/2cfe2bb1-31f9-4afa-adaf-41a8a45a0e05',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager (m/f/d) - Full remote France',
        'Entreprise': 'n.c. (via Jobgether)', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Full remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM full remote basé en France sur des comptes enterprise en cybersécurité.",
        'Lien': 'https://jobs.lever.co/jobgether/9a0a18a3-1fe1-4aa2-b6db-dcac7867fb17',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Enterprise Customer Success Manager (Remote)',
        'Entreprise': 'n.c. (via Jobgether)', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': 'Full remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Segment enterprise en full remote ; le portefeuille grands comptes est le point fort du parcours.",
        'Lien': 'https://jobs.lever.co/jobgether/13b858c6-42a5-4055-9cb9-570c56c31fd6',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Sr. Customer Success Manager (Remote)',
        'Entreprise': 'n.c. (via Jobgether)', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': 'Full remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Poste CSM senior full remote ; séniorité alignée.",
        'Lien': 'https://jobs.lever.co/jobgether/fc8e9da0-9871-49ff-82b5-9b4a39c6d692',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Customer Success Manager - French Speaker',
        'Entreprise': 'Brevo', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM senior francophone chez un éditeur SaaS français bien établi ; 4 ans d'expérience minimum demandés.",
        'Lien': 'https://jobs.lever.co/brevo/8cba557a-b2f5-4652-bd86-5e000940239b',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Customer Success Manager (French Speaker)',
        'Entreprise': 'Sitetracker', 'Source': 'jobs.lever.co',
        'Contrat': 'CDI', 'Localisation': 'France / Benelux', 'Remote': 'Remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Portefeuille France et Benelux en remote, français et anglais requis ; éditeur SaaS américain.",
        'Lien': 'https://jobs.lever.co/sitetracker/3d537233-47b4-4f8c-b393-6479ecabe968',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager - Remote',
        'Entreprise': 'Namastay', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Télétravail total',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Télétravail total affiché sur l'annonce ; critère numéro un de Gaëtan.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/namastay/jobs/customer-success-manager-remote_paris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager - Full Remote H/F',
        'Entreprise': 'Obat', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': 'Télétravail total',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Full remote sur un SaaS bâtiment ; poste accessible depuis Anglet.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/obat/jobs/customer-success-manager-full-remote-h-f-x_nantes',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Implementation Manager EMEA',
        'Entreprise': 'Remote', 'Source': 'himalayas.app',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Full remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Remote.com est une plateforme RH/paie globale ; le poste mêle implémentation et customer success, exactement le croisement du profil.",
        'Lien': 'https://himalayas.app/companies/remote/jobs/customer-success-implementation-manager-emea',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Manager, Growth Customer Success - EMEA',
        'Entreprise': 'Remote', 'Source': 'himalayas.app',
        'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Full remote',
        'Salaire / TJM': '50-111 K$', 'Durée mission': None,
        'Fit / Notes': "Poste de management d'équipe CSM chez Remote.com ; plateforme RH globale.",
        'Lien': 'https://himalayas.app/companies/remote/jobs/manager-growth-customer-success-emea',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager - UK or Germany',
        'Entreprise': 'Zilliant', 'Source': 'himalayas.app',
        'Contrat': 'CDI', 'Localisation': 'UK ou Allemagne', 'Remote': 'Full remote',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Remote UK ou Allemagne ; à qualifier sur la possibilité de travailler depuis la France.",
        'Lien': 'https://himalayas.app/companies/zilliant/jobs/customer-success-manager-uk-or-germany',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Senior Customer Success / Account Manager',
        'Entreprise': 'Beamy', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Poste mixte CSM et Account Manager sur des grands comptes ; les deux facettes du parcours.",
        'Lien': 'https://www.welcometothejungle.com/en/companies/beamy/jobs/senior-customer-success_paris',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager Senior (H/F)',
        'Entreprise': 'Diduenjoy', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Télétravail occasionnel',
        'Salaire / TJM': '50-62 K€', 'Durée mission': None,
        'Fit / Notes': "CSM senior avec fourchette affichée sous la cible ; télétravail seulement occasionnel.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/diduenjoy/jobs/customer-success-manager-senior-h-f_paris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager Senior - H/F',
        'Entreprise': 'ARMIS', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Télétravail fréquent',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "CSM senior avec télétravail fréquent ; le full remote reste à négocier.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/armis/jobs/customer-success-manager-senior-h-f-paris_paris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager',
        'Entreprise': 'Reverse Contact', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Télétravail total',
        'Salaire / TJM': '40-55 K€', 'Durée mission': None,
        'Fit / Notes': "Full remote ; rémunération sous la cible mais le TJM et le salaire ne servent pas de filtre.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/visum/jobs/customer-success-manager_paris_RC_xDJ6YrA',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager EMEA',
        'Entreprise': 'Jus Mundi', 'Source': 'LinkedIn',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Publié il y a quelques heures ; legal tech parisienne, portefeuille EMEA.",
        'Lien': 'https://fr.linkedin.com/jobs/customer-success-manager-emplois-france',
        'CV à envoyer': CV_CSM_EN, 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': '13/08/2026',
    },

    # ================= IA =================
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'AI Trainer',
        'Entreprise': 'Focus Cloud Group', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Hauts-de-Seine', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': '5 jours',
        'Fit / Notes': "Mission courte de formation IA, exactement le poste de formateur IA visé ; format court idéal pour amorcer une activité.",
        'Lien': FW + '/fr/tech-it/job-mission/autre/ai-trainer',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '10/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Expert Data SAP & IA Générative (H/F)',
        'Entreprise': 'Pickmeup', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Châtillon', 'Remote': None,
        'Salaire / TJM': '400-570 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "Croisement SAP et IA générative, précisément le positionnement différenciant que Gaëtan cherche à occuper.",
        'Lien': FW + '/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/expert-data-sap-ia-generative-h-f',
        'CV à envoyer': CV_IA, 'Prétention': '570 €/j',
        'Date trouvée': D, 'Date publiée': '06/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Formateur freelance en Intelligence Artificielle',
        'Entreprise': 'n.c. (via mission-freelances.fr)', 'Source': 'mission-freelances.fr',
        'Contrat': 'Mission freelance', 'Localisation': 'Hauts-de-Seine', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Poste de formateur IA en freelance, cible principale de l'onglet IA.",
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-freelance-en-intelligence-artificielle-hauts-de-seine-a2fb3e3c/',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '10/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Formateur(trice) Accompagnement & Sensibilisation Intelligence Artificielle (H/F)',
        'Entreprise': 'n.c. (via Indeed / mission-freelances.fr)', 'Source': 'mission-freelances.fr',
        'Contrat': 'Mission freelance', 'Localisation': 'Toulon', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Acculturation et sensibilisation IA sans exigence data science ; correspond au profil formateur non technique.",
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-trice-accompagnement-sensibilisation-intelligence-artificielle-h-f-toulon-116298f1/',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '11/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'PMO / Chef de projet Gouvernance Projet IA',
        'Entreprise': 'n.c. (via Freelance-Informatique)', 'Source': 'freelance-informatique.fr',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': '6 mois renouvelables',
        'Fit / Notes': "Gouvernance de programme IA avec animation d'ateliers et conduite du changement ; le croisement PMO et IA est différenciant sur ce profil.",
        'Lien': 'https://www.freelance-informatique.fr/mission-pmo-chef-de-projet-gouvernance-projet-ia-250905B006',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'PMO / Chef de Projet IA',
        'Entreprise': 'HAYS France', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Coordination de projets IA en contexte international, avec volet acculturation IA de l'organisation.",
        'Lien': FW + '/fr/tech-it/assistant-chef-de-projet/job-mission/pmo-chef-de-projet-ia',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Mission freelance PMO / Chef de projet IA',
        'Entreprise': 'n.c. (via Collective.work)', 'Source': 'collective.work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Même famille de mission publiée sur Collective.work ; plateforme freelance senior à activer.",
        'Lien': 'https://www.collective.work/job/pmo-chef-de-projet-ia-7kjv',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de projet MOA / PMO - IA',
        'Entreprise': 'n.c. (via Collective.work)', 'Source': 'collective.work',
        'Contrat': 'Mission freelance', 'Localisation': 'Serris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Rôle MOA sur programme IA ; la posture AMOA est déjà une cible du profil SIRH.",
        'Lien': 'https://www.collective.work/jobs/fr/chef-de-projet-moa-pmo-ia-vhez',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant Assurance IARD - Change Management & Intelligence Artificielle',
        'Entreprise': 'YGL consulting', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'France', 'Remote': None,
        'Salaire / TJM': '600-700 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "Conduite du changement liée à l'IA, sans exigence data science ; le secteur assurance est à découvrir.",
        'Lien': FW + '/fr/tech-it/job-mission/project-management-officer/consultant-assurance-iard-change-management-intelligence-artificielle',
        'CV à envoyer': CV_IA, 'Prétention': '700 €/j',
        'Date trouvée': D, 'Date publiée': '30/07/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chef de Produit Plateforme IA (AI Platform Product Manager)',
        'Entreprise': 'JCW Search Ltd', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '610-1110 £/j', 'Durée mission': '12 mois',
        'Fit / Notes': "Product management sur plateforme IA ; TJM très élevé, exigences techniques à qualifier.",
        'Lien': FW + '/fr/tech-it/job-mission/responsable-produit/chef-de-produit-plateforme-ia-ai-platform-product-manager',
        'CV à envoyer': CV_IA, 'Prétention': '800-1000 €/j',
        'Date trouvée': D, 'Date publiée': '05/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Expert IA Générative - Agents IA, Copilot et Industrialisation',
        'Entreprise': 'AVA2I', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Île-de-France', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': '1 an',
        'Fit / Notes': "Déploiement de Copilot et d'agents IA en entreprise ; publiée aujourd'hui, volet industrialisation à qualifier.",
        'Lien': FW + '/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-ia-generative-agents-ia-copilot-et-industrialisation',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '13/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Responsable de Plateforme IA / Head of AI Platform',
        'Entreprise': 'n.c. (via Free-Work / mission-freelances.fr)', 'Source': 'mission-freelances.fr',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Poste de responsable de plateforme IA ; niveau de séniorité intéressant, technicité à vérifier.",
        'Lien': 'https://www.mission-freelances.fr/missions/responsable-de-plateforme-ia-head-of-ai-platform-paris-71e0cae7/',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '12/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Expert IA',
        'Entreprise': 'n.c. (via Free-Work / mission-freelances.fr)', 'Source': 'mission-freelances.fr',
        'Contrat': 'Mission freelance', 'Localisation': 'Île-de-France', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Intitulé large, à qualifier sur le niveau de technicité attendu.",
        'Lien': 'https://www.mission-freelances.fr/missions/expert-ia-ile-de-france-43afcde7/',
        'CV à envoyer': CV_IA, 'Prétention': '650-750 €/j',
        'Date trouvée': D, 'Date publiée': '10/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Expert IA générative & outils Claude F/H',
        'Entreprise': 'SMARTPOINT', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '570-620 €/j', 'Durée mission': '12 mois',
        'Fit / Notes': "Mission centrée sur les outils Claude, que Gaëtan utilise quotidiennement ; niveau technique à qualifier.",
        'Lien': FW + '/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-ia-generative-outils-claude-f-h',
        'CV à envoyer': CV_IA, 'Prétention': '620 €/j',
        'Date trouvée': D, 'Date publiée': '04/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Chef de Projet IA - Product Owner IA H/F',
        'Entreprise': 'n.c. (via LesJeudis)', 'Source': 'lesjeudis.com',
        'Contrat': 'CDI', 'Localisation': 'Île-de-France', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Poste mêlant chef de projet et Product Owner sur des sujets IA ; deux rôles déjà tenus.",
        'Lien': 'https://lesjeudis.com/fr/job/chef-de-projet-ia-product-owner-ia-hf-450053',
        'CV à envoyer': CV_IA, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Expert Méthode & IA',
        'Entreprise': 'INFOTEL CONSEIL', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Saint-Herblain', 'Remote': None,
        'Salaire / TJM': '300-470 €/j', 'Durée mission': '6 mois',
        'Fit / Notes': "Volet méthode et IA ; contour du poste flou, à qualifier avant de candidater.",
        'Lien': FW + '/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-methode-ia',
        'CV à envoyer': CV_IA, 'Prétention': '470 €/j',
        'Date trouvée': D, 'Date publiée': '11/08/2026',
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Product Owner Solutions IA H/F',
        'Entreprise': 'DAVRICOURT', 'Source': 'free-work',
        'Contrat': 'CDI', 'Localisation': 'Lille', 'Remote': None,
        'Salaire / TJM': '45-50 K€', 'Durée mission': None,
        'Fit / Notes': "Product Owner IA en CDI ; fourchette de rémunération sous la cible et poste plutôt junior.",
        'Lien': FW + '/fr/tech-it/job-mission/product-owner/product-owner-solutions-ia-h-f-5',
        'CV à envoyer': CV_IA, 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '12/08/2026',
    },
]


def _liens_existants():
    import openpyxl
    wb = openpyxl.load_workbook(add_offre.FICHIER)
    lien_idx = add_offre._col_index(wb['Offres SIRH'], 'Lien')
    liens = set()
    for ws in (wb['Offres SIRH'], wb['Offres CSM'], wb['Offres IA'], wb['Fait']):
        for row in ws.iter_rows(min_row=2):
            v = row[lien_idx].value
            if v:
                liens.add(str(v).strip())
    return liens


if __name__ == '__main__':
    connus = _liens_existants()
    nouvelles = [o for o in OFFRES if o['Lien'] not in connus]
    doublons = len(OFFRES) - len(nouvelles)
    print(f"{len(OFFRES)} offres collectees, {doublons} deja presentes, {len(nouvelles)} a ajouter\n")
    add_offre.ajouter_offres(nouvelles)
