"""Relance de recherche exhaustive du 09/08/2026 - toutes sources CLAUDE.md (5 agents paralleles)."""

import add_offre

add_offre.COLS = add_offre.COLS + ['Date trouvée', 'Date publiée']

D = '09/08/2026'

OFFRES = [
    # ---------------- SAP / SIRH ----------------
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Sr. Business Analyst, SAP Payroll Belgium and France',
        'Entreprise': 'Rimini Street', 'Source': 'RemoteRocketship',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui (remote confirmé)',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "10 ans d'expérience SAP Paie France/Belgique exigés, remote France confirmé. Correspond très directement au socle SAP HR/L'Oréal.",
        'Lien': 'https://www.remoterocketship.com/company/riministreet/jobs/business-analyst-sap-payroll-france-remote/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.pdf', 'Prétention': '90-110 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Manager HR & Transformation - Bureau de Marseille',
        'Entreprise': 'Sia Partners', 'Source': 'sia-partners.com',
        'Contrat': 'CDI', 'Localisation': 'Marseille', 'Remote': 'Hybride probable',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Niveau Manager, scope explicite SIRH/Digital HR, cabinet déjà identifié comme cible pertinente.",
        'Lien': 'https://www.sia-partners.com/en/career/manager-hr-transformation-bureau-de-marseille',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '75-90 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': "Responsable SIRH et Data RH (F/H/NB)",
        'Entreprise': 'Chateauform', 'Source': 'talents.chateauform.com',
        'Contrat': 'CDI', 'Localisation': 'Saint-Ouen', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Niveau Responsable, administration et cohérence fonctionnelle du SIRH groupe.",
        'Lien': 'https://talents.chateauform.com/jobs/8110495-responsable-sirh-et-data-rh-f-h-nb',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Manager Consultant SIRH F/H',
        'Entreprise': 'KPMG France', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Paris (10e)', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Poste manager confirmé (5+ ans), pilotage de missions SIRH/transformation RH en cabinet ; profil senior proche du parcours L'Oréal/SAP.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/kpmg-france/jobs/manager-consultant-sirh-f-h_paris_KF_0o6gkGl',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '75-90 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Manager en HR Transformation F/H',
        'Entreprise': 'PwC', 'Source': 'Glassdoor',
        'Contrat': None, 'Localisation': 'Neuilly-sur-Seine', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Équipe HR Transformation PwC, niveau manager. Statut d'activité non confirmé (Glassdoor bloque le fetch direct), à vérifier avant candidature.",
        'Lien': 'https://www.glassdoor.fr/job-listing/manager-en-hr-transformation-fh-pwc-JV_IC3041419_KO0,31_KE32,35.htm?jl=1009932776973',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '75-90 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant - HR & Transformation Bureau de Lyon',
        'Entreprise': 'Sia Partners', 'Source': 'sia-partners.com',
        'Contrat': 'CDI', 'Localisation': 'Lyon', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Change strategy et Digital HR/SIRH, même cabinet que la mission Marseille déjà remontée.",
        'Lien': 'https://www.sia-partners.com/fr/career/consultant-hr-transformation-bureau-de-lyon',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Expert solution ServiceNow Employee Experience / SIRH H/F',
        'Entreprise': 'Devoteam', 'Source': 'devoteam.com',
        'Contrat': 'CDI', 'Localisation': 'Levallois-Perret', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Expertise SIRH pointue sur une offre ServiceNow HR, cabinet conseil digital.",
        'Lien': 'https://www.devoteam.com/jobs/expert-solution-servicenow-employee-experience-sirh-hf-120115547508482758/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Tech Lead - SIRH H/F',
        'Entreprise': 'Crédit Agricole CIB', 'Source': 'jobs.ca-cib.com',
        'Contrat': 'CDI', 'Localisation': 'Guyancourt', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "SIRH Groupe sous Oracle HCM SaaS pour 60k employés ; poste plus technique/dev qu'attendu, à valider en entretien.",
        'Lien': 'https://jobs.ca-cib.com/offre-de-emploi/imprimer-fiche-emploi-tech-lead-sirh-h-f_99927.aspx',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': "CDI - Consultant métier en Système d'Information RH H/F",
        'Entreprise': 'Naval Group', 'Source': 'naval-group.com',
        'Contrat': 'CDI', 'Localisation': 'Ollioules/Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Référent SIRH sur le périmètre GPEC & Formation, grand compte industriel.",
        'Lien': 'https://www.naval-group.com/fr/talents/offer/2026-53338',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': '2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant Oracle HCM H/F',
        'Entreprise': 'Inetum', 'Source': 'inetum.com',
        'Contrat': 'CDI', 'Localisation': 'Saint-Ouen', 'Remote': None,
        'Salaire / TJM': '42-65 K€', 'Durée mission': None,
        'Fit / Notes': "3-5 ans d'expérience SIRH/Oracle Cloud HCM demandés ; fourchette affichée un peu sous la cible.",
        'Lien': 'https://www.inetum.com/fr/accueil/carrieres/1ff08c76-dc58-4d4c-b7c4-8b7f9a58bdd5.html',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '65 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant Technique HR Access',
        'Entreprise': 'Inetum', 'Source': 'inetum.com',
        'Contrat': 'CDI', 'Localisation': 'Saint-Ouen', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "10 ans d'expérience SIRH requis, acteur SAP France majeur déjà bien identifié.",
        'Lien': 'https://www.inetum.com/fr/emploi/consultant-technique-hr-access',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Expert SAP HR TIME F/H',
        'Entreprise': 'VINCI Construction', 'Source': 'jobs.vinci.com',
        'Contrat': 'CDI', 'Localisation': 'Nanterre', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Transformation S/4, module SAP HR Time, grand compte industriel.",
        'Lien': 'https://jobs.vinci.com/fr/emploi/nanterre/expert-sap-hr-time-f-h/1440/14346869120',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP HR Run Expert (Confirmé) F/H',
        'Entreprise': 'VINCI', 'Source': 'jobs.vinci.com',
        'Contrat': 'CDI', 'Localisation': 'Saint-Denis', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "SAP HR Run pour VINCI Energies, même groupe que le poste Nanterre.",
        'Lien': 'https://jobs.vinci.com/en/job/saint-denis/consultant-sap-hr-confirme-f-h/1440/28871319232',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Expert SAP Paie F/H',
        'Entreprise': 'VINCI Construction', 'Source': 'welcometothejungle.com',
        'Contrat': 'CDI', 'Localisation': 'Nanterre', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Expertise SAP Paie au sein de l'équipe SAP HR VINCI, complémentaire aux deux autres postes VINCI remontés.",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/vinci-construction-fr/jobs/expert-sap-paie-f-h_nanterre',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SIRH F/H',
        'Entreprise': 'n.c. (via APEC)', 'Source': 'apec.fr',
        'Contrat': None, 'Localisation': 'Issy-les-Moulineaux (92)', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "URL d'annonce individuelle réelle issue de WebSearch ; APEC bloque le fetch direct (mur de login), détails à vérifier manuellement.",
        'Lien': 'https://www.apec.fr/candidat/recherche-emploi.html/emploi/detail-offre/176288045W',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Consultant formateur logiciels SIRH',
        'Entreprise': 'Kelio', 'Source': 'welcometothejungle.com',
        'Contrat': None, 'Localisation': 'Ile-de-France (Paris)', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Éditeur SIRH (gestion des temps), profil formation+SIRH proche du parcours ; détails non confirmés (fetch direct bloqué).",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/kelio/jobs/consultant-formateur-logiciels-sirh-ile-de-france-h-f_paris_KELIO_LNb8Mqy',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': "Consultant(e) Customer Success Junior - Mid-Market",
        'Entreprise': 'Lucca', 'Source': 'jobs.world.luccasoftware.com',
        'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': 'Hybride (2j télétravail/semaine)',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Éditeur SIRH FR déjà identifié comme cible ; segment Mid-Market et titre 'Junior', moins aligné avec le profil senior mais même famille métier CSM SIRH.",
        'Lien': 'https://jobs.world.luccasoftware.com/lucca/customer-success-sirh-midmarket-junior-fc069879-3773-4524-ae17-2325b840c370',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '60-70 K€',
        'Date trouvée': D, 'Date publiée': '03/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'SAP HCM Payroll or SF EC Payroll Consultant',
        'Entreprise': 'n.c. (via Eursap)', 'Source': 'eursap.eu',
        'Contrat': 'CDI', 'Localisation': 'Pays-Bas', 'Remote': None,
        'Salaire / TJM': "jusqu'à 103 480 €/an + bonus", 'Durée mission': None,
        'Fit / Notes': "Bon fit SAP HCM/SF Payroll mais poste basé aux Pays-Bas ; à clarifier si le remote depuis la France est envisageable.",
        'Lien': 'https://eursap.eu/jobs/sap-hcm-payroll-or-sf-ec-payroll-consultant-35441-nl',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH_EN.pdf', 'Prétention': '90-110 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Consultant expérimenté en HR Transformation F/H',
        'Entreprise': 'PwC', 'Source': 'Glassdoor',
        'Contrat': None, 'Localisation': 'Neuilly-sur-Seine', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Équipe HR Transformation PwC, diagnostic SIRH ; statut d'activité non confirmé (Glassdoor bloque le fetch direct).",
        'Lien': 'https://www.glassdoor.fr/job-listing/consultant-exp%C3%A9riment%C3%A9-en-hr-transformation-fh-pwc-JV_IC3041419_KO0,46_KE47,50.htm?jl=1009932776858',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '70-85 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Expert HR Access F/H',
        'Entreprise': 'La Poste Groupe (i-TEAM)', 'Source': 'laposterecrute.fr',
        'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Poste très technique (COBOL, développement HR Access), moins aligné avec le profil fonctionnel de Gaëtan.",
        'Lien': 'https://www.laposterecrute.fr/offre/2026-213570',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Consultant SIRH Workday',
        'Entreprise': 'Metaline', 'Source': 'Teamtailor',
        'Contrat': 'CDI', 'Localisation': 'Lille', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Support N2 Workday, niveau plus junior que le profil de Gaëtan.",
        'Lien': 'https://metaline.teamtailor.com/jobs/7315629-consultant-sirh-workday',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Adjoint(e) Responsable Paie (H/F)',
        'Entreprise': 'HR Path', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '650-700€/j', 'Durée mission': '3 mois',
        'Fit / Notes': "HR Path est un partenaire SIRH clé, mais le poste vise l'opérationnel paie plutôt que le conseil SAP HCM/SF.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/directeur-de-la-data-cdo/adjoint-e-responsable-paie-h-f',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-700€/j',
        'Date trouvée': D, 'Date publiée': '04/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager SIRH',
        'Entreprise': 'MLMCONSEIL', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Rouen', 'Remote': None,
        'Salaire / TJM': '100-470€/j (fourchette large)', 'Durée mission': '6 mois',
        'Fit / Notes': "Bon fit Product Owner SIRH ; possible doublon d'une mission Rouen déjà repostée par plusieurs intermédiaires, à vérifier avant candidature.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/product-manager-sirh-1',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '650-750€/j',
        'Date trouvée': D, 'Date publiée': '08/07/2026',
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Knowledge Manager',
        'Entreprise': 'Argain Consulting Innovation', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Le Mans', 'Remote': None,
        'Salaire / TJM': '350-400€/j', 'Durée mission': '3 mois',
        'Fit / Notes': "Accompagnement des usages IA et fiabilisation d'un corpus de connaissances ; rôle plus documentaire que formation.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/community-manager-social-media-manager/knowledge-manager-14',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Prétention': '350-400€/j',
        'Date trouvée': D, 'Date publiée': '29/07/2026',
    },
    # ---------------- CSM ----------------
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager F/H',
        'Entreprise': 'n.c. (via APEC)', 'Source': 'apec.fr',
        'Contrat': None, 'Localisation': 'Toulouse (31)', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "URL d'annonce individuelle réelle issue de WebSearch ; APEC bloque le fetch direct (mur de login), détails à vérifier manuellement.",
        'Lien': 'https://www.apec.fr/candidat/recherche-emploi.html/emploi/detail-offre/173994098W',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager, SMB',
        'Entreprise': 'ZigZag Global', 'Source': 'RemoteRocketship',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Fintech gestion des dépenses ; fetch direct bloqué, détails non confirmés au-delà du titre.",
        'Lien': 'https://www.remoterocketship.com/company/zigzag-global-global/jobs/customer-success-manager-smb-france-remote/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager, French',
        'Entreprise': 'Ventrata', 'Source': 'RemoteRocketship',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Fetch direct bloqué, détails non confirmés au-delà du titre.",
        'Lien': 'https://www.remoterocketship.com/company/ventrata/jobs/customer-success-manager-french-france-remote/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Relationship Manager',
        'Entreprise': 'Fortive', 'Source': 'RemoteRocketship',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Gestion de comptes/programmes SaaS (détection gaz) ; fetch direct bloqué.",
        'Lien': 'https://www.remoterocketship.com/company/fortive/jobs/customer-success-relationship-manager-france-remote/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Customer Success Specialist, French-speaking',
        'Entreprise': 'One Click LCA', 'Source': 'RemoteRocketship',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "SaaS décarbonation/construction, société finlandaise ; fetch direct bloqué.",
        'Lien': 'https://www.remoterocketship.com/company/one-click-lca/jobs/customer-success-specialist-french-speaking-france-remote/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.pdf', 'Prétention': '80-95 K€',
        'Date trouvée': D, 'Date publiée': None,
    },
    # ---------------- IA ----------------
    {
        'Priorité': '⭐⭐⭐⭐', 'Poste': 'Expert IA Générative & Outils Claude F/H',
        'Entreprise': 'SMARTPOINT', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': '570-620€/j', 'Durée mission': '12 mois',
        'Fit / Notes': "Accompagnement à la prise en main de Claude Cowork/Claude Code et montée en compétences des collaborateurs ; bon fit acculturation IA générative.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-ia-generative-outils-claude-f-h',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': '570-620€/j',
        'Date trouvée': D, 'Date publiée': '04/08/2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': 'Formateur·rice IA Générative',
        'Entreprise': 'France IA', 'Source': 'welcometothejungle.com',
        'Contrat': 'Freelance', 'Localisation': 'Marseille', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Organisme construisant un réseau de formateurs indépendants IA dans 6 villes dès septembre 2026 ; détails non confirmés (fetch direct bloqué).",
        'Lien': 'https://www.welcometothejungle.com/fr/companies/france-ia-1/jobs/328bb365-1819-4f31-b78a-5a8c6f66f6d5',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': '2026',
    },
    {
        'Priorité': '⭐⭐⭐', 'Poste': "Formateur(trice) freelance en intelligence artificielle",
        'Entreprise': 'n.c.', 'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance', 'Localisation': 'Chambéry et Bourg-en-Bresse', 'Remote': 'Non (présentiel)',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Formateur IA générative freelance, bon fit métier ; localisation présentielle Savoie/Ain à confirmer côté remote.",
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-trice-freelance-en-intelligence-artificielle-chambery-et-bourg-en-bresse-27cdb82e/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': "Formateur (H/F) Création de contenus rédactionnels et visuels par de l'IA générative",
        'Entreprise': 'n.c.', 'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance/mission', 'Localisation': 'Chambéry', 'Remote': 'Non',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Formation IA générative orientée création de contenus, périmètre plus étroit que l'acculturation visée.",
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-h-f-creation-de-contenus-redactionnels-et-visuels-par-de-l-ia-generati-chambery-505d4b6c/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': "Formateur (H/F) Création de contenus rédactionnels et visuels par de l'IA",
        'Entreprise': 'n.c.', 'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance/mission', 'Localisation': 'Chartres', 'Remote': 'Non',
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Même type de mission que la précédente (ville différente), orientée création de contenu par IA.",
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-h-f-creation-de-contenus-redactionnels-et-visuels-par-de-l-ia-chartres-fc80b0e8/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Formateur Indépendant IA',
        'Entreprise': 'n.c.', 'Source': 'infreelancing.com',
        'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Nouvelle plateforme freelance non couverte jusqu'ici ; détails non confirmés (fetch direct bloqué).",
        'Lien': 'https://infreelancing.com/missions-freelance/236811/formateur-independant-ia',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Expert Cybersécurité IA Générative H/F',
        'Entreprise': 'OUICODING', 'Source': 'free-work',
        'Contrat': 'Mission freelance', 'Localisation': 'Saint-Denis', 'Remote': None,
        'Salaire / TJM': '600-800€/j', 'Durée mission': '1 mois',
        'Fit / Notes': "Volet accompagnement des équipes sur l'IA mais dominante technique cybersécurité, fit partiel.",
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant-cyber-securite/expert-cybersecurite-ia-generative-h-f',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': '600-800€/j',
        'Date trouvée': D, 'Date publiée': '23/07/2026',
    },
    {
        'Priorité': '⭐⭐', 'Poste': 'Partenaire Développement & Avant-Vente IA - Lead Business Development',
        'Entreprise': 'n.c.', 'Source': 'mission-freelances.fr',
        'Contrat': None, 'Localisation': 'Paris', 'Remote': None,
        'Salaire / TJM': None, 'Durée mission': None,
        'Fit / Notes': "Avant-vente IA, proche du profil pre-sales mais business dev générique plutôt que HR Tech ; à vérifier en détail.",
        'Lien': 'https://www.mission-freelances.fr/missions/partenaire-developpement-avant-vente-ia-lead-business-development-paris-ec77a6cc/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.pdf', 'Prétention': None,
        'Date trouvée': D, 'Date publiée': None,
    },
]


def _liens_existants():
    import openpyxl
    wb = openpyxl.load_workbook(add_offre.FICHIER)
    lien_idx = add_offre._col_index(wb['Offres SIRH'], 'Lien')
    liens = set()
    for ws in (wb['Offres SIRH'], wb['Offres CSM'], wb['Offres IA'], wb['Fait']):
        for row in ws.iter_rows(min_row=2):
            v = row[lien_idx].value
            if v:
                liens.add(str(v).strip())
    return liens


if __name__ == '__main__':
    connus = _liens_existants()
    nouvelles = [o for o in OFFRES if o['Lien'] not in connus]
    doublons = len(OFFRES) - len(nouvelles)
    print(f"{len(OFFRES)} offres collectees, {doublons} deja presentes, {len(nouvelles)} a ajouter\n")
    add_offre.ajouter_offres(nouvelles)
