"""Script d'ajout des nouvelles offres trouvées le 21 juillet 2026."""
import sys
sys.path.insert(0, '/Users/gaetan/Documents/IA/recherche-taf')

from add_offre import ajouter_offres

offres = [
    # ===== OFFRES CSM =====
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Manager, Customer Success (Remote - EMEA)',
        'Entreprise': 'n8n',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote Europe',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Plateforme workflow automation leader ; poste senior management CSM EMEA full remote ; anglais requis ; très bon fit profil senior',
        'Lien': 'https://jobs.ashbyhq.com/n8n/018bb06a-6147-4e04-aa4b-8a9daf0558bd',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Senior Customer Success Manager (EMEA)',
        'Entreprise': 'n8n',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote Europe',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Plateforme workflow automation (alternative Zapier, très forte croissance) ; senior CSM EMEA full remote ; profil senior enterprise parfait',
        'Lien': 'https://jobs.ashbyhq.com/n8n/ffafc55a-6fcc-4dfb-aef2-7979391d3ffb',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Senior Customer Success Manager, EMEA',
        'Entreprise': 'Mural',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote Europe',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Outil collaboration visuelle enterprise ; portfolio strategic accounts ; remote EU confirmé ; anglais requis',
        'Lien': 'https://jobs.ashbyhq.com/mural/9537d46c-8909-45c5-a696-dbffb33c0bbe',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Senior Payroll Customer Success Manager - EMEA',
        'Entreprise': 'Remote (Remote.com)',
        'Source': 'euremotejobs.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Remote.com plateforme paie/HRIS global (concurrent Deel/Oyster) ; croisement parfait CSM senior + expertise SIRH/paie/RH international ; full remote',
        'Lien': 'https://euremotejobs.com/job/senior-payroll-customer-success-manager-emea/',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Strategic Customer Success Manager - EMEA',
        'Entreprise': 'Maze',
        'Source': 'jobs.ashbyhq.com / Wellfound',
        'Contrat': 'CDI',
        'Localisation': 'Remote UK/EU',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Plateforme UX research SaaS ; strategic accounts C-level ; 5+ ans requis ; remote UK ou Portugal annoncé ; vérifier si France OK',
        'Lien': 'https://jobs.ashbyhq.com/mazedesign/b1c19922-af31-4740-a93d-6bb5ae0b3c62',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Strategic Customer Success Manager - EMEA',
        'Entreprise': 'Ashby',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote Europe',
        'Remote': 'Oui',
        'Salaire / TJM': '105-125K€',
        'Durée mission': '',
        'Fit / Notes': 'Ashby est un ATS RH haut de gamme (concurrent Greenhouse/Lever) ; salaire 105-125K€ ; strategic enterprise accounts ; excellent fit profil RH + CSM senior',
        'Lien': 'https://jobs.ashbyhq.com/ashby/1cf7c730-caba-4fc3-8b98-52a0735ef14b',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'High Touch Customer Success Manager - EMEA',
        'Entreprise': 'Ashby',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote Europe',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'ATS RH haut de gamme ; mid-market high touch ; full remote Europe ; anglais requis ; profil recrutement/RH tech différenciant',
        'Lien': 'https://jobs.ashbyhq.com/ashby/62d4f71e-f56c-447a-a965-a9c2ea8eac5e',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Customer Success Manager, EMEA',
        'Entreprise': 'HackerOne',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Leader cybersécurité (bug bounty / ethical hacking) ; EMEA full remote ; anglais requis ; secteur cybersécurité enterprise',
        'Lien': 'https://jobs.ashbyhq.com/hackerone/29422a55-bd09-4095-81d2-6ce7f4543a4f',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Customer Success Manager (French Speaking) - Remote',
        'Entreprise': 'Immersive Labs',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Plateforme cyber resilience SaaS ; French speaking ; full remote ; anglais + français requis ; marché FR à développer',
        'Lien': 'https://jobs.ashbyhq.com/immersivelabs/6516d68a-e513-40bf-99f4-bebc2135a3f2',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Customer Success Manager, Deel IT (French Speaking)',
        'Entreprise': 'Deel',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Division IT de Deel (gestion équipements/laptops/MDM) ; French speaking ; rôle distinct du CSM France généraliste déjà dans le tableur',
        'Lien': 'https://jobs.ashbyhq.com/deel/2fc7826c-3e54-40d8-ad26-22364517c27d',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Customer Success Manager (EMEA)',
        'Entreprise': 'Oyster HR',
        'Source': 'euremotejobs.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote EMEA',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Plateforme global employment / EOR (comme Deel/Remote) ; EMEA full remote ; croisement CSM + SIRH/RH global ; bonne synérgie profil',
        'Lien': 'https://euremotejobs.com/job/customer-success-manager-emea-6/',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Senior Customer Success Manager (French Speaker)',
        'Entreprise': 'Sitetracker',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDI',
        'Localisation': 'Londres (hybride)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'SaaS gestion infrastructure/télécom/énergie ; French speaker marché FR + Benelux ; basé Londres - clarifier si remote France possible',
        'Lien': 'https://jobs.lever.co/sitetracker/3d537233-47b4-4f8c-b393-6479ecabe968',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Customer Success Manager - French Speaker',
        'Entreprise': 'Adthena',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Search intelligence / marketing analytics SaaS ; French speaker ; remote ; profil moins enterprise',
        'Lien': 'https://jobs.ashbyhq.com/adthena/97e15863-1bc9-425a-9d2f-c642a052d927',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Customer Success Manager (EMEA)',
        'Entreprise': 'Pylon',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'SaaS support client B2B ; EMEA ; startup ; anglais requis ; profil moins senior',
        'Lien': 'https://jobs.ashbyhq.com/pylon-labs/d93299b7-c934-4d19-83fe-1949ec7af4b9',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Customer Success Manager (EMEA)',
        'Entreprise': 'Sift',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Plateforme fraud prevention/trust SaaS ; EMEA full remote ; anglais requis ; clientèle e-commerce/fintech',
        'Lien': 'https://jobs.ashbyhq.com/sift/fd490694-a66f-4d4d-b8da-37e434335a74',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Customer Success Manager (Full Remote)',
        'Entreprise': 'Reverse Contact (Visum)',
        'Source': 'welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'France - Full Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '40-55K€',
        'Durée mission': '',
        'Fit / Notes': 'SaaS enrichissement données B2B ; full remote FR ; salaire 40-55K€ en dessous du cible senior ; à vérifier si la rémunération est négociable',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/visum/jobs/customer-success-manager_paris_RC_xDJ6YrA',
        'CV à envoyer': '',
        'Prétention': '',
    },
    # ===== OFFRES SIRH =====
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Consultant SIRH AMOA',
        'Entreprise': 'Clap Partners',
        'Source': 'welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'Montrouge',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Cabinet conseil SIRH SuccessFactors ; hybride Montrouge ; AMOA ; profil distinct du poste Core RH déjà dans le tableur',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/clap-partners-fr/jobs/consultant-sirh-amoa_montrouge_CP_QAOJO2z',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Consultant AMOA SIRH Learning H/F',
        'Entreprise': 'Clap Partners',
        'Source': 'welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'Montrouge',
        'Remote': 'Partiel',
        'Fit / Notes': 'Cabinet conseil SIRH ; module Learning SuccessFactors ; hybride Montrouge ; formation utilisateurs-clés = différenciant',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/clap-partners-fr/jobs/consultant-amoa-sirh-learning-h-f_montrouge',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'SAP SuccessFactors Senior/Lead Consultant',
        'Entreprise': 'Investigo',
        'Source': 'free-work.com',
        'Contrat': 'CDI',
        'Localisation': 'Angleterre (hybride)',
        'Remote': 'Partiel',
        'Salaire / TJM': '80-90K£/an',
        'Durée mission': '',
        'Fit / Notes': 'Cabinet recrutement SAP UK ; salaire 80-90K£ ; basé Angleterre hybride ; à clarifier si remote depuis France possible',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/sap-successfactors-senior-lead-consultant-permanent-ps80-000-ps90-000-per-annum-benefits',
        'CV à envoyer': '',
        'Prétention': '',
    },
    # ===== OFFRES IA =====
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Formateur / Consultant IA générative',
        'Entreprise': 'Mantra Pro (ex-GrowthMakers)',
        'Source': 'welcometothejungle.com',
        'Contrat': 'Freelance',
        'Localisation': 'France - Full Remote',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Formation dirigeants TPE/PME sur IA générative 1-2 jours ; 100% remote ; missions freelance ponctuelles ; parfait angle formateur IA sans data science',
        'Lien': 'https://www.welcometothejungle.com/en/companies/growthmakers/jobs/formateur-ia-et-ia-generative_paris',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': 'Formateur en IA générative et agentique',
        'Entreprise': 'N/C (via mission-freelances.fr)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Télétravail',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Animation visioconférence 4-8 personnes ; prompt engineering + no-code + IA agentique ; RGPD/éthique ; statut indépendant requis ; publié 29 juin 2026',
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-en-intelligence-artificielle-generative-et-agentique-teletravail-c892d79e/',
        'CV à envoyer': '',
        'Prétention': '',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': None,
        'Poste': "Formateur IA appliquée à l'acquisition client",
        'Entreprise': 'N/C (via mission-freelances.fr)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Télétravail',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Formation à distance IA pour prospection/acquisition client ; marketing + IA ; statut SIREN requis ; publié 15 juillet 2026',
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-ia-appliquee-a-l-acquisition-client-teletravail-68ec066a/',
        'CV à envoyer': '',
        'Prétention': '',
    },
]

if __name__ == '__main__':
    ajouter_offres(offres)
