"""
Ajout des offres trouvées lors de la recherche du 2026-07-28.
Sources couvertes : LinkedIn (SAP HCM, SIRH, SuccessFactors, CSM, Formateur IA),
free-work.com (WebSearch SIRH + IA), Ashby (Owkin, Delinea), Lever (Jobgether, Brevo, Sitetracker),
Greenhouse (GoCardless, Samsara), SQORUS, DXC Technology, Deloitte SF, ALTHEA, mc2i,
Trustpair, Pennylane, Figma, Workday CSM, Cegid, SD Worx Payroll,
Strada (nouveau poste entry-level), WorkDispo Formateur IA, LinkedIn Formateur.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from add_offre import ajouter_offres

offres = [

    # ── ONGLET OFFRES SIRH ─────────────────────────────────────────────────────

    # SQORUS - SAP SuccessFactors + Workday
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP SuccessFactors expérimenté (H/F)',
        'Entreprise': 'SQORUS',
        'Source': 'LinkedIn / fr.trabajo.org',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '60-75K€',
        'Durée mission': '',
        'Fit / Notes': 'SQORUS Great Place to Work 8 ans, 1500+ missions CAC40/SBF120. SAP SF expert, posté il y a 1 jour (28/07/2026). Très récent.',
        'Lien': 'https://www.sqorus.com/carrieres/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Senior Oracle HCM Cloud (H/F)',
        'Entreprise': 'SQORUS',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'SQORUS multi-SIRH (SF/Workday/Oracle), posté il y a 18 heures. Fit partiel (Oracle HCM distant de SAP HCM).',
        'Lien': 'https://www.sqorus.com/carrieres/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # DXC Technology - SAP SuccessFactors
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Senior SAP SuccessFactors (H/F)',
        'Entreprise': 'DXC Technology',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'DXC Technology partenaire SAP SF majeur, 130k employés, 70 pays. Postes Paris, posté il y a 2 semaines. SAP SF EC/Payroll/Compensation.',
        'Lien': 'https://careers.dxc.com/global/en/job/51541252/SAP-SuccessFactors-Consultant',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP SuccessFactors Compensation (H/F)',
        'Entreprise': 'DXC Technology',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Module Compensation SF, spécialisé. Posté il y a 2 semaines.',
        'Lien': 'https://careers.dxc.com/global/en/job/51541252/SAP-SuccessFactors-Consultant',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Deloitte - SAP SuccessFactors
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Senior HR Transformation - SAP SuccessFactors (F/H)',
        'Entreprise': 'Deloitte',
        'Source': 'LinkedIn / welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'La Défense (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Deloitte Technology & Transformation, SAP SF + change management RH. Posté il y a 1 semaine. Excellent fit profil.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/deloitte/jobs/consultant-senior-hr-transformation-sap-successfactors-f-h_la-defense',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Analyst SuccessFactors (F/H)',
        'Entreprise': 'Deloitte',
        'Source': 'LinkedIn / welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'Lille',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Deloitte Lille, support SAP SF niveaux 1-3, incidents, config. Posté il y a 4 jours. Profil junior/confirmé.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/deloitte/jobs/analyst-successfactors-f-h_lille',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '65-75K€',
    },

    # SAP - Principal Solution Advisor HCM / SuccessFactors
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Principal Solution Advisor, HCM (F/H)',
        'Entreprise': 'SAP',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Levallois-Perret',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'SAP pre-sales HCM, posté il y a 4 jours. Profil solution advisor senior, 14 ans SAP = fit parfait. Même famille que le poste SAP SuccessFactors déjà identifié.',
        'Lien': 'https://jobs.sap.com/go/SAP-Jobs-in-France/850401/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '95-115K€',
    },

    # ALTHEA - Cabinet conseil SIRH
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) Senior SIRH (H/F)',
        'Entreprise': 'ALTHEA',
        'Source': 'LinkedIn / welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'Issy-les-Moulineaux / Nantes',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'ALTHEA 250+ consultants, expert SIRH transformation RH. Posté il y a 3 semaines. Missions CAC40 SBF120, SAP SF/Workday/Oracle.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/althea/jobs/consultant-sirh-senior-grand-ouest-nantes_issy-les-moulineaux',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Manager / Senior Manager SIRH (H/F)',
        'Entreprise': 'ALTHEA',
        'Source': 'LinkedIn / welcometothejungle.com',
        'Contrat': 'CDI',
        'Localisation': 'Issy-les-Moulineaux',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'ALTHEA niveau Manager/Senior, pilotage projets SIRH. Posté il y a 3 semaines. Niveau tres senior requis.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/althea/jobs/manager-sirh-nantes-cdi-h-f_saint-herblain',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '80-95K€',
    },

    # mc2i - Consultant SIRH/Paie
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) en Transformation Numérique SIRH/Paie (H/F)',
        'Entreprise': 'mc2i',
        'Source': 'welcometothejungle.com / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris (8e)',
        'Remote': 'Partiel',
        'Salaire / TJM': '38-55K€',
        'Durée mission': '',
        'Fit / Notes': 'mc2i cabinet conseil independant 35 ans, 3e Great Place to Work 2025. SIRH/Paie, HR Access/Pléiades/SAP RH. Posté juillet 2026.',
        'Lien': 'https://talents.mc2i.fr/nos-offres/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Cegid - Consultant SIRH Paie Grands Comptes
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH Paie / Grands Comptes (F/H/NB)',
        'Entreprise': 'Cegid',
        'Source': 'jobs.cegid.com',
        'Contrat': 'CDI',
        'Localisation': 'Lyon / France',
        'Remote': 'Partiel',
        'Salaire / TJM': '80K€ (Paris 9e)',
        'Durée mission': '',
        'Fit / Notes': 'Cegid éditeur SIRH leader FR, portefeuille ~30 clients, profil paie + relation client. Poste publié juillet 2026. Salaire 80K€ Paris mentionné.',
        'Lien': 'https://jobs.cegid.com/fr/annonce/3815699-consultant-sirh-paie-grands-comptes-fhnb-69009-lyon',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # SD Worx - Payroll Implementation Consultant (nouveau vs celui déjà dans le tableur)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Payroll Implementation Consultant (French Speaking)',
        'Entreprise': 'SD Worx',
        'Source': 'careers.sdworx.com',
        'Contrat': 'CDI',
        'Localisation': 'France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'SD Worx paie/RH internationale, 90k clients. Consultant paie + implémentation HRIS. Posté juin 2026. Différent du poste SIRH implémentation déjà ajouté.',
        'Lien': 'https://careers.sdworx.com/jobs/7783766-payroll-implementation-consultant',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Strada - Entry-level SAP HCM (nouveau poste)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Entry-level SAP HCM Payroll Consultant (French speaker)',
        'Entreprise': 'Strada (ex-Alight)',
        'Source': 'careers.alight.com',
        'Contrat': 'CDI',
        'Localisation': 'Colombes, France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Nouveau poste Strada, profil junior/confirmé paie SAP FR. Différent des deux postes Senior déjà ajoutés. Posté 2026.',
        'Lien': 'https://careers.alight.com/strada/us/en/job/ALIGUSR30484STRADAENUS/Entry-level-SAP-HCM-Payroll-Consultant-French-speaker',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '60-70K€',
    },

    # free-work.com - AMOA SIRH nouvelles missions
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant AMOA SIRH (Performance & International) - Full remote possible',
        'Entreprise': 'Cherry Pick (pour client)',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'AMOA SIRH international, lien Group HR et entités locales, évaluation de la performance. Full remote possible. Très bon fit profil L\'Oréal mondial.',
        'Lien': 'https://www.free-work.com/fr/tech-it/consultant-moa-amoa/job-mission/consultant-amoa-sirh-performance-international-full-remote-possible',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant AMOA SIRH / Recette fonctionnelle',
        'Entreprise': 'Signe + (pour client public)',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Marseille',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Secteur public, recette fonctionnelle SIRH. Posté 15/02/2026. A vérifier si toujours actif.',
        'Lien': 'https://www.free-work.com/fr/tech-it/consultant-moa-amoa/job-mission/consultant-amoa-sirh-recette-fonctionnelle',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '600-700€/j',
    },
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de Projet SIRH Senior - Projet from scratch',
        'Entreprise': 'Scalesquad (pour client bancaire)',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Montpellier',
        'Remote': 'Partiel (2j/sem)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Chef de projet SIRH senior 7 ans exp requis, secteur bancaire, projet from scratch. Oracle HCM migration. Posté 2026.',
        'Lien': 'https://www.free-work.com/fr/tech-it/administrateur-erp/job-mission/chef-de-projet-sirh-senior-projet-from-scratch-montpellier',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de Projet SIRH HR4Y (H/F)',
        'Entreprise': 'FED SAS (pour client)',
        'Source': 'free-work.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris (75001)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Chef de projet SIRH 5 ans exp requis, HR4Y, périmètre international. CDI.',
        'Lien': 'https://www.free-work.com/fr/tech-it/assistant-chef-de-projet/job-mission/chef-de-projet-sirh-hr4y-h-f-7',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de Projet IA / Transformation Digitale (F/H)',
        'Entreprise': 'CELAD',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Noisy-le-Grand (93)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'CDP IA + transformation digitale, déploiement solutions IA, objectif 2026. Posté 05/06/2026.',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/assistant-chef-de-projet/chef-de-projet-ia-transformation-digitale-f-h',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500-650€/j',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de projet IA (H/F)',
        'Entreprise': 'Mindquest (pour client)',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Issy-les-Moulineaux (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Mission CDP IA, client majeur, optimisation processus métiers IA. Posté 19/05/2026.',
        'Lien': 'https://www.free-work.com/fr/tech-it/assistant-chef-de-projet/job-mission/chef-de-projet-ia-h-f-92',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500-650€/j',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant AMOA GTA SIRH (H/F)',
        'Entreprise': 'Tenth Revolution Group',
        'Source': 'free-work.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris (75)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'AMOA GTA SIRH, CDI. Tenth Revolution Group spécialiste SAP RH.',
        'Lien': 'https://www.free-work.com/fr/tech-it/consultant-moa-amoa/job-mission/consultant-amoa-gta-sirh',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP HCM & SuccessFactors Expert',
        'Entreprise': 'Client (via free-work)',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Île-de-France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Mission SAP HCM + SF, harmonisation processus RH + ServiceNow HRSD. Fit parfait expertise L\'Oréal.',
        'Lien': 'https://www.free-work.com/fr/tech-it/consultant-erp-ms-dynamics-oracle-sage-sap/job-mission/consultant-sap-hcm-successfactors-expert',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Support Applicatif SIRH - SAP SuccessFactors EC & PMGM',
        'Entreprise': 'WorldWide People (pour client)',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris (présentiel)',
        'Remote': 'Non',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'L2 support SF EC & PMGM, certification SF requise. Présentiel Paris. Moins attractif remote absent.',
        'Lien': 'https://www.free-work.com/fr/tech-it/administrateur-applicatif-erp-crm-sirh/job-mission/246016-support-applicatif-sur-sirh-presentiel-a-paris-certification-sap-successfactors-ec-pmgm',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '550-650€/j',
    },

    # ── ONGLET OFFRES CSM ──────────────────────────────────────────────────────

    # Owkin - Senior CSM (IA biotech)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager',
        'Entreprise': 'Owkin',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris / Remote France, UK, DE',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Owkin AI Biology (BASI), clients pharma/biotech/académiques. Partenaire stratégique, lifecycle K Pro. Posté 12/06/2026. Croisement parfait IA + CSM enterprise.',
        'Lien': 'https://jobs.ashbyhq.com/owkin/a2332329-a5da-4bc3-a6eb-ea8bbc49e637',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # GoCardless - Enterprise France CSM
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager - Enterprise France',
        'Entreprise': 'GoCardless',
        'Source': 'boards.greenhouse.io',
        'Contrat': 'CDI',
        'Localisation': 'Paris (Hybride)',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'GoCardless paiements bancaires, 100k+ clients, $130Bn/an. Profil CSM Enterprise France, plans de succès, renouvellements. Partenariat Sales/Onboarding.',
        'Lien': 'https://boards.greenhouse.io/gocardless/jobs/2426911',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Trustpair - CSM Europe
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager (Europe) (M/F/Mx)',
        'Entreprise': 'Trustpair',
        'Source': 'jobs.trustpair.com / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris (Hybride)',
        'Remote': 'Hybride',
        'Salaire / TJM': '38-55K€ + variable 5-10.5K€',
        'Durée mission': '',
        'Fit / Notes': 'Trustpair plateforme anti-fraude fournisseurs, 400+ entreprises Fortune 500. CSM B2B enterprise Europe. 4 ans exp requis. Salaire affiché. Paris/NYC/London/Milan.',
        'Lien': 'https://jobs.trustpair.com/jobs/7378138-customer-success-manager-europe-m-f-mx',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Pennylane - CSM SAAS
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager - SAAS',
        'Entreprise': 'Pennylane',
        'Source': 'welcometothejungle.com / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Pennylane FinTech FR fastest-growing, 1000+ Pennylaners, plateforme PME Europe. CSM SaaS B2B. Posté 27/02/2026.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/pennylane/jobs/customer-success-manager-saas_paris_PENNY_dWlD9JV',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Figma - Customer Enablement Manager Paris
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Enablement Manager - French Speaking (Paris, FR)',
        'Entreprise': 'Figma',
        'Source': 'Thrive Capital Jobs / Greenhouse',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Figma design leader, Paris office, accompagnement adoption enterprise, partenariat AE. Posté 22/04/2026. Profil CSM/enablement senior EN requis.',
        'Lien': 'https://jobs.thrivecap.com/companies/figma-2/jobs/75635051-customer-enablement-manager-paris-france',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Workday - Senior CSM French Speaking
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager - French Speaking',
        'Entreprise': 'Workday',
        'Source': 'workday.wd5.myworkdayjobs.com',
        'Contrat': 'CDI',
        'Localisation': 'Europe (Remote)',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Workday HCM, CSM French speaker EMEA, posté 03/03/2026. Croisement parfait HRIS + CSM enterprise. A vérifier si encore actif.',
        'Lien': 'https://workday.wd5.myworkdayjobs.com/en-US/Workday/job/Senior-Customer-Success-Manager---French-Speaking_JR-0104970',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Delinea - CSM French Speaking
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager (French Speaking)',
        'Entreprise': 'Delinea',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'France (Remote)',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Delinea cybersécurité IAM/PAM, CSM French speaker. Profil CSM enterprise B2B. Remote France.',
        'Lien': 'https://jobs.ashbyhq.com/delinea/3d0f78d9-9d90-4461-8a26-ab06a6839474',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Septeo - CSM RH
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager RH (H/F)',
        'Entreprise': 'SEPTEO',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Bordeaux',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Septeo éditeur logiciels RH, CSM domaine RH. Posté il y a 2 semaines. Bordeaux = proche Anglet.',
        'Lien': 'https://fr.linkedin.com/jobs/view/customer-success-manager-rh-h-f-at-septeo-4439722601',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Nosto - CSM Paris
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager',
        'Entreprise': 'Nosto',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Nosto plateforme personalisation e-commerce, CSM Paris. Posté il y a 4 jours.',
        'Lien': 'https://fr.linkedin.com/jobs/view/customer-success-manager-at-nosto-4444458274',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Deel - CSM IT French or German
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager, Deel IT (German or French)',
        'Entreprise': 'Deel',
        'Source': 'jobs.ashbyhq.com',
        'Contrat': 'CDI',
        'Localisation': 'Remote',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Deel HRIS global (150+ pays), CSM IT/HRIS. French ou German speaker, remote. Croisement HRIS + CSM parfait. Profil senior.',
        'Lien': 'https://jobs.ashbyhq.com/deel/2fc7826c-3e54-40d8-ad26-22364517c27d',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Index Ventures - Remote Senior Payroll CSM
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Payroll Customer Success Manager - EMEA',
        'Entreprise': 'Remote (via Index Ventures)',
        'Source': 'indexventures.com jobs',
        'Contrat': 'CDI',
        'Localisation': 'Remote (EMEA)',
        'Remote': '100%',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Remote.com plateforme EOR/HRIS global, CSM Senior paie EMEA. Expertise paie internationale requise. Fit fort avec background L\'Oréal/SAP paie.',
        'Lien': 'https://www.indexventures.com/startup-jobs/remote/senior-payroll-customer-success-manager-emea-2/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # ── ONGLET OFFRES IA ────────────────────────────────────────────────────────

    # Formateur IA LinkedIn - Walter Learning
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur - Intelligence Artificielle Générative (F/H)',
        'Entreprise': 'Walter Learning',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Walter Learning organisme formation leader, formateur IA générative. Posté il y a 2 mois. A vérifier disponibilité.',
        'Lien': 'https://fr.linkedin.com/jobs/formateur-intelligence-artificielle-emplois-france',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '60-75K€',
    },
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur en Intelligence Artificielle (F/H)',
        'Entreprise': 'Groupe MDA',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'France',
        'Remote': 'Partiel',
        'Fit / Notes': 'Groupe MDA formation IT/IA, CDI formateur IA France. Posté il y a 3 semaines. MDA = cabinet conseil ET formation.',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Lien': 'https://fr.linkedin.com/jobs/formateur-intelligence-artificielle-emplois-france',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '65-80K€',
    },

    # Scrum Master IA Générative / SAFe - CELAD
    {
        'Priorité': '⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Scrum Master Senior - IA Générative / SAFe',
        'Entreprise': 'CELAD',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Scrum Master equipes IA générative, SAFe. Posté 21/07/2026. Profil plus technique que cible.',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/scrum-master-agile-coach/scrum-master-senior-ia-generative-safe',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '500-600€/j',
    },

]

if __name__ == '__main__':
    ajouter_offres(offres, verbose=True)
    print("\nTerminé. Offres ajoutées dans offres_emploi.xlsx")
