"""
Ajout des offres trouvées lors de la recherche du 2026-07-30.
Sources couvertes : LinkedIn (SAP HCM, SIRH, SuccessFactors, CSM, Formateur IA),
free-work.com (IA/IA générative + WebSearch SIRH + SAP HCM), AshbyHQ, Lever,
welcometothejungle.com, HR Path, Deloitte, KPMG, EY, Grant Thornton, mc2i, Wavestone,
Strada (Alight), DXC Technology, SQORUS, Onepoint, Infotel Conseil, Movement Group,
ConvictionsRH, Mister IA, Keyrus, Wemodo, Walter Learning, DataBird, Nextra-Partners,
mission-freelances.fr.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from add_offre import ajouter_offres

offres = [

    # ── ONGLET OFFRES SIRH ─────────────────────────────────────────────────────

    # SAP — Principal Solution Advisor SuccessFactors (nouveau poste ~24/07/2026)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Principal Solution Advisor, SuccessFactors (F/H)',
        'Entreprise': 'SAP',
        'Source': 'LinkedIn / SAP Jobs France',
        'Contrat': 'CDI',
        'Localisation': 'Levallois-Perret (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste pre-sales HCM senior SAP France, publié ~24/07/2026 (il y a 6 jours). 10-15 ans expérience SAP requis dont 3-5 ans HCM, Cloud SaaS B2B, anglais+français. Fit exceptionnel : 14 ans SAP HR, L\'Oréal 40 pays, profil face client. Voir jobs.sap.com/go/SAP-Jobs-in-France/850401/ pour le lien actif.',
        'Lien': 'https://fr.linkedin.com/jobs/view/principal-solution-advisor-successfactors-f-h-at-sap-4415727184',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '95-115K€',
    },

    # Deloitte — Consultant Senior HR Transformation SAP SuccessFactors
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Senior HR Transformation - SAP SuccessFactors (F/H)',
        'Entreprise': 'Deloitte',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Deloitte Human Capital. Pilotage projets SAP SuccessFactors, ateliers métier, déploiement opérationnel, certifications SF proposées. 5-10 ans SIRH requis. Fit excellent croisement SAP HR + conseil grands comptes.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/deloitte/jobs/consultant-senior-hr-transformation-sap-successfactors-f-h_paris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # KPMG — Responsable SIRH (migration PeopleSoft → SAP SuccessFactors)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Responsable SIRH F/H (migration PeopleSoft → SAP SuccessFactors)',
        'Entreprise': 'KPMG France',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'La Défense (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste interne KPMG : manager la migration PeopleSoft vers SAP SuccessFactors, management d\'équipe. Min. 10 ans SIRH. Pas un poste conseil mais fit technique exceptionnel — migration SAP HR = coeur du profil. KPMG groupe international 180+ pays.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/kpmg-france/jobs/responsable-sirh-f-h_courbevoie',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '90-110K€',
    },

    # HR Path — Consultant SIRH Senior/Lead (Workday/Oracle/SAP SuccessFactors)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH Senior/Lead (Workday / Oracle HCM / SAP SuccessFactors) H/F',
        'Entreprise': 'HR Path',
        'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris La Défense',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Publié 27/07/2026. Niveau Senior/Lead/Chef de projet SIRH, projets internationaux, min. 4 ans SIRH, Workday ou Oracle HCM ou SAP SF, anglais professionnel. HR Path = spécialiste #1 RH tech Europe. Fit excellent — senior assumé dans l\'intitulé.',
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SIRH-%28HF%29-Workday-%E2%80%A2-Oracle-HCM-%E2%80%A2-SAP-SuccessFactors-75-92042/1419350533/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Strada (ex-Alight) — Consultant SAP HCM Paie senior
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP HCM Paie senior',
        'Entreprise': 'Strada (ex-Alight / ex-NGA Human Resources)',
        'Source': 'careers.alight.com/strada',
        'Contrat': 'CDI',
        'Localisation': 'Colombes (92)',
        'Remote': 'Oui (depuis toute la France)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Strada = 1er partenaire mondial SAP HR. Configuration payroll SAP HCM France (cycles, schémas, contributions, accounting). 5+ ans SAP HCM Payroll requis. Fit parfait. Remote depuis toute la France confirmé. 2 annonces actives (R-27911 et R-32021).',
        'Lien': 'https://careers.alight.com/strada/us/en/job/ALIGUSR32021STRADAENUS/Consultant-SAP-HCM-Paie-senior',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Duonext — Consultant SAP Paie HCM Payroll (freelance, démarrage sept. 2026)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP Paie HCM Payroll',
        'Entreprise': 'Client via Duonext',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Département 92',
        'Remote': 'Hybride (2-3j/semaine sur site)',
        'Salaire / TJM': '650-750€/j',
        'Durée mission': '6 mois min. renouvelables',
        'Fit / Notes': 'Publié 22/06/2026. Démarrage septembre 2026. Transformation RH, expertise paie France obligatoire (DSN, contributions, accounting), 8-10 ans requis. Très bon fit L\'Oréal paie France multisite.',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-paie-hcm-payroll',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },

    # Apps IT Limited — SAP HCM French Payroll (100% remote)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'SAP HCM Technico-Functional Consultant French Payroll',
        'Entreprise': 'Apps IT Limited',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'France',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '650-750€/j',
        'Durée mission': '6 mois',
        'Fit / Notes': 'Publié 17/06/2026. 100% remote — fit parfait pour Anglet. Profil technico-fonctionnel SAP HCM French Payroll. À vérifier disponibilité (publié il y a 6 semaines). Lien : rechercher "Apps IT" sur free-work.com/fr/tech-it/jobs/sap-hcm.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sap-hcm',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },

    # Movement Group — SAP HCM Consultant French Payroll (100% remote, 12 mois)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'SAP HCM Consultant French Payroll',
        'Entreprise': 'Client via Movement Group',
        'Source': 'movementgroup.uk',
        'Contrat': 'Freelance',
        'Localisation': 'Remote',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '650-750€/j',
        'Durée mission': '12 mois + extension',
        'Fit / Notes': 'Movement Group = cabinet recrutement SAP UK/Europe. 100% remote, 12 mois extensible. Outside IR35 (client probablement UK/international). 3+ ans SAP Payroll France requis. Durée et remote = fit parfait.',
        'Lien': 'https://movementgroup.uk/job/sap-hcm-consultant-time-management/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '650-750€/j',
    },

    # HR Path — Consultant SAP SuccessFactors H/F (publié 16/07/2026)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP SuccessFactors (H/F)',
        'Entreprise': 'HR Path',
        'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris La Défense',
        'Remote': 'Oui (télétravail + déplacements ponctuels internationaux)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Publié 16/07/2026. Modules EC, PMGM, RCM, RMK, ONB, COMP, LMS, ECP. Min. 2 ans SAP SF, anglais courant, projets internationaux. HR Path cabinet spécialisé RH tech. Fit excellent.',
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SAP-SuccessFactors-%28HF%29-75-92042/818651901/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # HR Path — Consultant SAP HCM H/F (publié 19/07/2026)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP HCM (H/F)',
        'Entreprise': 'HR Path',
        'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI',
        'Localisation': 'Villeneuve-d\'Ascq / Strasbourg / Lyon / Toulouse',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Publié 19/07/2026. Toutes phases implémentation SAP HCM (PA, OM, Paie, GTA), ateliers, paramétrage, formation. Min. 2 ans SAP HCM. Plusieurs localisations hors Paris. Lyon/Toulouse plus proches d\'Anglet.',
        'Lien': 'https://jobs.hr-path.com/job/Villeneuve-d%E2%80%99Ascq-Consultant-SAP-HCM-%28HF%29-59-59650/770170201/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # DXC Technology — Consultant Senior SAP SuccessFactors
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Senior SAP SuccessFactors',
        'Entreprise': 'DXC Technology',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel (déplacements client 2-3j/semaine)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'DXC Technology groupe IT services mondial. 3 postes ouverts : 1 Senior SF généraliste + 2 Compensation. Publié il y a 3 semaines. Min. 3 ans, anglais B2. Fit solide SAP SF.',
        'Lien': 'https://fr.linkedin.com/jobs/view/consultant-senior-sap-successfactors-at-dxc-technology-4438231698',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # SQORUS — Consultant SAP SuccessFactors expérimenté H/F
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP SuccessFactors expérimenté (H/F)',
        'Entreprise': 'SQORUS',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris et périphérie',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'SQORUS cabinet conseil SIRH. 5 ans SIRH minimum, multi-modules SF, projets internationaux, anglais B2. Publié il y a 3 jours (30/07/2026). 55 candidatures. Bonne adéquation profil.',
        'Lien': 'https://fr.linkedin.com/jobs/view/consultant-sap-successfactors-exp%C3%A9riment%C3%A9-h-f-at-sqorus-4396619283',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Strada — Consultant SAP HCM Time senior
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP HCM Time senior',
        'Entreprise': 'Strada (ex-Alight)',
        'Source': 'careers.alight.com/strada',
        'Contrat': 'CDI',
        'Localisation': 'Colombes (92)',
        'Remote': 'Oui (depuis toute la France)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Strada 1er partenaire SAP HR. Module Time Management SAP HCM. Remote France confirmé. En complément du poste Paie senior (voir autre entrée).',
        'Lien': 'https://careers.alight.com/strada/us/en/job/ALIGUSR27913STRADAENUS/Consultant-SAP-HCM-Time-senior',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Infotel Conseil — Expert Technico-Fonctionnel SAP HCM (grande compagnie aérienne)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Expert Technico-Fonctionnel SAP HCM',
        'Entreprise': 'Infotel Conseil (client : grande compagnie aérienne FR)',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Roissy-en-France (95)',
        'Remote': 'Partiel',
        'Salaire / TJM': '540-750€/j',
        'Durée mission': '3 mois renouvelables',
        'Fit / Notes': 'Publié 24/06/2026. Client = grande compagnie aérienne française (probablement Air France). AMOA/BA hybride : specs SF EC, tests, formation, liaison métier/dev. 10+ ans requis, SAP HCM PA/OM, SF EC apprécié. Fit excellent L\'Oréal 10 ans SAP HR.',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/expert-technico-fonctionnel-sap-hcm',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },

    # LeHibou — Expert SAP SuccessFactors (posté 30/07/2026 = aujourd'hui)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Expert SAP SuccessFactors',
        'Entreprise': 'LeHibou (via free-work.com)',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Saint-Ouen-sur-Seine (93)',
        'Remote': 'Partiel',
        'Salaire / TJM': '575€/j',
        'Durée mission': '6 mois',
        'Fit / Notes': 'POSTÉ CE JOUR (30/07/2026) — à postuler rapidement. LeHibou = plateforme N°1 freelance IT grands comptes FR. TJM 575€/j = sous cible mais renégociable. SAP SuccessFactors expert.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sap-successfactors',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },

    # EY — Manager / Senior Manager Transformation RH (plus senior que les postes déjà dans tableur)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Manager / Senior Manager Transformation RH (H/F)',
        'Entreprise': 'EY',
        'Source': 'careers.ey.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris La Défense',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Publié 14/07/2026. EY People Consulting — Programmes internationaux digitalisation RH, SAP SuccessFactors + Workday + ServiceNow, intégration IA/GenAI dans les RH, management d\'équipes. Niveau Manager/Senior Manager = plus senior que les autres postes EY dans tableur.',
        'Lien': 'https://careers.ey.com/ey/job/Paris-La-D%C3%A9fense-ManagerSenior-Manager-en-Transformation-RH-HF-%28Paris%29-92037/1404311033/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Grant Thornton — Consultant Senior SIRH et Conseil RH H/F
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Senior SIRH et Conseil RH (H/F)',
        'Entreprise': 'Grant Thornton',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Neuilly-sur-Seine',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Grant Thornton Operational Consulting. Sélection SIRH (RFP, specs), gestion projet SIRH (design, config, tests, migration data, formation), change management. Min. 5 ans SIRH dont 2 ans conseil. Fit excellent. Salaire consultant senior GT ~60-75K€ estimé.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/grant-thornton/jobs/consultant-senior-en-sirh-et-conseil-rh-neuilly-h-f_neuilly-sur-seine_GT_XWDWeVd',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # Wavestone — Senior Consultant/Manager HR Technologies (Lyon)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Consultant/Manager HR Technologies - People & Change',
        'Entreprise': 'Wavestone',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Lyon',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Wavestone Practice People & Change (140 consultants). AMOA SIRH, sélection solutions (Core HR, Talent, Paie, Analytics), feuilles de route SIRH, projets internationaux. Fit excellent — c\'est exactement le profil. Lyon = plus accessible qu\'IDF depuis Anglet.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/wavestone/jobs/senior-consultant-e-manager-euse-hr-technologies-people-change-cdi_lyon',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # mc2i — Consultant Talent Management / HRIS Internationally H/F
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Talent Management / HRIS Internationally (H/F)',
        'Entreprise': 'mc2i',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Paris (8e)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'mc2i cabinet conseil digital indépendant 1350+ personnes, 3e Great Place to Work 2025. Core HR international, Talent Management (perf, formation, mobilité), Workday / SuccessFactors / Cornerstone. Anglais fort requis. Fit très bon international.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/mc2i/jobs/consultant-in-talent-management-hris-internationally-h-f_paris_MC2I_5zbyXXD',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '70-85K€',
    },

    # ConvictionsRH — Consultant AMOA SAP SuccessFactors H/F
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant AMOA SAP SuccessFactors (H/F)',
        'Entreprise': 'ConvictionsRH',
        'Source': 'convictionsrh.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Min. 3 ans SF, modules EC/RCM/ONB/COMP/LMS/ECP, anglais courant, projets internationaux. ConvictionsRH = cabinet conseil SIRH (présences FR/BE/CH/ES/PT/MA/CA). Profil conseil/AMOA valorisé. Bon fit.',
        'Lien': 'https://www.convictionsrh.com/job/consultante-amoa-sap-successfactors-h-f/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # PREREQUIS — Consultant SAP ECC HCM Time Management Senior (600-650€/j)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SAP ECC HCM Time Management Senior (H/F)',
        'Entreprise': 'Client via PREREQUIS',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'La Garenne-Colombes (92)',
        'Remote': 'Hybride (3j remote + 2j lundi/mercredi sur site)',
        'Salaire / TJM': '600-650€/j',
        'Durée mission': '110 jours renouvelables',
        'Fit / Notes': 'Publié 01/07/2026. Support et amélioration Time Management SAP HCM. 5-10 ans expérience requis. TJM 600-650€/j = sous cible mais hybride 3j remote.',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-ecc-hcm-time-management-senior-h-f',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },

    # Onepoint — Consultant SIRH F/H
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant SIRH (F/H)',
        'Entreprise': 'Onepoint',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Publié il y a 1 jour (30/07/2026). Onepoint cabinet conseil digital. Missions AMOA, audit SIRH, déploiements SAP/Oracle/Workday/ADP, conduite du changement. 2-8 ans expérience. 200+ candidatures — très concurrentiel. Grande école requise.',
        'Lien': 'https://fr.linkedin.com/jobs/view/consultant-sirh-%E2%80%93-f-h-at-onepoint-4329056727',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # HR Path — Consultant Senior AMOA GA/Paie H/F (publié 28/07/2026)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Senior AMOA GA/Paie (H/F)',
        'Entreprise': 'HR Path',
        'Source': 'jobs.hr-path.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris La Défense',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Publié 28/07/2026. AMOA RH, GA/Paie, expertise Cegid/Cegedim/ADP/HR Access. Fit partiel — Gaëtan fort sur SAP HR mais pas spécialiste paie pure sur ces outils. À postuler si SAP HCM Paie France accepté.',
        'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-Senior-AMOA-GAPaie-%28HF%29-75-92042/1419635633/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # CGI — Consultant fonctionnel SIRH F/H
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant fonctionnel SIRH (F/H)',
        'Entreprise': 'CGI',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'CGI groupe IT services. SAP-HR / SuccessFactors, secteurs transport + secteur public + RH. Fit partiel (secteur public moins dans la cible mais compétences SAP HR directement applicables).',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/cgi/jobs/consultant-sirh-f-h-transport-secteur-public-et-hr_paris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # ── ONGLET OFFRES CSM ──────────────────────────────────────────────────────

    # Owkin — Senior Customer Success Manager (IA pharma, remote France)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager',
        'Entreprise': 'Owkin',
        'Source': 'AshbyHQ',
        'Contrat': 'CDI',
        'Localisation': 'Paris (remote France/UK/DE accepté)',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Owkin IA biologique pour pharma/biotech/académiques. CSM stratégique produit K Pro, gestion NRR, CLV, adoption. Mentor junior CSMs. Publié ~12/06/2026 (vérifier disponibilité). Fort fit : senior, B2B enterprise, IA, remote France.',
        'Lien': 'https://jobs.ashbyhq.com/owkin/a2332329-a5da-4bc3-a6eb-ea8bbc49e637',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Sitetracker — Senior Customer Success Manager French Speaker (remote EMEA)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager (French Speaker)',
        'Entreprise': 'Sitetracker',
        'Source': 'Lever',
        'Contrat': 'CDI',
        'Localisation': 'Remote EMEA (France + Benelux)',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Sitetracker SaaS infrastructure/construction. Gestion portefeuille enterprise France + Benelux, plans de succès, renouvellements, navigation grands comptes complexes. Remote EMEA. Fit très fort : senior, French speaker, remote, enterprise B2B.',
        'Lien': 'https://jobs.lever.co/sitetracker/3d537233-47b4-4f8c-b393-6479ecabe968',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Navan — Enterprise Customer Success Manager French Speaking (Paris)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Enterprise Customer Success Manager (French Speaking)',
        'Entreprise': 'Navan',
        'Source': 'LinkedIn / TheMuse',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Navan scale-up bien financé travel & expense management. CSM enterprise, clients C-suite, onboarding, adoption, retention. Publié il y a 2 semaines. French speaking, enterprise B2B = bon fit.',
        'Lien': 'https://www.linkedin.com/jobs/view/enterprise-customer-success-manager-french-speaking-at-navan',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Heidi Health — Customer Success Manager France (IA médicale)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager France',
        'Entreprise': 'Heidi Health AI',
        'Source': 'LinkedIn (posté 28/07/2026)',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'À confirmer',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Heidi IA médicale forte expansion Europe. Poste France visible LinkedIn il y a 2 jours (28/07/2026). Postes CSM actifs aussi en DE/UK/IE. IA + CSM senior + France = fort fit. Vérifier heidihealth.com/careers pour détails.',
        'Lien': 'https://www.heidihealth.com/careers',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Immersive Labs — Customer Success Manager French Speaking (remote EU, cybersécurité)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager (French Speaking)',
        'Entreprise': 'Immersive Labs',
        'Source': 'AshbyHQ',
        'Contrat': 'CDI',
        'Localisation': 'Remote Europe',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Immersive Labs plateforme formation cybersécurité. CSM francophones, 100% remote. Profil CSM senior, B2B SaaS. Secteur cyber = nouveau mais missions CSM standards. Salaire estimé ~$91-132k US (Europe moins).',
        'Lien': 'https://jobs.ashbyhq.com/immersivelabs/6516d68a-e513-40bf-99f4-bebc2135a3f2',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Delinea — Customer Success Manager French Speaking (remote EU, identity security)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager (French Speaking)',
        'Entreprise': 'Delinea',
        'Source': 'AshbyHQ',
        'Contrat': 'CDI',
        'Localisation': 'Remote France / Europe',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Delinea identity security (PAM/cybersécurité). CSM French speaking pour marché francophone, 100% remote. Profil CSM enterprise B2B. Secteur cybersécurité = nouveau mais fort fit remote + senior.',
        'Lien': 'https://jobs.ashbyhq.com/delinea/3d0f78d9-9d90-4461-8a26-ab06a6839474',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # n8n — Manager Customer Success EMEA (remote, gestion d'équipe)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Manager, Customer Success EMEA',
        'Entreprise': 'n8n',
        'Source': 'AshbyHQ',
        'Contrat': 'CDI',
        'Localisation': 'Remote EMEA (Paris/Londres/Barcelone/Berlin)',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'n8n plateforme automation bien connue. Management d\'équipe CSMs EMEA, rattaché VP Global CS. 10+ ans CS requis, 2+ ans management. Poste de manager = si Gaëtan ouvert au management. Remote EMEA = fit géographique parfait.',
        'Lien': 'https://jobs.ashbyhq.com/n8n/018bb06a-6147-4e04-aa4b-8a9daf0558bd',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Oodrive — Customer Success Manager Senior (hybride Paris, éditeur SaaS souverain)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager Senior',
        'Entreprise': 'Oodrive',
        'Source': 'careers.oodrive.com / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris Poissonnière',
        'Remote': 'Hybride (2j remote/semaine)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Oodrive éditeur SaaS souverain (signature électronique, coffre-fort numérique). Équipe 4 CSMs, clients enterprise, gestion NRR/GRR, renouvellements, expansion. Poste senior. Paris 3j/semaine = contrainte depuis Anglet.',
        'Lien': 'https://careers.oodrive.com/jobs/7973683-customer-success-manager-senior',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Brevo — Senior Customer Success Manager French Speaker (Paris, CRM)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager (French Speaker)',
        'Entreprise': 'Brevo',
        'Source': 'Lever',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '~95K€ total comp (Glassdoor)',
        'Durée mission': '',
        'Fit / Notes': 'Brevo scale-up CRM/email marketing. CSM senior French speaker, 4+ ans requis. Salaire ~95K€ total comp Glassdoor Paris. Fit correct mais B2B CRM moins enterprise/SAP que l\'expérience de Gaëtan.',
        'Lien': 'https://jobs.lever.co/brevo/8cba557a-b2f5-4652-bd86-5e000940239b',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # AssessFirst — Customer Success Manager France (100% remote, RH Tech)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager France',
        'Entreprise': 'AssessFirst',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'France',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'AssessFirst SaaS RH prédictif (recrutement basé sur sciences comportementales). CSM marché France, health scoring. 100% remote = fit parfait pour Anglet. Connexion secteur RH Tech avec profil SIRH. Salaire probablement sous cible (40-55K€ estimé).',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/assessfirst/jobs/customer-success-manager-france_paris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # NUMA — Customer Success Manager bilingue EN/FR (100% remote, formation leadership)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager bilingue EN/FR',
        'Entreprise': 'NUMA',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'France',
        'Remote': 'Oui (remote first)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'NUMA cabinet formation/conseil leadership et transformation. CSM bilingue, gestion coaches externes, coordination clients entreprises. 100% remote. Lien formation/transformation = synergies avec profil IA et SIRH de Gaëtan.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/numa/jobs/customer-success-manager_paris_NUMA_x89JJdA',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Trustpair — Customer Success Manager Europe (Paris, fintech, salaire bas)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager Europe (M/F/Mx)',
        'Entreprise': 'Trustpair',
        'Source': 'Welcome to the Jungle / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '38-55K€ + variable (sous cible)',
        'Durée mission': '',
        'Fit / Notes': 'Trustpair fintech lutte fraude aux paiements. Portefeuille grands comptes européens, renouvellements. Publié il y a 1 semaine. Salaire affiché 38-55K€ = sous cible Gaëtan. À inclure mais négociation difficile.',
        'Lien': 'https://jobs.trustpair.com/jobs/7378138-customer-success-manager-europe-m-f-mx',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # Modjo — Customer Success Manager Mid-Market (remote Paris, IA conversations)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager Mid-Market',
        'Entreprise': 'Modjo',
        'Source': 'Welcome to the Jungle / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Oui (remote autorisé)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Modjo plateforme IA analyse conversations commerciales. Portefeuille mid-market €15k-€60k ARR. Publié il y a 1 semaine. IA + CSM + remote = bon fit, mais mid-market (pas enterprise). Scale-up FR connue.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/modjo/jobs/customer-success-manager-mid-market-f-m_paris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-95K€',
    },

    # ── ONGLET OFFRES IA ────────────────────────────────────────────────────────

    # Mister IA — Chef de projet BU Conseil IA générative
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Chef de projet BU Conseil IA générative',
        'Entreprise': 'Mister IA',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Paris 8e',
        'Remote': 'À confirmer',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Mister IA cabinet conseil + organisme formation spécialisé IA générative, 100+ collaborateurs, 30 000 personnes formées, CA 12M€ en 2026. Coordination missions BU Conseil, pilotage équipe consultants IA. Fit parfait : gestion comptes + IA quotidien + coordination équipes = coeur du profil Gaëtan.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/mister-ia/jobs/chef-de-projet-bu-conseil-h-f-cdi-paris-8e-asap_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '70-85K€',
    },

    # Mister IA — Formateur/Formatrice IA générative
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur/Formatrice IA générative',
        'Entreprise': 'Mister IA',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel (présentiel + distanciel pour sessions)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Mister IA organisme formation IA générative n°1 FR. Animer sessions présentiel/distanciel, préparer contenu pédagogique, accompagner participants. Fit excellent : pédagogue naturel, usage quotidien IA générative. Entreprise en croissance explosive.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/mister-ia/jobs/formateur-formatrice-en-intelligence-artificielle-generative_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '60-75K€',
    },

    # Keyrus — Consultant IA générative Innovation (Bordeaux hybride)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant IA générative Innovation (AI Innovation Consultant)',
        'Entreprise': 'Keyrus France',
        'Source': 'jobs.keyrus.fr',
        'Contrat': 'CDI',
        'Localisation': 'Bordeaux',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Keyrus cabinet conseil data & IA. Posté 25/06/2026. Accompagnement organisations pour identifier et déployer cas d\'usage IA générative, animation ateliers, prototypes no-code/low-code, conduite du changement IA. Bordeaux = accessible depuis Anglet (2h). Fit très bon sans Python/data science pur requis.',
        'Lien': 'https://jobs.keyrus.fr/jobs/7969635-ai-innovation-consultant-h-f-nb',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '60-75K€',
    },

    # Wemodo — Formateur.ice IA génératives (100% remote, freelance)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur.ice IA génératives (freelance)',
        'Entreprise': 'Wemodo (ex Webmyday)',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'Freelance',
        'Localisation': 'France',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Wemodo animer formations certifiantes IA générative (ChatGPT, Claude, Gemini, Midjourney, Firefly), rôle jury d\'examen. 100% remote = fit parfait Anglet. SIRET requis. Expérience min. 2 ans outils IA générative.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/web-my-day/jobs/formateur-ice-referent-e-ia_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '400-600€/j',
    },

    # Nextra-Partners — Consultant Formateur IA (Marseille hybride, CDI ou freelance)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Formateur IA',
        'Entreprise': 'Nextra-Partners',
        'Source': 'nextra.factorial.fr',
        'Contrat': 'CDI ou Freelance',
        'Localisation': 'Marseille',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Cabinet conseil Data & IA Marseille/Toulouse. Conception et animation parcours formation IA/Data + développement commercial de l\'Academy. 13e mois + bonus déplafonné. Anglais courant requis. Fit bon : pédagogie + conseil + dev commercial. Marseille = plus accessible qu\'IDF depuis Anglet.',
        'Lien': 'https://nextra.factorial.fr/job_posting/consultant-e-formateur-rice-ia-cdi-ou-freelance-257298',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '60-75K€',
    },

    # Walter Learning — Formateur Intelligence Artificielle générative (CDD mi-temps, quasi-remote)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur Intelligence Artificielle générative (CDD 12 mois mi-temps)',
        'Entreprise': 'Walter Learning',
        'Source': 'careers.werecruit.io / LinkedIn',
        'Contrat': 'CDD 12 mois mi-temps',
        'Localisation': 'Paris (remote total sauf tournage Marseille)',
        'Remote': 'Oui (quasi-total)',
        'Salaire / TJM': '',
        'Durée mission': '12 mois',
        'Fit / Notes': 'Walter Learning formation certifiante. Concevoir et animer ~21h sur IA générative responsable (ChatGPT, Gemini, Copilot, DALL-E, Midjourney, IA Act, RGPD). CDD mi-temps = activité complémentaire possible. SIRET préféré. Tournage vidéo occasionnel Marseille.',
        'Lien': 'https://careers.werecruit.io/fr/walter-learning/offres/formateur---intelligence-artificielle-generative-3cde70',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '400-600€/j',
    },

    # DataBird — Formateur IA générative agentique (freelance, 2h/semaine)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur IA générative agentique (freelance)',
        'Entreprise': 'DataBird',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'Freelance',
        'Localisation': 'Paris (à distance)',
        'Remote': 'Oui (2h de live mardi soir)',
        'Salaire / TJM': '',
        'Durée mission': 'Récurrent',
        'Fit / Notes': 'DataBird forme profils métier à l\'IA agentique (agents IA, Make, Dust). Animation 2h/semaine le mardi soir. Mission complémentaire idéale — charge légère. DataBird forme des non-développeurs.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/data-bird/jobs/formateur-rice-freelance-ia-generative_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '400-600€/j',
    },

    # Wemodo — Formateur Automations No-Code IA générative (100% remote)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur Automations No-Code IA générative (freelance)',
        'Entreprise': 'Wemodo (ex Webmyday)',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'Freelance',
        'Localisation': 'France',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Wemodo formation automation no-code (Make, Zapier, n8n). Intégration agents IA via API. 100% remote. Un peu plus technique que le poste IA générative Wemodo, mais sans Python/data science. À considérer si Gaëtan à l\'aise avec no-code automation.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/web-my-day/jobs/formateur-ice-referent-automations-no-code_paris',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '400-600€/j',
    },

    # mission-freelances.fr — Formateur Intelligence Artificielle générative Île-de-France
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur Intelligence Artificielle générative (freelance)',
        'Entreprise': 'Client non précisé (via mission-freelances.fr)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Île-de-France',
        'Remote': 'Partiel (présentiel et/ou distanciel)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Publiée 25/06/2026. Formation certifiante IA générative responsable. ChatGPT, Gemini, Copilot, DALL-E, Midjourney, Adobe Firefly ; prompt engineering ; IA Act + RGPD. NDA + SIRET requis. Certification RS6776 souhaitée. Fit bon.',
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-formatrice-en-intelligence-artificielle-generative-ile-de-france-a5471a52/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '400-600€/j',
    },

]

if __name__ == '__main__':
    ajouter_offres(offres, verbose=True)
    print("\nTerminé. Offres ajoutées dans offres_emploi.xlsx")
