"""Relance exhaustive du 27/08/2026 : 4 recherches parallèles."""

from add_offre import ajouter_offres

FW = "https://www.free-work.com/fr/tech-it/job-mission/"
FI = "https://www.freelance-informatique.fr/"
MF = "https://www.mission-freelances.fr/missions/"

offres = [
    # ── free-work.com / jobs/sirh ────────────────────────────────────────
    {'Priorité': '⭐⭐⭐', 'Poste': 'Business Analyst projets digitaux (H/F)', 'Entreprise': 'Link Consulting',
     'Source': 'free-work.com', 'Lien': FW + 'business-analyst/business-analyst-projets-digitaux-h-f-1',
     'Contrat': 'CDI', 'Localisation': 'Toulouse', 'Remote': 'Non précisé', 'Salaire / TJM': '50-53k€/an'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant Expert Paie CEGEDIM / Team RH - Migration SIRH', 'Entreprise': 'Orviden',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-applicatif-erp-crm-sirh/consultant-expert-paie-cegedim-team-rh-migration-sirh',
     'Contrat': 'Freelance', 'Localisation': 'Toulouse', 'Remote': 'Non précisé', 'Salaire / TJM': '400-520€/j', 'Durée mission': '9 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Expert GTA - Horoquartz (H/F)', 'Entreprise': 'Mindquest',
     'Source': 'free-work.com', 'Lien': FW + 'expert-seo-consultant-referencement/expert-gta-horoquartz-h-f',
     'Contrat': 'Freelance', 'Localisation': 'Aix-en-Provence', 'Remote': 'Non précisé', 'Salaire / TJM': '480-500€/j', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Manager SIRH', 'Entreprise': 'HR DNA',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-applicatif-erp-crm-sirh/manager-sirh-11',
     'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Salaire / TJM': '60-110k€/an'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de projet IT / Responsable SIRH (H/F)', 'Entreprise': 'LeHibou',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-applicatif-erp-crm-sirh/chef-de-projet-it-responsable-sirh-h-f',
     'Contrat': 'Freelance', 'Localisation': 'Bordeaux', 'Remote': 'Non précisé', 'Salaire / TJM': '675€/j', 'Durée mission': '9 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chargé de missions SIRH N2 - Workday HCM (H/F)', 'Entreprise': 'HR DNA',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-applicatif-erp-crm-sirh/charge-de-missions-sirh-n2-workday-hcm-h-f-25',
     'Contrat': 'Freelance', 'Localisation': 'Neuilly-sur-Marne', 'Remote': 'Non précisé', 'Salaire / TJM': '250-500€/j', 'Durée mission': '24 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Project Manager SIRH', 'Entreprise': 'DSI group',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-applicatif-erp-crm-sirh/project-manager-sirh-2',
     'Contrat': 'Freelance', 'Localisation': 'Luxembourg', 'Remote': 'Non précisé', 'Durée mission': '5 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Owner / Chef de Projet Oracle HCM', 'Entreprise': 'SKYLLIT',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-de-base-de-donnee-oracle-sybase/product-owner-chef-de-projet-oracle-hcm',
     'Contrat': 'Freelance', 'Localisation': 'Paris 75008', 'Remote': 'Non précisé', 'Durée mission': '1 an'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': "Product Manager / Owner SIRH (H/F)", 'Entreprise': 'Lùkla',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-applicatif-erp-crm-sirh/product-manager-owner-sirh-h-f',
     'Contrat': 'Freelance', 'Localisation': 'Rouen', 'Remote': 'Non précisé', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': "Gestionnaire d'Application SIRH", 'Entreprise': 'Montreal Associates',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-applicatif-erp-crm-sirh/gestionnaire-dapplication-sirh',
     'Contrat': 'Freelance', 'Localisation': 'Bretagne', 'Remote': 'Non précisé', 'Salaire / TJM': '400-600€/j', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Adjoint(e) Responsable Paie (H/F)', 'Entreprise': 'HR Path',
     'Source': 'free-work.com', 'Lien': FW + 'directeur-de-la-data-cdo/adjoint-e-responsable-paie-h-f',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Salaire / TJM': '650-700€/j', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Consultant Transformation RH (Core HR)', 'Entreprise': 'Mon Consultant Indépendant',
     'Source': 'free-work.com', 'Lien': FW + 'consultant/senior-consultant-transformation-rh-target-operating-model-core-hr-1',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Salaire / TJM': '500-550€/j', 'Durée mission': '4 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant Transformation RH - Core HR', 'Entreprise': 'VISIAN',
     'Source': 'free-work.com', 'Lien': FW + 'consultant/consultant-transformation-rh-core-hr',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Durée mission': '1 an'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef de Projet SIRH (H/F)', 'Entreprise': 'HAYS France',
     'Source': 'free-work.com', 'Lien': FW + 'autre/chef-de-projet-sirh-h-f-79',
     'Contrat': 'Freelance', 'Localisation': 'Bordeaux', 'Remote': 'Non précisé', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Project Manager Data RH (H/F)', 'Entreprise': 'Insitoo Freelances',
     'Source': 'free-work.com', 'Lien': FW + 'community-manager-social-media-manager/project-manager-data-rh-h-f',
     'Contrat': 'Freelance', 'Localisation': 'Marseille', 'Remote': 'Non précisé', 'Salaire / TJM': '550-600€/j', 'Durée mission': '2 ans'},
    {'Priorité': '⭐⭐', 'Poste': 'Référent Paie SIRH H/F', 'Entreprise': 'Mindquest',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-applicatif-erp-crm-sirh/referent-paie-sirh-h-f-13',
     'Contrat': 'Freelance', 'Localisation': 'Aix-en-Provence', 'Remote': 'Non précisé', 'Durée mission': '4 mois'},

    # ── free-work.com / jobs/sap-hcm + sap-successfactors ───────────────
    {'Priorité': '⭐⭐⭐', 'Poste': 'Architecte d\'entreprise / Urbaniste SI', 'Entreprise': 'SKILL EXPERT',
     'Source': 'free-work.com', 'Lien': FW + 'architecte-dentreprise-urbaniste-si/architecte-dentreprise-urbaniste-si-4',
     'Contrat': 'Freelance', 'Localisation': 'Roissy-en-France', 'Remote': 'Non précisé', 'Salaire / TJM': '600-650€/j', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'SAP SuccessFactors Senior/Lead Consultant', 'Entreprise': 'INVESTIGO',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-erp-ms-dynamics-oracle-sage-sap/sap-successfactors-senior-lead-consultant-permanent-ps80-000-ps90-000-per-annum-benefits',
     'Contrat': 'CDI', 'Localisation': 'Angleterre, UK', 'Remote': 'Non précisé', 'Salaire / TJM': '£80-90k/an'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'SAP SuccessFactors Consultant (M/F)', 'Entreprise': 'Mindquest',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-erp-ms-dynamics-oracle-sage-sap/sap-successfactors-consultant-m-f',
     'Contrat': 'Freelance', 'Localisation': 'Pays-Bas', 'Remote': 'Non précisé', 'Durée mission': '10 mois'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant SAP SuccessFactors CoreHR (H/F)', 'Entreprise': 'HR Path',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-corehr-h-f',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Salaire / TJM': '450-600€/j', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Expert SAP SuccessFactors', 'Entreprise': 'LeHibou',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-erp-ms-dynamics-oracle-sage-sap/expert-sap-successfactors-1',
     'Contrat': 'Freelance', 'Localisation': 'Saint-Ouen-sur-Seine', 'Remote': 'Non précisé', 'Salaire / TJM': '575€/j', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP SF Onboarding (ONB)', 'Entreprise': 'LINKWAY',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-onboarding-onb',
     'Contrat': 'Freelance', 'Localisation': 'Île-de-France', 'Remote': 'Non précisé', 'Salaire / TJM': '400€/j', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP SF LMS', 'Entreprise': 'LINKWAY',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-learning-management-system-lms',
     'Contrat': 'Freelance', 'Localisation': 'Île-de-France', 'Remote': 'Non précisé', 'Salaire / TJM': '400€/j', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP SF PMGM', 'Entreprise': 'LINKWAY',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-performance-goal-management-pmgm',
     'Contrat': 'Freelance', 'Localisation': 'Île-de-France', 'Remote': 'Non précisé', 'Salaire / TJM': '400€/j', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP SF Recruitment (RCM)', 'Entreprise': 'LINKWAY',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-recruitment-rcm',
     'Contrat': 'Freelance', 'Localisation': 'Île-de-France', 'Remote': 'Non précisé', 'Salaire / TJM': '400€/j', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP SF Succession Planning (SP)', 'Entreprise': 'LINKWAY',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-succession-planning-sp',
     'Contrat': 'Freelance', 'Localisation': 'La Défense', 'Remote': 'Non précisé', 'Salaire / TJM': '400€/j', 'Durée mission': '12 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'SAP PMO Successfactors (H/F)', 'Entreprise': 'Mindquest',
     'Source': 'free-work.com', 'Lien': FW + 'sap-pmo-successfactors-h-f-75',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP SUCCESSFACTOR', 'Entreprise': 'Intuition IT Solutions',
     'Source': 'free-work.com', 'Lien': FW + 'consultant-sap-successfactor-2',
     'Contrat': 'Freelance', 'Localisation': 'Versailles', 'Remote': 'Non précisé', 'Durée mission': '24 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'Key User - SAP SuccessFactors', 'Entreprise': 'CRYSTAL PLACEMENT',
     'Source': 'free-work.com', 'Lien': FW + 'key-user-sap-successfactors',
     'Contrat': 'Freelance', 'Localisation': 'Bruxelles', 'Remote': 'Non précisé', 'Durée mission': '8 mois'},

    # ── free-work.com / IA + product-owner ──────────────────────────────
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant IA Générative & Solutions Agentiques', 'Entreprise': 'LeHibou',
     'Source': 'free-work.com', 'Lien': FW + 'architecte-solutions/consultant-ia-generative-solutions-agentiques',
     'Contrat': 'Freelance', 'Localisation': 'Levallois-Perret', 'Remote': 'Non précisé', 'Salaire / TJM': '550€/j', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant IA Générative / Claude (Anthropic)', 'Entreprise': 'SMARTPOINT',
     'Source': 'free-work.com', 'Lien': FW + 'consultant/consultant-ia-generative-claude-anthropic',
     'Contrat': 'Freelance', 'Localisation': 'Île-de-France', 'Remote': 'Non précisé', 'Salaire / TJM': '500-600€/j', 'Durée mission': '12 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Expert IA générative et Plateforme IA H/F', 'Entreprise': 'Freelance.com',
     'Source': 'free-work.com', 'Lien': FW + 'expert-seo-consultant-referencement/expert-ia-generative-et-plateforme-ia-h-f',
     'Contrat': 'Freelance', 'Localisation': 'Île-de-France', 'Remote': 'Non précisé', 'Salaire / TJM': '510-590€/j', 'Durée mission': '1 an'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager / Product Owner', 'Entreprise': 'TEOLIA CONSULTING',
     'Source': 'free-work.com', 'Lien': FW + 'product-owner/product-manager-285',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Salaire / TJM': '400-550€/j', 'Durée mission': '12 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Proxy Product Owner Confirmé', 'Entreprise': 'Freelance.com',
     'Source': 'free-work.com', 'Lien': FW + 'product-owner/proxy-product-owner-confirme-2',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Salaire / TJM': '40-45k€/an ou 400-540€/j', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Owner Applications Opérationnelles / ERP', 'Entreprise': 'Byrongroup',
     'Source': 'free-work.com', 'Lien': FW + 'administrateur-applicatif-erp-crm-sirh/product-owner-applications-operationnelles-erp',
     'Contrat': 'Freelance', 'Localisation': 'Île-de-France', 'Remote': 'Non précisé', 'Salaire / TJM': '490-570€/j', 'Durée mission': '1 an'},

    # ── freelance-informatique.fr (data-obf) ────────────────────────────
    {'Priorité': '⭐⭐⭐', 'Poste': 'Expert HR ACCESS', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-expert-hr-access-sur-paris-116748-de', 'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef de Projet Fonctionnel ERP', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-fonctionnel-erp-pour-nantes-116699-de', 'Contrat': 'Freelance', 'Localisation': 'Nantes', 'Remote': 'Non précisé', 'Durée mission': '120 j.o.'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SIRH (H/F)', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-consultant-sirh-h-f-116636-de', 'Contrat': 'Freelance', 'Localisation': 'Archamps (74)', 'Remote': 'Non précisé', 'Durée mission': '4 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Expert Workday Accounting Center - Lead Implémentation Finance', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-expert-workday-accounting-center-lead-implementation-finance-lille-116403-de', 'Contrat': 'Freelance', 'Localisation': 'Lille', 'Remote': 'Non précisé', 'Durée mission': '7 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef de projet SIRH confirmé', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-sirh-confirme-114018-de', 'Contrat': 'Freelance', 'Localisation': 'Gonesse (95)', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'AMOA SIRH DATA', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-amoa-sirh-data-sur-paris-113689-de', 'Contrat': 'Freelance', 'Localisation': 'Courbevoie', 'Remote': 'Non précisé', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-consultant-sirh-113215-de', 'Contrat': 'Freelance', 'Localisation': 'Marseille', 'Remote': 'Non précisé', 'Durée mission': '22 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef de projet SIRH WorkDay (Certif. obligatoire)', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-sirh-workday-certification-obligatoire-110752-de', 'Contrat': 'Freelance', 'Localisation': 'Marne-la-Vallée', 'Remote': 'Non précisé', 'Durée mission': '12 mois'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de projet fonctionnel SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-sirh-110424-de', 'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui (Télétravail)', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'Chef de projet transverse SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-transverse-sirh-defense-et-remote-105678-de', 'Contrat': 'Freelance', 'Localisation': 'La Défense', 'Remote': 'Hybride', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Owner/Chef de projet SIRH (F/H)', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-product-owner-chef-de-projet-sirh-f-h-104881-de', 'Contrat': 'Freelance', 'Localisation': 'Grenoble', 'Remote': 'Non précisé', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'Chef de projet technique SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-sirh-sur-marne-la-vallee-tt-101702-de', 'Contrat': 'Freelance', 'Localisation': 'Marne-la-Vallée', 'Remote': 'Hybride', 'Durée mission': '14 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef de Projet SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-sirh-sur-paris-101573-de', 'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Durée mission': '12 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef de Projet SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-sirh-sur-bordeaux-99971-de', 'Contrat': 'Freelance', 'Localisation': 'Bordeaux', 'Remote': 'Non précisé', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'Chef de projet MOE / Expert GTA', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-moe-expert-gta-112667-de', 'Contrat': 'Freelance', 'Localisation': 'Paris 75012', 'Remote': 'Non précisé', 'Durée mission': '36 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant AMOA SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-consultant-amoa-sirh-paris-112194-de', 'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Durée mission': '12 mois'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant SIRH / Support ERP & PAIE', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-consultant-sirh-support-erp-paie-105111-de', 'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui (Télétravail)', 'Durée mission': '10 j.o.'},
    {'Priorité': '⭐⭐', 'Poste': 'Administrateur SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-administrateur-sirh-104351-de', 'Contrat': 'Freelance', 'Localisation': 'Trappes', 'Remote': 'Non précisé', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant MOA SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-consultant-moa-sirh-103498-de', 'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Durée mission': '12 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'Consultant AMOA formation/Learning', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-consultant-amoa-domaine-fonctionnel-formation-learning-101672-de', 'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chefs de projet et Consultants Technico-fonctionnels HCM', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chefs-de-projet-et-consultants-technico-fonctionnels-hcm-99731-de', 'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'Chef de projet/PMO migration HRA', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-pmo-projet-migration-hra-96988-de', 'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'Chef de projet Bureautique et application RH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-chef-de-projet-bureautique-et-application-rh-88861-de', 'Contrat': 'Freelance', 'Localisation': 'Poissy', 'Remote': 'Non précisé', 'Durée mission': '7 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'SIRH / AO', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-sirh-ao-88086-de', 'Contrat': 'Freelance', 'Localisation': 'Paris (75)', 'Remote': 'Non précisé', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant SIRH SuccessFactors', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-consultant-sirh-successfactors-sur-issy-115627-de', 'Contrat': 'Freelance', 'Localisation': 'Issy-les-Moulineaux', 'Remote': 'Non précisé', 'Durée mission': '9 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Expert Workday IT F/H', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-expert-workday-it-f-h-115424-de', 'Contrat': 'Freelance', 'Localisation': 'Puteaux', 'Remote': 'Non précisé', 'Durée mission': '6 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'Consultant Senior SAP SF (Recruiting & EC) - sur site Luxembourg', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-consultant-senior-sap-successfactors-recruiting-employee-central-lieu-luxembourg-sur-site-114529-de', 'Contrat': 'Freelance', 'Localisation': 'Luxembourg', 'Remote': 'Présentiel', 'Durée mission': '12 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Expert Technique SIRH', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-expert-technique-sirh-113399-de', 'Contrat': 'Freelance', 'Localisation': 'Paris 75015', 'Remote': 'Non précisé', 'Durée mission': '12 mois'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant SAP SuccesFactors', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-consultant-sap-succesfactors-sur-la-defense-112172-de', 'Contrat': 'Freelance', 'Localisation': 'La Défense', 'Remote': 'Non précisé', 'Durée mission': '3 mois'},
    {'Priorité': '⭐⭐', 'Poste': 'Payroll Specialist', 'Entreprise': 'N/C', 'Source': 'freelance-informatique.fr',
     'Lien': FI + 'mission-payroll-specialist-sur-clamart-111050-de', 'Contrat': 'Freelance', 'Localisation': 'Clamart', 'Remote': 'Non précisé', 'Durée mission': '3 mois'},

    # ── mission-freelances.fr ────────────────────────────────────────────
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success / Account Manager (immobilier)', 'Entreprise': 'Realadvisor',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'customer-success-account-manager-immobilier-teletravail-f69563e7',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager SaaS', 'Entreprise': 'Vusion',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'customer-success-manager-saas-nanterre-5fe6b636',
     'Contrat': 'Freelance', 'Localisation': 'Nanterre', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager', 'Entreprise': 'Croissance Esthetique',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'customer-success-manager-teletravail-49c96bf3',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Customer Success Manager', 'Entreprise': 'Realadvisor',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'customer-success-manager-teletravail-8a4833c0',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Founding Customer Success Manager', 'Entreprise': 'Gotam',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'founding-customer-success-manager-teletravail-c4e12456',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé (lancement Italie)', 'Remote': 'Oui',
     'Fit / Notes': 'Founding CSM 0→1 : valorise directement le statut de co-fondateur WallOfTraders.com'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager SIRH H/F (Oracle HCM)', 'Entreprise': 'Unitechsolutions',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'product-manager-sirh-h-f-paris-d64b6274',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Formateur en IA (générative et agentique)', 'Entreprise': 'Mindness',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-en-intelligence-artificielle-generative-et-agentique-teletravail-c892d79e',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': "Formateur/Formatrice freelance IA générative & no-code", 'Entreprise': 'Schoolia',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-formatrice-freelance-en-ia-generative-et-automatisation-no-code-teletravail-c73e30a9',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur Freelance IA + automatisation', 'Entreprise': 'Formalyonconseil',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-freelance-en-intelligence-artificielle-avec-automatisation-des-taches-saint-renan-c5abaf86',
     'Contrat': 'Freelance', 'Localisation': 'Saint-Renan', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur freelance IA (certifiante)', 'Entreprise': 'Focuscloudgroup',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-freelance-en-intelligence-artificielle-hauts-de-seine-a2fb3e3c',
     'Contrat': 'Freelance', 'Localisation': 'Hauts-de-Seine', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur Freelance IA générative (certifiante)', 'Entreprise': '3s Pro',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-freelance-en-intelligence-artificielle-saint-ouen-ddf20cad',
     'Contrat': 'Freelance', 'Localisation': 'Saint-Ouen', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': "Formateur IA appliquée à l'acquisition client", 'Entreprise': 'N/C',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-ia-appliquee-a-l-acquisition-client-teletravail-68ec066a',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur IA H/F', 'Entreprise': 'Dmhassocies',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-ia-h-f-marseille-1f01f6ef',
     'Contrat': 'Freelance', 'Localisation': 'Marseille', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur IA (secteur bancaire)', 'Entreprise': 'Ouicoding',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-ia-paris-3bc3fe0d',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur indépendant en IA', 'Entreprise': 'Wmn Digital',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-independant-en-intelligence-artificielle-france-entiere-9ed682d6',
     'Contrat': 'Freelance', 'Localisation': 'France entière (itinérant)', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur indépendant en IA', 'Entreprise': 'Becompro',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-independant-en-intelligence-artificielle-sainte-maxime-2496e710',
     'Contrat': 'Freelance', 'Localisation': 'Sainte-Maxime', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐', 'Poste': "Formateur·rice IA", 'Entreprise': 'Simplon',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-rice-ia-bayonne-6742bcda',
     'Contrat': 'Freelance', 'Localisation': 'Bayonne', 'Remote': 'Non précisé',
     'Fit / Notes': "Mission locale à deux pas d'Anglet"},
    {'Priorité': '⭐⭐', 'Poste': "Formateur(rice) IA", 'Entreprise': 'Focuscloudgroup',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-rice-ia-hauts-de-seine-3f3c17b8',
     'Contrat': 'Freelance', 'Localisation': 'Hauts-de-Seine', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': "Formateur·rice·s freelances en IA", 'Entreprise': 'Contournement',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-rice-s-freelances-en-ia-teletravail-9cc97c82',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': "Formateur·rice spécialisé·e en IA", 'Entreprise': 'Dmhassocies',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-rice-specialise-e-en-ia-marseille-1495a35f',
     'Contrat': 'Freelance', 'Localisation': 'Marseille', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur(trice) Accompagnement & Sensibilisation IA', 'Entreprise': 'Consul Team',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-trice-accompagnement-sensibilisation-intelligence-artificielle-h-f-toulon-116298f1',
     'Contrat': 'Freelance', 'Localisation': 'Toulon', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur(trice) en IA', 'Entreprise': 'N/C',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-trice-en-ia-bordeaux-d91c6fa2',
     'Contrat': 'Freelance', 'Localisation': 'Bordeaux', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Formateur(trice) en ligne IA & dev web', 'Entreprise': 'Vendogram',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-trice-en-ligne-intelligence-artificielle-et-developpement-web-teletravail-de3cf7d0',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur(trice) IA', 'Entreprise': 'Simplon',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-trice-freelance-en-intelligence-artificielle-chambery-et-bourg-en-bresse-27cdb82e',
     'Contrat': 'Freelance', 'Localisation': 'Chambéry / Bourg-en-Bresse', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': "Formateur(trice) indépendant(e) IA (certif. RS7344)", 'Entreprise': 'Smartoptimisation',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-trice-independant-e-en-ia-strasbourg-9a675c34',
     'Contrat': 'Freelance', 'Localisation': 'Strasbourg', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Formateur(trice) IA générative', 'Entreprise': 'Simplon',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'formateur-trice-intelligence-artificielle-montreuil-178e0062',
     'Contrat': 'Freelance', 'Localisation': 'Montreuil', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'AI-First Adoption Lead', 'Entreprise': 'Veepee',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'ai-first-adoption-lead-saint-denis-ccdb5a69',
     'Contrat': 'Freelance', 'Localisation': 'Saint-Denis', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant Change Management', 'Entreprise': 'Yeets',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'consultant-change-management-puteaux-18319661',
     'Contrat': 'Freelance', 'Localisation': 'Puteaux', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Consultant Communication & Conduite du Changement', 'Entreprise': 'Porters',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'consultant-communication-conduite-du-changement-h-f-toulouse-16a04e03',
     'Contrat': 'Freelance', 'Localisation': 'Toulouse', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐', 'Poste': 'Consultant(e) Change Management (Digital Workplace/M365)', 'Entreprise': 'Visian',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'consultant-e-change-management-accompagnement-au-changement-paris-52be4ee1',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Consultant(e) Senior Stratégie & Transformation IA', 'Entreprise': 'Keoni',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'consultant-e-senior-strategie-transformation-ia-paris-9830c4b1',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'PMO / Chef de Projet Transformation Digitale (santé, international)', 'Entreprise': 'Noesn',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'pmo-chef-de-projet-transformation-digitale-teletravail-58124e36',
     'Contrat': 'Freelance', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager IA', 'Entreprise': 'Ever T',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'product-manager-ia-paris-a80209f9',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager IA', 'Entreprise': 'Wecotechnology',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'product-manager-ia-paris-e49bf612',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Owner IA Senior', 'Entreprise': 'Groupedigit',
     'Source': 'mission-freelances.fr', 'Lien': MF + 'product-owner-ia-senior-paris-f8e6296b',
     'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé'},

    # ── hansonregan.com ──────────────────────────────────────────────────
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'SAP FPSL Stream Lead', 'Entreprise': 'N/C', 'Source': 'hansonregan.com',
     'Lien': 'https://hansonregan.com/job/sap-fpsl-stream-lead/', 'Contrat': 'Freelance', 'Localisation': 'France', 'Remote': 'Non précisé', 'Salaire / TJM': '804€/j'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'SAP HCM Payroll', 'Entreprise': 'N/C', 'Source': 'hansonregan.com',
     'Lien': 'https://hansonregan.com/job/sap-hcm-payroll/', 'Contrat': 'Freelance', 'Localisation': 'Anywhere', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'SAP SuccessFactors Time Off', 'Entreprise': 'N/C', 'Source': 'hansonregan.com',
     'Lien': 'https://hansonregan.com/job/sap-successfactors-time-off/', 'Contrat': 'Freelance', 'Localisation': 'Anywhere', 'Remote': 'Non précisé', 'Salaire / TJM': '415€/j'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'SAP SuccessFactors EC', 'Entreprise': 'N/C', 'Source': 'hansonregan.com',
     'Lien': 'https://hansonregan.com/job/sap-successfactors-ec/', 'Contrat': 'Freelance', 'Localisation': 'Anywhere', 'Remote': 'Non précisé', 'Salaire / TJM': '52€/h'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'SAP ECS Client Relationship Manager', 'Entreprise': 'N/C', 'Source': 'hansonregan.com',
     'Lien': 'https://hansonregan.com/job/sap-ecs-client-relationship-manager/', 'Contrat': 'Freelance', 'Localisation': 'France', 'Remote': 'Non précisé', 'Salaire / TJM': '750€/j'},
    {'Priorité': '⭐⭐', 'Poste': 'Technical Consultant – D365 Contact Center (CCaaS)', 'Entreprise': 'N/C', 'Source': 'hansonregan.com',
     'Lien': 'https://hansonregan.com/job/technical-consultant-d365-contact-center-ccaas/', 'Contrat': 'Freelance', 'Localisation': 'Belgique', 'Remote': 'Non précisé', 'Salaire / TJM': '708€/j'},

    # ── whitehallresources.com ───────────────────────────────────────────
    {'Priorité': '⭐⭐', 'Poste': 'SAP SuccessFactors Architect', 'Entreprise': 'N/C', 'Source': 'whitehallresources.com',
     'Lien': 'https://whitehallresources.com/job/sap-successfactors-architect-36302/', 'Contrat': 'CDI', 'Localisation': 'République Tchèque', 'Remote': 'Hybride'},
    {'Priorité': '⭐⭐', 'Poste': 'SAP SuccessFactor EC Consultant', 'Entreprise': 'N/C', 'Source': 'whitehallresources.com',
     'Lien': 'https://whitehallresources.com/job/sap-successfactor-ec-consultant-36401/', 'Contrat': 'Freelance', 'Localisation': 'Angleterre', 'Remote': 'Non précisé'},

    # ── welcometothejungle.com ───────────────────────────────────────────
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Chef de projet SIRH (H/F) - N2F', 'Entreprise': 'N2jsoft', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/en/companies/n2jsoft-fr/jobs/chef-de-projet-sirh-h-f-n2f_montagnat_N2JSO_YbKVlVW',
     'Contrat': 'CDI', 'Localisation': 'Montagnat', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Product Manager (full remote avec déplacements)', 'Entreprise': 'RISE', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/rise/jobs/28b1f52c-1924-40ec-b7e0-18bbdcda6c56',
     'Contrat': 'CDI', 'Localisation': 'Europe (déplacements)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Product Manager', 'Entreprise': 'Side', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/side/jobs/product-manager_paris_SIDE_jRLO2Ar',
     'Contrat': 'CDI', 'Localisation': 'Paris/Remote', 'Remote': 'Oui', 'Salaire / TJM': '55-59K€'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Product Manager', 'Entreprise': 'Inqom', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/inqom/jobs/product-manager',
     'Contrat': 'CDI', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Product Manager', 'Entreprise': 'Follow Health', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/follow-health/jobs/product-manager',
     'Contrat': 'CDI', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Onboarding - Formateur H/F', 'Entreprise': 'Organilog', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/organilog/jobs/custome-success-manager-specialite-formateur-h-f-teletravail_pontchateau',
     'Contrat': 'CDI', 'Localisation': 'Pontchâteau', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Technical Customer Success', 'Entreprise': 'La Growth Machine', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/lagrowthmachine/jobs/customer-success-manager',
     'Contrat': 'CDI', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager (Junior)', 'Entreprise': "dartagnan (JustRelate Group)", 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/dartagnan/jobs/customer-success-manager-junior-h-f-d',
     'Contrat': 'CDI', 'Localisation': 'Non précisé', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager', 'Entreprise': 'AssessFirst', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/assessfirst/jobs/customer-success-manager_paris_ASSES_M4x97o8',
     'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager - Remote', 'Entreprise': 'Namastay', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/namastay/jobs/customer-success-manager-remote_paris',
     'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager', 'Entreprise': 'Visum (Reverse Contact)', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/visum/jobs/customer-success-manager_paris_RC_xDJ6YrA',
     'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager', 'Entreprise': 'Haiku (Clerk)', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/clerk/jobs/customer-success-manager_begles',
     'Contrat': 'CDI', 'Localisation': 'Bègles', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager (CDI)', 'Entreprise': 'Filiz', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/filiz/jobs/customer-success-manager-cdi_paris',
     'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager', 'Entreprise': 'iRaiser', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/iraiser/jobs/customer-success-manager_paris',
     'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager - 100% Télétravail', 'Entreprise': 'Boost', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/boost/jobs/customer-success-manager-100-teletravail-cdi_marseille_BOOST_eZ732bL',
     'Contrat': 'CDI', 'Localisation': 'Marseille', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef(fe) de projet SIRH F/H', 'Entreprise': 'CGI', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/cgi/jobs/chef-fe-de-projet-sirh-f-h_nantes_CGI_oVZJzWp',
     'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef de projet SIRH', 'Entreprise': 'Clap Partners', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/clap-partners-fr/jobs/chef-de-projet-sirh_montrouge_CP_9zLw9qm',
     'Contrat': 'CDI', 'Localisation': 'Montrouge', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Consultant fonctionnel SIRH (H/F)', 'Entreprise': 'Primexis', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/primexis/jobs/consultant-fonctionnel-sirh-h-f_puteaux',
     'Contrat': 'CDI', 'Localisation': 'Puteaux', 'Remote': 'Partiel'},
    {'Priorité': '⭐⭐⭐', 'Poste': "Consultant(e) Gestion des talents / SIRH international H/F", 'Entreprise': 'mc2i', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/mc2i/jobs/consultant-en-gestion-des-talents-sirh-a-l-international-h-f_paris-8e-arrondissement_MC2I_Z9qdR7o',
     'Contrat': 'CDI', 'Localisation': 'Paris 8e', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef de projet SIRH', 'Entreprise': 'Silae', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/silae/jobs/chef-de-projet-sirh_nantes',
     'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Chef de projet IT SIRH', 'Entreprise': 'Objectware', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/objectware/jobs/chef-de-projet-it-sirh_paris',
     'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Partiel'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Chef(fe) de projet SIRH F/H', 'Entreprise': 'CGI', 'Source': 'welcometothejungle.com',
     'Lien': 'https://www.welcometothejungle.com/fr/companies/cgi/jobs/chef-fe-de-projet-sirh-f-h_paris',
     'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Oui'},

    # ── euremotejobs.com ─────────────────────────────────────────────────
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Customer Success Manager - Germany', 'Entreprise': 'Chainguard', 'Source': 'euremotejobs.com (Greenhouse)',
     'Lien': 'https://job-boards.greenhouse.io/chainguard/jobs/4704918006', 'Contrat': 'CDI', 'Localisation': 'Allemagne', 'Remote': 'Remote-first Europe'},
    {'Priorité': '⭐⭐', 'Poste': 'Customer Success Executive, SMB', 'Entreprise': 'Triptease', 'Source': 'euremotejobs.com',
     'Lien': 'https://apply.workable.com/triptease/j/EA4BDD16ED/', 'Contrat': 'CDI', 'Localisation': 'Worldwide (focus AMERS)', 'Remote': 'Oui'},

    # ── remoterocketship.com ─────────────────────────────────────────────
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Customer Success Manager', 'Entreprise': 'Amplemarket', 'Source': 'remoterocketship.com (Greenhouse)',
     'Lien': 'https://job-boards.eu.greenhouse.io/amplemarket/jobs/4948414101', 'Contrat': 'CDI', 'Localisation': 'Remote, Europe', 'Remote': 'Oui'},

    # ══════════════════════════════════════════════════════════════════
    # CLUSTER 2 : API ATS + éditeurs HRIS
    # ══════════════════════════════════════════════════════════════════

    # ── Atlassian ────────────────────────────────────────────────────────
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Account Manager, Strategic - France', 'Entreprise': 'Atlassian', 'Source': 'Atlassian careers API',
     'Lien': 'https://globalcareers-atlassian.icims.com/jobs/25256/account-manager%2c-strategic---france/job',
     'Contrat': 'CDI', 'Localisation': 'Remote - France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Principal Customer Success Manager, Strategic, France', 'Entreprise': 'Atlassian', 'Source': 'Atlassian careers API',
     'Lien': 'https://globalcareers-atlassian.icims.com/jobs/26057/principal-customer-success-manager%2c-strategic%2c-france/job',
     'Contrat': 'CDI', 'Localisation': 'Remote - France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Senior Principal Customer Success Manager, Strategic - France', 'Entreprise': 'Atlassian', 'Source': 'Atlassian careers API',
     'Lien': 'https://globalcareers-atlassian.icims.com/jobs/26241/senior-principal-customer-success-manager%2c-strategic---france/job',
     'Contrat': 'CDI', 'Localisation': 'Remote - France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Principal Customer Success Manager, Strategic DACH', 'Entreprise': 'Atlassian', 'Source': 'Atlassian careers API',
     'Lien': 'https://globalcareers-atlassian.icims.com/jobs/26063/principal-customer-success-manager%2c-strategic-dach/job',
     'Contrat': 'CDI', 'Localisation': 'Remote - Allemagne (option France)', 'Remote': 'Remote EMEA'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Enterprise Account Manager - Southern Europe', 'Entreprise': 'Atlassian', 'Source': 'Atlassian careers API',
     'Lien': 'https://globalcareers-atlassian.icims.com/jobs/25503/enterprise-account-manager---southern-europe/job',
     'Contrat': 'CDI', 'Localisation': 'Remote - UK', 'Remote': 'Remote EMEA'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Architect (AI)', 'Entreprise': 'Atlassian', 'Source': 'Atlassian careers API',
     'Lien': 'https://globalcareers-atlassian.icims.com/jobs/26380/customer-success-architect-%28ai%29/job',
     'Contrat': 'CDI', 'Localisation': 'Londres / Remote', 'Remote': 'Non précisé'},

    # ── Ashby ────────────────────────────────────────────────────────────
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Regional Manager, Customer Success EMEA', 'Entreprise': 'Constructor', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/constructor/5f24d378-f17b-4032-a2cc-079fd670563d', 'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Product Manager: Customer Onboarding Experience', 'Entreprise': 'Constructor', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/constructor/e8fa6194-ef2e-47d3-ab45-a9112d87da24', 'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Product Manager - Merchant Intelligence and Analytics', 'Entreprise': 'Constructor', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/constructor/e7426b59-431b-418b-a501-dde7f13b21bf', 'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Product Manager: Recall', 'Entreprise': 'Constructor', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/constructor/7bc86d05-145d-4b7c-aa6e-b0b207d46117', 'Contrat': 'CDI', 'Localisation': 'Remote - EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Account Manager, DACH', 'Entreprise': 'Constructor', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/constructor/776e4870-92d3-40d4-b2ea-c530537cd616', 'Contrat': 'CDI', 'Localisation': 'Remote - EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Sales Engineer (DACH)', 'Entreprise': 'Constructor', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/constructor/3b1910b4-f99a-4011-8e83-839cc6d74b29', 'Contrat': 'CDI', 'Localisation': 'Remote - Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Manager of Dedicated Implementations - EMEA', 'Entreprise': 'Ashby', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/ashby/35a01a05-8efd-4bc3-a4bf-0a31d902102d', 'Contrat': 'CDI', 'Localisation': 'Remote - UE', 'Remote': 'Oui', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Strategic Customer Success Manager - EMEA', 'Entreprise': 'Ashby', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/ashby/1cf7c730-caba-4fc3-8b98-52a0735ef14b', 'Contrat': 'CDI', 'Localisation': 'Remote - UE', 'Remote': 'Oui', 'Salaire / TJM': '€62K-€133K', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Mid-Market Customer Success Manager - EMEA', 'Entreprise': 'Ashby', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/ashby/62d4f71e-f56c-447a-a965-a9c2ea8eac5e', 'Contrat': 'CDI', 'Localisation': 'Remote - UE', 'Remote': 'Oui', 'Salaire / TJM': '€45K-€105K', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Technical Account Manager - Benelux', 'Entreprise': 'Camunda', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/camunda/d5ce4070-2d06-4529-956f-a93d05eefd99', 'Contrat': 'CDI', 'Localisation': 'Pays-Bas', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Technical Account Manager - DACH', 'Entreprise': 'Camunda', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/camunda/05070fb6-de7a-4a03-b885-442032da57ec', 'Contrat': 'CDI', 'Localisation': 'Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager, Self Managed Service', 'Entreprise': 'Camunda', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/camunda/5652a3f3-e418-4e91-b58b-4be13f36853b', 'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Product Manager - Core Platform', 'Entreprise': 'Camunda', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/camunda/b771e145-a5cf-4867-ad13-b54830e3b744', 'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Principal Product Manager - Time to First Production', 'Entreprise': 'Camunda', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/camunda/7f97e255-53a0-4a8a-a7e3-92b1ed9da743', 'Contrat': 'CDI', 'Localisation': 'Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Enterprise Solutions Engineer - EMEA', 'Entreprise': 'Dash0', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/dash0/d7fa3468-1e5c-4109-bdcf-0fa0f2f9c15b', 'Contrat': 'CDI', 'Localisation': 'EMEA - Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Enterprise Solutions Engineer - UK', 'Entreprise': 'Dash0', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/dash0/6526471a-8f48-425c-9329-2a8dcb175783', 'Contrat': 'CDI', 'Localisation': 'EMEA - Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Enterprise Solutions Engineer - Nordics', 'Entreprise': 'Dash0', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/dash0/eee66924-267e-4731-803f-85a43866bc9c', 'Contrat': 'CDI', 'Localisation': 'EMEA - Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Commercial Solutions Engineer - Nordics', 'Entreprise': 'Dash0', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/dash0/31c63bf9-c837-43c4-9deb-ba0da290cdd7', 'Contrat': 'CDI', 'Localisation': 'EMEA - Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Pre-Sales Solutions Engineer - Europe', 'Entreprise': 'Deepgram', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/deepgram/7ac1a5bc-f305-4f2a-a547-394566a549b2', 'Contrat': 'CDI', 'Localisation': 'EU - Remote', 'Remote': 'Oui', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Implementation Consultant, EMEA', 'Entreprise': 'Fieldguide', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/fieldguide/457735c7-3ea7-4621-b64e-d62de0d774e5', 'Contrat': 'CDI', 'Localisation': 'Remote (UK)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Product Manager - EMEA - Remote', 'Entreprise': 'Pencil', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/pencil/e4bbf9ae-0be6-455f-8b24-f960be4c6f2c', 'Contrat': 'CDI', 'Localisation': 'Europe', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Lead Product Manager - Editor - EMEA', 'Entreprise': 'Pencil', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/pencil/765370fa-a2b2-487f-af2e-73a53cd1bad6', 'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager - Media - Remote', 'Entreprise': 'Pencil', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/pencil/e5fae779-63bd-43d8-b21c-646786d52a97', 'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Senior Product Manager 🇫🇷', 'Entreprise': 'Pennylane', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/pennylane/a4555925-195a-4a59-9367-fcaf27f2113d', 'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Customer Success Manager - Medium Accounts', 'Entreprise': 'Pennylane', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/pennylane/d9c454b4-11ab-49f3-9ffe-4b444aecb99d', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Customer Success Manager - SAAS', 'Entreprise': 'Pennylane', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/pennylane/9f24fb70-d2bb-496f-9ed3-02bb9c9d7ad0', 'Contrat': 'CDI', 'Localisation': 'Toute la France (remote)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Responsable Onboarding Comptable', 'Entreprise': 'Pennylane', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/pennylane/7ed8cb99-0b04-4227-b267-7610805e4fc4', 'Contrat': 'CDI', 'Localisation': 'Toute la France (remote)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Solutions Engineer, DACH', 'Entreprise': 'Mural', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/mural/a88d6f5b-0b8f-431e-95b9-ee28dac07bd5', 'Contrat': 'CDI', 'Localisation': 'Allemagne (Remote)', 'Remote': 'Oui', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Enterprise Solution Engineer (Pre-Sales)', 'Entreprise': 'Zip', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/zip/dbfa71ad-7bef-4e5d-a227-277451ee2a26', 'Contrat': 'CDI', 'Localisation': 'Remote - Allemagne', 'Remote': 'Oui', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior ERP Solutions Consultant', 'Entreprise': 'Zip', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/zip/8529f344-71e2-4fcf-944a-c8457e71faa1', 'Contrat': 'CDI', 'Localisation': 'Remote - Allemagne', 'Remote': 'Oui', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Sales Engineer, EMEA', 'Entreprise': 'Socket', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/socket/b88a5ea5-fb24-4e42-b567-072bf14a14ba', 'Contrat': 'CDI', 'Localisation': 'UK', 'Remote': 'Oui', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Technical Account Manager, Europe', 'Entreprise': 'Socket', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/socket/8dec8a77-dafa-448a-a31c-4bf09e9d4f0d', 'Contrat': 'CDI', 'Localisation': 'UK', 'Remote': 'Oui', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager - EMEA', 'Entreprise': 'Tilla', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/tilla/823e58d1-e986-42d9-9441-47f31bb77a52', 'Contrat': 'CDI', 'Localisation': 'Grèce', 'Remote': 'Oui', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Technical Programs Manager - Scaled Customer Success (Remote Europe)', 'Entreprise': 'n8n', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/n8n/d550716c-8cb9-4efe-9a52-b4cd67e193e1', 'Contrat': 'CDI', 'Localisation': 'Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Lead - Western Europe', 'Entreprise': 'ElevenLabs', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/elevenlabs/0dbfbe3e-7218-4045-ba78-28b0d2e5ab6d', 'Contrat': 'CDI', 'Localisation': 'Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success - DACH', 'Entreprise': 'ElevenLabs', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/elevenlabs/830e66a8-892c-4c68-b61c-494591236eef', 'Contrat': 'CDI', 'Localisation': 'Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Customer Success Manager - Public Sector & Defense, France', 'Entreprise': 'Cohere', 'Source': 'Ashby API',
     'Lien': 'https://jobs.ashbyhq.com/cohere/597e18f5-c33c-4350-8bcd-05a751cece3a', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Non précisé'},

    # ── Lever ────────────────────────────────────────────────────────────
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager (Internal HRIS / HR Tech)', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/c47e031c-99f7-4fb6-aff9-36d2d7f3593e', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui',
     'Fit / Notes': 'Croisement PM + HRIS interne, excellent fit'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Technical Account Manager', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/715dbfc2-1967-4375-b953-0f70303480c6', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Solutions Engineer', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/9f9eb428-fa95-459d-b11c-a4f3e2e0ce4a', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Owner', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/bed53c98-5b74-4c55-8ee3-0dd12d4c7b77', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Payments Solution Architect', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/f61f525e-4842-4fb9-b954-ae60d09f6514', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Banking Onboarding Manager', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/f1c0f557-3287-4c17-9ce0-ee59e425ff67', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Client Account Manager', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/142d6d42-7f21-4b38-a696-532591fc9e02', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'GTM Product Manager - Marketing Operations', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/d6b44fb8-26e0-4ca3-be80-40a5519e00bf', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Principal Product Manager - Time to First Production', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/787b912e-3171-4012-90c9-b5c9e752f30e', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Product Manager - Media', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/8ebc2ced-cdfa-430b-b8a5-d0e1141f2f32', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Product Manager Flashbid / Dynamic Yield', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/aafb59fb-fe4d-4e69-8339-5aeb47c26e92', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Product Manager UX Orchestration', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/ff28b407-30a0-40b2-882a-b04a0b64225c', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Project/Product Manager — PSP & Payment Integrations', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/589d954d-3487-4e5d-81d3-f795ed26ef47', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Property Management Account Manager', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/c3437077-73c4-4f96-9dd5-8e4b14460ea5', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Senior Product Manager, Funnels/Workflow', 'Entreprise': 'Jobgether (client anonymisé)', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/jobgether/61e08264-4aba-471e-9ad8-0fb6ccac3b85', 'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Key Account Manager Mid Market', 'Entreprise': '360Learning', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/360learning/62f460c2-9a8f-4a25-a847-0f8905d9feef', 'Contrat': 'CDI', 'Localisation': 'Paris (remote)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Solution Deployment Manager', 'Entreprise': '360Learning', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/360learning/0dba50d1-52f4-4114-8421-2f9e19210fde', 'Contrat': 'CDI', 'Localisation': 'Paris (remote)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Solution Expert', 'Entreprise': '360Learning', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/360learning/c574052f-09e5-4446-a977-e29d1162410d', 'Contrat': 'CDI', 'Localisation': 'Paris (remote)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Technical Consultant', 'Entreprise': '360Learning', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/360learning/c517940f-ef45-4ff6-bf72-5fe7305e2c6a', 'Contrat': 'CDI', 'Localisation': 'Paris (remote)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Solutions Engineer DACH', 'Entreprise': '360Learning', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/360learning/11721c63-a8b7-43a3-ac05-3c8b352f3b07', 'Contrat': 'CDI', 'Localisation': 'Espagne (remote)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Account Manager', 'Entreprise': 'Superside', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/superside/9951089c-3c7a-4d18-bd90-594b31c6cd3a', 'Contrat': 'CDI', 'Localisation': 'Global', 'Remote': 'Oui (worldwide)'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Implementation Consultant - Commercial', 'Entreprise': 'Veeva Systems', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/veeva/f4c4c9f0-4bba-4800-91b5-7dbd61208ac1', 'Contrat': 'CDI', 'Localisation': 'France - Paris', 'Remote': 'Oui', 'Onglet': 'Offres USA'},
    {'Priorité': '⭐⭐', 'Poste': 'Mid-Market Customer Success Manager EMEA', 'Entreprise': 'Teramind', 'Source': 'Lever API',
     'Lien': 'https://jobs.lever.co/teramind/20c481dc-06b9-41da-99b7-9be053d5b5f7', 'Contrat': 'CDI', 'Localisation': 'Pologne', 'Remote': 'Oui', 'Onglet': 'Offres USA'},

    # ── Greenhouse ───────────────────────────────────────────────────────
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Senior Product Manager, Remote Build', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7331443003', 'Contrat': 'CDI', 'Localisation': 'Remote-France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Account Manager - EMEA', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7834363003', 'Contrat': 'CDI', 'Localisation': 'Remote-EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Product Manager, APIs', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7831380003', 'Contrat': 'CDI', 'Localisation': 'Remote-EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Senior Workday Implementation Specialist', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7548213003', 'Contrat': 'CDI', 'Localisation': 'Remote-EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Workday Implementation Specialist', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7635556003', 'Contrat': 'CDI', 'Localisation': 'Remote-EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Payroll Implementation Specialist - NL & Belgique', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7799068003', 'Contrat': 'CDI', 'Localisation': "Remote-Europe de l'Ouest", 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Product Manager, Billing Platform', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7885108003', 'Contrat': 'CDI', 'Localisation': 'Remote-EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Product Manager, Contractor Management', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7885031003', 'Contrat': 'CDI', 'Localisation': 'Remote-EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Product Manager, Fraud and Compliance', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7814948003', 'Contrat': 'CDI', 'Localisation': 'Remote-EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Senior Product Manager', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7720367003', 'Contrat': 'CDI', 'Localisation': 'EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Global Payroll Implementation Country Lead - Germany', 'Entreprise': 'Remote.com', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/remotecom/jobs/7741670003', 'Contrat': 'CDI', 'Localisation': 'Remote - EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Customer Success Architect, EMEA', 'Entreprise': 'GitLab', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/gitlab/jobs/8561952002', 'Contrat': 'CDI', 'Localisation': 'Remote Autriche/France/Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Architect, CEUR', 'Entreprise': 'GitLab', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/gitlab/jobs/8646852002', 'Contrat': 'CDI', 'Localisation': 'Remote Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Manager, Customer Success Managers, EMEA', 'Entreprise': 'GitLab', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/gitlab/jobs/8613199002', 'Contrat': 'CDI', 'Localisation': 'Remote Autriche/Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Professional Services Engineer', 'Entreprise': 'GitLab', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/gitlab/jobs/8745623002', 'Contrat': 'CDI', 'Localisation': 'Remote Italie/NL/Espagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Solutions Architect - France', 'Entreprise': 'GitLab', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/gitlab/jobs/8656506002', 'Contrat': 'CDI', 'Localisation': 'Remote, France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Professional Services Project Manager (EMEA)', 'Entreprise': 'GitLab', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/gitlab/jobs/8622433002', 'Contrat': 'CDI', 'Localisation': 'Remote EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Enterprise Customer Success Manager', 'Entreprise': 'Canonical', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/canonical/jobs/6856788', 'Contrat': 'CDI', 'Localisation': 'Home based - Worldwide', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Enterprise Customer Success Manager (French speaker)', 'Entreprise': 'Canonical', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/canonical/jobs/7084000', 'Contrat': 'CDI', 'Localisation': 'Home based - EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Cloud Professional Services Manager', 'Entreprise': 'Canonical', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/canonical/jobs/6283017', 'Contrat': 'CDI', 'Localisation': 'Home based - Worldwide', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Solution Architecture Manager', 'Entreprise': 'Canonical', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/canonical/jobs/5516858', 'Contrat': 'CDI', 'Localisation': 'Home based - Worldwide', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Product Manager (AI)', 'Entreprise': 'Canonical', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/canonical/jobs/6643476', 'Contrat': 'CDI', 'Localisation': 'Home based - EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Technical Product Manager', 'Entreprise': 'Canonical', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/canonical/jobs/6980703', 'Contrat': 'CDI', 'Localisation': 'Home based - EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Solutions Engineer', 'Entreprise': 'Grafana Labs', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/grafanalabs/jobs/6121627004', 'Contrat': 'CDI', 'Localisation': 'France (Remote)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Product Manager, Infrastructure Observability', 'Entreprise': 'Grafana Labs', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/grafanalabs/jobs/6008080004', 'Contrat': 'CDI', 'Localisation': 'Irlande (Remote, aussi DE/ES/SE/UK)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Staff Product Manager, OpenTelemetry', 'Entreprise': 'Grafana Labs', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/grafanalabs/jobs/6161252004', 'Contrat': 'CDI', 'Localisation': 'Irlande (Remote, aussi DE/ES/SE/UK)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Manager, Solutions Engineering - NorBen', 'Entreprise': 'Grafana Labs', 'Source': 'Greenhouse API',
     'Lien': 'https://job-boards.greenhouse.io/grafanalabs/jobs/6121600004', 'Contrat': 'CDI', 'Localisation': 'Pays-Bas (Remote)', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Enterprise Sales Engineer - France', 'Entreprise': 'Chainguard', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/chainguard/jobs/4702184006', 'Contrat': 'CDI', 'Localisation': 'France - Remote', 'Remote': 'Oui',
     'Fit / Notes': 'Excellent fit Solutions Engineer, France explicite'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Partner Sales Engineer', 'Entreprise': 'Chainguard', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/chainguard/jobs/4701683006', 'Contrat': 'CDI', 'Localisation': 'France/Allemagne - Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager - EMEA', 'Entreprise': 'Chainguard', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/chainguard/jobs/4696446006', 'Contrat': 'CDI', 'Localisation': 'Allemagne - Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Manager, Customer Success Management - EMEA/APJ', 'Entreprise': 'Chainguard', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/chainguard/jobs/4707928006', 'Contrat': 'CDI', 'Localisation': 'UK - Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Account Manager, EMEA', 'Entreprise': 'Customer.io', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/customerio/jobs/7915379', 'Contrat': 'CDI', 'Localisation': 'EMEA Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Customer Success Manager, EMEA', 'Entreprise': 'Customer.io', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/customerio/jobs/8089365', 'Contrat': 'CDI', 'Localisation': 'EMEA Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Sr Account Manager, EMEA', 'Entreprise': 'Customer.io', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/customerio/jobs/8121617', 'Contrat': 'CDI', 'Localisation': 'EMEA Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Enterprise Customer Success Manager', 'Entreprise': 'Samsara', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://www.samsara.com/company/careers/roles/8132327?gh_jid=8132327', 'Contrat': 'CDI', 'Localisation': 'Remote - Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Implementation Consultant', 'Entreprise': 'Samsara', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://www.samsara.com/company/careers/roles/8088205?gh_jid=8088205', 'Contrat': 'CDI', 'Localisation': 'Remote - Allemagne', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Implementation Consultant', 'Entreprise': 'Samsara', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://www.samsara.com/company/careers/roles/7961276?gh_jid=7961276', 'Contrat': 'CDI', 'Localisation': 'Remote - UK', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Strategic Implementation Consultant', 'Entreprise': 'Samsara', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://www.samsara.com/company/careers/roles/8074111?gh_jid=8074111', 'Contrat': 'CDI', 'Localisation': 'Remote - UK', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Product Manager', 'Entreprise': 'Samsara', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://www.samsara.com/company/careers/roles/8039663?gh_jid=8039663', 'Contrat': 'CDI', 'Localisation': 'Londres/Remote-UK', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Product Manager – Business Applications', 'Entreprise': 'Dataiku', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/dataiku/jobs/6122317004', 'Contrat': 'CDI', 'Localisation': 'France, Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Sr Product Manager', 'Entreprise': 'Dataiku', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/dataiku/jobs/5812604004', 'Contrat': 'CDI', 'Localisation': 'France/Allemagne/NL/UK/Espagne, Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐⭐', 'Poste': 'Technical Account Manager - France', 'Entreprise': 'Dataiku', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/dataiku/jobs/6148352004', 'Contrat': 'CDI', 'Localisation': 'France, Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Implementation Consultant', 'Entreprise': 'Degreed', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://job-boards.greenhouse.io/degreed/jobs/6130184004', 'Contrat': 'CDI', 'Localisation': 'UK Based, Remote', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Sales Engineer, Enterprise', 'Entreprise': 'Fivetran', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://www.fivetran.com/careers/job?gh_jid=7822654003', 'Contrat': 'CDI', 'Localisation': 'Remote Irlande/UK, EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Senior Sales Engineer, Enterprise', 'Entreprise': 'Fivetran', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://www.fivetran.com/careers/job?gh_jid=7742243003', 'Contrat': 'CDI', 'Localisation': 'Remote Allemagne, EMEA', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Enterprise Sales Engineer, France', 'Entreprise': 'Abnormal AI', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://abnormal.ai/careers/jobs/7978334003?gh_jid=7978334003', 'Contrat': 'CDI', 'Localisation': 'Remote - France', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐⭐', 'Poste': 'Professional Services Consultant (Self Service), EMEA', 'Entreprise': 'Abnormal AI', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://abnormal.ai/careers/jobs/7809574003?gh_jid=7809574003', 'Contrat': 'CDI', 'Localisation': 'Remote - Irlande', 'Remote': 'Oui'},
    {'Priorité': '⭐⭐', 'Poste': 'Sales Engineer, Mid Market UKI', 'Entreprise': 'Abnormal AI', 'Source': 'Greenhouse API', 'Onglet': 'Offres USA',
     'Lien': 'https://abnormal.ai/careers/jobs/7886250003?gh_jid=7886250003', 'Contrat': 'CDI', 'Localisation': 'Remote - UK', 'Remote': 'Oui'},

    # ── Éditeurs HRIS / HR Path ──────────────────────────────────────────
    {'Priorité': '⭐⭐⭐', 'Poste': 'SAP SuccessFactors Consultant - Europe', 'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
     'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-SAP-SuccessFactors-Consultant-Europe-75-92042/1057307701/',
     'Contrat': 'CDI', 'Localisation': 'Paris La Défense + 6 villes UE', 'Remote': 'Non précisé'},
    {'Priorité': '⭐⭐⭐⭐', 'Poste': 'Consultant SIRH (H/F) — Workday • Oracle HCM • SAP SuccessFactors', 'Entreprise': 'HR Path', 'Source': 'jobs.hr-path.com',
     'Lien': 'https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SIRH-%28HF%29-Workday-%E2%80%A2-Oracle-HCM-%E2%80%A2-SAP-SuccessFactors-75-92042/1419350533/',
     'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': 'Non précisé', 'Fit / Notes': 'Publiée le 25/08/2026, très fraîche'},
]

if __name__ == "__main__":
    ajouter_offres(offres)
