# -*- coding: utf-8 -*-
"""Relance recherche du 22/08/2026 : compilation des 4 recherches parallèles
(boards FR/freelance, API ATS + éditeurs HRIS, boards remote/VC/LinkedIn, IA/PM/niche).
"""

from add_offre import ajouter_offres

CV_CSM = "CV_GaetanFRANCOIS_CSM_EN.pdf"
CV_CSM_FR = "CV_GaetanFRANCOIS_CSM.pdf"
CV_SIRH_EN = "Resume_GaetanFRANCOIS_SIRH_EN.pdf"
CV_SIRH_FR = "Resume_GaetanFRANCOIS_SIRH.pdf"
CV_PM_EN = "Resume_GaetanFRANCOIS_PM_EN.pdf"
CV_PM_FR = "Resume_GaetanFRANCOIS_PM_FR.pdf"
CV_PM_PLATFORM = "Resume_GaetanFRANCOIS_PM_Platform_EN.pdf"
CV_IA = "Resume_GaetanFRANCOIS_IA.pdf"
CV_ASHBY = "Resume_GaetanFRANCOIS_Ashby_EN.pdf"
CV_DATAMIG = "Resume_GaetanFRANCOIS_DataMigrationLead_EN.pdf"
CV_CONSTRUCTOR = "Resume_GaetanFRANCOIS_Constructor_EN.pdf"

OFFRES = [
    # ── free-work.com : SIRH / SAP HCM / SuccessFactors (freelance FR) ──
    dict(Poste="Consultant Expert Paie CEGEDIM / Team RH - Migration SIRH", Entreprise="Orviden",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/consultant-expert-paie-cegedim-team-rh-migration-sirh",
         Contrat="Freelance", Localisation="Toulouse", Remote="Partiel", **{"Salaire / TJM": "400-520€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "Migration SIRH Cegedim"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Chargé de missions SIRH N2 - Workday HCM (H/F)", Entreprise="HR DNA",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/charge-de-missions-sirh-n2-workday-hcm-h-f-25",
         Contrat="Freelance", Localisation="Neuilly-sur-Marne", Remote="Partiel", **{"Salaire / TJM": "250-500€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "SIRH Workday HCM senior"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Chef de projet IT / Responsable SIRH (H/F)", Entreprise="LeHibou",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/chef-de-projet-it-responsable-sirh-h-f",
         Contrat="Freelance", Localisation="Bordeaux", Remote="Partiel (2j/sem)", **{"Salaire / TJM": "675€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "Chef de projet SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Product Manager / Owner SIRH (H/F)", Entreprise="Lùkla",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/product-manager-owner-sirh-h-f",
         Contrat="Freelance", Localisation="Rouen", Remote="Partiel", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Croisement PM x SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Adjoint(e) Responsable Paie (H/F)", Entreprise="HR Path",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/directeur-de-la-data-cdo/adjoint-e-responsable-paie-h-f",
         Contrat="Freelance", Localisation="Paris", Remote="Partiel", **{"Salaire / TJM": "650-700€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "HR Path, éditeur connu"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant Transformation RH - Core HR", Entreprise="VISIAN",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant/consultant-transformation-rh-core-hr",
         Contrat="Freelance/CDI", Localisation="Paris", Remote="Partiel", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Transformation RH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Senior Consultant Transformation RH | TOM & Core HR", Entreprise="Mon Consultant Indépendant",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant/senior-consultant-transformation-rh-target-operating-model-core-hr-1",
         Contrat="Freelance", Localisation="Paris", Remote="Partiel", **{"Salaire / TJM": "500-550€/j"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "TOM/Core HR, très aligné L'Oréal"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SAP SuccessFactors CoreHR (H/F)", Entreprise="HR Path",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-corehr-h-f",
         Contrat="Freelance", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "450-600€/j"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "SuccessFactors CoreHR, HR Path"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Product Manager SIRH", Entreprise="Signe +",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/product-manager-sirh-3",
         Contrat="Freelance", Localisation="Rouen", Remote="Non précisé", **{"Salaire / TJM": "400-470€/j"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Product Manager SIRH", Entreprise="MLMCONSEIL",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/product-manager-sirh-1",
         Contrat="Freelance", Localisation="Rouen", Remote="Non précisé", **{"Salaire / TJM": "100-470€/j"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM SIRH (même mission via autre cabinet)"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="AMOA RH", Entreprise="CAT-AMANIA",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-moa-amoa/amoa-rh-2",
         Contrat="Freelance/CDI", Localisation="Paris", Remote="Partiel", **{"Salaire / TJM": "53-55k€/an ; 440-490€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "AMOA RH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Administrateur/référent SIRH (Workday) et DATA RH F/H", Entreprise="Mindquest",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/responsable-sirh-et-data-rh-f-h",
         Contrat="CDI", Localisation="Montrouge", Remote="Partiel", **{"Salaire / TJM": "42-69k€/an"},
         Priorité="⭐⭐", **{"Fit / Notes": "SIRH Workday"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="PMO SIRH H/F", Entreprise="HAYS France",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/pmo-sirh-h-f",
         Contrat="Freelance", Localisation="Guyancourt", Remote="Partiel", **{"Salaire / TJM": "450-540€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "PMO SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Business product owner SIRH", Entreprise="Mon Consultant Indépendant",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/business-product-owner-sirh",
         Contrat="Freelance", Localisation="Paris", Remote="Partiel", **{"Salaire / TJM": "500-550€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "PO SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Chef de projet fonctionnel SIRH - secteur immobilier", Entreprise="Mon Consultant Indépendant",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/chef-de-projet-fonctionnel-sirh-secteur-de-limmobilier",
         Contrat="Freelance", Localisation="Paris", Remote="Partiel", **{"Salaire / TJM": "550-590€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "Chef de projet SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Expert SAP SuccessFactors", Entreprise="LeHibou",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/expert-sap-successfactors-1",
         Contrat="Freelance", Localisation="Saint-Ouen-sur-Seine", Remote="Partiel", **{"Salaire / TJM": "575€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "SuccessFactors expert"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SAP SuccessFactors Onboarding (ONB)", Entreprise="LINKWAY",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-onboarding-onb",
         Contrat="Freelance", Localisation="Île-de-France", Remote="100%", **{"Salaire / TJM": "400€/j"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "SuccessFactors Onboarding, télétravail total"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SAP SuccessFactors LMS", Entreprise="LINKWAY",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-learning-management-system-lms",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "400€/j"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "SuccessFactors LMS, formation"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SAP SuccessFactors PMGM", Entreprise="LINKWAY",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-performance-goal-management-pmgm",
         Contrat="Freelance", Localisation="Île-de-France", Remote="100%", **{"Salaire / TJM": "400€/j"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "SuccessFactors PMGM, télétravail total"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SAP SuccessFactors RCM", Entreprise="LINKWAY",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-recruitment-rcm",
         Contrat="Freelance", Localisation="Île-de-France", Remote="100%", **{"Salaire / TJM": "400€/j"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "SuccessFactors RCM, télétravail total"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SAP SuccessFactors SP", Entreprise="LINKWAY",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-succession-planning-sp",
         Contrat="Freelance", Localisation="La Défense", Remote="100%", **{"Salaire / TJM": "400€/j"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "SuccessFactors Succession Planning, télétravail total"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Ingénieur SAP Success Factors (anglais)", Entreprise="BI SOLUTIONS",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/ingenieur-sap-success-factors-anglais-450-e-par-j",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Partiel", **{"Salaire / TJM": "400-450€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "SF, anglais requis (atout)"}, **{"CV à envoyer": CV_SIRH_EN}),
    dict(Poste="SAP PMO Successfactors (H/F)", Entreprise="Mindquest",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/sap-pmo-successfactors-h-f-75",
         Contrat="Freelance", Localisation="Paris", Remote="Partiel", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PMO SuccessFactors"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Expert Technico-Fonctionnel SAP HCM", Entreprise="INFOTEL CONSEIL",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/expert-technico-fonctionnel-sap-hcm",
         Contrat="Freelance (3 mois)", Localisation="Roissy-en-France", Remote="Partiel", **{"Salaire / TJM": "540-750€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "SAP HCM technico-fonctionnel"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="SAP SuccessFactors Senior/Lead Consultant", Entreprise="INVESTIGO",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/sap-successfactors-senior-lead-consultant-permanent-ps80-000-ps90-000-per-annum-benefits",
         Contrat="CDI", Localisation="Angleterre", Remote="Hybride", **{"Salaire / TJM": "£80-90k/an"},
         Priorité="⭐⭐", **{"Fit / Notes": "UK, SF senior/lead"}, **{"CV à envoyer": CV_SIRH_EN}),

    # ── free-work.com : IA ──
    dict(Poste="Product Owner Solutions IA H/F", Entreprise="DAVRICOURT",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/product-owner/product-owner-solutions-ia-h-f-6",
         Contrat="CDI", Localisation="Lille", Remote="Partiel", **{"Salaire / TJM": "45-50k€/an"},
         Priorité="⭐⭐", **{"Fit / Notes": "PO orienté IA"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Consultant IA Générative / Claude (Anthropic)", Entreprise="SMARTPOINT",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/consultant/consultant-ia-generative-claude-anthropic",
         Contrat="Freelance/CDI", Localisation="Île-de-France", Remote="Partiel", **{"Salaire / TJM": "500-600€/j"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Usage quotidien de Claude, fit direct"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Expert IA générative & outils Claude F/H", Entreprise="SMARTPOINT",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-ia-generative-outils-claude-f-h",
         Contrat="Freelance", Localisation="Paris", Remote="Partiel", **{"Salaire / TJM": "570-620€/j"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Outils Claude"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Expert IA générative et Plateforme IA H/F", Entreprise="Freelance.com",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-ia-generative-et-plateforme-ia-h-f",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Partiel", **{"Salaire / TJM": "510-590€/j"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Consultant IA générative"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Chef de Projet IA agentique gouvernance et archi Data", Entreprise="ARDEMIS PARTNERS",
         Source="free-work.com", Lien="https://www.free-work.com/fr/tech-it/job-mission/assistant-chef-de-projet/chef-de-projet-ia-agentique-gouvernance-et-archi-data",
         Contrat="Freelance/CDI", Localisation="Paris", Remote="Partiel", **{"Salaire / TJM": "400-500€/j"},
         Priorité="⭐⭐", **{"Fit / Notes": "Chef de projet IA, croisement PMO"}, **{"CV à envoyer": CV_IA}),

    # ── freelance-informatique.fr (data-obf) ──
    dict(Poste="Chef de projet SIRH confirmé", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-confirme-114018-de",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Chef de projet SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="AMOA SIRH Data sur Paris", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-amoa-sirh-data-sur-paris-113689-de",
         Contrat="Freelance", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "AMOA SIRH Data"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SIRH", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-consultant-sirh-113215-de",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Consultant SIRH générique"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Chef de projet SIRH Workday (certification obligatoire)", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-workday-certification-obligatoire-110752-de",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Chef de projet SIRH Workday"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Chef de projet transverse SIRH, Défense et remote", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-chef-de-projet-transverse-sirh-defense-et-remote-105678-de",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Chef de projet SIRH secteur Défense"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Product Owner / Chef de projet SIRH F/H", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-product-owner-chef-de-projet-sirh-f-h-104881-de",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PO/Chef de projet SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Chefs de projet et consultants technico-fonctionnels HCM", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-chefs-de-projet-et-consultants-technico-fonctionnels-hcm-99731-de",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Consultant technico-fonctionnel HCM"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SIRH SuccessFactors sur Issy", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-consultant-sirh-successfactors-sur-issy-115627-de",
         Contrat="Freelance", Localisation="Issy-les-Moulineaux", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "SuccessFactors"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Expert Workday IT F/H", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-expert-workday-it-f-h-115424-de",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Expert Workday"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant senior SAP SuccessFactors Recruiting/Employee Central", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-consultant-senior-sap-successfactors-recruiting-employee-central-lieu-luxembourg-sur-site-114529-de",
         Contrat="Freelance", Localisation="Luxembourg", Remote="Sur site", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "SuccessFactors Recruiting/EC senior, sur site Luxembourg"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Expert technique SIRH", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-expert-technique-sirh-113399-de",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Expert technique SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SAP SuccessFactors sur La Défense", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-consultant-sap-succesfactors-sur-la-defense-112172-de",
         Contrat="Freelance", Localisation="La Défense", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "SuccessFactors"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Expert HR Access sur Paris", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-expert-hr-access-sur-paris-116748-de",
         Contrat="Freelance", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "HR Access"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SIRH H/F", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-consultant-sirh-h-f-116636-de",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Consultant SIRH générique"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Expert Workday Accounting Center - Lead Implementation Finance", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-expert-workday-accounting-center-lead-implementation-finance-lille-116403-de",
         Contrat="Freelance", Localisation="Lille", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Workday Accounting Center, implémentation"}, **{"CV à envoyer": CV_DATAMIG}),
    dict(Poste="Chef de projet Workday sur Lille", Entreprise="N/C",
         Source="freelance-informatique.fr", Lien="https://www.freelance-informatique.fr/mission-chef-de-projet-workday-sur-lille-116386-de",
         Contrat="Freelance", Localisation="Lille", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Chef de projet Workday"}, **{"CV à envoyer": CV_SIRH_FR}),

    # ── mission-freelances.fr : IA ──
    dict(Poste="Formateur en IA générative et agentique", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/formateur-en-intelligence-artificielle-generative-et-agentique-teletravail-c892d79e/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "Formateur IA générative et agentique, cœur de cible"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Formateur IA appliquée à l'acquisition client", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/formateur-ia-appliquee-a-l-acquisition-client-teletravail-68ec066a/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Formation IA appliquée business"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Formateur·rice / Expert·e IA Générative Freelance", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/formateur-rice-expert-e-ia-generative-freelance-teletravail-0b5af74c/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Conception contenus pédagogiques IA"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Formateur·rice·s freelances en IA", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/formateur-rice-s-freelances-en-ia-teletravail-9cc97c82/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "IA + no-code, sans data science pur"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Formateur(trice) en ligne - IA et développement web", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/formateur-trice-en-ligne-intelligence-artificielle-et-developpement-web-teletravail-de3cf7d0/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Formation en ligne IA"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Formateur / Formatrice en IA Générative (certifiante)", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/formateur-formatrice-en-intelligence-artificielle-generative-ile-de-france-a5471a52/",
         Contrat="Freelance", Localisation="Île-de-France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Formation certifiante usage responsable IA"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Consultant(e) Senior Stratégie & Transformation IA", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/consultant-e-senior-strategie-transformation-ia-paris-9830c4b1/",
         Contrat="Freelance", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Diagnostic maturité IA, conduite du changement"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Consultant IA / AI Solutions Engineer", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/consultant-ia-ai-solutions-engineer-lyon-a6697d82/",
         Contrat="Freelance", Localisation="Lyon", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Industrialisation solutions IA générative"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Formateur(trice) Accompagnement & Sensibilisation IA (H/F)", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/formateur-trice-accompagnement-sensibilisation-intelligence-artificielle-h-f-toulon-116298f1/",
         Contrat="Freelance", Localisation="Toulon", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Sensibilisation IA en entreprise"}, **{"CV à envoyer": CV_IA}),
    dict(Poste="Formateur(trice) indépendant(e) en IA (certification RS7344)", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/formateur-trice-independant-e-en-ia-strasbourg-9a675c34/",
         Contrat="Freelance", Localisation="Strasbourg", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Formation certifiante dirigeants/indépendants"}, **{"CV à envoyer": CV_IA}),

    # ── mission-freelances.fr : CSM ──
    dict(Poste="Customer Success Manager (esthétique premium)", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/customer-success-manager-teletravail-49c96bf3/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM portefeuille clients"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Customer Success Manager (plateforme immobilière)", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/customer-success-manager-teletravail-8a4833c0/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM SaaS"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Customer Success / Account Manager - Immobilier", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/customer-success-account-manager-immobilier-teletravail-f69563e7/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM/AM"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Founding Customer Success Manager (lancement Italie)", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/founding-customer-success-manager-teletravail-c4e12456/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "CSM fondateur, poste à fort impact"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Customer Success Manager SaaS", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/customer-success-manager-saas-nanterre-5fe6b636/",
         Contrat="Freelance", Localisation="Nanterre", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM SaaS retail"}, **{"CV à envoyer": CV_CSM_FR}),

    # ── mission-freelances.fr : PM ──
    dict(Poste="Product Manager SIRH H/F (Oracle HCM)", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/product-manager-sirh-h-f-paris-d64b6274/",
         Contrat="Freelance", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Croisement PM x SIRH direct"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Product Manager Commercial", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/product-manager-commercial-teletravail-eb6ed03a/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM télétravail total"}, **{"CV à envoyer": CV_PM_FR}),
    dict(Poste="Product Manager / Designer", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/product-manager-designer-teletravail-c185d8f2/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM télétravail total"}, **{"CV à envoyer": CV_PM_FR}),
    dict(Poste="Product Manager Paiement Digital", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/product-manager-paiement-digital-teletravail-9aa507ee/",
         Contrat="Freelance", Localisation="Non précisé", Remote="Télétravail", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM télétravail total"}, **{"CV à envoyer": CV_PM_FR}),
    dict(Poste="Product Manager Plateforme IA", Entreprise="N/C",
         Source="mission-freelances.fr", Lien="https://www.mission-freelances.fr/missions/product-manager-plateforme-ia-paris-991d7208/",
         Contrat="Freelance", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM x IA (GenAI, LLM, agents)"}, **{"CV à envoyer": CV_PM_PLATFORM}),

    # ── welcometothejungle.com ──
    dict(Poste="Customer Success Onboarding - Formateur H/F", Entreprise="Organilog",
         Source="welcometothejungle.com", Lien="https://www.welcometothejungle.com/fr/companies/organilog/jobs/custome-success-manager-specialite-formateur-h-f-teletravail_pontchateau",
         Contrat="CDI", Localisation="Pontchâteau", Remote="Télétravail total", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "CSM + volet formateur, très bon fit"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Technical Customer Success", Entreprise="La Growth Machine",
         Source="welcometothejungle.com", Lien="https://www.welcometothejungle.com/fr/companies/lagrowthmachine/jobs/customer-success-manager",
         Contrat="CDI", Localisation="Paris", Remote="Télétravail total", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Technical CSM, télétravail total"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Consultant SIRH H/F", Entreprise="Septeo",
         Source="welcometothejungle.com", Lien="https://www.welcometothejungle.com/fr/companies/septeo/jobs/consultant-sirh-h-f_lyon_SEPTE_MjlzpK8",
         Contrat="CDI", Localisation="Lyon", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Consultant SIRH éditeur"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Customer Success Manager Onboarding", Entreprise="Qobra",
         Source="welcometothejungle.com", Lien="https://www.welcometothejungle.com/en/companies/qobra/jobs/customer-success-manager-onboarding-cdi-paris_paris",
         Contrat="CDI", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM Onboarding"}, **{"CV à envoyer": CV_CSM_FR}),

    # ── collective.work ──
    dict(Poste="Consultant Salesforce Freelance - Projet SIRH/RH - Full Remote (H/F)", Entreprise="N/C",
         Source="collective.work", Lien="https://www.collective.work/job/consultant-salesforce-freelance-projet-sirh-rh-full-remote-hf-b4np",
         Contrat="Freelance", Localisation="Paris", Remote="Full Remote", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Croisement SIRH/RH, full remote confirmé"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Manager de transition SAP senior", Entreprise="N/C",
         Source="collective.work", Lien="https://www.collective.work/jobs/fr/manager-de-transition-sap-senior-0uae",
         Contrat="Freelance", Localisation="Puteaux", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Management de transition SAP, proche profil L'Oréal"}, **{"CV à envoyer": CV_SIRH_FR}),

    # ── LinkedIn radar → ACT-ON HRIS (SmartRecruiters + site direct, tous hybrides) ──
    dict(Poste="Consultant(e) AMOA SIRH (F/H) — Neuilly", Entreprise="ACT-ON HRIS",
         Source="LinkedIn → SmartRecruiters", Lien="https://jobs.smartrecruiters.com/ACT-ON/744000045913473-consultant-e-amoa-sirh-f-h-",
         Contrat="CDI", Localisation="Neuilly-sur-Seine", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "AMOA SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant(e) SIRH (F/H) — Lille", Entreprise="ACT-ON HRIS",
         Source="LinkedIn → SmartRecruiters", Lien="https://jobs.smartrecruiters.com/ACT-ON/743999813824936-consultant-e-sirh",
         Contrat="CDI", Localisation="Lille", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Consultant SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant(e) SIRH - HCM (F/H) — Neuilly", Entreprise="ACT-ON HRIS",
         Source="LinkedIn → SmartRecruiters", Lien="https://jobs.smartrecruiters.com/ACT-ON/743999786658388-consultant-e-sirh-hcm",
         Contrat="CDI", Localisation="Neuilly-sur-Seine", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Consultant SIRH HCM"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant(e) AMOA SIRH (F/H) — Lyon", Entreprise="ACT-ON HRIS",
         Source="LinkedIn → actongroup.com", Lien="https://actongroup.com/offre/consultante-amoa-sirh-fh-lyon-3/",
         Contrat="CDI", Localisation="Lyon", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "AMOA SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant(e) AMOA SIRH (F/H) — Lille", Entreprise="ACT-ON HRIS",
         Source="LinkedIn → actongroup.com", Lien="https://actongroup.com/offre/consultante-amoa-sirh-fh-lille/",
         Contrat="CDI", Localisation="Lille", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "AMOA SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant(e) AMOA SIRH (F/H) — Nantes", Entreprise="ACT-ON HRIS",
         Source="LinkedIn → actongroup.com", Lien="https://actongroup.com/offre/consultante-amoa-sirh-fh-nantes-3/",
         Contrat="CDI", Localisation="Nantes", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "AMOA SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant Hr Access H/F — Lyon", Entreprise="ACT-ON HRIS",
         Source="LinkedIn → actongroup.com", Lien="https://actongroup.com/offre/consultant-hr-access-hf-lyon/",
         Contrat="CDI", Localisation="Lyon", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "HR Access"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant(e) GTA (F/H) — Neuilly", Entreprise="ACT-ON HRIS",
         Source="LinkedIn → actongroup.com", Lien="https://actongroup.com/offre/consultante-gta-fh-neuilly-sur-seine/",
         Contrat="CDI", Localisation="Neuilly-sur-Seine", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "GTA"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant.e Confirmé.e Intégration SAP SuccessFactors (F/H)", Entreprise="ACT-ON HRIS",
         Source="LinkedIn → actongroup.com", Lien="https://actongroup.com/offre/consultante-confirmee-integration-sap-successfactors-fh-france-neuilly-sur-seine/",
         Contrat="CDI", Localisation="Neuilly-sur-Seine", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "SuccessFactors intégration"}, **{"CV à envoyer": CV_SIRH_FR}),

    # ══════════════════ API ATS + éditeurs HRIS ══════════════════

    # Alan (Ashby)
    dict(Poste="Senior Customer Success Manager - France", Entreprise="Alan",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/alan/fb56b456-c00c-418c-b5b9-ea3aee8a2169",
         Contrat="CDI", Localisation="Paris", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "CSM senior, assurtech FR"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Operational Onboarding Manager - France", Entreprise="Alan",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/alan/149e6bff-b83d-4f7f-bfa8-9eb251bf437c",
         Contrat="CDI", Localisation="Anywhere in France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Onboarding, full remote France"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Product Manager - Sales AI", Entreprise="Alan",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/alan/7c57f914-4542-40d1-84c2-b3ac02154967",
         Contrat="CDI", Localisation="Paris/Lyon/Marseille/Bordeaux", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM x IA (Sales AI)"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Key Account Manager", Entreprise="Alan",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/alan/95e2e61d-9720-496a-aac5-7b7266a3ef7e",
         Contrat="CDI", Localisation="Paris/Bordeaux", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Account Manager"}, **{"CV à envoyer": CV_CSM}),

    # Ashby (ATS lui-même)
    dict(Poste="Strategic Customer Success Manager - EMEA", Entreprise="Ashby",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/ashby/1cf7c730-caba-4fc3-8b98-52a0735ef14b",
         Contrat="CDI", Localisation="Remote - EU", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "CSM stratégique, full remote EU"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Mid-Market Customer Success Manager - EMEA", Entreprise="Ashby",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/ashby/62d4f71e-f56c-447a-a965-a9c2ea8eac5e",
         Contrat="CDI", Localisation="Remote - EU", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "CSM, full remote EU"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Manager of Dedicated Implementations - EMEA", Entreprise="Ashby",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/ashby/35a01a05-8efd-4bc3-a4bf-0a31d902102d",
         Contrat="CDI", Localisation="Remote - EU", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "Manager implémentation, full remote EU, excellent fit"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Mid-Market Account Executive - EMEA (French Speaking)", Entreprise="Ashby",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/ashby/86a60834-ba64-484d-9658-afa1bc97a957",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Account Executive francophone, full remote"}, **{"CV à envoyer": CV_CSM}),

    # Camunda
    dict(Poste="Senior Product Manager - Core Platform (Remote)", Entreprise="Camunda",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/camunda/b771e145-a5cf-4867-ad13-b54830e3b744",
         Contrat="CDI", Localisation="Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "PM plateforme technique B2B, full remote"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Technical Account Manager - Benelux", Entreprise="Camunda",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/camunda/d5ce4070-2d06-4529-956f-a93d05eefd99",
         Contrat="CDI", Localisation="Netherlands", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "TAM plateforme technique"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Technical Account Manager - DACH", Entreprise="Camunda",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/camunda/05070fb6-de7a-4a03-b885-442032da57ec",
         Contrat="CDI", Localisation="Germany", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "TAM plateforme technique"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Sales Engineer UK", Entreprise="Camunda",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/camunda/f1a149e1-8f94-4c69-ab23-9bf79fe4770c",
         Contrat="CDI", Localisation="UK", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Sales Engineer"}, **{"CV à envoyer": CV_CSM}),

    # Cohere
    dict(Poste="Customer Success Manager - Public Sector & Defense, France", Entreprise="Cohere",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/cohere/597e18f5-c33c-4350-8bcd-05a751cece3a",
         Contrat="CDI", Localisation="France", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "CSM France explicite, éditeur IA de pointe"}, **{"CV à envoyer": CV_CSM}),

    # Constructor
    dict(Poste="Regional Manager, Customer Success EMEA", Entreprise="Constructor",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/constructor/5f24d378-f17b-4032-a2cc-079fd670563d",
         Contrat="CDI", Localisation="Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Manager CS, full remote"}, **{"CV à envoyer": CV_CONSTRUCTOR}),
    dict(Poste="Product Manager: Customer Onboarding Experience", Entreprise="Constructor",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/constructor/e8fa6194-ef2e-47d3-ab45-a9112d87da24",
         Contrat="CDI", Localisation="Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "PM onboarding, full remote"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Product Manager - Merchant Intelligence and Analytics", Entreprise="Constructor",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/constructor/e7426b59-431b-418b-a501-dde7f13b21bf",
         Contrat="CDI", Localisation="Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM analytics, full remote"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Product Manager: Recall", Entreprise="Constructor",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/constructor/7bc86d05-145d-4b7c-aa6e-b0b207d46117",
         Contrat="CDI", Localisation="Remote - EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM, full remote EMEA"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Account Manager, DACH", Entreprise="Constructor",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/constructor/776e4870-92d3-40d4-b2ea-c530537cd616",
         Contrat="CDI", Localisation="Remote - EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "AM DACH, full remote"}, **{"CV à envoyer": CV_CONSTRUCTOR}),
    dict(Poste="Sales Engineer (DACH)", Entreprise="Constructor",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/constructor/3b1910b4-f99a-4011-8e83-839cc6d74b29",
         Contrat="CDI", Localisation="Remote - Germany", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Sales Engineer, full remote"}, **{"CV à envoyer": CV_CSM}),

    # Dash0
    dict(Poste="Commercial Solutions Engineer - EMEA", Entreprise="Dash0",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/dash0/88dc8222-497c-4d58-ad5b-e862a6602c51",
         Contrat="CDI", Localisation="EMEA - Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Solutions Engineer, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Enterprise Solutions Engineer - EMEA", Entreprise="Dash0",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/dash0/d7fa3468-1e5c-4109-bdcf-0fa0f2f9c15b",
         Contrat="CDI", Localisation="EMEA - Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Solutions Engineer, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Enterprise Solutions Engineer - UK", Entreprise="Dash0",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/dash0/6526471a-8f48-425c-9329-2a8dcb175783",
         Contrat="CDI", Localisation="EMEA - Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Solutions Engineer, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Enterprise Solutions Engineer - Nordics", Entreprise="Dash0",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/dash0/eee66924-267e-4731-803f-85a43866bc9c",
         Contrat="CDI", Localisation="EMEA - Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Solutions Engineer, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Commercial Solutions Engineer - Nordics", Entreprise="Dash0",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/dash0/31c63bf9-c837-43c4-9deb-ba0da290cdd7",
         Contrat="CDI", Localisation="EMEA - Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Solutions Engineer, full remote"}, **{"CV à envoyer": CV_CSM}),

    # Docker
    dict(Poste="Senior Sales Engineer, Strategic (EMEA)", Entreprise="Docker",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/docker/3c43c05d-7d06-4144-904c-fa457cd3c51a",
         Contrat="CDI", Localisation="England", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Sales Engineer, éditeur connu"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Technical Account Manager (EMEA)", Entreprise="Docker",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/docker/de4dce34-7643-4c29-9113-230e7a591195",
         Contrat="CDI", Localisation="England", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "TAM, éditeur connu"}, **{"CV à envoyer": CV_CSM}),

    # ElevenLabs
    dict(Poste="Enterprise Solutions Engineer - France", Entreprise="ElevenLabs",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/elevenlabs/ce00fe7b-a93a-436b-bd5e-2eff87c48f23",
         Contrat="CDI", Localisation="France", Remote="Sur site", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Solutions Engineer France, IA audio de pointe"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Account Executive - ElevenCreative - France", Entreprise="ElevenLabs",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/elevenlabs/7ce7ff0a-564c-488a-aee1-db227b6a50ca",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Account Executive France, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Deployment Strategist - France - Global Expansion", Entreprise="ElevenLabs",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/elevenlabs/063115f6-3780-4920-97dd-c99489b6cfc2",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Déploiement client France, full remote, IA de pointe"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Customer Success Lead - Western Europe", Entreprise="ElevenLabs",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/elevenlabs/0dbfbe3e-7218-4045-ba78-28b0d2e5ab6d",
         Contrat="CDI", Localisation="Germany", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "CS Lead Western Europe"}, **{"CV à envoyer": CV_CSM}),

    # Fieldguide
    dict(Poste="Implementation Consultant, EMEA", Entreprise="Fieldguide",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/fieldguide/ce860562-e628-4bf3-9a3a-24caf7734405",
         Contrat="CDI", Localisation="Remote (UK)", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Implementation Consultant, full remote"}, **{"CV à envoyer": CV_ASHBY}),

    # Mural
    dict(Poste="Senior Solutions Engineer, DACH", Entreprise="Mural",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/mural/a88d6f5b-0b8f-431e-95b9-ee28dac07bd5",
         Contrat="CDI", Localisation="Germany Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Solutions Engineer, full remote"}, **{"CV à envoyer": CV_CSM}),

    # n8n
    dict(Poste="Technical Programs Manager - Scaled Customer Success (Remote Europe)", Entreprise="n8n",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/n8n/d550716c-8cb9-4efe-9a52-b4cd67e193e1",
         Contrat="CDI", Localisation="Remote Europe", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "CS scalé, full remote Europe, éditeur automatisation IA"}, **{"CV à envoyer": CV_CSM}),

    # Omni
    dict(Poste="Senior Solutions Engineer (Pre-Sales), EMEA", Entreprise="Omni",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/omni/6f7d41f0-c449-44be-845c-2fbdf226d0fa",
         Contrat="CDI", Localisation="Dublin", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Pre-sales technique"}, **{"CV à envoyer": CV_CSM}),

    # Pencil
    dict(Poste="Senior Product Manager - EMEA - Remote", Entreprise="Pencil",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/pencil/e4bbf9ae-0be6-455f-8b24-f960be4c6f2c",
         Contrat="CDI", Localisation="Europe", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "PM EMEA full remote, excellent fit récurrent"}, **{"CV à envoyer": CV_PM_EN}),
    dict(Poste="Lead Product Manager - Editor - EMEA", Entreprise="Pencil",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/pencil/765370fa-a2b2-487f-af2e-73a53cd1bad6",
         Contrat="CDI", Localisation="EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Lead PM, full remote EMEA"}, **{"CV à envoyer": CV_PM_EN}),
    dict(Poste="Director, Customer Success Partnerships", Entreprise="Pencil",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/pencil/f05810cc-91b4-4aab-ab64-35e01bed4901",
         Contrat="CDI", Localisation="EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Director CS Partnerships, full remote"}, **{"CV à envoyer": CV_CSM}),

    # Pennylane
    dict(Poste="Senior Product Manager", Entreprise="Pennylane",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/pennylane/a4555925-195a-4a59-9367-fcaf27f2113d",
         Contrat="CDI", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM, éditeur fintech FR"}, **{"CV à envoyer": CV_PM_FR}),
    dict(Poste="Customer Success Manager Grands Comptes - Cabinets comptables", Entreprise="Pennylane",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/pennylane/41c5e0a9-0793-4ce0-804a-3729fc4d1941",
         Contrat="CDI", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM grands comptes"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Training Manager / Responsable de Formation - région PACA", Entreprise="Pennylane",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/pennylane/abb59e6e-d876-4b9d-b185-2d06c84084aa",
         Contrat="CDI", Localisation="France (PACA)", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Training Manager, croise formation/SIRH"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Customer Success Manager - SAAS", Entreprise="Pennylane",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/pennylane/9f24fb70-d2bb-496f-9ed3-02bb9c9d7ad0",
         Contrat="CDI", Localisation="All France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "CSM SaaS, full remote France explicite"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Customer Success Manager - Medium Accounts", Entreprise="Pennylane",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/pennylane/d9c454b4-11ab-49f3-9ffe-4b444aecb99d",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "CSM medium accounts, remote"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Responsable Onboarding Comptable", Entreprise="Pennylane",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/pennylane/7ed8cb99-0b04-4227-b267-7610805e4fc4",
         Contrat="CDI", Localisation="All France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Onboarding, remote France"}, **{"CV à envoyer": CV_ASHBY}),

    # Photoroom (hybride)
    dict(Poste="Senior Product Manager, SMB e-commerce Growth", Entreprise="Photoroom",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/photoroom/cfe36a59-a475-44dd-925b-5cb4f93ec831",
         Contrat="CDI", Localisation="Paris", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM growth, IA image"}, **{"CV à envoyer": CV_PM_EN}),
    dict(Poste="Senior Product Manager, Core Product", Entreprise="Photoroom",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/photoroom/3bd8a6ab-496b-4f54-b9df-eb0b13fb46d2",
         Contrat="CDI", Localisation="Paris", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM core product, IA image"}, **{"CV à envoyer": CV_PM_EN}),
    dict(Poste="Staff Product Manager, Agentic & AI Platform", Entreprise="Photoroom",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/photoroom/e51e28e4-b740-44d6-922a-8a7b00a245a8",
         Contrat="CDI", Localisation="Paris", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM plateforme IA agentique"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Product Manager, Editing Foundations", Entreprise="Photoroom",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/photoroom/4886fd85-2b2c-4dca-bf48-1dbc370629bc",
         Contrat="CDI", Localisation="Paris", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM éditeur IA image"}, **{"CV à envoyer": CV_PM_EN}),

    # Socket
    dict(Poste="Sales Engineer, EMEA", Entreprise="Socket",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/socket/b88a5ea5-fb24-4e42-b567-072bf14a14ba",
         Contrat="CDI", Localisation="UK", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Sales Engineer"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Technical Account Manager, Europe", Entreprise="Socket",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/socket/8dec8a77-dafa-448a-a31c-4bf09e9d4f0d",
         Contrat="CDI", Localisation="UK", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "TAM Europe"}, **{"CV à envoyer": CV_CSM}),

    # Swans
    dict(Poste="Implementation Consultant (CRM, Automation, Data, AI)", Entreprise="Swans",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/swans/92cccf95-5548-44f5-8044-8b2d926b766a",
         Contrat="CDI", Localisation="Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Implementation Consultant, full remote, croisement IA"}, **{"CV à envoyer": CV_ASHBY}),

    # Tilla
    dict(Poste="Customer Success Manager - EMEA", Entreprise="Tilla",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/tilla/823e58d1-e986-42d9-9441-47f31bb77a52",
         Contrat="CDI", Localisation="Greece", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "CSM EMEA"}, **{"CV à envoyer": CV_CSM}),

    # Vanta
    dict(Poste="GRC Pre-Sales Consultant / Solutions Engineer – EMEA", Entreprise="Vanta",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/vanta/d38e7474-2b44-415c-824a-3debb757c9af",
         Contrat="CDI", Localisation="London/Dublin", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Pre-sales GRC"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Manager, Solutions Engineering - EMEA", Entreprise="Vanta",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/vanta/2daebe8c-69af-44f3-a81f-38fb17da30a0",
         Contrat="CDI", Localisation="London", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Manager Solutions Engineering"}, **{"CV à envoyer": CV_CSM}),

    # Zip
    dict(Poste="Senior ERP Solutions Consultant", Entreprise="Zip",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/zip/40e7432d-d779-4e56-9d0b-189fbdbbc9f9",
         Contrat="CDI", Localisation="London", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "ERP Solutions Consultant, croise migration de données"}, **{"CV à envoyer": CV_DATAMIG}),
    dict(Poste="Senior ERP Solutions Consultant (Remote Germany)", Entreprise="Zip",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/zip/8529f344-71e2-4fcf-944a-c8457e71faa1",
         Contrat="CDI", Localisation="Remote - Germany", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "ERP Solutions Consultant, full remote"}, **{"CV à envoyer": CV_DATAMIG}),
    dict(Poste="Enterprise Solution Engineer (Pre-Sales)", Entreprise="Zip",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/zip/dbfa71ad-7bef-4e5d-a227-277451ee2a26",
         Contrat="CDI", Localisation="Remote - Germany", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Solution Engineer pre-sales, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Solutions Consultant - Project Manager", Entreprise="Zip",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/zip/b33dc8ac-d350-4c10-babb-9ff7ea3b5cb1",
         Contrat="CDI", Localisation="London", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Solutions Consultant / PM"}, **{"CV à envoyer": CV_CSM}),

    # Kong (non-remote confirmé)
    dict(Poste="Staff Customer Success Manager", Entreprise="Kong Inc",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/kong/dbab32ac-1eb5-4a61-8a43-b647a746f27e",
         Contrat="CDI", Localisation="Allemagne", Remote="Non", **{"Salaire / TJM": "N/C"},
         Priorité="⭐", **{"Fit / Notes": "CSM API/infra, non-remote confirmé"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Staff Customer Success Manager (Nordics & Benelux)", Entreprise="Kong Inc",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/kong/9fc64b8f-9a6c-4d88-8d46-7edf90c8b7d4",
         Contrat="CDI", Localisation="Pays-Bas", Remote="Non", **{"Salaire / TJM": "N/C"},
         Priorité="⭐", **{"Fit / Notes": "CSM Nordics/Benelux, non-remote confirmé"}, **{"CV à envoyer": CV_CSM}),

    # ── API Lever ──
    dict(Poste="Key Account Manager Mid Market", Entreprise="360Learning",
         Source="API Lever", Lien="https://jobs.lever.co/360learning/62f460c2-9a8f-4a25-a847-0f8905d9feef",
         Contrat="CDI", Localisation="Paris", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Account Manager, remote, éditeur LMS/HR-tech"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Solution Deployment Manager", Entreprise="360Learning",
         Source="API Lever", Lien="https://jobs.lever.co/360learning/0dba50d1-52f4-4114-8421-2f9e19210fde",
         Contrat="CDI", Localisation="Paris", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Déploiement client, remote, éditeur LMS"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Solution Deployment Manager (Spain)", Entreprise="360Learning",
         Source="API Lever", Lien="https://jobs.lever.co/360learning/d53b936c-27f6-48f9-93dd-c4518bdddff1",
         Contrat="CDI", Localisation="Spain", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Déploiement client, remote"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Solutions Engineer DACH", Entreprise="360Learning",
         Source="API Lever", Lien="https://jobs.lever.co/360learning/11721c63-a8b7-43a3-ac05-3c8b352f3b07",
         Contrat="CDI", Localisation="Spain", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Solutions Engineer, remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Implementation Consultant - Commercial", Entreprise="Veeva",
         Source="API Lever", Lien="https://jobs.lever.co/veeva/f4c4c9f0-4bba-4800-91b5-7dbd61208ac1",
         Contrat="CDI", Localisation="France - Paris", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Implementation Consultant France, remote"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Customer Solutions Engineer Paris", Entreprise="Scality",
         Source="API Lever", Lien="https://jobs.lever.co/scality/fd966dc8-4f44-4735-81a3-7d4bd16ba342",
         Contrat="CDI", Localisation="Paris", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Solutions Engineer"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Enterprise Customer Success Manager - FR/ENG", Entreprise="Brevo",
         Source="API Lever", Lien="https://jobs.lever.co/brevo/293fd590-ebf0-4ab4-acf6-731130ed8d40",
         Contrat="CDI", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM enterprise, éditeur SaaS FR"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Product Manager", Entreprise="Brevo",
         Source="API Lever", Lien="https://jobs.lever.co/brevo/b3cc667c-dc00-40c6-8546-865942f96131",
         Contrat="CDI", Localisation="Paris", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM éditeur SaaS FR"}, **{"CV à envoyer": CV_PM_FR}),
    dict(Poste="Enterprise Account Manager, France", Entreprise="Contentsquare",
         Source="API Lever", Lien="https://jobs.lever.co/contentsquare/39dd5542-7e2d-4bd4-867a-921b2083748c",
         Contrat="CDI", Localisation="Paris Area", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "AM enterprise France"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Product Manager - User and Lifecycle Analytics", Entreprise="Contentsquare",
         Source="API Lever", Lien="https://jobs.lever.co/contentsquare/2f1fa0dc-bc37-43ac-85c8-734fc719e03a",
         Contrat="CDI", Localisation="Paris Area", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM analytics"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Product Manager [Accounting expertise, DE]", Entreprise="Qonto",
         Source="API Lever", Lien="https://jobs.lever.co/qonto/53f5103c-e7eb-4b7f-baa4-777968faf405",
         Contrat="CDI", Localisation="Paris", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM éditeur fintech FR"}, **{"CV à envoyer": CV_PM_FR}),
    dict(Poste="Staff Product Manager [AI Products]", Entreprise="Qonto",
         Source="API Lever", Lien="https://jobs.lever.co/qonto/7c6908ae-fa05-49a2-8680-ca1aeb885460",
         Contrat="CDI", Localisation="Paris", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM produit IA"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Account Manager", Entreprise="Aircall",
         Source="API Lever", Lien="https://jobs.lever.co/aircall/2fd5d679-fda9-46bc-b1e0-9438cf4f748c",
         Contrat="CDI", Localisation="Paris", Remote="Hybride", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Account Manager éditeur SaaS FR"}, **{"CV à envoyer": CV_CSM_FR}),

    # Jobgether (filtré France)
    dict(Poste="Commercial IT Team Lead – Data Migration", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/1fdcee08-6ad7-4dec-af34-b21f03b5e9dc",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "Excellent fit Data Migration Lead"}, **{"CV à envoyer": CV_DATAMIG}),
    dict(Poste="Product Manager (Internal HRIS / HR Tech)", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/c47e031c-99f7-4fb6-aff9-36d2d7f3593e",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "Excellent fit croisement PM x HRIS interne"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Technical Product Manager – GenAI Programmes", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/24b1bb55-b737-4786-9e20-59bd969da871",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM GenAI, remote France"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Group Product Manager - Platform Experience", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/3d05c794-a034-48cf-918c-14933214114b",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM plateforme"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Product Manager, APIs", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/b8f8d83e-53fd-4a1b-a22d-2f2ac946a353",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM APIs, lacune connue (produit dev), à noter en LM"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Project / Product Manager — PSP & Payment Integrations", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/589d954d-3487-4e5d-81d3-f795ed26ef47",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM paiements"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Customer Success Partner - German Speaking", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/73173375-9297-4bfc-a2b9-abbb7eadf01e",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CS Partner"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Director of Customer Success", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/188b3da3-6e29-455f-af5e-a2e7a62aee4b",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Director CS"}, **{"CV à envoyer": CV_CONSTRUCTOR}),
    dict(Poste="Account Manager, DACH", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/5a447c58-50d3-4cb3-934b-31d4e3e66f0a",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "AM DACH"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Web3 Product Manager", Entreprise="Jobgether (client anonymisé)",
         Source="API Lever - Jobgether", Lien="https://jobs.lever.co/jobgether/44031788-b8b9-48f0-a065-3159dfaedf66",
         Contrat="CDI", Localisation="France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM, secteur Web3"}, **{"CV à envoyer": CV_PM_EN}),

    # ── API Greenhouse ──
    dict(Poste="Enterprise Sales Engineer - France", Entreprise="Chainguard",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/chainguard/jobs/4702184006",
         Contrat="CDI", Localisation="France - Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "Meilleure offre CSM/pre-sales de la relance, France remote explicite"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Customer Success Manager - Germany", Entreprise="Chainguard",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/chainguard/jobs/4704918006",
         Contrat="CDI", Localisation="Germany - Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM senior, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Enterprise Customer Success Manager (French speaker)", Entreprise="Canonical",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/canonical/jobs/7084000",
         Contrat="CDI", Localisation="Home based - EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "CSM francophone, full remote EMEA"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Product Manager - AI", Entreprise="Canonical",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/canonical/jobs/6643476",
         Contrat="CDI", Localisation="Home based - EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "PM produit IA, full remote"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Manager, Product Manager", Entreprise="Canonical",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/canonical/jobs/6458166",
         Contrat="CDI", Localisation="Home based - EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Manager PM, full remote"}, **{"CV à envoyer": CV_PM_EN}),
    dict(Poste="Account Manager, EMEA", Entreprise="Customer.io",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/customerio/jobs/7915379",
         Contrat="CDI", Localisation="EMEA Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Account Manager EMEA, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Customer Success Manager, EMEA", Entreprise="Customer.io",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/customerio/jobs/8089365",
         Contrat="CDI", Localisation="EMEA Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "CSM EMEA, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Sr Account Manager, EMEA", Entreprise="Customer.io",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/customerio/jobs/8121617",
         Contrat="CDI", Localisation="EMEA Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "AM senior EMEA, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Implementation Consultant, UK", Entreprise="Degreed",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/degreed/jobs/6130184004",
         Contrat="CDI", Localisation="UK Based / Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Implementation Consultant, éditeur LMS/HR-tech, excellent fit sectoriel"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Customer Success Architect, EMEA", Entreprise="GitLab",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/gitlab/jobs/8561952002",
         Contrat="CDI", Localisation="Remote, Austria/France/Germany", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "CS Architect, France explicitement listée en remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Manager, Customer Success Managers, EMEA", Entreprise="GitLab",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/gitlab/jobs/8613199002",
         Contrat="CDI", Localisation="Remote, Austria/Germany", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Manager CSM EMEA"}, **{"CV à envoyer": CV_CONSTRUCTOR}),
    dict(Poste="Senior Professional Services Project Manager (EMEA)", Entreprise="GitLab",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/gitlab/jobs/8622433002",
         Contrat="CDI", Localisation="Remote", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Professional Services PM, full remote"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Solutions Engineer - France", Entreprise="Grafana Labs",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/grafanalabs/jobs/6121627004",
         Contrat="CDI", Localisation="France (Remote)", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "Solutions Engineer France, sans contrainte de langue"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Product Manager, Remote Build", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7331443003",
         Contrat="CDI", Localisation="Remote-France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "PM Remote-France explicite, éditeur HRIS le mieux aligné"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Account Manager - EMEA", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7834363003",
         Contrat="CDI", Localisation="Remote-EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "AM senior EMEA, éditeur HRIS"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Product Manager, Billing Platform", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7885108003",
         Contrat="CDI", Localisation="Remote-EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "PM billing, éditeur HRIS"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Product Manager, Contractor Management", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7885031003",
         Contrat="CDI", Localisation="Remote-EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "PM contractor management, éditeur HRIS"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Product Manager, Fraud and Compliance", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7814948003",
         Contrat="CDI", Localisation="Remote-EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM fraud/compliance"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Product Manager, APIs", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7831380003",
         Contrat="CDI", Localisation="Remote-EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM APIs"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Product Manager, Reporting & Insights", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7885155003",
         Contrat="CDI", Localisation="Remote-EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM reporting"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Workday Implementation Specialist", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7635556003",
         Contrat="CDI", Localisation="Remote-EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Implémentation Workday, éditeur HRIS"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Senior Workday Implementation Specialist (2)", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7548213003",
         Contrat="CDI", Localisation="Remote-EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Implémentation Workday, éditeur HRIS"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Global Payroll Implementation Country Lead - Germany", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7741670003",
         Contrat="CDI", Localisation="Remote-EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Implémentation payroll, éditeur HRIS"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Senior Payroll Implementation Specialist - NL & Belgium", Entreprise="Remote.com",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/remotecom/jobs/7799068003",
         Contrat="CDI", Localisation="Remote-Western Europe", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Implémentation payroll, éditeur HRIS"}, **{"CV à envoyer": CV_ASHBY}),

    # ── Atlassian ──
    dict(Poste="Account Manager, Strategic - France", Entreprise="Atlassian",
         Source="API carrières Atlassian", Lien="https://globalcareers-atlassian.icims.com/jobs/25256/account-manager%2c-strategic---france/job",
         Contrat="CDI", Localisation="Remote - France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "AM stratégique, France remote explicite, grand compte"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Principal Customer Success Manager, Strategic, France", Entreprise="Atlassian",
         Source="API carrières Atlassian", Lien="https://globalcareers-atlassian.icims.com/jobs/26057/principal-customer-success-manager%2c-strategic%2c-france/job",
         Contrat="CDI", Localisation="Remote - France / Paris", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "CSM Principal stratégique France"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Principal Customer Success Manager, Strategic - France", Entreprise="Atlassian",
         Source="API carrières Atlassian", Lien="https://globalcareers-atlassian.icims.com/jobs/26241/senior-principal-customer-success-manager%2c-strategic---france/job",
         Contrat="CDI", Localisation="Remote - France / Paris", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐⭐", **{"Fit / Notes": "CSM Senior Principal stratégique France"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Senior Services Solutions Advocate", Entreprise="Atlassian",
         Source="API carrières Atlassian", Lien="https://globalcareers-atlassian.icims.com/jobs/26249/senior-services-solutions-advocate/job",
         Contrat="CDI", Localisation="Paris / Remote - France", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Solutions Advocate, France remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Strategic Solutions Sales Executive - Southern Europe", Entreprise="Atlassian",
         Source="API carrières Atlassian", Lien="https://globalcareers-atlassian.icims.com/jobs/25170/strategic-solutions-sales-executive---southern-europe/job",
         Contrat="CDI", Localisation="Paris/Amsterdam/London/Remote-FR", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Solutions Sales Executive Southern Europe"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Principal Customer Success Manager, Strategic DACH", Entreprise="Atlassian",
         Source="API carrières Atlassian", Lien="https://globalcareers-atlassian.icims.com/jobs/26063/principal-customer-success-manager%2c-strategic-dach/job",
         Contrat="CDI", Localisation="Remote-Germany, France listée", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM Principal DACH, France éligible"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Field CTO - EMEA, DX", Entreprise="Atlassian",
         Source="API carrières Atlassian", Lien="https://globalcareers-atlassian.icims.com/jobs/24899/field-cto---emea%2c-dx/job",
         Contrat="CDI", Localisation="Remote-France/UK/Germany", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Field CTO EMEA, France éligible"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Enterprise Solutions Engineer, New Logo (Italian speaking)", Entreprise="Atlassian",
         Source="API carrières Atlassian", Lien="https://globalcareers-atlassian.icims.com/jobs/25775/enterprise-solutions-engineer%2c-new-logo--%28italian-speaking%29/job",
         Contrat="CDI", Localisation="Paris/Remote-Germany/UK", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Solutions Engineer, italien requis"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Account Executive, Enterprise Southern Europe (Italian Speaking)", Entreprise="Atlassian",
         Source="API carrières Atlassian", Lien="https://globalcareers-atlassian.icims.com/jobs/25434/account-executive%2c-enterprise-southern-europe-%28italian-speaking%29/job",
         Contrat="CDI", Localisation="Remote-France/Netherlands", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Account Executive, italien requis"}, **{"CV à envoyer": CV_CSM}),

    # ── Éditeurs HRIS / partenaires SAP ──
    dict(Poste="Consultant SAP HCM (H/F)", Entreprise="HR Path",
         Source="jobs.hr-path.com", Lien="https://jobs.hr-path.com/job/Villeneuve-d%E2%80%99Ascq-Consultant-SAP-HCM-%28HF%29-59-59650/770170201/",
         Contrat="CDI", Localisation="Villeneuve-d'Ascq", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Consultant SAP HCM, HR Path"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SAP SuccessFactors (H/F)", Entreprise="HR Path",
         Source="jobs.hr-path.com", Lien="https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SAP-SuccessFactors-%28HF%29-75-92042/818651901/",
         Contrat="CDI", Localisation="Paris La Défense", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Consultant SuccessFactors, HR Path"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="SAP SuccessFactors Consultant - Europe", Entreprise="HR Path",
         Source="jobs.hr-path.com", Lien="https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-SAP-SuccessFactors-Consultant-Europe-75-92042/1057307701/",
         Contrat="CDI", Localisation="Paris La Défense", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "SuccessFactors Europe, HR Path"}, **{"CV à envoyer": CV_SIRH_EN}),
    dict(Poste="Consultant SIRH Paie HR Access", Entreprise="HR Path",
         Source="jobs.hr-path.com", Lien="https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SIRH-Paie-HR-Access-Paris-La-D%C3%A9fense-%28HF%29-75-92042/888056701/",
         Contrat="CDI", Localisation="Paris La Défense", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "SIRH Paie HR Access"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SIRH (H/F) | Workday • Oracle HCM • SAP SuccessFactors", Entreprise="HR Path",
         Source="jobs.hr-path.com", Lien="https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SIRH-%28HF%29-Workday-%E2%80%A2-Oracle-HCM-%E2%80%A2-SAP-SuccessFactors-75-92042/1419350533/",
         Contrat="CDI", Localisation="Paris La Défense", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Consultant SIRH multi-éditeurs"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Chef de Projet HR Access", Entreprise="HR Path",
         Source="jobs.hr-path.com", Lien="https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Chef-de-Projet-HR-Access-Paris-La-D%C3%A9fense-75-92042/904222801/",
         Contrat="CDI", Localisation="Paris La Défense", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Chef de projet HR Access"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant Senior AMOA GA/Paie (H/F)", Entreprise="HR Path",
         Source="jobs.hr-path.com", Lien="https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-Senior-AMOA-GAPaie-%28HF%29-75-92042/1419635633/",
         Contrat="CDI", Localisation="Paris La Défense", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "AMOA GA/Paie senior"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SIRH Paie (F/H/NB)", Entreprise="Cegid",
         Source="jobs.cegid.com", Lien="https://jobs.cegid.com/fr/annonce/3815603-consultant-sirh-paie-fhnb-69009-lyon",
         Contrat="CDI", Localisation="Lyon", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Consultant SIRH Paie, éditeur Cegid"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Consultant SIRH Grands Comptes (F/H/NB)", Entreprise="Cegid",
         Source="jobs.cegid.com", Lien="https://jobs.cegid.com/fr/annonce/3151485-consultant-sirh-grands-comptes-fhnb-92100-boulogne-billancourt",
         Contrat="CDI", Localisation="Boulogne-Billancourt", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Consultant SIRH grands comptes, éditeur Cegid"}, **{"CV à envoyer": CV_SIRH_FR}),
    dict(Poste="Customer Success SIRH Grands Comptes", Entreprise="Lucca",
         Source="jobs.world.luccasoftware.com", Lien="https://jobs.world.luccasoftware.com/lucca/customer-success-sirh-grands-comptes-8d12e285-9f5c-4dcd-ba4c-661c80abe25c",
         Contrat="CDI", Localisation="Paris", Remote="Hybride (2j/sem)", **{"Salaire / TJM": "45-55k€/an"},
         Priorité="⭐⭐", **{"Fit / Notes": "CSM SIRH grands comptes, éditeur Lucca"}, **{"CV à envoyer": CV_CSM_FR}),
    dict(Poste="Customer Success SIRH Mid-Market Junior", Entreprise="Lucca",
         Source="jobs.world.luccasoftware.com", Lien="https://jobs.world.luccasoftware.com/lucca/customer-success-sirh-midmarket-junior-fc069879-3773-4524-ae17-2325b840c370",
         Contrat="CDI", Localisation="Nantes", Remote="Hybride (2j/sem)", **{"Salaire / TJM": "37-40k€/an"},
         Priorité="⭐", **{"Fit / Notes": "CSM SIRH junior, éditeur Lucca (niveau junior)"}, **{"CV à envoyer": CV_CSM_FR}),

    # ══════════════════ Boards remote/VC/LinkedIn ══════════════════
    dict(Poste="Customer Success Manager", Entreprise="Enode",
         Source="API Ashby (via WebSearch)", Lien="https://jobs.ashbyhq.com/enode/3def5099-9ccc-4ea8-97ef-f8e7a9f04990",
         Contrat="CDI", Localisation="Remote Europe", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "CSM senior climate-tech, full remote Europe confirmé"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Customer Success Manager II", Entreprise="Braze",
         Source="API Greenhouse (via WebSearch)", Lien="https://job-boards.greenhouse.io/braze/jobs/8074870",
         Contrat="CDI", Localisation="Remote - Spain", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM éditeur SaaS engagement client, EMEA remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Product Manager", Entreprise="Landed",
         Source="workatastartup.com (YC)", Lien="https://www.workatastartup.com/jobs/72468",
         Contrat="CDI", Localisation="Non précisé", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "SaaS avec ATS/HRIS/calendriers/job boards, croisement SIRH"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Customer Success Manager", Entreprise="FurtherAI",
         Source="workatastartup.com (YC)", Lien="https://www.workatastartup.com/jobs/78629",
         Contrat="CDI", Localisation="Non précisé", Remote="Non précisé", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Croisement IA x CSM, premier CSM de la boîte"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Customer Success Manager - Payroll Specialist", Entreprise="First Gen Financial",
         Source="Wellfound", Lien="https://wellfound.com/jobs/3737937-customer-success-manager-payroll-specialist",
         Contrat="CDI", Localisation="Remote (Work from Home)", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "HRIS/payroll explicitement mentionné"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Customer Success Manager, Key Accounts", Entreprise="Ceros",
         Source="Wellfound", Lien="https://wellfound.com/jobs/3345558-customer-success-manager-key-accounts",
         Contrat="CDI", Localisation="Remote (Work from Home)", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "CSM enterprise, éditeur SaaS créatif"}, **{"CV à envoyer": CV_CSM}),

    # ══════════════════ IA / PM / niche ══════════════════
    dict(Poste="Senior Product Manager", Entreprise="Typeform",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/typeform/jobs/8121116",
         Contrat="CDI", Localisation="Allemagne/Irlande/Pays-Bas/Portugal/Espagne/UK", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "PM SaaS B2B, full remote EMEA"}, **{"CV à envoyer": CV_PM_EN}),
    dict(Poste="Senior Product Manager - Analytics", Entreprise="Typeform",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/typeform/jobs/7090089",
         Contrat="CDI", Localisation="Allemagne/Irlande/Pays-Bas/Portugal/Espagne/UK", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM analytics IA-first, full remote"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Senior Product Manager - Create", Entreprise="Typeform",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/typeform/jobs/8066471",
         Contrat="CDI", Localisation="Allemagne/Irlande/Pays-Bas/Portugal/Espagne/UK", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "PM builder/design, full remote"}, **{"CV à envoyer": CV_PM_EN}),
    dict(Poste="Technical Product Manager - Money and Risk", Entreprise="Yuno",
         Source="API Lever", Lien="https://jobs.lever.co/yuno/d57cd987-7689-4d5c-a491-38209349105b",
         Contrat="CDI", Localisation="Amsterdam", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "PM technique fintech, remote (lacune connue : produit dev)"}, **{"CV à envoyer": CV_PM_PLATFORM}),
    dict(Poste="Implementation Consultant, EMEA (Fieldguide, doublon vérifié)", Entreprise="Fieldguide",
         Source="API Ashby", Lien="https://jobs.ashbyhq.com/fieldguide/ce860562-e628-4bf3-9a3a-24caf7734405",
         Contrat="CDI", Localisation="Remote (UK)", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "Implementation Consultant audit/compliance SaaS, full remote"}, **{"CV à envoyer": CV_ASHBY}),
    dict(Poste="Technical Account Manager, EMEA", Entreprise="Hightouch",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/hightouch/jobs/6146017004",
         Contrat="CDI", Localisation="Europe", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐⭐", **{"Fit / Notes": "TAM data activation platform, full remote"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Solutions Engineer, Mid-Market, EMEA", Entreprise="Hightouch",
         Source="API Greenhouse", Lien="https://job-boards.greenhouse.io/hightouch/jobs/5990367004",
         Contrat="CDI", Localisation="EMEA", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐⭐", **{"Fit / Notes": "Pre-sales technique, cohérent avec expérience avant-vente L'Oréal"}, **{"CV à envoyer": CV_CSM}),
    dict(Poste="Professional Services Consultant (Self Service), EMEA", Entreprise="Abnormal Security",
         Source="API Greenhouse", Lien="https://abnormal.ai/careers/jobs/7809574003?gh_jid=7809574003",
         Contrat="CDI", Localisation="Remote UK", Remote="Oui", **{"Salaire / TJM": "N/C"},
         Priorité="⭐⭐", **{"Fit / Notes": "Déploiement post-vente, secteur nouveau mais compétence transférable"}, **{"CV à envoyer": CV_ASHBY}),
]

if __name__ == "__main__":
    ajouter_offres(OFFRES)
