"""
Ajout des offres trouvées lors de la recherche du 2026-07-31.
Sources couvertes : LinkedIn (SAP HCM, SIRH, SuccessFactors, CSM, Formateur IA),
free-work.com (IA/IA générative + WebSearch SIRH + SAP HCM/SF), AshbyHQ, Lever,
welcometothejungle.com, HR Path, Deloitte, EY, KPMG, Wavestone, ACT-ON HRIS,
Mercer | ConvictionsRH, Arago Consulting, Sopra Steria, ALTHEA, Inetum,
Strada (Alight), Movement Group, Mindquest, YGL Consulting, Eramet, Sonepar,
Tenth Revolution Group, mission-freelances.fr, Harvey AI, Synthesia, Camunda,
SecurityScorecard, Saviynt, WalkMe, Canonical, Deel, Remote.com, Riot Security,
Pennylane, Pipedrive, Adthena, Webmyday, iQo, Cherry Pick, Valeo, Notion.
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
from add_offre import ajouter_offres

offres = [

    # ── ONGLET OFFRES SIRH ─────────────────────────────────────────────────────

    # ACT-ON HRIS — Consultant AMOA SIRH (Neuilly — publié il y a 6j)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) AMOA SIRH (F/H)',
        'Entreprise': 'ACT-ON HRIS',
        'Source': 'SmartRecruiters / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Neuilly-sur-Seine (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'ACT-ON HRIS filiale SIRH du groupe ACT-ON (600+ collab., 65M€ CA). Profil exact : SAP SuccessFactors, HR Access, AMOA, specs fonctionnelles, conduite du changement. 15 ans SAP + 40 pays L\'Oréal = profil senior idéal. Lien : jobs.smartrecruiters.com/ACT-ON/744000045913473',
        'Lien': 'https://jobs.smartrecruiters.com/ACT-ON/744000045913473-consultant-e-amoa-sirh-f-h-',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75-85K€',
    },

    # ACT-ON HRIS — Consultant SuccessFactors (publié il y a 2j — très récent)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) SuccessFactors (F/H)',
        'Entreprise': 'ACT-ON HRIS',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Neuilly-sur-Seine (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste SAP SuccessFactors dédié chez ACT-ON HRIS, publié il y a 2 jours — fenêtre idéale pour postuler. Gaëtan cumule 14 ans SAP HR/HCM ; correspond exactement au profil recherché par ce cabinet spécialisé HumanTech.',
        'Lien': 'https://fr.linkedin.com/jobs/view/consultant-e-successfactors-f-h-at-act-on-hris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75-85K€',
    },

    # ACT-ON HRIS — Consultant CONFIRME SIRH SAP HR (publié ce matin même !)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Confirmé SIRH - SAP HR (H/F)',
        'Entreprise': 'ACT-ON HRIS',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Neuilly-sur-Seine (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste SAP HR publié ce matin même (31/07/2026, il y a 17h) — postuler en priorité absolue aujourd\'hui. Intitulé "Confirmé" = niveau intermédiaire, Gaëtan au-dessus, peut négocier un niveau senior. ACT-ON HRIS = cabinet SIRH pur spécialisé.',
        'Lien': 'https://fr.linkedin.com/jobs/view/consultant-confirme-sirh-sap-hr-h-f-at-act-on-hris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75-85K€',
    },

    # Arago Consulting — HRIS & AI Tech Pre-Sales Specialist (Bordeaux — proximité Anglet)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'HRIS & AI Tech Pre-Sales Specialist',
        'Entreprise': 'Arago Consulting',
        'Source': 'SmartRecruiters',
        'Contrat': 'CDI',
        'Localisation': 'Paris ou Bordeaux',
        'Remote': 'Partiel (déplacements clients)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Arago = 1er partenaire européen SAP SuccessFactors. Croisement parfait pre-sales IA+SIRH : 14 ans SAP, 40 pays L\'Oréal, usage quotidien IA générative, profil face-client senior. Bordeaux = 2h d\'Anglet. Lien : jobs.smartrecruiters.com/Arago/744000139094386',
        'Lien': 'https://jobs.smartrecruiters.com/Arago/744000139094386-hris-ai-tech-pre-sales-specialist',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '90-110K€',
    },

    # Mercer | ConvictionsRH — AMOA SAP SuccessFactors (CDI, rebrand 2025)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) AMOA SAP SuccessFactors (H/F)',
        'Entreprise': 'Mercer | ConvictionsRH',
        'Source': 'convictionsrh.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris + Lyon / Bordeaux / Toulouse / Nantes / Marseille',
        'Remote': 'Partiel (coworking flexible)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Mercer | ConvictionsRH (intégration Marsh 2025) = acteur clé SIRH France sur SAP SF, Workday, Oracle. 3+ ans SAP SF requis ; Gaëtan dépasse largement avec 14 ans SAP HR. Plusieurs localisations FR dont Bordeaux/Toulouse proches Anglet. Note : peut être la même annonce que ConvictionsRH trouvée le 30/07 — vérifier avant de postuler.',
        'Lien': 'https://www.convictionsrh.com/job/consultante-amoa-sap-successfactors-h-f/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75-85K€',
    },

    # Mercer | ConvictionsRH — Expert AMOA SIRH Freelance (sous-traitance)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Expert(e) AMOA et/ou Intégration SIRH (Freelance)',
        'Entreprise': 'Mercer | ConvictionsRH',
        'Source': 'convictionsrh.com',
        'Contrat': 'Freelance',
        'Localisation': 'Selon missions clients',
        'Remote': 'Flexible selon clients',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Mission freelance sous-traitance chez Mercer | ConvictionsRH sur SAP SF, Workday, Oracle HCM — cadrage, specs, recette, montées de version. Contact direct : soustraitance@convictionsrh.com. Gaëtan = profil expert indépendant idéal.',
        'Lien': 'https://www.convictionsrh.com/job/expert-amoa-et-ou-integration-sirh-freelance/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },

    # Sopra Steria Next — Consultant SIRH Transformation digitale (publié il y a 42 min !)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) SIRH Transformation Digitale - People Experience & Change (F/H)',
        'Entreprise': 'Sopra Steria Next',
        'Source': 'careers.soprasteria.fr',
        'Contrat': 'CDI',
        'Localisation': 'Courbevoie (92)',
        'Remote': 'Partiel (2j/semaine max)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Poste publié ce matin même (31/07/2026, il y a 42 min) — à postuler dans la journée. Sopra Steria Next = cabinet conseil transformation RH/SIRH, audit systèmes, implémentation, accompagnement changement. Remote limité = contrainte pour Anglet mais poste très récent à saisir.',
        'Lien': 'https://careers.soprasteria.fr/job/consultant-sirh-transformation-digitale-f-h-people-and-change-ile-de-france-in-courbevoie-france-jid-4122',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # ACT-ON STRATEGY — Consultant Stratégie et Transformation RH (publié hier)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) Stratégie et Transformation RH (F/H)',
        'Entreprise': 'ACT-ON STRATEGY',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Neuilly-sur-Seine (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Branche stratégie RH du groupe ACT-ON — conseil en transformation RH, lien métier/digital, conduite du changement. Moins centré SAP que les autres postes ACT-ON mais Gaëtan peut valoriser 15 ans transformation SIRH grands comptes et usage quotidien IA.',
        'Lien': 'https://fr.linkedin.com/jobs/view/consultant-e-strat%C3%A9gie-et-transformation-rh-f-h-at-act-on-strategy',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # ACT-ON HRIS — AMOA SIRH Lyon/Lille/Nantes (3 postes distincts, publiés il y a 6j)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) AMOA SIRH (F/H) - Régions',
        'Entreprise': 'ACT-ON HRIS',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Lyon / Lille / Nantes',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'ACT-ON HRIS a 3 postes identiques AMOA SIRH en régions publiés il y a 6 jours. Lyon (2h Anglet) et Nantes accessibles. Même profil que le poste Neuilly — à postuler en complément si IDF non retenu.',
        'Lien': 'https://fr.linkedin.com/jobs/search/?keywords=ACT-ON+HRIS+AMOA+SIRH',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # Mercer | ConvictionsRH — AMOA Workday (CDI)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) AMOA Workday (H/F)',
        'Entreprise': 'Mercer | ConvictionsRH',
        'Source': 'convictionsrh.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris + villes FR',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Modules HCM Core, Recruiting, Talent & Performance, Absence, Learning, Compensation, Payroll. Gaëtan non certifié Workday mais profil AMOA SIRH senior + SAP HR 14 ans + L\'Oréal mondial sont directement transférables sur ce type de projet.',
        'Lien': 'https://www.convictionsrh.com/job/consultante-amoa-workday-h-f/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-85K€',
    },

    # HR Path — Consultant(e) SIRH Workday/Oracle/SAP SF (nouveau poste vs. Senior/Lead du 30/07)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) SIRH Workday / Oracle HCM / SAP SuccessFactors (H/F)',
        'Entreprise': 'HR Path',
        'Source': 'LinkedIn / jobs.hr-path.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris et périphérie',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Nouveau poste HR Path distinct du Senior/Lead trouvé le 30/07 — profil généraliste SIRH multi-solutions (Workday, Oracle, SAP SF). Gaëtan peut se positionner sur la colonne SAP HCM/SF. Publié il y a 3 jours.',
        'Lien': 'https://jobs.hr-path.com/jobs',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75-85K€',
    },

    # ALTHEA — Consultant Senior SIRH Grand Ouest / Nantes
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) SIRH Senior - Grand Ouest / Nantes',
        'Entreprise': 'ALTHEA',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Saint-Herblain (44) / Issy-les-Moulineaux (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'ALTHEA cabinet de conseil SIRH (conseil + IT + métier). Poste senior 3-5 ans — niveau en dessous de Gaëtan mais négociable. Outils cibles : Workday/Oracle HCM/SAP SF. Nantes depuis Anglet = accessible pour déplacements ponctuels.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/althea/jobs/consultant-sirh-senior-grand-ouest-nantes_issy-les-moulineaux',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # Mindquest — PMO SuccessFactors (freelance, free-work.com)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'PMO SAP SuccessFactors',
        'Entreprise': 'Client via Mindquest',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Mission PMO SAP SuccessFactors chez Mindquest (cabinet spécialisé IT/Data) — combine gestion de projet SIRH grands comptes et expertise SAP SF. Profil idéal pour Gaëtan qui a piloté des projets SAP HR sur 40 pays.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/sap-successfactors',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-750€/j',
    },

    # YGL Consulting — AMOA SIRH Pléiades 4you (freelance)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) AMOA SIRH - Pléiades 4you',
        'Entreprise': 'Client via YGL Consulting',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '600-700€/j',
        'Durée mission': '',
        'Fit / Notes': 'YGL Consulting recrute un consultant AMOA SIRH sur logiciel Pléiades 4you (paie/admin). Gaëtan a le background AMOA SIRH mais pas d\'expérience directe Pléiades — à postuler si besoin de diversifier les missions. YGL actif sur plusieurs missions SIRH et IA.',
        'Lien': 'https://www.free-work.com/fr/tech-it/administrateur-applicatif-erp-crm-sirh/job-mission/amoa-sirh-pleiades-4you',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '650-700€/j',
    },

    # Inetum — Consultant SIRH SAP HCM SF (Tunis — vérifier remote depuis France)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) SIRH SAP HCM SuccessFactors (H/F)',
        'Entreprise': 'Inetum',
        'Source': 'inetum.com / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Tunis, Tunisie',
        'Remote': 'À confirmer (vérifier si remote France possible)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Inetum (acteur majeur SAP France/EMEA) recrute un consultant SAP SF avec 2+ ans exp. et certification SF. Poste basé en Tunisie — contacter pour confirmer si 100% remote depuis France accepté avant de postuler.',
        'Lien': 'https://www.inetum.com/fr/accueil/carrieres/d726923c-1981-42ba-89d3-b4d0355b578d.html',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': 'À préciser selon conditions remote',
    },

    # Sonepar — HRIS Project Manager (grand groupe international, publié il y a 3 semaines)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'HRIS Project Manager',
        'Entreprise': 'Sonepar',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris (Ville)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Sonepar (distributeur électrique mondial, 40 pays) recrute un PM SIRH orienté SAP SuccessFactors — poste interne grand groupe similaire à l\'expérience L\'Oréal. Publié il y a 3 semaines, encore probablement actif.',
        'Lien': 'https://fr.linkedin.com/jobs/view/hris-project-manager-at-sonepar',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-90K€',
    },

    # KPMG — Consultant Senior RH People Strategy & Transformation
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Senior RH People Strategy & Transformation (F/H)',
        'Entreprise': 'KPMG France',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Courbevoie (La Défense)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'KPMG recrute un consultant senior transformation RH avec exposition digitale/SIRH (SAP S/4, SF, Workday). Gaëtan peut valoriser sa double casquette SAP+conseil client grands comptes. Remote limité = contrainte depuis Anglet.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/kpmg-france/jobs/consultant-senior-rh-people-strategy-transformation-f-h_courbevoie',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '80-90K€',
    },

    # Eramet — Lead Technique SIRH & Intégration
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Lead Technique SIRH & Intégration (H/F)',
        'Entreprise': 'Eramet',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Eramet (groupe minier mondial) recrute un lead SIRH & intégration côté client/utilisateur final. Profil technique intégration peut être au-delà de la zone confort de Gaëtan mais expérience L\'Oréal côté client SAP HR est valorisable.',
        'Lien': 'https://fr.linkedin.com/jobs/view/lead-technique-sirh-int%C3%A9gration-h-f-at-eramet',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '75-85K€',
    },

    # ACT-ON HRIS — MOA HR Access (moins prioritaire — outil non maîtrisé)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant(e) MOA HR Access (F/H)',
        'Entreprise': 'ACT-ON HRIS',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Neuilly-sur-Seine (92)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'ACT-ON HRIS recrute aussi sur HR Access (MOE). Gaëtan n\'a pas d\'expérience directe HR Access mais profil SIRH global et SAP permet de se positionner. Moins prioritaire que le poste AMOA généraliste ACT-ON du même jour.',
        'Lien': 'https://fr.linkedin.com/jobs/view/consultant-e-moa-hr-access-at-act-on-hris',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # Tenth Revolution Group — Consultant SIRH AMOA GTA
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant AMOA GTA SIRH',
        'Entreprise': 'Tenth Revolution Group',
        'Source': 'free-work.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris (75001) et Île-de-France',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Tenth Revolution Group (ex-Frank Recruitment, spécialiste SAP/SIRH) recrute plusieurs consultants AMOA GTA SIRH 5+ ans. Gaëtan dépasse ce seuil. Utile aussi comme contact réseau cabinet recrutement SAP/SIRH.',
        'Lien': 'https://www.free-work.com/fr/tech-it/consultant-moa-amoa/job-mission/consultant-amoa-gta-sirh-14',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # ── ONGLET OFFRES CSM ──────────────────────────────────────────────────────

    # Harvey AI — Enterprise Customer Success Manager EMEA (Paris office ouvert 2026)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Enterprise Customer Success Manager, EMEA',
        'Entreprise': 'Harvey AI',
        'Source': 'AshbyHQ',
        'Contrat': 'CDI',
        'Localisation': 'Paris (bureau ouvert mai 2026)',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Harvey = licorne IA juridique (1500+ clients, Fortune 100), expansion Paris 2026. CSM enterprise EMEA pour cabinets d\'avocats + institutions financières. Onboarding, formation, adoption IA. Profil CSM enterprise SaaS + IA quotidienne de Gaëtan = fit fort sur l\'approche, secteur juridique = nouveau.',
        'Lien': 'https://jobs.ashbyhq.com/harvey/d911b15e-29e4-453e-b192-4201c7937e1f',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '85-95K€',
    },

    # Synthesia — Strategic Customer Success Manager French Speaking (Paris)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Strategic Customer Success Manager (French Speaking)',
        'Entreprise': 'Synthesia',
        'Source': 'AshbyHQ',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Synthesia (plateforme IA vidéo, 90%+ Fortune 100, 25M$ investi Paris 2026) recrute un CSM stratégique French Speaking pour comptes enterprise français. Gaëtan avec 15 ans CS grands comptes + IA quotidienne = parfaitement positionné. Entreprise IA en pleine croissance.',
        'Lien': 'https://jobs.ashbyhq.com/synthesia/84342701-d3e1-4915-987a-cdec0cb1bee8',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '85-95K€',
    },

    # Canonical — Enterprise Customer Success Manager French Speaker (100% remote EMEA)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Enterprise Customer Success Manager (French Speaker)',
        'Entreprise': 'Canonical',
        'Source': 'canonical.com/careers',
        'Contrat': 'CDI',
        'Localisation': 'EMEA (100% remote)',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Canonical (Ubuntu/Linux enterprise, 1500+ clients globaux) recrute un enterprise CSM French Speaker 100% remote EMEA — onboarding, adoption, expansion. Budget dev perso 2000$/an inclus. Gaëtan n\'est pas expert Linux mais le profil CSM enterprise grands comptes est très solide. Fit géographique parfait pour Anglet.',
        'Lien': 'https://canonical.com/careers/7084000',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '85-95K€',
    },

    # Camunda — Senior Customer Success Manager France (remote, salaire attractif)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager (France, remote)',
        'Entreprise': 'Camunda',
        'Source': 'euremotejobs.com / awesomejobs.io',
        'Contrat': 'CDI',
        'Localisation': 'France (100% remote)',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '75 000-123 500£/an',
        'Durée mission': '',
        'Fit / Notes': 'Camunda (BPM/process automation enterprise) recrute un senior CSM France en full remote. Plage salariale très large (75-123K£). 5+ ans CS enterprise requis, FR+EN, expérience grandes institutions financières. Vérifier si poste toujours actif sur camunda.com/careers.',
        'Lien': 'https://www.awesomejobs.io/remote-job/customer-success-manager-at-camunda',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '90-105K€',
    },

    # WalkMe — Senior Customer Success Manager French Speaking (lié à SAP)
    {
        'Priorité': '⭐⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager (French Speaking)',
        'Entreprise': 'WalkMe',
        'Source': 'jobs.lever.co',
        'Contrat': 'CDI',
        'Localisation': 'London (base) — remote France à vérifier',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'WalkMe (plateforme adoption digitale, maintenant SAP company) recrute un senior CSM French Speaking — portefeuille Fortune 1000, jusqu\'à 6M$ ARR, 5+ ans enterprise SaaS. Gaëtan correspond parfaitement et WalkMe est directement lié à l\'écosystème SAP. Vérifier possibilité remote depuis France.',
        'Lien': 'https://jobs.lever.co/walkme/4f34a9f8-b991-417b-8e20-13252c6550b8',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '85-95K€',
    },

    # SecurityScorecard — Senior CSM EMEA French Speaking (remote Europe)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Customer Success Manager EMEA (French Speaking)',
        'Entreprise': 'SecurityScorecard',
        'Source': 'builtin.com',
        'Contrat': 'CDI',
        'Localisation': 'EMEA (remote Europe)',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'SecurityScorecard (cybersécurité, Sequoia/Silver Lake, 290M$ levés) recrute un senior CSM EMEA French Speaking — full remote Europe. Gaëtan peut valoriser son profil CSM enterprise senior ; secteur cybersécurité = nouveau mais approche CS transférable.',
        'Lien': 'https://builtin.com/job/sales/senior-customer-success-manager-emea-french-speaking/754421',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '85-95K€',
    },

    # Deel — Customer Success Manager French Speaker (HRIS global, remote)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager (French Speaker)',
        'Entreprise': 'Deel',
        'Source': 'AshbyHQ',
        'Contrat': 'CDI',
        'Localisation': 'Remote (France/Espagne/Belgique)',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Deel (HRIS/paie mondiale, 150+ pays) recrute un CSM French Speaker pour Deel IT — remote depuis France. Profil naturel pour Gaëtan qui combine SIRH international + CSM SaaS + paie globale L\'Oréal 40 pays.',
        'Lien': 'https://jobs.ashbyhq.com/deel/2fc7826c-3e54-40d8-ad26-22364517c27d',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-90K€',
    },

    # Remote.com — Senior Payroll Customer Success Manager EMEA (100% remote)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Senior Payroll Customer Success Manager, EMEA',
        'Entreprise': 'Remote.com',
        'Source': 'euremotejobs.com',
        'Contrat': 'CDI',
        'Localisation': 'EMEA (100% remote)',
        'Remote': 'Oui (100% remote)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Remote.com (plateforme paie/RH globale) recrute un senior CSM Payroll EMEA — lien direct avec l\'expertise paie internationale SAP de Gaëtan. Fit fort entre expérience L\'Oréal paie 40 pays et ce poste spécialisé payroll CSM. 100% remote = parfait pour Anglet.',
        'Lien': 'https://euremotejobs.com/job/senior-payroll-customer-success-manager-emea/',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '85-95K€',
    },

    # Saviynt — CSM France IAM/IGA (remote Paris)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager France (IAM/IGA)',
        'Entreprise': 'Saviynt',
        'Source': 'builtin.com / remoterocketship.com',
        'Contrat': 'CDI',
        'Localisation': 'Paris, Île-de-France (remote)',
        'Remote': 'Oui',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Saviynt (identity security, Sequoia-backed) recrute un CSM France IAM/IGA — résidence en France requise, connaissance cybersécurité appréciée mais pas bloquante. Profil CSM enterprise + SaaS de Gaëtan est solide. Poste publié il y a 15 jours.',
        'Lien': 'https://www.remoterocketship.com/company/saviynt/jobs/customer-success-manager-iam-iga-france',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-90K€',
    },

    # Harvey AI — CSM Mid-Market EMEA Paris (2e poste Harvey)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager Mid-Market, EMEA',
        'Entreprise': 'Harvey AI',
        'Source': 'AshbyHQ / LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Hybride',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Harvey recrute aussi un CSM Mid-Market EMEA Paris en plus du poste Enterprise. Niveau moins senior mais même entreprise IA juridique avec bureau Paris. À postuler si le poste Enterprise ne convient pas ou en complément.',
        'Lien': 'https://jobs.ashbyhq.com/harvey/b7398afc-09c5-45c9-bbc1-1d00f722b798',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '80-90K€',
    },

    # Riot Security — CSM Expansion Mid-Market France (Paris présentiel — contrainte forte)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager Expansion Mid-Market France',
        'Entreprise': 'Riot Security',
        'Source': 'jobs.lever.co / Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Très limité (2j/mois max)',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Riot Security (cybersécurité awareness, Y Combinator, 2000+ clients, 20→40M€ ARR en 2026). CSM Expansion Mid-Market France. Remote très limité = contrainte forte pour Gaëtan à Anglet. À noter uniquement si déplacement Paris hebdomadaire envisageable.',
        'Lien': 'https://jobs.lever.co/tryriot/5fa84b70-04be-4b8f-99fe-338a276a2b7e',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # Pennylane — CSM SaaS (mid-market PME, salaire probablement sous cible)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager SaaS',
        'Entreprise': 'Pennylane',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Paris (Saint Lazare)',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Pennylane (SaaS comptabilité PME France) — CSM déploiement, formation, adoption. Profil moins enterprise que la cible Gaëtan (PME vs. grands comptes) et salaire probablement sous cible. Bonne tech française mais fit partiel. Publié 24 juin 2026.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/pennylane/jobs/customer-success-manager-saas_paris_PENNY_dWlD9JV',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.html',
        'Prétention': '70-80K€',
    },

    # Adthena — CSM French Speaker (search intelligence IA — secteur éloigné)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Customer Success Manager (French Speaker)',
        'Entreprise': 'Adthena',
        'Source': 'AshbyHQ',
        'Contrat': 'CDI',
        'Localisation': 'Non précisée',
        'Remote': 'À vérifier',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Adthena (search intelligence IA, marché pub digitale). CSM French Speaker. Gaëtan n\'a pas d\'expérience SEM/SEA mais profil CSM enterprise + IA quotidienne peut compenser. Secteur media/marketing = éloigné de la cible SIRH/SaaS. À postuler si peu d\'autres options.',
        'Lien': 'https://jobs.ashbyhq.com/adthena/97e15863-1bc9-425a-9d2f-c642a052d927',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM_EN.html',
        'Prétention': '75-85K€',
    },

    # ── ONGLET OFFRES IA ────────────────────────────────────────────────────────

    # mission-freelances.fr — Consultant IA Générative & Conduite du changement (Paris)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant IA Générative & Conduite du changement',
        'Entreprise': 'Client non précisé (via mission-freelances.fr)',
        'Source': 'mission-freelances.fr',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'À préciser',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Mission déploiement et adoption outils IA générative — lien stratégie/équipes métier, ateliers sensibilisation, intégration IA dans workflows. Profil consultant expérimenté avec PO/change management recherché. Gaëtan : expérience PO startup + IA quotidienne + conduite du changement SIRH = fit fort.',
        'Lien': 'https://www.mission-freelances.fr/missions/consultant-ia-generative-conduite-du-changement-paris-87a17202/',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '600-750€/j',
    },

    # iQo — Consultant Intelligence Artificielle Sénior (CDI Paris)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Intelligence Artificielle Sénior',
        'Entreprise': 'iQo',
        'Source': 'Welcome to the Jungle',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'iQo (cabinet conseil impact B Corp, 5 ans) recrute un consultant senior IA — missions de stratégie IA, platformisation IA, programmes de transformation. Gaëtan peut se positionner sur le croisement IA + transformation RH/SIRH. Remote partiel = contrainte pour Anglet.',
        'Lien': 'https://www.welcometothejungle.com/fr/companies/iqo/jobs/consultant-senior-ia_paris_IQO_jXWlwra',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '80-90K€',
    },

    # Cherry Pick — Formateur IA / Évangélisation (550-600€/j, récurrent)
    {
        'Priorité': '⭐⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur IA et Évangélisation',
        'Entreprise': 'Cherry Pick',
        'Source': 'workdispo.com',
        'Contrat': 'Freelance',
        'Localisation': 'Paris',
        'Remote': 'Partiel (2j minimum remote)',
        'Salaire / TJM': '550-600€ HT/j',
        'Durée mission': 'Récurrent',
        'Fit / Notes': 'Cherry Pick recrute régulièrement des formateurs IA / évangélisateurs pour groupes industriels (Microsoft Copilot, chatbot interne, acculturation IA). Mission citée (mars 2026) potentiellement expirée — contacter Cherry Pick directement pour missions similaires. Profil Gaëtan = fit parfait.',
        'Lien': 'https://www.workdispo.com/job/formateur-ia-evangelisation',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '600-700€/j',
    },

    # Valeo — AI Adoption Leader / Intelligence Artificielle (publié ce matin !)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'AI Adoption Leader - Intelligence Artificielle',
        'Entreprise': 'Valeo',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'Paris',
        'Remote': 'Partiel',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Valeo (équipementier automobile mondial) recrute un AI Adoption Leader — acculturation, déploiement IA, conduite du changement. Publié ce matin (31/07/2026). Poste interne grand groupe = moins freelance-friendly mais valorise l\'expérience transformation digitale de Gaëtan.',
        'Lien': 'https://fr.linkedin.com/jobs/view/ai-adoption-leader-at-valeo',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '80-95K€',
    },

    # Formateur en Intelligence Artificielle — Groupe MDA (CDI France)
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Formateur en Intelligence Artificielle (F/H)',
        'Entreprise': 'Groupe MDA',
        'Source': 'LinkedIn',
        'Contrat': 'CDI',
        'Localisation': 'France',
        'Remote': 'Non précisé',
        'Salaire / TJM': '',
        'Durée mission': '',
        'Fit / Notes': 'Groupe MDA recrute un formateur IA en CDI — profil formateur terrain. Gaëtan peut valoriser ses compétences pédagogiques et son usage quotidien IA. Publié il y a 1 mois = probablement encore actif. Consulter site MDA directement pour détails.',
        'Lien': 'https://fr.linkedin.com/jobs/view/formateur-en-intelligence-artificielle-f-h-at-groupe-mda',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '55-70K€',
    },

    # YGL Consulting — Consultant Change Management & IA générative - Assurance IARD
    {
        'Priorité': '⭐⭐⭐',
        'Statut': '',
        'Fait': '',
        'Poste': 'Consultant Change Management & IA générative - Assurance IARD',
        'Entreprise': 'YGL Consulting',
        'Source': 'free-work.com',
        'Contrat': 'Freelance',
        'Localisation': 'Non précisée',
        'Remote': 'Non précisé',
        'Salaire / TJM': '600-700€/j',
        'Durée mission': '',
        'Fit / Notes': 'YGL Consulting recrute un consultant conduite du changement IA dans le secteur assurance IARD — profil assurance requis. Gaëtan n\'a pas d\'expérience assurance mais profil change management + IA générative peut être transférable. Posté le 30/07/2026.',
        'Lien': 'https://www.free-work.com/fr/tech-it/jobs/ia',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_IA.html',
        'Prétention': '650-700€/j',
    },

]

if __name__ == '__main__':
    ajouter_offres(offres, verbose=True)
    print("\nTerminé. Offres ajoutées dans offres_emploi.xlsx")
