"""
Relance de recherche complète du 26/08/2026 : 4 recherches parallèles
(boards FR/freelance, APIs ATS + éditeurs HRIS, boards remote/VC EU + niches,
recherche USA remote worldwide/EMEA).

Ordre d'insertion volontaire : USA d'abord, puis API ATS EMEA, puis boards
remote/VC EU, puis boards FR/freelance. Plusieurs offres (GitLab, Dataiku,
Remote.com, Ashby, Chainguard) ont été trouvées à la fois par le cluster USA
(avec Onglet='Offres USA' explicite, ces entreprises étant basées aux USA) et
par un cluster EMEA classique (sans ce marqueur). En les insérant dans cet
ordre, add_offre.py garde la première occurrence de chaque Lien identique et
ignore les suivantes : la version USA (correctement routée vers l'onglet
Offres USA) l'emporte donc sur la version EMEA dupliquée.

Exclusions décidées avant insertion (règle absolue du projet contre les liens
génériques) :
- "Solutions Engineer EMEA" Vapi/Omni : vérifiés Hybrid sur une ville précise
  malgré le titre EMEA, non retenus par l'agent lui-même (Priorité "-").
- Customer Success Manager chez Alguna (YC) : le lien trouvé pointe vers la
  page entreprise workatastartup.com, pas vers la fiche de poste individuelle.
"""

import json

import add_offre
from add_offre import ajouter_offres

D = '2026-08-26'

USA_JSON = r'''
[
  {"Poste":"Senior Product Manager, Remote Build","Entreprise":"Remote.com","Source":"API Greenhouse remotecom","Lien":"https://job-boards.greenhouse.io/remotecom/jobs/7331443003","Contrat":"CDI","Localisation":"Remote-France","Remote":"Oui (Remote-France explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éligibilité France certaine (mention explicite dans le champ location). Éditeur EOR, le mieux aligné du marché.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Account Manager - EMEA","Entreprise":"Remote.com","Source":"API Greenhouse remotecom","Lien":"https://job-boards.greenhouse.io/remotecom/jobs/7834363003","Contrat":"CDI","Localisation":"Remote-EMEA","Remote":"Oui (Remote-EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éligibilité forte : EMEA explicitement listé, Remote.com est lui-même un EOR global.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Workday Implementation Specialist","Entreprise":"Remote.com","Source":"API Greenhouse remotecom","Lien":"https://job-boards.greenhouse.io/remotecom/jobs/7635556003","Contrat":"CDI","Localisation":"Remote-EMEA","Remote":"Oui (Remote-EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Excellent fit HRIS/Workday. Éligibilité forte, EMEA explicite.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Product Manager, APIs","Entreprise":"Remote.com","Source":"API Greenhouse remotecom","Lien":"https://job-boards.greenhouse.io/remotecom/jobs/7831380003","Contrat":"CDI","Localisation":"Remote-EMEA","Remote":"Oui (Remote-EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éligibilité forte, EMEA explicite. Produit orienté API, légèrement technique.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Product Manager, Billing Platform","Entreprise":"Remote.com","Source":"API Greenhouse remotecom","Lien":"https://job-boards.greenhouse.io/remotecom/jobs/7885108003","Contrat":"CDI","Localisation":"Remote-EMEA","Remote":"Oui (Remote-EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éligibilité forte, EMEA explicite.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Product Manager, Contractor Management","Entreprise":"Remote.com","Source":"API Greenhouse remotecom","Lien":"https://job-boards.greenhouse.io/remotecom/jobs/7885031003","Contrat":"CDI","Localisation":"Remote-EMEA","Remote":"Oui (Remote-EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éligibilité forte, EMEA explicite.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Product Manager, Fraud and Compliance","Entreprise":"Remote.com","Source":"API Greenhouse remotecom","Lien":"https://job-boards.greenhouse.io/remotecom/jobs/7814948003","Contrat":"CDI","Localisation":"Remote-EMEA","Remote":"Oui (Remote-EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éligibilité forte, EMEA explicite.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Product Manager","Entreprise":"Remote.com","Source":"API Greenhouse remotecom","Lien":"https://job-boards.greenhouse.io/remotecom/jobs/7720367003","Contrat":"CDI","Localisation":"EMEA","Remote":"Oui (EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Poste générique, éligibilité forte EMEA.","Priorité":"⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Customer Success Architect, EMEA","Entreprise":"GitLab","Source":"API Greenhouse gitlab","Lien":"https://job-boards.greenhouse.io/gitlab/jobs/8561952002","Contrat":"CDI","Localisation":"Remote, Austria; Remote, France; Remote, Germany","Remote":"Oui (France explicitement listée)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Meilleure garantie possible : la France apparaît nommément dans la liste des pays éligibles.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Manager, Customer Success Managers, EMEA","Entreprise":"GitLab","Source":"API Greenhouse gitlab","Lien":"https://job-boards.greenhouse.io/gitlab/jobs/8613199002","Contrat":"CDI","Localisation":"Remote, Austria; Remote, Germany","Remote":"Oui - EMEA (France non listée nommément)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éligibilité internationale à confirmer : Autriche et Allemagne citées, pas la France, mais GitLab est une entreprise totalement distribuée en Europe.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Professional Services Project Manager (EMEA)","Entreprise":"GitLab","Source":"API Greenhouse gitlab","Lien":"https://job-boards.greenhouse.io/gitlab/jobs/8622433002","Contrat":"CDI","Localisation":"Remote (EMEA)","Remote":"Oui (EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Bon fit chef de projet déploiement client, EMEA explicite.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Professional Services Engineer","Entreprise":"GitLab","Source":"API Greenhouse gitlab","Lien":"https://job-boards.greenhouse.io/gitlab/jobs/8745623002","Contrat":"CDI","Localisation":"Remote, Italy; Remote, Netherlands; Remote, Spain","Remote":"Oui - Europe (France non listée nommément)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éligibilité internationale à confirmer : trois pays européens cités mais pas la France.","Priorité":"⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Product Manager – Business Applications","Entreprise":"Dataiku","Source":"API Greenhouse dataiku","Lien":"https://job-boards.greenhouse.io/dataiku/jobs/6122317004","Contrat":"CDI","Localisation":"France, Remote","Remote":"Oui (France explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éditeur IA authentique, France explicitement listée, meilleur niveau de garantie.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Sr Product Manager","Entreprise":"Dataiku","Source":"API Greenhouse dataiku","Lien":"https://job-boards.greenhouse.io/dataiku/jobs/5812604004","Contrat":"CDI","Localisation":"France, Remote (parmi de nombreux pays EMEA)","Remote":"Oui (France explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"France explicitement listée parmi les localisations éligibles.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Technical Account Manager - France","Entreprise":"Dataiku","Source":"API Greenhouse dataiku","Lien":"https://job-boards.greenhouse.io/dataiku/jobs/6148352004","Contrat":"CDI","Localisation":"France, Paris; France, Remote","Remote":"Oui (France explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Intitulé même du poste porte 'France'. Excellent fit TAM + éditeur IA.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Technical Account Manager - UK","Entreprise":"Dataiku","Source":"API Greenhouse dataiku","Lien":"https://job-boards.greenhouse.io/dataiku/jobs/6145018004","Contrat":"CDI","Localisation":"United Kingdom, Remote","Remote":"Oui - UK Remote (France non listée nommément)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Poste UK-remote chez un éditeur qui recrute par ailleurs explicitement en France ; éligibilité France à confirmer en entretien.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Manager of Dedicated Implementations - EMEA","Entreprise":"Ashby","Source":"API Ashby ashby","Lien":"https://jobs.ashbyhq.com/ashby/35a01a05-8efd-4bc3-a4bf-0a31d902102d","Contrat":"CDI","Localisation":"Remote - European Union","Remote":"Oui (UE explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Union Européenne explicitement citée, la France en fait partie.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Strategic Customer Success Manager - EMEA","Entreprise":"Ashby","Source":"API Ashby ashby","Lien":"https://jobs.ashbyhq.com/ashby/1cf7c730-caba-4fc3-8b98-52a0735ef14b","Contrat":"CDI","Localisation":"Remote - European Union","Remote":"Oui (UE explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Union Européenne explicitement citée.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Mid-Market Customer Success Manager - EMEA","Entreprise":"Ashby","Source":"API Ashby ashby","Lien":"https://jobs.ashbyhq.com/ashby/62d4f71e-f56c-447a-a965-a9c2ea8eac5e","Contrat":"CDI","Localisation":"Remote - European Union","Remote":"Oui (UE explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Union Européenne explicitement citée.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Pre-Sales Solutions Engineer - Europe","Entreprise":"Deepgram","Source":"API Ashby deepgram","Lien":"https://jobs.ashbyhq.com/deepgram/7ac1a5bc-f305-4f2a-a547-394566a549b2","Contrat":"CDI","Localisation":"EU | Remote","Remote":"Oui (UE explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éditeur IA vocale authentique, avant-vente technique, UE explicite.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Sales Engineer (remote, Europe)","Entreprise":"Checkly","Source":"API Ashby checkly","Lien":"https://jobs.ashbyhq.com/checkly/0dea9c4c-cecd-48d2-803a-56e3cfa1a873","Contrat":"CDI","Localisation":"Remote (UTC+1 to UTC+2)","Remote":"Oui (Europe explicite, fuseau compatible France)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Confirmé via HN Who's Hiring août 2026. Fuseau UTC+1/+2 correspond exactement à la France.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Technical Account Executive - EMEA","Entreprise":"PostHog","Source":"API Ashby posthog","Lien":"https://jobs.ashbyhq.com/posthog/f8af3807-3595-4580-a65c-dad2e268ace5","Contrat":"CDI","Localisation":"Remote","Remote":"Oui (EMEA explicite, confirmé GMT-8 à GMT+2 sur HN)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Corroboré par une annonce HN Who's Hiring (fuseau GMT-8 à GMT+2, couvre la France). Éditeur IA/analytics authentique.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Technical Customer Success Manager - EMEA","Entreprise":"PostHog","Source":"API Ashby posthog","Lien":"https://jobs.ashbyhq.com/posthog/0be1b52c-2401-4ae2-b7fc-5d018c1ff96f","Contrat":"CDI","Localisation":"Remote (EMEA)","Remote":"Oui (EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"EMEA explicite, excellent fit CSM technique.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Technical Account Manager - EMEA","Entreprise":"PostHog","Source":"API Ashby posthog","Lien":"https://jobs.ashbyhq.com/posthog/b42fd20b-b647-4f42-b725-b29ca472cba8","Contrat":"CDI","Localisation":"Remote (EMEA)","Remote":"Oui (EMEA explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"EMEA explicite, excellent fit TAM.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Enterprise Sales Engineer - France","Entreprise":"Chainguard","Source":"API Greenhouse chainguard","Lien":"https://job-boards.greenhouse.io/chainguard/jobs/4702184006","Contrat":"CDI","Localisation":"France - Remote","Remote":"Oui (France explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Meilleure garantie possible : intitulé et localisation portent tous deux 'France'.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Product Manager [IC4]","Entreprise":"Sourcegraph","Source":"API Greenhouse sourcegraph91","Lien":"https://job-boards.greenhouse.io/sourcegraph91/jobs/6113147004","Contrat":"CDI","Localisation":"Remote","Remote":"Oui - description dit explicitement 'we hire almost anywhere in the world', préférence EST/Europe","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Déclaration d'ouverture internationale la plus explicite trouvée ce jour. Poste PM orienté développeurs/IA agentique (SDK, code), lacune connue du profil à assumer honnêtement en lettre de motivation.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Partner Solutions Architect","Entreprise":"Elastic","Source":"API Greenhouse elastic","Lien":"https://jobs.elastic.co/jobs?gh_jid=7995008","Contrat":"CDI","Localisation":"France","Remote":"Oui (France explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"France explicitement listée. Rôle pre-sales technique via partenaires.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Forward Deployed Product Manager - AI Agent (EMEA)","Entreprise":"Cresta","Source":"API Greenhouse cresta","Lien":"https://job-boards.greenhouse.io/cresta/jobs/5068157008","Contrat":"CDI","Localisation":"United Kingdom (Remote)","Remote":"EMEA dans l'intitulé, mais localisation rattachée au Royaume-Uni : éligibilité France à confirmer","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Éditeur IA conversationnelle authentique. Base UK, pas de garantie France.","Priorité":"⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Product Manager - Marketplace","Entreprise":"Supabase","Source":"API Ashby supabase","Lien":"https://jobs.ashbyhq.com/supabase/23c9ce7e-6b7b-4316-8f00-8f318e902441","Contrat":"CDI","Localisation":"Remote, Anywhere","Remote":"Oui (Worldwide explicite, la mention la plus forte possible)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Meilleure trouvaille de la relance côté ouverture internationale ('Remote, Anywhere' littéral). Produit backend/développeurs (Postgres), lacune connue du profil sur les produits orientés dev.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Product Manager - Security & Trust (EMEA/AMER)","Entreprise":"Supabase","Source":"API Ashby supabase","Lien":"https://jobs.ashbyhq.com/supabase/b8010a28-109c-46a9-b8b7-c7f9b24077fa","Contrat":"CDI","Localisation":"Remote, Anywhere","Remote":"Oui (Worldwide explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"'Remote, Anywhere' explicite. Même lacune dev que ci-dessus, sujet trust/sécurité un peu moins technique.","Priorité":"⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Technical Account Management (TAM) Leader","Entreprise":"Supabase","Source":"API Ashby supabase","Lien":"https://jobs.ashbyhq.com/supabase/f52fd120-5fbe-4e0d-949d-01e217ec77d6","Contrat":"CDI","Localisation":"Remote, Anywhere","Remote":"Oui (Worldwide explicite)","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"'Remote, Anywhere' explicite. Rôle de management de la relation compte plutôt que produit pur, meilleur fit que les PM Supabase.","Priorité":"⭐⭐⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Implementation Engineer (EMEA)","Entreprise":"Docker","Source":"API Ashby docker","Lien":"https://jobs.ashbyhq.com/docker/7eb2fabc-f792-4e92-bd5f-50a646732163","Contrat":"CDI","Localisation":"England","Remote":"EMEA dans l'intitulé, localisation Angleterre : éligibilité France à confirmer","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Bon fit déploiement client, mais base UK sans garantie d'ouverture France.","Priorité":"⭐⭐⭐","Onglet":"Offres USA"},
  {"Poste":"Senior Technical Account Manager (EMEA)","Entreprise":"Docker","Source":"API Ashby docker","Lien":"https://jobs.ashbyhq.com/docker/de4dce34-7643-4c29-9113-230e7a591195","Contrat":"CDI","Localisation":"England","Remote":"EMEA dans l'intitulé, localisation Angleterre : éligibilité France à confirmer","Salaire / TJM":"N/C","Durée mission":"","Fit / Notes":"Bon fit TAM, base UK sans garantie d'ouverture France.","Priorité":"⭐⭐⭐","Onglet":"Offres USA"}
]
'''

ATS_JSON = r'''
[
  {"Poste":"Customer Success Manager - Medium Accounts","Entreprise":"Pennylane","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/pennylane/d9c454b4-11ab-49f3-9ffe-4b444aecb99d","Contrat":"CDI","Localisation":"France","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Éditeur FinTech FR déjà bon filon récurrent, CSM medium accounts","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Customer Success Manager - SAAS","Entreprise":"Pennylane","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/pennylane/9f24fb70-d2bb-496f-9ed3-02bb9c9d7ad0","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Full remote France explicite","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Strategic Account Manager","Entreprise":"Siena AI","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/siena/6335ebaf-54e2-49ae-bc50-4a686de55d9e","Contrat":"CDI","Localisation":"Remote - Europe (+ villes US)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Startup IA service client, AM stratégique remote Europe","Priorité":"⭐⭐⭐"},
  {"Poste":"Principal Product Manager - Time to First Production","Entreprise":"Camunda","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/camunda/7f97e255-53a0-4a8a-a7e3-92b1ed9da743","Contrat":"CDI","Localisation":"Remote EMEA","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Éditeur plateforme B2B technique, PM senior EMEA","Priorité":"⭐⭐⭐"},
  {"Poste":"Customer Success Lead - Western Europe","Entreprise":"ElevenLabs","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/elevenlabs/0dbfbe3e-7218-4045-ba78-28b0d2e5ab6d","Contrat":"CDI","Localisation":"Allemagne / France","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"IA générative, CS Lead Europe de l'Ouest, France explicite","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Enterprise Deployment - Chief of Staff","Entreprise":"ElevenLabs","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/elevenlabs/a0389dc2-77d8-439b-960b-2acb8712991e","Contrat":"CDI","Localisation":"Multi-pays dont France","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Chief of Staff, valorise le statut de co-fondateur WallOfTraders.com","Priorité":"⭐⭐⭐"},
  {"Poste":"Enterprise Solutions Engineer - EMEA","Entreprise":"Dash0","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/dash0/d7fa3468-1e5c-4109-bdcf-0fa0f2f9c15b","Contrat":"CDI","Localisation":"EMEA - Remote","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Observability startup, SE EMEA remote large","Priorité":"⭐⭐⭐"},
  {"Poste":"Regional Manager, Customer Success EMEA","Entreprise":"Constructor","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/constructor/5f24d378-f17b-4032-a2cc-079fd670563d","Contrat":"CDI","Localisation":"Remote - France / Espagne / Portugal","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Éditeur déjà excellent fit récurrent, management CS EMEA avec option France","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Senior Product Manager - Merchant Intelligence and Analytics","Entreprise":"Constructor","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/constructor/e7426b59-431b-418b-a501-dde7f13b21bf","Contrat":"CDI","Localisation":"Remote - EMEA","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Plateforme B2B technique, PM EMEA","Priorité":"⭐⭐⭐"},
  {"Poste":"Senior Product Manager: Recall","Entreprise":"Constructor","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/constructor/7bc86d05-145d-4b7c-aa6e-b0b207d46117","Contrat":"CDI","Localisation":"Remote - EMEA","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"PM EMEA, même éditeur","Priorité":"⭐⭐⭐"},
  {"Poste":"Account Manager, DACH","Entreprise":"Constructor","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/constructor/776e4870-92d3-40d4-b2ea-c530537cd616","Contrat":"CDI","Localisation":"Remote - EMEA","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"AM EMEA remote large malgré intitulé DACH","Priorité":"⭐⭐⭐"},
  {"Poste":"Senior Product Manager - EMEA - Remote","Entreprise":"Pencil","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/pencil/e4bbf9ae-0be6-455f-8b24-f960be4c6f2c","Contrat":"CDI","Localisation":"Europe","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Filon déjà confirmé excellent fit (note du 21/08), toujours ouvert","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Lead Product Manager - Editor - EMEA","Entreprise":"Pencil","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/pencil/765370fa-a2b2-487f-af2e-73a53cd1bad6","Contrat":"CDI","Localisation":"EMEA","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Même éditeur, poste lead product","Priorité":"⭐⭐⭐"},
  {"Poste":"Strategic Customer Success Manager - EMEA","Entreprise":"Ashby","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/ashby/1cf7c730-caba-4fc3-8b98-52a0735ef14b","Contrat":"CDI","Localisation":"Remote - Union Européenne","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"CSM stratégique EMEA, éditeur ATS lui-même","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Mid-Market Customer Success Manager - EMEA","Entreprise":"Ashby","Source":"Ashby","Lien":"https://jobs.ashbyhq.com/ashby/62d4f71e-f56c-447a-a965-a9c2ea8eac5e","Contrat":"CDI","Localisation":"Remote - Union Européenne","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"CSM mid-market EMEA","Priorité":"⭐⭐⭐"},
  {"Poste":"Implementation Consultant - Commercial (Remote or Onsite)","Entreprise":"Veeva Systems","Source":"Lever","Lien":"https://jobs.lever.co/veeva/f4c4c9f0-4bba-4800-91b5-7dbd61208ac1","Contrat":"CDI","Localisation":"France - Paris","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Implementation Consultant France, vertical pharma nouveau mais expérience déploiement transférable","Priorité":"⭐⭐⭐"},
  {"Poste":"Account Manager, DACH","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/5a447c58-50d3-4cb3-934b-31d4e3e66f0a","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Republication Jobgether filtrée France","Priorité":"⭐⭐⭐"},
  {"Poste":"Banking Onboarding Manager","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/f1c0f557-3287-4c17-9ce0-ee59e425ff67","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Onboarding Manager, fintech","Priorité":"⭐⭐⭐"},
  {"Poste":"Client Account Manager","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/142d6d42-7f21-4b38-a696-532591fc9e02","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Account Manager généraliste France remote","Priorité":"⭐⭐⭐"},
  {"Poste":"Director of Customer Success","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/188b3da3-6e29-455f-af5e-a2e7a62aee4b","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Poste de direction CS, valorise l'expérience 0→1 fondateur","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"GTM Product Manager - Marketing Operations","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/d6b44fb8-26e0-4ca3-be80-40a5519e00bf","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"PM GTM/marketing ops","Priorité":"⭐⭐⭐"},
  {"Poste":"Product Manager (Internal HRIS / HR Tech)","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/c47e031c-99f7-4fb6-aff9-36d2d7f3593e","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Croisement PM + HRIS interne, excellent fit direct","Priorité":"⭐⭐⭐⭐⭐"},
  {"Poste":"Product Manager (Senior/Staff-level)","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/2ff29dcf-3553-4f81-9eb1-04b55d085a58","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"PM senior générique France remote","Priorité":"⭐⭐⭐"},
  {"Poste":"Product Owner","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/bed53c98-5b74-4c55-8ee3-0dd12d4c7b77","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Product Owner générique France remote","Priorité":"⭐⭐⭐"},
  {"Poste":"Project / Product Manager — PSP & Payment Integrations","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/589d954d-3487-4e5d-81d3-f795ed26ef47","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"PM intégrations paiement","Priorité":"⭐⭐⭐"},
  {"Poste":"Senior Implementation Engineer","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/56ee30cd-122a-4fc2-aed4-cdc6c83f6597","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Implementation Engineer senior","Priorité":"⭐⭐⭐"},
  {"Poste":"Senior Product Manager, Funnels/Workflow","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/61e08264-4aba-471e-9ad8-0fb6ccac3b85","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"PM produit funnel/workflow","Priorité":"⭐⭐⭐"},
  {"Poste":"Solutions Architect","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/157f84c2-e482-4b48-878b-7b87e894546c","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Solutions Architect France remote","Priorité":"⭐⭐⭐"},
  {"Poste":"Solutions Architecture Senior Manager","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/3feb57e5-02f8-416f-bb37-bb43ed2c1eb7","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Poste de management solutions architecture","Priorité":"⭐⭐⭐"},
  {"Poste":"Solutions Engineer","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/9f9eb428-fa95-459d-b11c-a4f3e2e0ce4a","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Solutions Engineer France remote","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Technical Account Manager","Entreprise":"Jobgether (client anonymisé)","Source":"Lever","Lien":"https://jobs.lever.co/jobgether/715dbfc2-1967-4375-b953-0f70303480c6","Contrat":"CDI","Localisation":"France (remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"TAM France remote","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Senior Account Manager","Entreprise":"Superside","Source":"Lever","Lien":"https://jobs.lever.co/superside/9951089c-3c7a-4d18-bd90-594b31c6cd3a","Contrat":"CDI","Localisation":"Global","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Éditeur creative-as-a-service, remote Global explicite","Priorité":"⭐⭐⭐"},
  {"Poste":"Solutions Engineer | France | Remote","Entreprise":"Grafana Labs","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/grafanalabs/jobs/6121627004","Contrat":"CDI","Localisation":"France (Remote)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"France remote explicite, observability/monitoring éditeur solide","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Customer Success Engineer","Entreprise":"Hightouch","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/hightouch/jobs/5770046004","Contrat":"CDI","Localisation":"Remote (Europe)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Data activation éditeur, CS Engineer Europe remote","Priorité":"⭐⭐⭐"},
  {"Poste":"Product Manager – Business Applications","Entreprise":"Dataiku","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/dataiku/jobs/6122317004","Contrat":"CDI","Localisation":"France, Remote","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Éditeur IA authentique, France explicite","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Sr Product Manager","Entreprise":"Dataiku","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/dataiku/jobs/5812604004","Contrat":"CDI","Localisation":"France, Remote (+ autres pays EMEA)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"PM senior France remote","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Technical Account Manager - France","Entreprise":"Dataiku","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/dataiku/jobs/6148352004","Contrat":"CDI","Localisation":"France, Paris / Remote","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"TAM + IA + France explicite, combinaison rare et très solide","Priorité":"⭐⭐⭐⭐⭐"},
  {"Poste":"Customer Success Architect, EMEA","Entreprise":"GitLab","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/gitlab/jobs/8561952002","Contrat":"CDI","Localisation":"Remote, Autriche / France / Allemagne","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"France explicitement listée, déjà bon filon GitLab confirmé","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Solutions Architect - France","Entreprise":"GitLab","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/gitlab/jobs/8656506002","Contrat":"CDI","Localisation":"Remote, France","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"France remote explicite","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Enterprise Customer Success Manager (French speaker)","Entreprise":"Canonical","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/canonical/jobs/7084000","Contrat":"CDI","Localisation":"Home based - EMEA","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Nouveau slug testé ce jour ; CSM francophone, très bon fit","Priorité":"⭐⭐⭐⭐⭐"},
  {"Poste":"Enterprise Customer Success Manager","Entreprise":"Canonical","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/canonical/jobs/6856788","Contrat":"CDI","Localisation":"Home based - Worldwide","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"CSM Entreprise remote worldwide","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Manager, Product Manager","Entreprise":"Canonical","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/canonical/jobs/6458166","Contrat":"CDI","Localisation":"Home based - EMEA","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Management PM + EMEA remote","Priorité":"⭐⭐⭐"},
  {"Poste":"Product Manager","Entreprise":"Canonical","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/canonical/jobs/5029257","Contrat":"CDI","Localisation":"Home based - EMEA","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"PM générique EMEA","Priorité":"⭐⭐⭐"},
  {"Poste":"Cloud Professional Services Manager","Entreprise":"Canonical","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/canonical/jobs/6283017","Contrat":"CDI","Localisation":"Home based - Worldwide","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Professional Services management, fit direct avec le parcours déploiement client","Priorité":"⭐⭐⭐"},
  {"Poste":"Account Manager, EMEA","Entreprise":"Customer.io","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/customerio/jobs/7915379","Contrat":"CDI","Localisation":"EMEA Remote","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"AM EMEA remote","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Customer Success Manager, EMEA","Entreprise":"Customer.io","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/customerio/jobs/8089365","Contrat":"CDI","Localisation":"EMEA Remote","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"CSM EMEA remote","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Sr Account Manager, EMEA","Entreprise":"Customer.io","Source":"Greenhouse","Lien":"https://job-boards.greenhouse.io/customerio/jobs/8121617","Contrat":"CDI","Localisation":"EMEA Remote","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"AM senior EMEA remote","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Account Manager, Strategic - France","Entreprise":"Atlassian","Source":"API carrières Atlassian","Lien":"https://globalcareers-atlassian.icims.com/jobs/25256/account-manager%2c-strategic---france/job","Contrat":"CDI","Localisation":"Remote - France","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Lien vérifié vivant (HTTP 200) ce jour ; France remote nommée","Priorité":"⭐⭐⭐⭐⭐"},
  {"Poste":"Principal Customer Success Manager, Strategic DACH","Entreprise":"Atlassian","Source":"API carrières Atlassian","Lien":"https://globalcareers-atlassian.icims.com/jobs/26063/principal-customer-success-manager%2c-strategic-dach/job","Contrat":"CDI","Localisation":"Remote Allemagne/Pays-Bas/Pologne/UK/France","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"France listée parmi les localisations remote éligibles","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Principal Customer Success Manager, Strategic, France","Entreprise":"Atlassian","Source":"API carrières Atlassian","Lien":"https://globalcareers-atlassian.icims.com/jobs/26057/principal-customer-success-manager%2c-strategic%2c-france/job","Contrat":"CDI","Localisation":"Remote - France (+ Paris)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Poste explicitement France, filon Atlassian confirmé à chaque relance","Priorité":"⭐⭐⭐⭐⭐"},
  {"Poste":"Senior Principal Customer Success Manager, Strategic - France","Entreprise":"Atlassian","Source":"API carrières Atlassian","Lien":"https://globalcareers-atlassian.icims.com/jobs/26241/senior-principal-customer-success-manager%2c-strategic---france/job","Contrat":"CDI","Localisation":"Remote - France (+ Paris)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Niveau senior principal, France explicite","Priorité":"⭐⭐⭐⭐⭐"},
  {"Poste":"Senior Services Solutions Advocate","Entreprise":"Atlassian","Source":"API carrières Atlassian","Lien":"https://globalcareers-atlassian.icims.com/jobs/26249/senior-services-solutions-advocate/job","Contrat":"CDI","Localisation":"Paris / Remote - France","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Solutions Advocate, France explicite","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Consultant SAP SuccessFactors (H/F)","Entreprise":"HR Path","Source":"jobs.hr-path.com","Lien":"https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SAP-SuccessFactors-%28HF%29-75-92042/818651901/","Contrat":"CDI","Localisation":"Paris La Défense","Remote":"Oui (télétravail confirmé, déplacements ponctuels)","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Fit direct SAP SuccessFactors, télétravail confirmé par fetch direct de la fiche","Priorité":"⭐⭐⭐⭐⭐"},
  {"Poste":"Consultant SIRH (H/F) | Workday • Oracle HCM • SAP SuccessFactors","Entreprise":"HR Path","Source":"jobs.hr-path.com","Lien":"https://jobs.hr-path.com/job/Paris-La-D%C3%A9fense-Cedex-Consultant-SIRH-%28HF%29-Workday-%E2%80%A2-Oracle-HCM-%E2%80%A2-SAP-SuccessFactors-75-92042/1419350533/","Contrat":"CDI","Localisation":"Paris La Défense (mobilité Lyon/Lille)","Remote":"Hybride (télétravail partiel mentionné)","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"Fiche mentionne 'possibilités de télétravail' sans confirmer total","Priorité":"⭐⭐⭐"},
  {"Poste":"Senior SAP Payroll Consultant, Belgium Payroll","Entreprise":"Strada (ex-Alight/NGA)","Source":"API Workday CXS Strada","Lien":"https://strada.wd12.myworkdayjobs.com/en-US/Careers/job/BE-Belgium-Virtual_40/Senior-SAP-Payroll-Consultant--Belgium-Payroll_R-3762","Contrat":"CDI","Localisation":"Belgique/France/Pays-Bas (virtuel)","Remote":"Oui","Salaire / TJM":"N/C","Durée mission":"N/C","Fit / Notes":"France listée parmi les 3 localisations éligibles ; Strada a migré vers Workday, ancien lien Alight mort","Priorité":"⭐⭐⭐"}
]
'''

EU_JSON = r'''
[
  {"Poste":"Senior Regional Customer Success Manager, EMEA (Portugal)","Entreprise":"Spring Health","Source":"euremotejobs.com","Lien":"https://euremotejobs.com/job/senior-regional-customer-success-manager-emea-portugal/","Contrat":"CDI","Localisation":"EMEA / Portugal","Remote":"Oui (avec déplacements ponctuels)","Salaire / TJM":"45 600 - 52 440 EUR/an","Durée mission":"","Fit / Notes":"Fully remote avec voyages locaux/internationaux occasionnels. Portefeuille 30+ comptes EMEA, cohérent avec le profil CSM senior.","Priorité":"⭐⭐⭐"}
]
'''

FR_JSON = r'''
[
  {"Poste":"Consultant Expert Paie CEGEDIM / Team RH - Migration SIRH","Entreprise":"Orviden","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/consultant-expert-paie-cegedim-team-rh-migration-sirh","Contrat":"Freelance/Mission","Localisation":"Toulouse","Remote":"Non précisé","Salaire / TJM":"400-520€/j","Durée mission":"Non précisée","Fit / Notes":"Migration SIRH côté paie, cohérent avec l'expérience de migration de données SAP HR.","Priorité":"⭐⭐⭐"},
  {"Poste":"Expert GTA - Horoquartz (H/F)","Entreprise":"Mindquest","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-gta-horoquartz-h-f","Contrat":"Freelance/Mission","Localisation":"Aix-en-Provence","Remote":"Non précisé","Salaire / TJM":"480-500€/j","Durée mission":"Non précisée","Fit / Notes":"GTA = brique SIRH connexe, moins central mais dans le périmètre.","Priorité":"⭐⭐"},
  {"Poste":"Manager SIRH","Entreprise":"HR DNA","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/manager-sirh-11","Contrat":"CDI","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"60-110k€/an","Durée mission":"","Fit / Notes":"Poste de management SIRH en CDI, correspond au profil chef de projet SIRH senior.","Priorité":"⭐⭐⭐"},
  {"Poste":"Chef de projet IT / Responsable SIRH (H/F)","Entreprise":"LeHibou","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/chef-de-projet-it-responsable-sirh-h-f","Contrat":"Freelance/Mission","Localisation":"Bordeaux","Remote":"Non précisé","Salaire / TJM":"675€/j","Durée mission":"Non précisée","Fit / Notes":"Chef de projet SIRH, bon TJM, LeHibou historiquement fiable.","Priorité":"⭐⭐⭐"},
  {"Poste":"Chargé de missions SIRH N2 - Workday HCM (H/F)","Entreprise":"HR DNA","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/charge-de-missions-sirh-n2-workday-hcm-h-f-25","Contrat":"Freelance/Mission","Localisation":"Neuilly-sur-Marne","Remote":"Non précisé","Salaire / TJM":"250-500€/j","Durée mission":"Non précisée","Fit / Notes":"Workday HCM, élargit le spectre HRIS au-delà de SAP.","Priorité":"⭐⭐⭐"},
  {"Poste":"Product Manager / Owner SIRH (H/F)","Entreprise":"Lùkla","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/product-manager-owner-sirh-h-f","Contrat":"Freelance/Mission","Localisation":"Rouen","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Croisement Product Manager + SIRH, exactement le profil recherché.","Priorité":"⭐⭐⭐"},
  {"Poste":"Gestionnaire d'Application SIRH","Entreprise":"Montreal Associates","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/gestionnaire-dapplication-sirh","Contrat":"Freelance/Mission","Localisation":"Bretagne","Remote":"Non précisé","Salaire / TJM":"400-600€/j","Durée mission":"Non précisée","Fit / Notes":"Gestion applicative SIRH, fit correct.","Priorité":"⭐⭐"},
  {"Poste":"Adjoint(e) Responsable Paie (H/F)","Entreprise":"HR Path","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/directeur-de-la-data-cdo/adjoint-e-responsable-paie-h-f","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"650-700€/j","Durée mission":"Non précisée","Fit / Notes":"HR Path, bon TJM, mais orienté paie pure plutôt que SAP HCM/SF.","Priorité":"⭐⭐"},
  {"Poste":"Senior Consultant Transformation RH (Target Operating Model / Core HR)","Entreprise":"Mon Consultant Indépendant","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant/senior-consultant-transformation-rh-target-operating-model-core-hr-1","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"500-550€/j","Durée mission":"Non précisée","Fit / Notes":"Transformation RH / Core HR / Target Operating Model, correspond très bien à l'expérience L'Oréal 40+ pays.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Consultant Transformation RH - Core HR","Entreprise":"VISIAN","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant/consultant-transformation-rh-core-hr","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Même thématique Core HR, probablement la même mission recroisée.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Chef de Projet SIRH (H/F)","Entreprise":"HAYS France","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/autre/chef-de-projet-sirh-h-f-79","Contrat":"Freelance/Mission","Localisation":"Bordeaux","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Chef de projet SIRH classique.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant SAP SuccessFactors CoreHR (H/F)","Entreprise":"HR Path","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-corehr-h-f","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"450-600€/j","Durée mission":"Non précisée","Fit / Notes":"SuccessFactors CoreHR pur, très bon match avec 14 ans SAP HR.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Référent Paie SIRH H/F","Entreprise":"Mindquest","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/referent-paie-sirh-h-f-13","Contrat":"Freelance/Mission","Localisation":"Aix-en-Provence","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Paie SIRH, fit modéré.","Priorité":"⭐⭐"},
  {"Poste":"Product Manager SIRH / Chef de Projet SIRH (Oracle HCM) (H/F)","Entreprise":"Freelance.com","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-de-base-de-donnee-oracle-sybase/product-manager-sirh-chef-de-projet-sirh-oracle-hcm-h-f","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Croisement PM + SIRH + Oracle HCM.","Priorité":"⭐⭐⭐"},
  {"Poste":"Chef de projet MOE SIRH H/F","Entreprise":"HAYS France","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/chef-de-projet-moe-sirh-h-f-1","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Chef de projet SIRH côté MOE.","Priorité":"⭐⭐⭐"},
  {"Poste":"Product Manager SIRH","Entreprise":"Signe +","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/product-manager-sirh-2","Contrat":"Freelance/Mission","Localisation":"Rouen","Remote":"Non précisé","Salaire / TJM":"400-470€/j","Durée mission":"Non précisée","Fit / Notes":"PM SIRH, bon croisement de compétences.","Priorité":"⭐⭐⭐"},
  {"Poste":"Senior Consultant Transformation RH (Target Operating Model / Core HR)","Entreprise":"NOVAMINDS","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant/senior-consultant-transformation-rh-target-operating-model-core-hr","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"650€/j","Durée mission":"Non précisée","Fit / Notes":"Même thématique très alignée transformation RH/Core HR global.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Product Manager SIRH","Entreprise":"MLMCONSEIL","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/product-manager-sirh-1","Contrat":"Freelance/Mission","Localisation":"Rouen","Remote":"Non précisé","Salaire / TJM":"100-470€/j","Durée mission":"Non précisée","Fit / Notes":"PM SIRH, probablement recoupement avec les missions Signe+.","Priorité":"⭐⭐⭐"},
  {"Poste":"SAP PMO Successfactors (H/F)","Entreprise":"Mindquest","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/sap-pmo-successfactors-h-f-75","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"PMO SuccessFactors, bon fit gestion de projet SAP HR.","Priorité":"⭐⭐⭐"},
  {"Poste":"Business Analyst PeopleDoc (UKG)","Entreprise":"HN SERVICES","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/business-analyst/business-analyst-peopledoc-ukg","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"40-45k€/an","Durée mission":"Non précisée","Fit / Notes":"SIRH adjacent (PeopleDoc/UKG), business analyst.","Priorité":"⭐⭐"},
  {"Poste":"AMOA RH","Entreprise":"CAT-AMANIA","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-moa-amoa/amoa-rh-2","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"53-55k€/an","Durée mission":"Non précisée","Fit / Notes":"AMOA RH, correspond au profil MOA/Business Analyst SIRH ciblé.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant Workday","Entreprise":"ARENA SI","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant/consultant-workday-15","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Workday, élargit le vivier HRIS hors SAP.","Priorité":"⭐⭐⭐"},
  {"Poste":"PMO SIRH H/F","Entreprise":"HAYS France","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/pmo-sirh-h-f","Contrat":"Freelance/Mission","Localisation":"Guyancourt","Remote":"Non précisé","Salaire / TJM":"450-540€/j","Durée mission":"Non précisée","Fit / Notes":"PMO SIRH, fit correct.","Priorité":"⭐⭐⭐"},
  {"Poste":"Business Analyste SIRH H/F","Entreprise":"DCS EASYWARE","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/business-analyste-sirh-h-f","Contrat":"Freelance/Mission","Localisation":"Orvault","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Business analyst SIRH.","Priorité":"⭐⭐"},
  {"Poste":"CONSULTANT SIRH HR ACCESS V9 EXPERT (GA/Paie)","Entreprise":"Savane Consulting","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/consultant-sirh-hr-access-v9-expert-ga-paie-h-f","Contrat":"CDI","Localisation":"Nanterre","Remote":"Non précisé","Salaire / TJM":"45-55k€/an","Durée mission":"","Fit / Notes":"HR Access expert, SIRH legacy connu du marché français.","Priorité":"⭐⭐⭐"},
  {"Poste":"Chef de Projet / Gestionnaire Application SIRH Senior","Entreprise":"ARGANA CONSULTING CORP LLP","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/chef-de-projet-gestionnaire-application-sirh-senior","Contrat":"Freelance/Mission","Localisation":"Bruz","Remote":"Non précisé","Salaire / TJM":"400-470€/j","Durée mission":"Non précisée","Fit / Notes":"Chef de projet SIRH senior.","Priorité":"⭐⭐⭐"},
  {"Poste":"SAP SuccessFactors Senior/Lead Consultant (Permanent)","Entreprise":"INVESTIGO","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/sap-successfactors-senior-lead-consultant-permanent-ps80-000-ps90-000-per-annum-benefits","Contrat":"CDI","Localisation":"England, Royaume-Uni","Remote":"Non précisé","Salaire / TJM":"£80,000-£90,000/an","Durée mission":"","Fit / Notes":"SuccessFactors senior/lead, end-to-end implementations ; éligibilité remote depuis la France à confirmer, poste UK.","Priorité":"⭐⭐⭐"},
  {"Poste":"SAP SuccessFactors Consultant (M/F)","Entreprise":"Mindquest","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/sap-successfactors-consultant-m-f","Contrat":"Freelance/Mission","Localisation":"Pays-Bas","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"SuccessFactors, mais localisation Pays-Bas sans mention remote.","Priorité":"⭐⭐"},
  {"Poste":"Expert SAP SuccessFactors","Entreprise":"LeHibou","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/expert-sap-successfactors-1","Contrat":"Freelance/Mission","Localisation":"Saint-Ouen-sur-Seine","Remote":"Non précisé","Salaire / TJM":"575€/j","Durée mission":"Non précisée","Fit / Notes":"Expert SF, très bon fit direct.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Consultant SAP SuccessFactors Onboarding (ONB)","Entreprise":"LINKWAY","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-onboarding-onb","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"400€/j","Durée mission":"Non précisée","Fit / Notes":"Module SF Onboarding.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant SAP SuccessFactors LMS","Entreprise":"LINKWAY","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-learning-management-system-lms","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"400€/j","Durée mission":"Non précisée","Fit / Notes":"Module SF LMS.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant SAP SuccessFactors PMGM","Entreprise":"LINKWAY","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-performance-goal-management-pmgm","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"400€/j","Durée mission":"Non précisée","Fit / Notes":"Module SF PMGM.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant SAP SuccessFactors Recruitment (RCM)","Entreprise":"LINKWAY","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-recruitment-rcm","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"400€/j","Durée mission":"Non précisée","Fit / Notes":"Module SF RCM.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant SAP SuccessFactors Succession Planning (SP)","Entreprise":"LINKWAY","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactors-succession-planning-sp","Contrat":"Freelance/Mission","Localisation":"La Défense","Remote":"Non précisé","Salaire / TJM":"400€/j","Durée mission":"Non précisée","Fit / Notes":"Module SF SP.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant SAP SuccessFactors","Entreprise":"Intuition IT Solutions","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/consultant-sap-successfactor-2","Contrat":"Freelance/Mission","Localisation":"Versailles","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Consultant SF générique.","Priorité":"⭐⭐⭐"},
  {"Poste":"Key User - SAP SuccessFactors","Entreprise":"CRYSTAL PLACEMENT","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/key-user-sap-successfactors","Contrat":"Freelance/Mission","Localisation":"Bruxelles, Belgique","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Poste Key User moins senior, localisation Belgique.","Priorité":"⭐⭐"},
  {"Poste":"Product Owner Solutions IA H/F","Entreprise":"DAVRICOURT","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/product-owner/product-owner-solutions-ia-h-f-6","Contrat":"CDI","Localisation":"Lille","Remote":"Non précisé","Salaire / TJM":"45-50k€/an","Durée mission":"","Fit / Notes":"Product Owner sur solutions IA, croisement PM x IA.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant IA Générative & Solutions Agentiques","Entreprise":"LeHibou","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/architecte-solutions/consultant-ia-generative-solutions-agentiques","Contrat":"Freelance/Mission","Localisation":"Levallois-Perret","Remote":"Non précisé","Salaire / TJM":"550€/j","Durée mission":"6 mois","Fit / Notes":"Consultant IA générative, cœur de cible formateur/conduite du changement IA.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Consultant IA Générative / Claude (Anthropic)","Entreprise":"SMARTPOINT","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/consultant/consultant-ia-generative-claude-anthropic","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"40-60k€/an ou 500-600€/j","Durée mission":"Non précisée","Fit / Notes":"Mission centrée sur Claude (Anthropic), usage quotidien d'outils IA générative par Gaëtan, excellent alignement.","Priorité":"⭐⭐⭐⭐⭐"},
  {"Poste":"Expert IA Générative - Agents IA, Copilot et Industrialisation","Entreprise":"AVA2I","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-ia-generative-agents-ia-copilot-et-industrialisation","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Peut être trop technique (industrialisation d'agents) ; à vérifier avant candidature.","Priorité":"⭐⭐"},
  {"Poste":"Expert IA générative et Plateforme IA H/F","Entreprise":"Freelance.com","Source":"free-work.com","Lien":"https://www.free-work.com/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-ia-generative-et-plateforme-ia-h-f","Contrat":"Freelance/Mission","Localisation":"Île-de-France","Remote":"Non précisé","Salaire / TJM":"510-590€/j","Durée mission":"Non précisée","Fit / Notes":"Plateforme IA, niveau de technicité à clarifier.","Priorité":"⭐⭐⭐"},
  {"Poste":"Chef de projet SIRH confirmé","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-confirme-114018-de","Contrat":"Freelance/Mission","Localisation":"Gonesse (95)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Chef de projet SIRH confirmé, fit direct.","Priorité":"⭐⭐⭐"},
  {"Poste":"AMOA SIRH DATA","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-amoa-sirh-data-sur-paris-113689-de","Contrat":"Freelance/Mission","Localisation":"Courbevoie (92)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"6 mois renouvelables","Fit / Notes":"AMOA SIRH orienté data, bon fit MOA/Business Analyst.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant SIRH","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-consultant-sirh-113215-de","Contrat":"Freelance/Mission","Localisation":"Marseille (13001)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"22 mois renouvelables","Fit / Notes":"Consultant SIRH généraliste, longue mission.","Priorité":"⭐⭐⭐"},
  {"Poste":"Chef de projet SIRH WorkDay (Certification Obligatoire)","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-workday-certification-obligatoire-110752-de","Contrat":"Freelance/Mission","Localisation":"Marne-la-Vallée (77)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"12 mois","Fit / Notes":"Workday, exige certification (à vérifier si Gaëtan la détient).","Priorité":"⭐⭐"},
  {"Poste":"Chef de projet fonctionnel SIRH","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-110424-de","Contrat":"Freelance/Mission","Localisation":"Non précisée","Remote":"Oui (Télétravail confirmé dans le titre)","Salaire / TJM":"Non précisé","Durée mission":"6 mois renouvelables","Fit / Notes":"Télétravail confirmé, chef de projet fonctionnel SIRH, très bon match.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Chef de projet transverse SIRH (La Défense et remote)","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-transverse-sirh-defense-et-remote-105678-de","Contrat":"Freelance/Mission","Localisation":"La Défense","Remote":"À vérifier (titre ambigu, potentiellement hybride)","Salaire / TJM":"Non précisé","Durée mission":"3 mois renouvelables","Fit / Notes":"Chef de projet transverse SIRH ; vérifier si le remote est total ou partiel avant de candidater.","Priorité":"⭐⭐"},
  {"Poste":"Product Owner/Chef de projet SIRH (F/H)","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-product-owner-chef-de-projet-sirh-f-h-104881-de","Contrat":"Freelance/Mission","Localisation":"Grenoble (38000)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"6 mois","Fit / Notes":"Croisement PO + SIRH.","Priorité":"⭐⭐⭐"},
  {"Poste":"Chef de Projet SIRH","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-sur-paris-101573-de","Contrat":"Freelance/Mission","Localisation":"Paris (75)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"12 mois renouvelables","Fit / Notes":"Chef de projet SIRH classique.","Priorité":"⭐⭐"},
  {"Poste":"Chef de Projet SIRH","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-sur-bordeaux-99971-de","Contrat":"Freelance/Mission","Localisation":"Bordeaux (33)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"3 mois renouvelables","Fit / Notes":"Chef de projet SIRH classique.","Priorité":"⭐⭐"},
  {"Poste":"Chef de projet MOE / Expert GTA","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-moe-expert-gta-112667-de","Contrat":"Freelance/Mission","Localisation":"Paris (75012)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"36 mois","Fit / Notes":"MOE + GTA, mission très longue.","Priorité":"⭐⭐"},
  {"Poste":"Consultant AMOA SIRH","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-consultant-amoa-sirh-paris-112194-de","Contrat":"Freelance/Mission","Localisation":"Paris (75000)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"12 mois renouvelables","Fit / Notes":"AMOA SIRH, bon fit MOA.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant SIRH / Support ERP & PAIE","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-consultant-sirh-support-erp-paie-105111-de","Contrat":"Freelance/Mission","Localisation":"Non précisée","Remote":"Oui (Télétravail confirmé dans le titre)","Salaire / TJM":"Non précisé","Durée mission":"10 jours ouvrés renouvelables","Fit / Notes":"Télétravail confirmé, mission courte mais bon signal remote.","Priorité":"⭐⭐⭐"},
  {"Poste":"Administrateur SIRH","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-administrateur-sirh-104351-de","Contrat":"Freelance/Mission","Localisation":"Trappes (78190)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"3 mois","Fit / Notes":"Administration SIRH, niveau moins senior.","Priorité":"⭐⭐"},
  {"Poste":"Consultant MOA SIRH","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-consultant-moa-sirh-103498-de","Contrat":"Freelance/Mission","Localisation":"Paris (75001)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"12 mois renouvelables","Fit / Notes":"MOA SIRH, bon fit.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant AMOA - Domaine fonctionnel Formation/Learning","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-consultant-amoa-domaine-fonctionnel-formation-learning-101672-de","Contrat":"Freelance/Mission","Localisation":"Paris (75013)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"6 mois renouvelables","Fit / Notes":"Domaine formation/learning, cohérent avec le profil formateur.","Priorité":"⭐⭐⭐"},
  {"Poste":"Chefs de projet et Consultants Technico-fonctionnels HCM","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chefs-de-projet-et-consultants-technico-fonctionnels-hcm-99731-de","Contrat":"Freelance/Mission","Localisation":"Paris (75001)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"6 mois renouvelables","Fit / Notes":"HCM explicite, très bon match technico-fonctionnel.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Chef de projet/PMO projet migration HRA","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-pmo-projet-migration-hra-96988-de","Contrat":"Freelance/Mission","Localisation":"Paris (75012)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"3 mois","Fit / Notes":"Migration HRA, cohérent avec l'expérience migration de données SAP HR.","Priorité":"⭐⭐⭐"},
  {"Poste":"Chef de projet Bureautique et application RH","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-bureautique-et-application-rh-88861-de","Contrat":"Freelance/Mission","Localisation":"Poissy","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"7 mois","Fit / Notes":"Application RH, fit modéré.","Priorité":"⭐⭐"},
  {"Poste":"SIRH / AO (Appel d'offres)","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-sirh-ao-88086-de","Contrat":"Freelance/Mission","Localisation":"Paris (75)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"3 mois renouvelables","Fit / Notes":"Mission liée à un appel d'offres SIRH, pourrait valoriser l'expérience pre-sales/avant-vente.","Priorité":"⭐⭐⭐"},
  {"Poste":"Consultant SIRH SuccessFactors","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-consultant-sirh-successfactors-sur-issy-115627-de","Contrat":"Freelance/Mission","Localisation":"Issy-les-Moulineaux (92)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"9 mois renouvelables","Fit / Notes":"SuccessFactors explicite, très bon match.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Expert Workday IT F/H","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-expert-workday-it-f-h-115424-de","Contrat":"Freelance/Mission","Localisation":"Puteaux (92800)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"6 mois renouvelables","Fit / Notes":"Workday, élargit le vivier HRIS.","Priorité":"⭐⭐⭐"},
  {"Poste":"Expert Technique SIRH","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-expert-technique-sirh-113399-de","Contrat":"Freelance/Mission","Localisation":"Paris (75015)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"12 mois renouvelables","Fit / Notes":"Volet technique SIRH, fit modéré.","Priorité":"⭐⭐"},
  {"Poste":"Consultant SAP SuccessFactors","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-consultant-sap-succesfactors-sur-la-defense-112172-de","Contrat":"Freelance/Mission","Localisation":"La Défense / Paris (75)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"3 mois renouvelables","Fit / Notes":"SF explicite.","Priorité":"⭐⭐⭐"},
  {"Poste":"Payroll Specialist","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-payroll-specialist-sur-clamart-111050-de","Contrat":"Freelance/Mission","Localisation":"Clamart (92)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"3 mois renouvelables","Fit / Notes":"Paie pure, fit modéré.","Priorité":"⭐⭐"},
  {"Poste":"Expert HR ACCESS","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-expert-hr-access-sur-paris-116748-de","Contrat":"Freelance/Mission","Localisation":"Paris (75000)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"3 mois renouvelables","Fit / Notes":"SIRH legacy HR Access, fit correct.","Priorité":"⭐⭐"},
  {"Poste":"Chef de Projet Fonctionnel ERP","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-chef-de-projet-fonctionnel-erp-pour-nantes-116699-de","Contrat":"Freelance/Mission","Localisation":"Nantes (44)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"120 jours ouvrés","Fit / Notes":"ERP fonctionnel généraliste, pas spécifique HR.","Priorité":"⭐⭐"},
  {"Poste":"Consultant SIRH (H/F)","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-consultant-sirh-h-f-116636-de","Contrat":"Freelance/Mission","Localisation":"Archamps (74160)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"4 mois renouvelables, début 01/09/2026","Fit / Notes":"Consultant SIRH générique, démarrage proche.","Priorité":"⭐⭐⭐"},
  {"Poste":"Expert Workday Accounting Center - Lead Implémentation Finance","Entreprise":"N/C","Source":"freelance-informatique.fr","Lien":"https://www.freelance-informatique.fr/mission-expert-workday-accounting-center-lead-implementation-finance-lille-116403-de","Contrat":"Freelance/Mission","Localisation":"Lille (59000)","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"7 mois","Fit / Notes":"Workday mais volet finance, pas RH ; fit plus faible.","Priorité":"⭐⭐"},
  {"Poste":"SAP HCM Payroll","Entreprise":"Client final anonymisé","Source":"hansonregan.com","Lien":"https://www.hansonregan.com/job/sap-hcm-payroll/","Contrat":"Freelance/Mission","Localisation":"Anywhere","Remote":"Oui (Anywhere)","Salaire / TJM":"Non précisé (EUR/jour)","Durée mission":"Non précisée","Fit / Notes":"SAP HCM Payroll en remote total, très bon fit avec 14 ans SAP HR.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"SAP SuccessFactors Time Off","Entreprise":"Client final anonymisé","Source":"hansonregan.com","Lien":"https://www.hansonregan.com/job/sap-successfactors-time-off/","Contrat":"Freelance/Mission","Localisation":"Anywhere","Remote":"Oui (Anywhere)","Salaire / TJM":"415€/j","Durée mission":"Non précisée","Fit / Notes":"SuccessFactors Time Off, remote total confirmé.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"SAP SuccessFactors EC","Entreprise":"Client final anonymisé","Source":"hansonregan.com","Lien":"https://www.hansonregan.com/job/sap-successfactors-ec/","Contrat":"Freelance/Mission","Localisation":"Anywhere","Remote":"Oui (Anywhere)","Salaire / TJM":"52€/heure","Durée mission":"Non précisée","Fit / Notes":"Employee Central, remote total confirmé, cœur de cible SF.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"SAP ECS Client Relationship Manager","Entreprise":"Client final anonymisé","Source":"hansonregan.com","Lien":"https://www.hansonregan.com/job/sap-ecs-client-relationship-manager/","Contrat":"Freelance/Mission","Localisation":"France","Remote":"Non précisé","Salaire / TJM":"700€/j","Durée mission":"Non précisée","Fit / Notes":"Rôle de type CSM dans un contexte SAP, correspond très bien au double profil CSM + SAP.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"SAP SuccessFactors Consultant – Performance","Entreprise":"Client final anonymisé","Source":"whitehallresources.com","Lien":"https://www.whitehallresources.com/job/sap-successfactors-consultant-performance-36128/","Contrat":"Freelance/Mission","Localisation":"City of London, Londres","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"SF Performance & Goals, mais localisation Londres sans mention remote, probablement sur site.","Priorité":"⭐⭐"},
  {"Poste":"SAP HCM Payroll/SF EC Payroll Consultant","Entreprise":"Client final anonymisé","Source":"eursap.eu","Lien":"https://www.eursap.eu/jobs/35441","Contrat":"CDI","Localisation":"Pays-Bas","Remote":"Non précisé","Salaire / TJM":"€103,480/an + bonus","Durée mission":"","Fit / Notes":"Bon salaire, HCM Payroll/SF EC, mais localisation Pays-Bas, remote à vérifier.","Priorité":"⭐⭐⭐"},
  {"Poste":"SAP SuccessFactors (Learning/LMS) End-User Trainer","Entreprise":"Client final anonymisé","Source":"eursap.eu","Lien":"https://www.eursap.eu/jobs/35575","Contrat":"Freelance/Mission","Localisation":"Pologne","Remote":"Non précisé","Salaire / TJM":"Market rates","Durée mission":"Non précisée","Fit / Notes":"Formation utilisateurs sur SF LMS, correspond au profil formateur, localisation Pologne.","Priorité":"⭐⭐⭐"},
  {"Poste":"Founding Customer Success Manager","Entreprise":"Gotam","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/founding-customer-success-manager-teletravail-c4e12456/","Contrat":"Freelance/Mission","Localisation":"Non précisée (lancement activité Italie)","Remote":"Oui (Télétravail confirmé)","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Founding CSM en télétravail total ; valorise directement le statut de co-fondateur WallOfTraders.com.","Priorité":"⭐⭐⭐⭐⭐"},
  {"Poste":"Product Manager SIRH (Oracle HCM)","Entreprise":"Unitechsolutions","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/product-manager-sirh-h-f-paris-d64b6274/","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"PM SIRH sur Oracle HCM, bon croisement de compétences.","Priorité":"⭐⭐⭐"},
  {"Poste":"Formateur en Intelligence Artificielle Générative et Agentique","Entreprise":"Mindness","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/formateur-en-intelligence-artificielle-generative-et-agentique-teletravail-c892d79e/","Contrat":"Freelance/Mission","Localisation":"Non précisée","Remote":"Oui (Télétravail confirmé)","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Formateur IA générative en full remote, correspond exactement au profil Formateur IA ciblé.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Formateur / Formatrice freelance en IA générative et automatisation no-code","Entreprise":"Schoolia","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/formateur-formatrice-freelance-en-ia-generative-et-automatisation-no-code-teletravail-c73e30a9/","Contrat":"Freelance/Mission","Localisation":"Non précisée","Remote":"Oui (Télétravail confirmé)","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Formation IA pour TPE/PME en full remote, acculturation IA sans data science pur.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Formateur IA appliquée à l'acquisition client","Entreprise":"N/C","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/formateur-ia-appliquee-a-l-acquisition-client-teletravail-68ec066a/","Contrat":"Freelance/Mission","Localisation":"Non précisée","Remote":"Oui (Télétravail confirmé)","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Formateur IA full remote, angle acquisition client.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Formateur·rice·s freelances en IA","Entreprise":"Contournement","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/formateur-rice-s-freelances-en-ia-teletravail-9cc97c82/","Contrat":"Freelance/Mission","Localisation":"Non précisée","Remote":"Oui (Télétravail confirmé)","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Formation IA et no-code en full remote.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Customer Success Manager","Entreprise":"Realadvisor","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/customer-success-manager-teletravail-8a4833c0/","Contrat":"Freelance/Mission","Localisation":"Non précisée","Remote":"Oui (Télétravail confirmé)","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"CSM full remote, plateforme digitale immobilière, bon fit CSM senior.","Priorité":"⭐⭐⭐⭐"},
  {"Poste":"Customer Success Manager","Entreprise":"Croissance Esthetique","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/customer-success-manager-teletravail-49c96bf3/","Contrat":"Freelance/Mission","Localisation":"Non précisée","Remote":"Oui (Télétravail confirmé)","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"CSM full remote, secteur esthétique premium, niche mais remote confirmé.","Priorité":"⭐⭐⭐"},
  {"Poste":"Product Manager Paiement Digital","Entreprise":"Wearesander","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/product-manager-paiement-digital-teletravail-9aa507ee/","Contrat":"Freelance/Mission","Localisation":"Non précisée","Remote":"Oui (Télétravail confirmé)","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"PM full remote, hors HRIS mais correspond au critère remote prioritaire de l'onglet PM.","Priorité":"⭐⭐⭐"},
  {"Poste":"Product Manager IA","Entreprise":"Ever T","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/product-manager-ia-paris-a80209f9/","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"PM sur moteur de recommandation IA, sur site Paris.","Priorité":"⭐⭐"},
  {"Poste":"Product Manager IA","Entreprise":"Wecotechnology","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/product-manager-ia-paris-e49bf612/","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"PM produit d'innovation digitale intégrant IA, sur site Paris.","Priorité":"⭐⭐"},
  {"Poste":"Product Owner IA Senior","Entreprise":"Groupedigit","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/product-owner-ia-senior-paris-f8e6296b/","Contrat":"Freelance/Mission","Localisation":"Paris","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"PO IA senior sur produits Data/IA, sur site Paris.","Priorité":"⭐⭐"},
  {"Poste":"Business Transformation Lead - Transformation digitale / IA","Entreprise":"Wheelofwork","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/business-transformation-lead-transformation-digitale-intelligence-artificielle-roissy-en-france-c772f32d/","Contrat":"Freelance/Mission","Localisation":"Roissy-en-France","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Croisement transformation digitale x IA, mais site probablement onsite (zone aéroportuaire).","Priorité":"⭐⭐"},
  {"Poste":"Formateur·rice IA","Entreprise":"Simplon","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/formateur-rice-ia-bayonne-6742bcda/","Contrat":"Freelance/Mission","Localisation":"Bayonne","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Formation IA générative pour valoriser des parcours de candidature ; mission locale à Bayonne, à deux pas d'Anglet.","Priorité":"⭐⭐⭐"},
  {"Poste":"Formateur(trice) indépendant(e) - Développer son activité avec l'IA (RS7344)","Entreprise":"Smartoptimisation","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/formateur-trice-independant-e-en-ia-strasbourg-9a675c34/","Contrat":"Freelance/Mission","Localisation":"Strasbourg","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Certification IA pour dirigeants/indépendants.","Priorité":"⭐⭐"},
  {"Poste":"Formateur(rice) IA","Entreprise":"Focuscloudgroup","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/formateur-rice-ia-hauts-de-seine-3f3c17b8/","Contrat":"Freelance/Mission","Localisation":"Hauts-de-Seine","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Formation certifiante IA niveau intermédiaire.","Priorité":"⭐⭐"},
  {"Poste":"Consultant IA / AI Solutions Engineer","Entreprise":"Ucase Consulting","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/consultant-ia-ai-solutions-engineer-lyon-a6697d82/","Contrat":"Freelance/Mission","Localisation":"Lyon","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Croisement IA générative x Solutions Engineer.","Priorité":"⭐⭐⭐"},
  {"Poste":"Directeur de Projet / Lead Product Manager","Entreprise":"Asteins","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/directeur-de-projet-lead-product-manager-pantin-9147386b/","Contrat":"Freelance/Mission","Localisation":"Pantin","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Structuration d'une organisation orientée Produit, fit générique.","Priorité":"⭐⭐"},
  {"Poste":"Product Owner IA Sales Senior","Entreprise":"Porters","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/product-owner-ia-sales-senior-marseille-7ca16dd2/","Contrat":"Freelance/Mission","Localisation":"Marseille","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"PO IA appliquée aux ventes, croisement IA x commercial.","Priorité":"⭐⭐"},
  {"Poste":"Formateur(trice) Accompagnement & Sensibilisation Intelligence Artificielle","Entreprise":"Consul Team","Source":"mission-freelances.fr","Lien":"https://www.mission-freelances.fr/missions/formateur-trice-accompagnement-sensibilisation-intelligence-artificielle-h-f-toulon-116298f1/","Contrat":"Freelance/Mission","Localisation":"Toulon","Remote":"Non précisé","Salaire / TJM":"Non précisé","Durée mission":"Non précisée","Fit / Notes":"Acculturation IA en entreprise, correspond bien au profil formateur/conduite du changement.","Priorité":"⭐⭐⭐"}
]
'''


def build(raw_json, note_suffix):
    offres = json.loads(raw_json)
    out = []
    for o in offres:
        entry = {
            'Priorité': o.get('Priorité'),
            'Statut': '', 'Fait': '',
            'Poste': o['Poste'], 'Entreprise': o['Entreprise'], 'Source': o.get('Source', ''),
            'Lien': o.get('Lien', ''), 'Contrat': o.get('Contrat', ''),
            'Localisation': o.get('Localisation', ''), 'Remote': o.get('Remote', ''),
            'Salaire / TJM': o.get('Salaire / TJM', ''), 'Durée mission': o.get('Durée mission', ''),
            'Fit / Notes': (o.get('Fit / Notes', '') + note_suffix).strip(),
            'CV à envoyer': '', 'Prétention': '',
        }
        if o.get('Onglet'):
            entry['Onglet'] = o['Onglet']
        out.append(entry)
    return out


OFFRES = []
OFFRES += build(USA_JSON, ' — relance 26/08/2026, cluster USA')
OFFRES += build(ATS_JSON, ' — relance 26/08/2026, cluster API ATS EMEA')
OFFRES += build(EU_JSON, ' — relance 26/08/2026, cluster boards remote EU')
OFFRES += build(FR_JSON, ' — relance 26/08/2026, cluster FR/freelance')

print(f"TOTAL avant dédoublonnage : {len(OFFRES)} offres")

ajouter_offres(OFFRES)
