"""Relance complète du 2026-08-20 : compilation des 4 recherches parallèles
(boards FR/freelance, API ATS + éditeurs HRIS, boards remote/VC/LinkedIn,
IA/PM/métiers de niche). Dédoublonnage contre les liens déjà en base."""

from add_offre import ajouter_offres, FICHIER
import openpyxl

# ── Dédoublonnage : charge tous les liens déjà présents ────────────────────
def liens_existants():
    wb = openpyxl.load_workbook(FICHIER)
    liens = set()
    for name in wb.sheetnames:
        ws = wb[name]
        header = [c.value for c in ws[1]]
        if 'Lien' not in header:
            continue
        idx = header.index('Lien')
        for row in ws.iter_rows(min_row=2, values_only=True):
            v = row[idx]
            if v:
                liens.add(str(v).strip().rstrip('/'))
    return liens

OFFRES = [
    # ── Cluster 1 : boards remote + VC + LinkedIn radar ────────────────────
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Strategic Customer Success Manager – French Speaking', Entreprise='Synthesia',
         Source='Ashby', Lien='https://jobs.ashbyhq.com/synthesia/84342701-d3e1-4915-987a-cdec0cb1bee8',
         Contrat='CDI', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'CSM Senior FR, éditeur AI scale-up bien financé'}),
    dict(Priorité='⭐⭐⭐', Poste='Customer Success Manager, EMEA', Entreprise='Customer.io',
         Source='WeWorkRemotely', Lien='https://weworkremotely.com/remote-jobs/customer-io-customer-success-manager-emea',
         Contrat='CDI', Localisation='UK/Irlande requis', Remote='Oui', **{'Salaire / TJM': '80 000 $', 'Fit / Notes': 'CSM senior remote mais résidence UK/IE requise à l’embauche'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Workday Implementation Specialist', Entreprise='Remote.com',
         Source='Greenhouse API', Lien='https://job-boards.greenhouse.io/remotecom/jobs/7635556003',
         Contrat='CDI', Localisation='Remote-EMEA', Remote='Oui', **{'Fit / Notes': 'Implémentation Workday/HRIS, EMEA inclut France'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Workday Implementation Specialist (2e poste)', Entreprise='Remote.com',
         Source='Greenhouse API', Lien='https://job-boards.greenhouse.io/remotecom/jobs/7548213003',
         Contrat='CDI', Localisation='Remote-EMEA', Remote='Oui', **{'Fit / Notes': 'Second poste identique ouvert en parallèle'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Senior Product Manager, Remote Build', Entreprise='Remote.com',
         Source='Greenhouse API', Lien='https://job-boards.greenhouse.io/remotecom/jobs/7331443003',
         Contrat='CDI', Localisation='Remote-France', Remote='Oui', **{'Fit / Notes': 'PM 100% remote France, éditeur HR tech'}, **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Product Manager, APIs', Entreprise='Remote.com',
         Source='Greenhouse API', Lien='https://job-boards.greenhouse.io/remotecom/jobs/7831380003',
         Contrat='CDI', Localisation='Remote-EMEA', Remote='Oui', **{'Fit / Notes': 'PM remote EMEA'}, **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager, Contractor Management', Entreprise='Remote.com',
         Source='Greenhouse API', Lien='https://job-boards.greenhouse.io/remotecom/jobs/7885031003',
         Contrat='CDI', Localisation='Remote-EMEA', Remote='Oui', **{'Fit / Notes': 'PM remote EMEA, HRIS'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager, Billing Platform', Entreprise='Remote.com',
         Source='Greenhouse API', Lien='https://job-boards.greenhouse.io/remotecom/jobs/7885108003',
         Contrat='CDI', Localisation='Remote-EMEA', Remote='Oui', **{'Fit / Notes': 'PM remote EMEA'}, **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Product Manager, Fraud and Compliance', Entreprise='Remote.com',
         Source='Greenhouse API', Lien='https://job-boards.greenhouse.io/remotecom/jobs/7814948003',
         Contrat='CDI', Localisation='Remote-EMEA', Remote='Oui', **{'Fit / Notes': 'PM remote EMEA'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Product Manager, Reporting & Insights', Entreprise='Remote.com',
         Source='Greenhouse API', Lien='https://job-boards.greenhouse.io/remotecom/jobs/7885155003',
         Contrat='CDI', Localisation='Remote-EMEA', Remote='Oui', **{'Fit / Notes': 'PM remote EMEA'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Global Payroll Implementation Country Lead – Germany', Entreprise='Remote.com',
         Source='Greenhouse API', Lien='https://job-boards.greenhouse.io/remotecom/jobs/7741670003',
         Contrat='CDI', Localisation='Remote-EMEA', Remote='Oui', **{'Fit / Notes': 'Implémentation paie/HRIS'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Consultant SAP SuccessFactors Compensation', Entreprise='DXC Technology',
         Source='LinkedIn radar → DXC', Lien='https://careers.dxc.com/fr/job-fr/23574872/consultant-sap-successfactors-compensation-paris-fr/',
         Contrat='Non précisé', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'SAP SuccessFactors, cœur de cible'}),
    dict(Priorité='⭐⭐⭐', Poste='CDI – Consultant métier en Système d’Information RH H/F', Entreprise='Naval Group',
         Source='LinkedIn radar', Lien='https://www.naval-group.com/fr/talents/offer/2026-53338',
         Contrat='CDI', Localisation='Ollioules/Toulon', Remote='Non précisé', **{'Fit / Notes': 'SIRH, grand compte'}),
    dict(Priorité='⭐⭐⭐', Poste='CDI – Consultant métier SIRH (Reporting) H/F', Entreprise='Naval Group',
         Source='LinkedIn radar', Lien='https://www.naval-group.com/fr/talents/offer/2025-48912',
         Contrat='CDI', Localisation='Ollioules', Remote='Non précisé', **{'Fit / Notes': 'SIRH, grand compte'}),
    dict(Priorité='⭐⭐', Poste='Developer Relations & Customer Success Manager – Maps Platform', Entreprise='MapTiler',
         Source='WeWorkRemotely/SpaceTalent', Lien='https://jobs.spacetalent.org/companies/maptiler/jobs/51002561-customer-success-manager',
         Contrat='Non précisé', Localisation='Remote Europe', Remote='Oui', **{'Fit / Notes': 'Orienté développeurs/API, écart technique à assumer en LM'}),

    # ── Cluster 2 : boards FR / freelance ────────────────────────────────
    dict(Priorité='⭐⭐⭐', Poste='Manager SIRH', Entreprise='HR DNA', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/administrateur-applicatif-erp-crm-sirh/manager-sirh-11',
         Contrat='CDI', Localisation='Paris', Remote='Partiel', **{'Salaire / TJM': '60-110k€/an', 'Fit / Notes': 'Chef de projet SIRH senior'}),
    dict(Priorité='⭐⭐⭐', Poste='Chargé de missions SIRH N2 - Workday HCM H/F', Entreprise='HR DNA', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/charge-de-missions-sirh-n2-workday-hcm-h-f-25',
         Contrat='Freelance', Localisation='Neuilly-sur-Marne', Remote='Partiel', **{'Salaire / TJM': '250-500€/j', 'Fit / Notes': 'SIRH Workday'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de projet IT / Responsable SIRH H/F', Entreprise='LeHibou', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/chef-de-projet-it-responsable-sirh-h-f',
         Contrat='Freelance', Localisation='Bordeaux', Remote='Partiel', **{'Salaire / TJM': '675€/j', 'Fit / Notes': 'Chef de projet SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Project Manager SIRH', Entreprise='DSI group', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/project-manager-sirh-2',
         Contrat='Freelance/CDI', Localisation='Luxembourg', Remote='Non précisé', **{'Fit / Notes': 'Chef de projet SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Product Manager / Owner SIRH H/F', Entreprise='Lùkla', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/product-manager-owner-sirh-h-f',
         Contrat='Freelance', Localisation='Rouen', Remote='Partiel', **{'Fit / Notes': 'PM SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Gestionnaire d’Application SIRH', Entreprise='Montreal Associates', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/gestionnaire-dapplication-sirh',
         Contrat='Freelance', Localisation='Bretagne', Remote='Partiel', **{'Salaire / TJM': '400-600€/j', 'Fit / Notes': 'Consultant SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Adjoint(e) Responsable Paie H/F', Entreprise='HR Path', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/adjoint-e-responsable-paie-h-f',
         Contrat='Freelance', Localisation='Paris', Remote='Partiel', **{'Salaire / TJM': '650-700€/j', 'Fit / Notes': 'HR Path, mission paie'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant Transformation RH - Core HR', Entreprise='VISIAN', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/consultant-transformation-rh-core-hr',
         Contrat='Freelance/CDI', Localisation='Paris', Remote='Partiel', **{'Fit / Notes': 'Transformation RH'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de Projet SIRH H/F', Entreprise='HAYS France', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/chef-de-projet-sirh-h-f-79',
         Contrat='Freelance', Localisation='Bordeaux', Remote='Partiel', **{'Fit / Notes': 'Chef de projet SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Senior Consultant Transformation RH (TOM - Core HR)', Entreprise='Mon Consultant Indépendant', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/senior-consultant-transformation-rh-target-operating-model-core-hr-1',
         Contrat='Freelance', Localisation='Paris', Remote='Partiel', **{'Salaire / TJM': '500-550€/j', 'Fit / Notes': 'Transformation RH senior'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Consultant SAP SuccessFactors CoreHR H/F', Entreprise='HR Path', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/consultant-sap-successfactors-corehr-h-f',
         Contrat='Freelance', Localisation='Paris', Remote='Non précisé', **{'Salaire / TJM': '450-600€/j', 'Fit / Notes': 'SAP SuccessFactors'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Chef de projet SIRH H/F', Entreprise='SPIE ICS', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/chef-de-projet-sirh-h-f-78',
         Contrat='Freelance/CDI', Localisation='Bordeaux', Remote='Non précisé', **{'Salaire / TJM': '450-600€/j', 'Fit / Notes': 'Chef de projet SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Product Manager SIRH / Chef de Projet SIRH (Oracle HCM) H/F', Entreprise='Freelance.com', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/product-manager-sirh-chef-de-projet-sirh-oracle-hcm-h-f',
         Contrat='Freelance', Localisation='Île-de-France', Remote='Partiel', **{'Fit / Notes': 'PM/Chef de projet SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de projet MOE SIRH H/F', Entreprise='HAYS France', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/chef-de-projet-moe-sirh-h-f-1',
         Contrat='CDI', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'Chef de projet SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Responsable applicatif SIRH H/F', Entreprise='GROUPE ARTEMYS', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/responsable-applicatif-sirh-h-f-freelance',
         Contrat='Freelance', Localisation='Paris', Remote='Partiel', **{'Salaire / TJM': '550-650€/j', 'Fit / Notes': 'SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Product Manager SIRH', Entreprise='Signe +', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/product-manager-sirh-3',
         Contrat='Freelance', Localisation='Rouen', Remote='Non précisé', **{'Salaire / TJM': '400-470€/j', 'Fit / Notes': 'PM SIRH'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant Technico-Fonctionnel HR Access Paie H/F', Entreprise='HR DNA', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/consultant-fonctionnel/consultant-technico-fonctionnel-hr-access-paie-h-f-6',
         Contrat='CDI', Localisation='Paris', Remote='Partiel', **{'Salaire / TJM': '60-65k€/an', 'Fit / Notes': 'HR Access'}),
    dict(Priorité='⭐⭐⭐', Poste='Expert Workday HCM N2/N3', Entreprise='HR DNA', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/expert-seo-consultant-referencement/expert-workday-hcm-n2-n3-3',
         Contrat='Freelance', Localisation='Saint-Ouen-sur-Seine', Remote='Partiel', **{'Salaire / TJM': '325-650€/j', 'Durée mission': '24 mois', 'Fit / Notes': 'Workday HCM'}),
    dict(Priorité='⭐⭐⭐', Poste='Architecte d’entreprise / Urbaniste SI', Entreprise='SKILL EXPERT', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/consultant-erp-ms-dynamics-oracle-sage-sap/architecte-dentreprise-urbaniste-si-4',
         Contrat='Freelance', Localisation='Roissy-en-France', Remote='Non précisé', **{'Salaire / TJM': '600-650€/j', 'Fit / Notes': 'Architecture SI, périphérique HCM'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant SAP Paie (HCM Payroll)', Entreprise='DUONEXT', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/consultant-sap-paie-hcm-payroll',
         Contrat='Freelance', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'SAP HCM Payroll'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Expert Technico-Fonctionnel SAP HCM', Entreprise='INFOTEL CONSEIL', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/expert-technico-fonctionnel-sap-hcm',
         Contrat='Freelance', Localisation='Roissy-en-France', Remote='Non précisé', **{'Salaire / TJM': '540-750€/j', 'Fit / Notes': 'SAP HCM'}),
    dict(Priorité='⭐⭐', Poste='SAP SuccessFactors Senior/Lead Consultant', Entreprise='INVESTIGO', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/sap-successfactors-senior-lead-consultant-permanent-ps80-000-ps90-000-per-annum-benefits',
         Contrat='CDI', Localisation='Angleterre', Remote='Non précisé', **{'Salaire / TJM': '£80-90k/an', 'Fit / Notes': 'SF senior, hors France'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Expert SAP SuccessFactors', Entreprise='LeHibou', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/expert-sap-successfactors-1',
         Contrat='Freelance', Localisation='Saint-Ouen-sur-Seine', Remote='Non précisé', **{'Salaire / TJM': '575€/j', 'Fit / Notes': 'SF expert'}),
    dict(Priorité='⭐⭐⭐', Poste='Ingénieur SAP Success Factors (anglais)', Entreprise='BI SOLUTIONS', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/ingenieur-sap-success-factors-anglais-450-e-par-j',
         Contrat='Freelance', Localisation='Île-de-France', Remote='Non précisé', **{'Salaire / TJM': '400-450€/j', 'Fit / Notes': 'SF, anglais requis'}),
    dict(Priorité='⭐⭐⭐', Poste='SAP PMO Successfactors H/F', Entreprise='Mindquest', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/sap-pmo-successfactors-h-f-75',
         Contrat='Freelance', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'PMO SF'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant SAP SUCCESSFACTOR', Entreprise='Intuition IT Solutions', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/consultant-sap-successfactor-2',
         Contrat='Freelance', Localisation='Versailles', Remote='Non précisé', **{'Fit / Notes': 'SF'}),
    dict(Priorité='⭐⭐⭐', Poste='Key User - SAP SuccessFactors', Entreprise='CRYSTAL PLACEMENT', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/key-user-sap-successfactors',
         Contrat='Freelance', Localisation='Bruxelles', Remote='Non précisé', **{'Fit / Notes': 'SF'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant SAP Success Factors ECP', Entreprise='Tenth Revolution Group', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/consultant-sap-success-factors-ecp-1',
         Contrat='Freelance', Localisation='Grand Est', Remote='Non précisé', **{'Fit / Notes': 'SF Payroll'}),
    dict(Priorité='⭐⭐⭐', Poste='Analyste fonctionnel SAP HR', Entreprise='CST Advisory', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/analyste-fonctionnel-sap-hr',
         Contrat='CDI', Localisation='Bruxelles', Remote='Non précisé', **{'Fit / Notes': 'SAP HR'}),
    dict(Priorité='⭐⭐⭐', Poste='Product Owner Solutions IA H/F', Entreprise='DAVRICOURT', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/product-owner/product-owner-solutions-ia-h-f-6',
         Contrat='CDI', Localisation='Lille', Remote='Non précisé', **{'Salaire / TJM': '45-50k€/an', 'Fit / Notes': 'Crossover PM/IA'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de Projet IA agentique (gouvernance, archi Data)', Entreprise='ARDEMIS PARTNERS', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/assistant-chef-de-projet/chef-de-projet-ia-agentique-gouvernance-et-archi-data',
         Contrat='Freelance/CDI', Localisation='Paris', Remote='Non précisé', **{'Salaire / TJM': '400-500€/j, 40-56k€/an', 'Durée mission': '6 mois', 'Fit / Notes': 'Chef de projet IA'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='AI Trainer', Entreprise='Focus Cloud Group', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/autre/ai-trainer',
         Contrat='Freelance', Localisation='Hauts-de-Seine', Remote='Présentiel', **{'Durée mission': '5 jours (24-28/08/2026)', 'Fit / Notes': 'Formateur IA généraliste, mission courte renouvelable'}),

    # freelance-informatique.fr — chef-de-projet-sirh-freelance-n112
    dict(Priorité='⭐⭐⭐', Poste='Administrateur SIRH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-administrateur-sirh-104351-de',
         Contrat='Freelance', Localisation='Trappes (78)', Remote='Non précisé', **{'Durée mission': '3 mois'}),
    dict(Priorité='⭐⭐⭐', Poste='AMOA SIRH DATA', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-amoa-sirh-data-sur-paris-113689-de',
         Contrat='Freelance', Localisation='Courbevoie (92)', Remote='Non précisé', **{'Durée mission': '6 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de projet Bureautique et application RH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-bureautique-et-application-rh-88861-de',
         Contrat='Freelance', Localisation='Poissy', Remote='Non précisé', **{'Durée mission': '7 mois'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de projet MOE / Expert GTA', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-moe-expert-gta-112667-de',
         Contrat='Freelance', Localisation='Paris (75012)', Remote='Non précisé', **{'Durée mission': '36 mois'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de projet/PMO projet migration HRA', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-pmo-projet-migration-hra-96988-de',
         Contrat='Freelance', Localisation='Paris (75012)', Remote='Non précisé', **{'Durée mission': '3 mois'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Chef de projet fonctionnel SIRH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-110424-de',
         Contrat='Freelance', Localisation='Télétravail', Remote='Oui', **{'Durée mission': '6 mois renouvelable', 'Fit / Notes': 'Télétravail confirmé dans le titre'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de projet SIRH confirmé', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-confirme-114018-de',
         Contrat='Freelance', Localisation='Gonesse (95500)', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐', Poste='Chef de Projet SIRH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-sur-bordeaux-99971-de',
         Contrat='Freelance', Localisation='Bordeaux (33)', Remote='Non précisé', **{'Durée mission': '3 mois renouvelable'}),
    dict(Priorité='⭐⭐', Poste='Chef de projet technique SIRH (+TT)', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-sur-marne-la-vallee-tt-101702-de',
         Contrat='Freelance', Localisation='Marne-la-Vallée (77) + télétravail', Remote='Partiel', **{'Durée mission': '14 mois'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de Projet SIRH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-sur-paris-101573-de',
         Contrat='Freelance', Localisation='Paris (75)', Remote='Non précisé', **{'Durée mission': '12 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Chef de projet SIRH WorkDay (certification obligatoire)', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-sirh-workday-certification-obligatoire-110752-de',
         Contrat='Freelance', Localisation='Marne-la-Vallée (77)', Remote='Non précisé', **{'Durée mission': '12 mois'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Chef de projet transverse SIRH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-transverse-sirh-defense-et-remote-105678-de',
         Contrat='Freelance', Localisation='La Défense et remote', Remote='Oui', **{'Durée mission': '3 mois renouvelable', 'Fit / Notes': 'Signal remote positif dans le titre'}),
    dict(Priorité='⭐⭐⭐', Poste='Chefs de projet et Consultants Technico-fonctionnels HCM', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chefs-de-projet-et-consultants-technico-fonctionnels-hcm-99731-de',
         Contrat='Freelance', Localisation='Paris (75001)', Remote='Non précisé', **{'Durée mission': '6 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant AMOA - Domaine fonctionnel formation/Learning', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-consultant-amoa-domaine-fonctionnel-formation-learning-101672-de',
         Contrat='Freelance', Localisation='Paris (75013)', Remote='Non précisé', **{'Durée mission': '6 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant AMOA SIRH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-consultant-amoa-sirh-paris-112194-de',
         Contrat='Freelance', Localisation='Paris (75000)', Remote='Non précisé', **{'Durée mission': '12 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant MOA SIRH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-consultant-moa-sirh-103498-de',
         Contrat='Freelance', Localisation='Paris (75001)', Remote='Non précisé', **{'Durée mission': '12 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant SIRH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-consultant-sirh-113215-de',
         Contrat='Freelance', Localisation='Marseille (13001)', Remote='Non précisé', **{'Durée mission': '22 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Consultant SIRH / Support ERP & PAIE', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-consultant-sirh-support-erp-paie-105111-de',
         Contrat='Freelance', Localisation='Télétravail', Remote='Oui', **{'Durée mission': '10 jours renouvelable', 'Fit / Notes': 'Télétravail confirmé dans le titre'}),
    dict(Priorité='⭐⭐⭐', Poste='Product Owner/Chef de projet SIRH F/H', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-product-owner-chef-de-projet-sirh-f-h-104881-de',
         Contrat='Freelance', Localisation='Grenoble (38000)', Remote='Non précisé', **{'Durée mission': '6 mois'}),
    dict(Priorité='⭐⭐⭐', Poste='SIRH / AO', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-sirh-ao-88086-de',
         Contrat='Freelance', Localisation='Paris (75)', Remote='Non précisé', **{'Durée mission': '3 mois renouvelable'}),
    # freelance-informatique.fr — categorie-modules-sap-hr-238
    dict(Priorité='⭐⭐⭐', Poste='Consultant SAP SuccessFactors', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-consultant-sap-succesfactors-sur-la-defense-112172-de',
         Contrat='Freelance', Localisation='La Défense (75)', Remote='Non précisé', **{'Durée mission': '3 mois renouvelable'}),
    dict(Priorité='⭐⭐', Poste='Consultant Senior SAP SuccessFactors (Recruiting & Employee Central)', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-consultant-senior-sap-successfactors-recruiting-employee-central-lieu-luxembourg-sur-site-114529-de',
         Contrat='Freelance', Localisation='Luxembourg, sur site', Remote='Présentiel', **{'Durée mission': '12 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant SIRH SuccessFactors', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-consultant-sirh-successfactors-sur-issy-115627-de',
         Contrat='Freelance', Localisation='Issy-les-Moulineaux (92)', Remote='Non précisé', **{'Durée mission': '9 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Expert Technique SIRH', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-expert-technique-sirh-113399-de',
         Contrat='Freelance', Localisation='Paris (75015)', Remote='Non précisé', **{'Durée mission': '12 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Expert Workday IT F/H', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-expert-workday-it-f-h-115424-de',
         Contrat='Freelance', Localisation='Puteaux (92800)', Remote='Non précisé', **{'Durée mission': '6 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Payroll Specialist', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-payroll-specialist-sur-clamart-111050-de',
         Contrat='Freelance', Localisation='Clamart (92)', Remote='Non précisé', **{'Durée mission': '3 mois renouvelable'}),
    # freelance-informatique.fr — categorie-progiciels-sirh-222
    dict(Priorité='⭐⭐⭐', Poste='Chef de projet Workday', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-chef-de-projet-workday-sur-lille-116386-de',
         Contrat='Freelance', Localisation='Lille (59)', Remote='Non précisé', **{'Durée mission': '3 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant SIRH (H/F)', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-consultant-sirh-h-f-116636-de',
         Contrat='Freelance', Localisation='Archamps (74160)', Remote='Non précisé', **{'Durée mission': '4 mois renouvelable, début 01/09/2026'}),
    dict(Priorité='⭐⭐⭐', Poste='Expert HR ACCESS', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-expert-hr-access-sur-paris-116748-de',
         Contrat='Freelance', Localisation='Paris (75000)', Remote='Non précisé', **{'Durée mission': '3 mois renouvelable'}),
    dict(Priorité='⭐⭐⭐', Poste='Expert Workday Accounting Center - Lead Implémentation Finance', Entreprise='N/C', Source='freelance-informatique.fr',
         Lien='https://www.freelance-informatique.fr/mission-expert-workday-accounting-center-lead-implementation-finance-lille-116403-de',
         Contrat='Freelance', Localisation='Lille (59000)', Remote='Non précisé', **{'Durée mission': '7 mois'}),

    # eursap.eu
    dict(Priorité='⭐⭐', Poste='SAP HCM Payroll or SF EC Payroll Consultant', Entreprise='N/C', Source='eursap.eu',
         Lien='https://www.eursap.eu/jobs/sap-hcm-payroll-or-sf-ec-payroll-consultant-35441-nl',
         Contrat='CDI', Localisation='Pays-Bas', Remote='Non précisé', **{'Fit / Notes': 'SAP HCM/SF Payroll, hors France'}),
    dict(Priorité='⭐⭐', Poste='SAP SuccessFactors (Learning/LMS) End-User Trainer', Entreprise='N/C', Source='eursap.eu',
         Lien='https://www.eursap.eu/jobs/sap-success-factors-learning-lms-trainer-PL-35575',
         Contrat='Contract', Localisation='Pologne', Remote='Non précisé', **{'Fit / Notes': 'Formateur SF, hors France'}),

    # hansonregan / whitehallresources
    dict(Priorité='⭐⭐', Poste='SAP SF LMS Consultant', Entreprise='N/C', Source='hansonregan.com',
         Lien='https://www.hansonregan.com/job/sap-sf-lms-consultant/',
         Contrat='Non précisé', Localisation='Portugal', Remote='Non précisé', **{'Salaire / TJM': 'Négociable', 'Fit / Notes': 'SF LMS'}),
    dict(Priorité='⭐', Poste='SAP SuccessFactors/HCM Consultant', Entreprise='N/C', Source='whitehallresources.com',
         Lien='https://www.whitehallresources.com/job/sap-successfactors-hcm-consultant-36005/',
         Contrat='Contract', Localisation='Muscat (Oman)', Remote='Non précisé', **{'Fit / Notes': 'SF/HCM, géo atypique'}),

    # ── Cluster 3 : IA / PM / niche ────────────────────────────────────────
    dict(Priorité='⭐⭐⭐⭐', Poste='Consultant IA Générative / Claude (Anthropic)', Entreprise='SMARTPOINT', Source='free-work.com',
         Lien='https://www.free-work.com/fr/tech-it/job-mission/consultant/consultant-ia-generative-claude-anthropic',
         Contrat='CDI ou Freelance', Localisation='Île-de-France', Remote='Partiel', **{'Salaire / TJM': '40-60k€/an ou 500-600€/j', 'Fit / Notes': 'Conduite du changement IA + cas d’usage Claude'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant Formateur IA Agentique', Entreprise='Scaltify', Source='LinkedIn',
         Lien='https://fr.linkedin.com/jobs/view/consultant-formateur-ia-agentique-at-scaltify-4445952904',
         Contrat='Non précisé', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'Formateur IA agentique, très aligné profil'}),
    dict(Priorité='⭐⭐', Poste='AI Adoption Leader (F/H)', Entreprise='Valeo', Source='LinkedIn/Workday',
         Lien='https://valeo.wd3.myworkdayjobs.com/fr-FR/Valeo/job/AI-Adoption-Leader--F-H-_JR-24020',
         Contrat='CDI', Localisation='Paris 17e (déplacements Créteil)', Remote='Hybride', **{'Fit / Notes': 'Conduite du changement IA, hybride 2j/sem'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='AI Adoption & Change Manager (GenAI) F/H', Entreprise='VISEO', Source='Glassdoor',
         Lien='https://www.glassdoor.fr/job-listing/ai-adoption-change-manager-genai-fh-viseo-JV_IC3040032_KO0,35_KE36,41.htm?jl=1010147311358',
         Contrat='Non précisé', Localisation='Boulogne-Billancourt', Remote='Non précisé', **{'Fit / Notes': 'Déploiement adoption IA générative à grande échelle, excellent fit métier'}),

    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Senior Product Manager - EMEA', Entreprise='Pencil', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/pencil/e4bbf9ae-0be6-455f-8b24-f960be4c6f2c',
         Contrat='Non précisé', Localisation='Remote EMEA', Remote='Oui', **{'Fit / Notes': 'Adtech GenAI, remote total EMEA, excellent fit'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Lead Product Manager - Editor - EMEA', Entreprise='Pencil', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/pencil/765370fa-a2b2-487f-af2e-73a53cd1bad6',
         Contrat='Non précisé', Localisation='EMEA', Remote='Oui', **{'Fit / Notes': 'PM EMEA remote'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager – Growth', Entreprise='Pragmatike', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/pragmatike/7fb8a428-8e86-4113-97ed-16cb0011f22e',
         Contrat='Contractor', Localisation='Remote', Remote='Oui', **{'Fit / Notes': 'AI consumer tech, growth PM'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior AI Product Manager (Remote - Europe)', Entreprise='EverAI', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/everai/694c19b7-d94f-4f66-97a7-5c881b0811bf',
         Contrat='Non précisé', Localisation='Remote Europe', Remote='Oui', **{'Fit / Notes': 'Produit IA, croisement double intérêt PM+IA'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Senior Product Manager - Core Platform (Remote)', Entreprise='Camunda', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/camunda/b771e145-a5cf-4867-ad13-b54830e3b744',
         Contrat='Non précisé', Localisation='Remote', Remote='Oui', **{'Fit / Notes': 'Plateforme B2B technique, orchestration agentique'}, **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager, AI (Remote from France)', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/e31102cb-844a-4a93-a923-29dbdce8b3d0',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'Fit / Notes': 'Remote depuis la France explicite'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager', Entreprise='360Learning', Source='Lever',
         Lien='https://jobs.lever.co/360learning/aac4031b-ef0e-4d2f-b85e-67ecb3b1814c',
         Contrat='CDI', Localisation='France, full remote', Remote='Oui', **{'Fit / Notes': 'Éditeur SaaS FR (learning)'}, **{'CV à envoyer': 'PM_FR'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Staff Product Manager - Superspace', Entreprise='Superside', Source='Lever',
         Lien='https://jobs.lever.co/superside/c6f48275-b841-420a-abf8-49178c966cee',
         Contrat='Non précisé', Localisation='Remote EMEA', Remote='Oui', **{'Fit / Notes': 'Niveau Staff, senior'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager, Payroll', Entreprise='Remote.com', Source='Greenhouse',
         Lien='https://boards.greenhouse.io/remotecom/jobs/5731298003',
         Contrat='Non précisé', Localisation='Remote', Remote='Oui', **{'Fit / Notes': 'HRIS/payroll global, priorité géo LATAM à vérifier'}, **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager, Billing', Entreprise='Remote.com', Source='Greenhouse',
         Lien='https://boards.greenhouse.io/remotecom/jobs/6064626003',
         Contrat='Non précisé', Localisation='Remote', Remote='Oui', **{'Fit / Notes': 'Fintech vertical chez Remote.com'}, **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager - Paris/Remote', Entreprise='Side', Source='WTTJ',
         Lien='https://www.welcometothejungle.com/fr/companies/side/jobs/product-manager_paris_SIDE_jRLO2Ar',
         Contrat='CDI', Localisation='Paris', Remote='Oui', **{'Salaire / TJM': '55-59K€', 'Fit / Notes': 'Télétravail total'}, **{'CV à envoyer': 'PM_FR'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager', Entreprise='Inqom', Source='WTTJ',
         Lien='https://www.welcometothejungle.com/fr/companies/inqom/jobs/product-manager',
         Contrat='CDI', Localisation='Paris/Tours', Remote='Oui', **{'Salaire / TJM': '50-55K€', 'Fit / Notes': 'Télétravail total'}, **{'CV à envoyer': 'PM_FR'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager (full remote avec déplacements)', Entreprise='RISE', Source='WTTJ',
         Lien='https://www.welcometothejungle.com/fr/companies/rise/jobs/28b1f52c-1924-40ec-b7e0-18bbdcda6c56',
         Contrat='CDI', Localisation='Full remote + déplacements Europe', Remote='Oui', **{'Fit / Notes': 'Déplacements clients, rappelle le profil terrain'}, **{'CV à envoyer': 'PM_FR'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager', Entreprise='Follow (Follow Health)', Source='WTTJ',
         Lien='https://www.welcometothejungle.com/fr/companies/follow-health/jobs/product-manager',
         Contrat='CDI', Localisation='Non précisé', Remote='Oui', **{'Fit / Notes': 'Télétravail total, secteur santé'}, **{'CV à envoyer': 'PM_FR'}),

    dict(Priorité='⭐⭐⭐⭐', Poste='Solutions Engineer (EMEA)', Entreprise='Photoroom', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/photoroom/c8f8c8f4-a6dd-4c73-b9e7-f445c611f970/application',
         Contrat='Non précisé', Localisation='Remote-friendly', Remote='Oui', **{'Fit / Notes': 'Startup française, avant-vente technique'}),
    dict(Priorité='⭐⭐⭐', Poste='Solutions Engineer, EMEA', Entreprise='Vantage', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/vantageanalytics/de65de6c-f1b6-41c4-81dc-5f15ebabc8c2',
         Contrat='Non précisé', Localisation='EMEA', Remote='Non précisé', **{'Fit / Notes': 'Analytics B2B, avant-vente'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Solutions Engineer, EMEA', Entreprise='Fieldguide', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/fieldguide/1f8de65a-7748-4753-bbb2-81898b0ee156',
         Contrat='Non précisé', Localisation='Remote-first', Remote='Oui', **{'Fit / Notes': 'Audit/compliance SaaS'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Solutions Engineer, Enterprise (EMEA)', Entreprise='Docker', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/docker/caf7e8f5-a6bf-482c-9393-fa09745d28c4',
         Contrat='Non précisé', Localisation='Remote EMEA', Remote='Oui', **{'Fit / Notes': 'Marque forte'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Solutions Engineer (EMEA)', Entreprise='Docker', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/docker/25acf9d4-2ed8-4a62-9f01-c314bf450522',
         Contrat='Non précisé', Localisation='Remote EMEA', Remote='Oui', **{'Fit / Notes': 'Poste ouvert en parallèle'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Partner Solutions Engineer (EMEA)', Entreprise='Docker', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/docker/45df55d1-c122-4b51-b4af-1f4b5d940c32',
         Contrat='Non précisé', Localisation='Remote EMEA', Remote='Oui', **{'Fit / Notes': 'Orienté partenaires'}),
    dict(Priorité='⭐⭐⭐', Poste='Solutions Engineer - EMEA', Entreprise='Qdrant', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/qdrant.tech/e20d73c8-35fe-47a7-9bfc-00fc824dcbf9',
         Contrat='Non précisé', Localisation='Europe', Remote='Non précisé', **{'Fit / Notes': 'Base de données vectorielle'}),
    dict(Priorité='⭐⭐⭐', Poste='Solutions Engineer - EMEA', Entreprise='Vapi', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/vapi/dce1928f-b432-4d6b-8c2f-b7c63c672310',
         Contrat='Non précisé', Localisation='Amsterdam, remote', Remote='Oui', **{'Fit / Notes': 'Filon Ashby récurrent'}),
    dict(Priorité='⭐⭐⭐', Poste='Senior Solutions Engineer (Pre-Sales) EMEA', Entreprise='Omni', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/omni/6f7d41f0-c449-44be-845c-2fbdf226d0fa',
         Contrat='Non précisé', Localisation='EMEA', Remote='Non précisé', **{'Fit / Notes': 'BI/analytics'}),
    dict(Priorité='⭐⭐⭐', Poste='Senior Enterprise Sales Engineer', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/a2bc865a-6cd2-4f34-b8d7-6879a3e4ae4e',
         Contrat='Non précisé', Localisation='France, full remote Europe', Remote='Oui'),
    dict(Priorité='⭐⭐⭐⭐', Poste='Sales Engineer - EN & FR speaker', Entreprise='Brevo', Source='Lever',
         Lien='https://jobs.lever.co/brevo/f45e3f5d-9a14-4df9-b101-97dc745d6217',
         Contrat='Non précisé', Localisation='Non précisé', Remote='Non précisé', **{'Fit / Notes': 'Éditeur SaaS FR (ex-Sendinblue), bilingue requis'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Sales Engineer', Entreprise='360Learning', Source='Lever',
         Lien='https://jobs.lever.co/360learning/4b9c2287-1b71-48a7-964d-2a04d3b2354b',
         Contrat='CDI', Localisation='France, full remote', Remote='Oui', **{'Fit / Notes': 'Intersection Sales/Product/CS'}),
    dict(Priorité='⭐⭐⭐', Poste='Remote Solutions Consultant', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/160e96fd-9be1-40cb-98c7-f26365896ab2',
         Contrat='Non précisé', Localisation='Remote', Remote='Oui'),
    dict(Priorité='⭐⭐⭐', Poste='Sales Systems Engineer', Entreprise='Loft Orbital', Source='Lever',
         Lien='https://jobs.lever.co/loftorbital/62f63c69-9dd3-4f02-b596-5ebb15d0efb1',
         Contrat='Non précisé', Localisation='Remote, France/Toulouse', Remote='Oui', **{'Fit / Notes': 'Secteur spatial, technique'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Technical Account Manager (EMEA)', Entreprise='Hightouch', Source='WTTJ',
         Lien='https://www.welcometothejungle.com/en/companies/hightouch/jobs/technical-account-manager_fr_r77mke4p',
         Contrat='CDI, full remote', Localisation='London/Paris/Remote EMEA', Remote='Oui', **{'Fit / Notes': 'Bon fit TAM'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Solutions Consultant, Global Payroll - EMEA', Entreprise='Remote.com', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/remotecom/jobs/7570194003',
         Contrat='Non précisé', Localisation='Remote EMEA', Remote='Oui', **{'Salaire / TJM': '61 950-139 400 USD/an', 'Fit / Notes': 'Avant-vente + HRIS/payroll, éditeur le mieux aligné'}),

    dict(Priorité='⭐⭐⭐⭐', Poste='ERP Implementation Consultant, HCM (Tyler Munis)', Entreprise='American Operator', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/americanoperator/59422576-8708-473e-a19e-c12cfee9d5bc',
         Contrat='Non précisé', Localisation='Remote, 25-50% déplacements', Remote='Oui', **{'Fit / Notes': 'HCM implementation'}),
    dict(Priorité='⭐⭐⭐', Poste='Implementation Consultant (CRM, Automation, Data, AI)', Entreprise='Swans', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/swans/92cccf95-5548-44f5-8044-8b2d926b766a',
         Contrat='Non précisé', Localisation='Non précisé', Remote='Non précisé', **{'Fit / Notes': 'Croisement implementation + IA'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Professional Services Consultant (Self Service), EMEA', Entreprise='Abnormal AI', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/abnormalsecurity/jobs/7809574003',
         Contrat='Non précisé', Localisation='Remote-Ireland', Remote='Oui', **{'Fit / Notes': 'Cybersécurité SaaS, déploiements haut volume'}),
    dict(Priorité='⭐⭐⭐', Poste='Team Manager, Technical Account Manager', Entreprise='Veeam', Source='WebSearch',
         Lien='https://careers.veeam.com/job/paris/team-manager-technical-account-manager/22681/88559684512',
         Contrat='Non précisé', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'Encadrement TAM, éditeur backup/data protection'}),
    dict(Priorité='⭐⭐⭐', Poste='Data Migration Consultant', Entreprise='Veeva Systems', Source='Lever',
         Lien='https://jobs.lever.co/veeva/6ce96f00-ba0e-48c5-89e7-bc4a69098ae7',
         Contrat='CDI, full remote', Localisation='Non précisé', Remote='Oui', **{'Fit / Notes': 'Migration de données, life sciences'}),
    dict(Priorité='⭐⭐⭐', Poste='Senior Migration Consultant - R&D (Remote)', Entreprise='Veeva Systems', Source='Lever',
         Lien='https://jobs.lever.co/veeva/c9cf5293-3695-438f-8277-74c9309c56ee',
         Contrat='Non précisé', Localisation='Remote', Remote='Oui', **{'Fit / Notes': 'Niveau senior'}),
    dict(Priorité='⭐⭐⭐', Poste='Senior Migration Consultant', Entreprise='Veeva Systems', Source='Lever',
         Lien='https://jobs.lever.co/veeva/227c4f6e-1a43-434f-a902-9835a0f82b10',
         Contrat='Non précisé', Localisation='Non précisé', Remote='Non précisé'),

    # ── Cluster 4 : API ATS + éditeurs HRIS ─────────────────────────────
    dict(Priorité='⭐⭐⭐⭐', Poste='Regional Manager, Customer Success EMEA', Entreprise='Constructor', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/constructor/5f24d378-f17b-4032-a2cc-079fd670563d',
         Contrat='CDI', Localisation='Remote', Remote='Oui', **{'Fit / Notes': 'CSM EMEA'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Product Manager - Merchant Intelligence and Analytics', Entreprise='Constructor', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/constructor/e7426b59-431b-418b-a501-dde7f13b21bf',
         Contrat='CDI', Localisation='Remote', Remote='Oui', **{'Fit / Notes': 'PM plateforme B2B'}, **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Product Manager: Recall', Entreprise='Constructor', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/constructor/7bc86d05-145d-4b7c-aa6e-b0b207d46117',
         Contrat='CDI', Localisation='Remote EMEA', Remote='Oui', **{'Fit / Notes': 'PM plateforme B2B'}, **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐', Poste='Sales Engineer (DACH)', Entreprise='Constructor', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/constructor/3b1910b4-f99a-4011-8e83-839cc6d74b29',
         Contrat='CDI', Localisation='Remote Allemagne', Remote='Oui', **{'Fit / Notes': 'Solutions/Sales Engineer'}),
    dict(Priorité='⭐⭐⭐', Poste='Enterprise Solutions Engineer - France', Entreprise='ElevenLabs', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/elevenlabs/ce00fe7b-a93a-436b-bd5e-2eff87c48f23',
         Contrat='CDI', Localisation='France', Remote='Présentiel', **{'Fit / Notes': 'Solutions Engineer France mais sur site'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Customer Success Lead - UK/I', Entreprise='ElevenLabs', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/elevenlabs/8f37f4e5-83f8-4e7d-b3b6-b5b406bf4eb9',
         Contrat='CDI', Localisation='UK, remote', Remote='Oui', **{'Fit / Notes': 'CSM EMEA'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Customer Success - Southern Europe', Entreprise='ElevenLabs', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/elevenlabs/78c564eb-ee87-46d9-b2fd-4322a223a547',
         Contrat='CDI', Localisation='Espagne, remote', Remote='Oui', **{'Fit / Notes': 'CSM EMEA'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Customer Success - DACH', Entreprise='ElevenLabs', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/elevenlabs/830e66a8-892c-4c68-b61c-494591236eef',
         Contrat='CDI', Localisation='Allemagne, remote', Remote='Oui', **{'Fit / Notes': 'CSM EMEA'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Enterprise Solutions Engineer - Netherlands', Entreprise='ElevenLabs', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/elevenlabs/3f10ccc9-56a9-40bf-b5f1-33ab5834ff4a',
         Contrat='CDI', Localisation='Pays-Bas, remote', Remote='Oui', **{'Fit / Notes': 'Solutions Engineer EMEA'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Manager, Customer Success (Remote-EMEA)', Entreprise='n8n', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/n8n/018bb06a-6147-4e04-aa4b-8a9daf0558bd',
         Contrat='CDI', Localisation='Remote EMEA', Remote='Oui', **{'Fit / Notes': 'CSM management EMEA'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Senior Customer Success Manager (EMEA)', Entreprise='n8n', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/n8n/ffafc55a-6fcc-4dfb-aef2-7979391d3ffb',
         Contrat='CDI', Localisation='Remote EMEA', Remote='Oui', **{'Fit / Notes': 'CSM senior EMEA'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Technical Programs Manager - Scaled Customer Success (Remote Europe)', Entreprise='n8n', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/n8n/d550716c-8cb9-4efe-9a52-b4cd67e193e1',
         Contrat='CDI', Localisation='Allemagne, remote Europe', Remote='Oui', **{'Fit / Notes': 'Croisement PM/CS'}),
    dict(Priorité='⭐⭐⭐', Poste='Head of Solutions Engineering', Entreprise='n8n', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/n8n/443fd5c2-6501-45cf-b8c8-851fe94d48f9',
         Contrat='CDI', Localisation='Berlin (bureau)', Remote='Non précisé', **{'Fit / Notes': 'Solutions Engineering leadership'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Manager of Dedicated Implementations - EMEA', Entreprise='Ashby', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/ashby/35a01a05-8efd-4bc3-a4bf-0a31d902102d',
         Contrat='CDI', Localisation='Remote UE', Remote='Oui', **{'Fit / Notes': 'Implementation'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Strategic Customer Success Manager - EMEA', Entreprise='Ashby', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/ashby/1cf7c730-caba-4fc3-8b98-52a0735ef14b',
         Contrat='CDI', Localisation='Remote UE', Remote='Oui', **{'Fit / Notes': 'CSM stratégique EMEA'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Senior Customer Success Manager - France', Entreprise='Alan', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/alan/fb56b456-c00c-418c-b5b9-ea3aee8a2169',
         Contrat='CDI', Localisation='Paris, remote', Remote='Oui', **{'Fit / Notes': 'CSM France, filon récurrent'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Operational Onboarding Manager - France', Entreprise='Alan', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/alan/149e6bff-b83d-4f7f-bfa8-9eb251bf437c',
         Contrat='CDI', Localisation='France entière, remote', Remote='Oui', **{'Fit / Notes': 'Onboarding/implementation'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager - Sales AI', Entreprise='Alan', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/alan/7c57f914-4542-40d1-84c2-b3ac02154967',
         Contrat='CDI', Localisation='Paris/Lyon/Marseille/Bordeaux', Remote='Oui', **{'Fit / Notes': 'PM France'}, **{'CV à envoyer': 'PM_FR'}),
    dict(Priorité='⭐⭐⭐', Poste='Key Account Manager', Entreprise='Alan', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/alan/95e2e61d-9720-496a-aac5-7b7266a3ef7e',
         Contrat='CDI', Localisation='Paris/Bordeaux', Remote='Oui', **{'Fit / Notes': 'Account Manager France'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Customer Success Manager - Medium Accounts', Entreprise='Pennylane', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/pennylane/d9c454b4-11ab-49f3-9ffe-4b444aecb99d',
         Contrat='CDI', Localisation='France, remote', Remote='Oui', **{'Fit / Notes': 'CSM, filon récurrent'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Customer Success Manager - SAAS', Entreprise='Pennylane', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/pennylane/9f24fb70-d2bb-496f-9ed3-02bb9c9d7ad0',
         Contrat='CDI', Localisation='France entière, remote', Remote='Oui', **{'Fit / Notes': 'CSM France remote'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Product Manager', Entreprise='Pennylane', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/pennylane/a4555925-195a-4a59-9367-fcaf27f2113d',
         Contrat='CDI', Localisation='Paris, remote', Remote='Oui', **{'Fit / Notes': 'PM France'}, **{'CV à envoyer': 'PM_FR'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Chef de Projet Fonctionnel – Migration Comptable', Entreprise='Pennylane', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/pennylane/c0db03d4-9a12-4015-821c-16e16b8c2936',
         Contrat='CDI', Localisation='France entière, remote', Remote='Oui', **{'Fit / Notes': 'Data Migration Lead'}),
    dict(Priorité='⭐⭐⭐', Poste='Training Manager / Responsable de Formation - région PACA', Entreprise='Pennylane', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/pennylane/abb59e6e-d876-4b9d-b185-2d06c84084aa',
         Contrat='CDI', Localisation='PACA, remote', Remote='Oui', **{'Fit / Notes': 'Formateur, transfert de connaissances'}),
    dict(Priorité='⭐⭐⭐', Poste='Product Manager - Security & Trust (EMEA/AMER)', Entreprise='Supabase', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/supabase/b8010a28-109c-46a9-b8b7-c7f9b24077fa',
         Contrat='CDI', Localisation='Remote (monde)', Remote='Oui', **{'Fit / Notes': 'PM produit dev-orienté, lacune connue à assumer'}, **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐', Poste='Commercial Solutions Engineer - EMEA', Entreprise='Dash0', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/dash0/88dc8222-497c-4d58-ad5b-e862a6602c51',
         Contrat='CDI', Localisation='EMEA-Remote', Remote='Oui', **{'Fit / Notes': 'Solutions Engineer EMEA'}),
    dict(Priorité='⭐⭐⭐', Poste='Enterprise Solutions Engineer - EMEA', Entreprise='Dash0', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/dash0/d7fa3468-1e5c-4109-bdcf-0fa0f2f9c15b',
         Contrat='CDI', Localisation='EMEA-Remote', Remote='Oui', **{'Fit / Notes': 'Solutions Engineer EMEA'}),
    dict(Priorité='⭐⭐', Poste='Commercial Solutions Engineer - Nordics', Entreprise='Dash0', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/dash0/31c63bf9-c837-43c4-9deb-ba0da290cdd7',
         Contrat='CDI', Localisation='EMEA-Remote', Remote='Oui', **{'Fit / Notes': 'Solutions Engineer EMEA (Nordics)'}),
    dict(Priorité='⭐⭐', Poste='Enterprise Solutions Engineer - Nordics', Entreprise='Dash0', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/dash0/eee66924-267e-4731-803f-85a43866bc9c',
         Contrat='CDI', Localisation='EMEA-Remote', Remote='Oui', **{'Fit / Notes': 'Solutions Engineer EMEA (Nordics)'}),
    dict(Priorité='⭐⭐⭐', Poste='Enterprise Solutions Engineer - UK', Entreprise='Dash0', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/dash0/6526471a-8f48-425c-9329-2a8dcb175783',
         Contrat='CDI', Localisation='EMEA-Remote', Remote='Oui', **{'Fit / Notes': 'Solutions Engineer EMEA'}),
    dict(Priorité='⭐⭐⭐', Poste='Technical Account Manager - Benelux', Entreprise='Camunda', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/camunda/d5ce4070-2d06-4529-956f-a93d05eefd99',
         Contrat='CDI', Localisation='Pays-Bas, remote', Remote='Oui', **{'Fit / Notes': 'TAM EMEA'}),
    dict(Priorité='⭐⭐⭐', Poste='Technical Account Manager - DACH', Entreprise='Camunda', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/camunda/05070fb6-de7a-4a03-b885-442032da57ec',
         Contrat='CDI', Localisation='Allemagne, remote', Remote='Oui', **{'Fit / Notes': 'TAM EMEA'}),
    dict(Priorité='⭐⭐⭐', Poste='Senior Sales Engineer UK', Entreprise='Camunda', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/camunda/f1a149e1-8f94-4c69-ab23-9bf79fe4770c',
         Contrat='CDI', Localisation='UK, remote', Remote='Oui', **{'Fit / Notes': 'Sales Engineer'}),
    dict(Priorité='⭐⭐⭐', Poste='Solutions Integration Architect - SAP', Entreprise='Zip', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/zip/3318e15f-0fb7-4a1a-9a06-9cc6e13a0aec',
         Contrat='CDI', Localisation='Londres, remote', Remote='Oui', **{'Fit / Notes': 'SAP + intégration système'}),
    dict(Priorité='⭐⭐⭐', Poste='Senior ERP Solutions Consultant', Entreprise='Zip', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/zip/8529f344-71e2-4fcf-944a-c8457e71faa1',
         Contrat='CDI', Localisation='Remote Allemagne', Remote='Oui', **{'Fit / Notes': 'ERP consultant'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Customer Success Manager', Entreprise='Zip', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/zip/a0f04025-e8e7-4164-b02c-d167371e035a',
         Contrat='CDI', Localisation='Londres, remote', Remote='Oui', **{'Fit / Notes': 'CSM'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Customer Success Manager - EMEA', Entreprise='Tilla', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/tilla/823e58d1-e986-42d9-9441-47f31bb77a52',
         Contrat='CDI', Localisation='Grèce, remote', Remote='Oui', **{'Fit / Notes': 'CSM EMEA'}),
    dict(Priorité='⭐⭐⭐', Poste='Customer Success Manager - France', Entreprise='Cohere', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/cohere/597e18f5-c33c-4350-8bcd-05a751cece3a',
         Contrat='CDI', Localisation='France', Remote='Non précisé', **{'Fit / Notes': 'CSM France, croisement IA'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='GRC Pre-Sales Consultant / Solutions Engineer – French Market, EMEA', Entreprise='Vanta', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/vanta/0c4739ee-dfb0-4d01-be48-b6a18b6f95ce',
         Contrat='CDI', Localisation='EMEA (French Market)', Remote='Oui', **{'Fit / Notes': 'Pre-sales, marché français'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Solutions Engineer (Upmarket, Pre-Sales) - EMEA [French Fluency]', Entreprise='Vanta', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/vanta/3be92c58-f17f-427b-8d78-bc1dda8affd1',
         Contrat='CDI', Localisation='EMEA', Remote='Oui', **{'Fit / Notes': 'Pre-sales francophone'}),
    dict(Priorité='⭐⭐⭐', Poste='Manager, Solutions Engineering - EMEA', Entreprise='Vanta', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/vanta/2daebe8c-69af-44f3-a81f-38fb17da30a0',
         Contrat='CDI', Localisation='Londres, remote', Remote='Oui', **{'Fit / Notes': 'Management Solutions Engineering'}),
    dict(Priorité='⭐⭐⭐', Poste='Channel Manager, France [French Fluency]', Entreprise='Vanta', Source='Ashby',
         Lien='https://jobs.ashbyhq.com/vanta/6714d9a8-2080-4c97-8314-031f426281da',
         Contrat='CDI', Localisation='Londres, remote', Remote='Oui', **{'Fit / Notes': 'Account/Channel France'}),

    dict(Priorité='⭐⭐⭐', Poste='Commercial IT Team Lead – Data Migration', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/1fdcee08-6ad7-4dec-af34-b21f03b5e9dc',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'Fit / Notes': 'Data Migration Lead'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Customer Success Manager', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/bbf57ea5-fdfc-458b-841b-f49d0704e96d',
         Contrat='Non précisé', Localisation='France', Remote='Oui'),
    dict(Priorité='⭐⭐⭐⭐', Poste='Director of Customer Success', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/188b3da3-6e29-455f-af5e-a2e7a62aee4b',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'Fit / Notes': 'CSM leadership'}),
    dict(Priorité='⭐⭐⭐', Poste='Enterprise Migrations Engineer', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/4dc89cde-5c5a-46cc-8034-835b458a36f7',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'Fit / Notes': 'Data Migration'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Group Product Manager - Platform Experience', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/3d05c794-a034-48cf-918c-14933214114b',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Product Manager (Internal HRIS / HR Tech)', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/c47e031c-99f7-4fb6-aff9-36d2d7f3593e',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'Fit / Notes': 'PM HRIS, excellent fit'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager (Senior/Staff-level)', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/2ff29dcf-3553-4f81-9eb1-04b55d085a58',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Product Manager', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/a5a8bf12-9b94-4d4c-a39e-ce4c0351f9fb',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐', Poste='Service Delivery Senior Manager – Software Publisher Services', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/2234c712-f2fa-4ec0-b6e3-4da2d048badb',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'Fit / Notes': 'Implementation/Professional Services'}),
    dict(Priorité='⭐⭐⭐', Poste='SMB Account Manager', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/170d75f7-38b2-4792-8502-469e704636e6',
         Contrat='Non précisé', Localisation='France', Remote='Oui'),
    dict(Priorité='⭐⭐⭐', Poste='Technical Account Manager', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/287fb3ac-1df4-43e4-9125-bf4f109ee898',
         Contrat='Non précisé', Localisation='France', Remote='Oui'),
    dict(Priorité='⭐⭐⭐⭐', Poste='Technical Product Manager – GenAI Programmes', Entreprise='N/C (via Jobgether)', Source='Lever',
         Lien='https://jobs.lever.co/jobgether/24b1bb55-b737-4786-9e20-59bd969da871',
         Contrat='Non précisé', Localisation='France', Remote='Oui', **{'Fit / Notes': 'PM + croisement IA'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐', Poste='Mid-Market Customer Success Manager EMEA', Entreprise='Teramind', Source='Lever',
         Lien='https://jobs.lever.co/teramind/20c481dc-06b9-41da-99b7-9be053d5b5f7',
         Contrat='Non précisé', Localisation='Pologne', Remote='Oui', **{'Fit / Notes': 'CSM EMEA'}),
    dict(Priorité='⭐⭐', Poste='Enterprise Account Manager, France', Entreprise='Contentsquare', Source='Lever',
         Lien='https://jobs.lever.co/contentsquare/39dd5542-7e2d-4bd4-867a-921b2083748c',
         Contrat='Non précisé', Localisation='Paris', Remote='Hybride'),
    dict(Priorité='⭐⭐', Poste='Senior Product Manager - User and Lifecycle Analytics', Entreprise='Contentsquare', Source='Lever',
         Lien='https://jobs.lever.co/contentsquare/2f1fa0dc-bc37-43ac-85c8-734fc719e03a',
         Contrat='Non précisé', Localisation='Paris', Remote='Hybride'),
    dict(Priorité='⭐⭐', Poste='Customer Solutions Engineer Paris', Entreprise='Scality', Source='Lever',
         Lien='https://jobs.lever.co/scality/fd966dc8-4f44-4735-81a3-7d4bd16ba342',
         Contrat='Non précisé', Localisation='Paris', Remote='Hybride'),

    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Account Manager - EMEA', Entreprise='Remote.com', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/remotecom/jobs/7834363003',
         Contrat='CDI', Localisation='Remote-EMEA', Remote='Oui'),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Customer Success Architect, EMEA', Entreprise='GitLab', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/gitlab/jobs/8561952002',
         Contrat='CDI', Localisation='Remote, France/Autriche/Allemagne', Remote='Oui', **{'Fit / Notes': 'CSM technique, France explicitement listée'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Solutions Architect - France', Entreprise='GitLab', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/gitlab/jobs/8656506002',
         Contrat='CDI', Localisation='Remote, France', Remote='Oui', **{'Fit / Notes': 'Solutions Architect France explicite'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Manager, Customer Success Managers, EMEA', Entreprise='GitLab', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/gitlab/jobs/8613199002',
         Contrat='CDI', Localisation='Remote, Autriche/Allemagne', Remote='Oui', **{'Fit / Notes': 'CSM management EMEA'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Professional Services Project Manager (EMEA)', Entreprise='GitLab', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/gitlab/jobs/8622433002',
         Contrat='CDI', Localisation='Remote', Remote='Oui', **{'Fit / Notes': 'Professional Services PM'}),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Enterprise Customer Success Manager (French speaker)', Entreprise='Canonical', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/canonical/jobs/7084000',
         Contrat='CDI', Localisation='Home based - EMEA', Remote='Oui', **{'Fit / Notes': 'CSM francophone, excellent fit'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager', Entreprise='Canonical', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/canonical/jobs/5029257',
         Contrat='CDI', Localisation='Home based - EMEA', Remote='Oui', **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Product Manager - AI', Entreprise='Canonical', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/canonical/jobs/6643476',
         Contrat='CDI', Localisation='Home based - EMEA', Remote='Oui', **{'Fit / Notes': 'PM + croisement IA'}, **{'CV à envoyer': 'PM_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Technical Product Manager', Entreprise='Canonical', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/canonical/jobs/6980703',
         Contrat='CDI', Localisation='Home based - EMEA', Remote='Oui', **{'CV à envoyer': 'PM_Platform_EN'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Solutions Engineer | France | Remote', Entreprise='Grafana Labs', Source='Greenhouse',
         Lien='https://job-boards.greenhouse.io/grafanalabs/jobs/6121627004',
         Contrat='CDI', Localisation='France', Remote='Oui', **{'Fit / Notes': 'Aucune langue requise'}),
    dict(Priorité='⭐⭐⭐', Poste='Senior Manager, Solutions Engineering Pre-Sales, Northern Europe', Entreprise='Cloudflare', Source='Greenhouse',
         Lien='https://boards.greenhouse.io/cloudflare/jobs/7439830?gh_jid=7439830',
         Contrat='CDI', Localisation='Distribué', Remote='Oui', **{'Fit / Notes': 'Pre-sales management EMEA'}),

    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Account Manager, Strategic - France', Entreprise='Atlassian', Source='API carrières Atlassian',
         Lien='https://globalcareers-atlassian.icims.com/jobs/25256/account-manager%2c-strategic---france/job',
         Contrat='Non précisé', Localisation='France', Remote='Oui'),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Principal Customer Success Manager, Strategic, France', Entreprise='Atlassian', Source='API carrières Atlassian',
         Lien='https://globalcareers-atlassian.icims.com/jobs/26057/principal-customer-success-manager%2c-strategic%2c-france/job',
         Contrat='Non précisé', Localisation='France/Paris', Remote='Oui'),
    dict(Priorité='⭐⭐⭐⭐⭐', Poste='Senior Principal Customer Success Manager, Strategic - France', Entreprise='Atlassian', Source='API carrières Atlassian',
         Lien='https://globalcareers-atlassian.icims.com/jobs/26241/senior-principal-customer-success-manager%2c-strategic---france/job',
         Contrat='Non précisé', Localisation='Paris/Remote', Remote='Oui'),
    dict(Priorité='⭐⭐⭐⭐', Poste='Senior Services Solutions Advocate', Entreprise='Atlassian', Source='API carrières Atlassian',
         Lien='https://globalcareers-atlassian.icims.com/jobs/26249/senior-services-solutions-advocate/job',
         Contrat='Non précisé', Localisation='Paris/Remote France', Remote='Oui'),
    dict(Priorité='⭐⭐⭐⭐', Poste='Strategic Solutions Sales Executive - Southern Europe', Entreprise='Atlassian', Source='API carrières Atlassian',
         Lien='https://globalcareers-atlassian.icims.com/jobs/25170/strategic-solutions-sales-executive---southern-europe/job',
         Contrat='Non précisé', Localisation='Paris/Remote France', Remote='Oui'),
    dict(Priorité='⭐⭐⭐', Poste='Manager, Account Executives, Enterprise (Southern Europe)', Entreprise='Atlassian', Source='API carrières Atlassian',
         Lien='https://globalcareers-atlassian.icims.com/jobs/25552/manager%2c-account-executives%2c-enterprise-%28southern-europe%29/job',
         Contrat='Non précisé', Localisation='Remote France (parmi autres)', Remote='Oui'),
    dict(Priorité='⭐⭐⭐', Poste='Field CTO - EMEA, DX', Entreprise='Atlassian', Source='API carrières Atlassian',
         Lien='https://globalcareers-atlassian.icims.com/jobs/24899/field-cto---emea%2c-dx/job',
         Contrat='Non précisé', Localisation='Remote France (parmi autres)', Remote='Oui'),

    dict(Priorité='⭐⭐⭐', Poste='Consultant SAP HCM Time senior', Entreprise='Strada (ex-Alight)', Source='Alight careers',
         Lien='https://careers.alight.com/strada/us/en/job/ALIGUSR27913STRADAENUS/Consultant-SAP-HCM-Time-senior',
         Contrat='CDI', Localisation='Colombes', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐', Poste='Consultant SAP HCM Paie senior', Entreprise='Strada (ex-Alight)', Source='Alight careers',
         Lien='https://careers.alight.com/strada/us/en/job/ALIGUSR27911STRADAENUS/Consultant-SAP-HCM-Paie-senior',
         Contrat='CDI', Localisation='Colombes', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐', Poste='Senior SAP HCM Payroll', Entreprise='Strada (ex-Alight)', Source='Alight careers',
         Lien='https://careers.alight.com/strada/us/en/job/ALIGUSR30184STRADAENUS/Senior-SAP-HCM-Payroll',
         Contrat='CDI', Localisation='Lyon', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐⭐', Poste='Solution Consultant HCM - Mid market France', Entreprise='Workday', Source='Workday careers',
         Lien='https://workday.wd5.myworkdayjobs.com/en-US/Workday/job/France-Paris/Solution-Consultant-HCM_JR-0088671',
         Contrat='CDI', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'Pre-sales'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Solution Consultant HCM', Entreprise='Workday', Source='Workday careers',
         Lien='https://workday.wd5.myworkdayjobs.com/en-US/Workday/job/France-Paris/Solution-Consultant-HCM_JR-0108989',
         Contrat='CDI', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'Pre-sales, segment large entreprise'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant Fonctionnel Confirmé HR Access', Entreprise='Inetum', Source='Inetum careers',
         Lien='https://www.inetum.com/fr/accueil/carrieres/4fb67a0a-5fa6-48b8-9c1a-0df7767ee7e3.html',
         Contrat='CDI', Localisation='France', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐', Poste='Consultant Support Client SIRH', Entreprise='Cegid', Source='Cegid careers',
         Lien='https://jobs.cegid.com/fr/annonce/3606181-consultant-support-client-sirh-fhnb-44300-nantes',
         Contrat='CDI', Localisation='Nantes', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐', Poste='Consultant Progiciel SIRH Paie', Entreprise='Cegid', Source='Cegid careers',
         Lien='https://jobs.cegid.com/fr/annonce/4122085-consultant-progiciel-sirh-paie-fhnb-69009-lyon',
         Contrat='CDI', Localisation='Lyon', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐', Poste='Consultant SIRH Paie', Entreprise='Cegid', Source='Cegid careers',
         Lien='https://jobs.cegid.com/fr/annonce/3815603-consultant-sirh-paie-fhnb-69009-lyon',
         Contrat='CDI', Localisation='Lyon', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐⭐', Poste='Consultant Customer Success - Grands Comptes', Entreprise='Lucca', Source='Lucca careers',
         Lien='https://jobs.world.luccasoftware.com/lucca/customer-success-sirh-grands-comptes-8d12e285-9f5c-4dcd-ba4c-661c80abe25c',
         Contrat='CDI', Localisation='Paris', Remote='Non précisé', **{'Fit / Notes': 'CSM SIRH grands comptes'}),
    dict(Priorité='⭐⭐⭐⭐', Poste='Consultant Customer Success - Grands Comptes', Entreprise='Lucca', Source='Lucca careers',
         Lien='https://jobs.world.luccasoftware.com/lucca/customer-success-sirh-grands-comptes-nantes-10a4ef2b-bfce-4a51-bbcd-1ea1554a6f6b',
         Contrat='CDI', Localisation='Nantes', Remote='Non précisé', **{'Fit / Notes': 'CSM SIRH grands comptes'}),
    dict(Priorité='⭐⭐⭐', Poste='Consultant Customer Success Junior - Mid-Market', Entreprise='Lucca', Source='Lucca careers',
         Lien='https://jobs.world.luccasoftware.com/lucca/customer-success-sirh-midmarket-junior-25b26c0d-574e-4559-8d2d-bdc90699c3d5',
         Contrat='CDI', Localisation='Paris', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐', Poste='Consultant Customer Success Junior - Mid-Market', Entreprise='Lucca', Source='Lucca careers',
         Lien='https://jobs.world.luccasoftware.com/lucca/customer-success-sirh-midmarket-junior-fc069879-3773-4524-ae17-2325b840c370',
         Contrat='CDI', Localisation='Nantes', Remote='Non précisé'),
    dict(Priorité='⭐⭐⭐', Poste='Product Manager - Solution « Rémunération »', Entreprise='Lucca', Source='Lucca careers',
         Lien='https://jobs.world.luccasoftware.com/lucca/product-manager--solution-remuneration-7eb65e52-850a-4302-bc63-32aa52835ba3',
         Contrat='CDI', Localisation='Paris', Remote='Non précisé', **{'CV à envoyer': 'PM_FR'}),
]


def main():
    existants = liens_existants()
    a_ajouter = []
    vus = set()
    doublons_internes = 0
    doublons_base = 0
    for offre in OFFRES:
        lien = offre['Lien'].strip().rstrip('/')
        if lien in existants:
            doublons_base += 1
            continue
        if lien in vus:
            doublons_internes += 1
            continue
        vus.add(lien)
        a_ajouter.append(offre)

    print(f"Compilé : {len(OFFRES)} offres brutes")
    print(f"Déjà en base (ignorées) : {doublons_base}")
    print(f"Doublons internes (ignorés) : {doublons_internes}")
    print(f"À ajouter : {len(a_ajouter)}")

    ajouter_offres(a_ajouter)


if __name__ == '__main__':
    main()
