# -*- coding: utf-8 -*-
"""Ajout des offres trouvées lors de la relance du 10/09/2026 (4 clusters parallèles)."""

from add_offre import ajouter_offres

AUJOURDHUI = "2026-09-10"

offres = [
    # ───────────── Offres SIRH ─────────────
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Manager SIRH',
        'Entreprise': 'Le Groupe Septeo', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/81180837.html',
        'Contrat': 'CDI', 'Localisation': 'Lyon', 'Remote': 'Non précisé',
        'Fit / Notes': 'Croisement Product Manager + SIRH, très bon fit.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Responsable SIRH Paie',
        'Entreprise': 'BYS Consulting', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83193476.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Salaire / TJM': '55-65K€',
        'Fit / Notes': 'Pilotage SIRH/paie senior.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Consultant Paie & AMOA SIRH',
        'Entreprise': 'Convictions RH', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83210870.html',
        'Contrat': 'CDI', 'Localisation': 'Paris/France', 'Remote': 'Non précisé',
        'Salaire / TJM': '46-70K€',
        'Fit / Notes': 'AMOA SIRH, cœur de cible.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Consultant AMOA SAP SuccessFactors',
        'Entreprise': 'Convictions RH', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83210612.html',
        'Contrat': 'CDI', 'Localisation': 'Paris/France', 'Remote': 'Non précisé',
        'Salaire / TJM': '46-70K€',
        'Fit / Notes': 'AMOA SAP SuccessFactors, cœur de cible.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Consultant SIRH & Paie',
        'Entreprise': 'Cegedim', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83213431.html',
        'Contrat': 'CDI', 'Localisation': 'Lyon', 'Remote': 'Non précisé (télétravail possible après essai)',
        'Fit / Notes': 'Consultant SIRH/paie.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Consultant SIRH & Paie',
        'Entreprise': 'Cegedim', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83213476.html',
        'Contrat': 'CDI', 'Localisation': 'Lille', 'Remote': 'Non précisé (télétravail possible après essai)',
        'Fit / Notes': 'Consultant SIRH/paie, poste jumeau (ville différente).',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Responsable de Comptes SIRH & Paie',
        'Entreprise': 'Cegedim', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83213320.html',
        'Contrat': 'CDI', 'Localisation': 'Boulogne-Billancourt', 'Remote': 'Non précisé (télétravail possible après essai)',
        'Fit / Notes': 'Gestion de comptes SIRH, croisement CSM/SIRH.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Business Analyst - GED - SIRH',
        'Entreprise': 'Randstad Professional (client bancaire)', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83011925.html',
        'Contrat': 'CDI', 'Localisation': 'Toulouse', 'Remote': 'Non précisé',
        'Salaire / TJM': '50-53K€',
        'Fit / Notes': 'Dématérialisation/GED, volet data proche du profil technico-fonctionnel.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH2.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Implementation Consultant - French Market',
        'Entreprise': 'Agicap', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/55878158.html',
        'Contrat': 'CDI', 'Localisation': 'Lyon', 'Remote': 'Non précisé',
        'Fit / Notes': 'Famille Implementation Consultant, cœur de compétence.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Workday Lead Consultant',
        'Entreprise': 'HR Path', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82031619.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': 'Consultant HRIS senior (Workday plutôt que SAP).',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Workday Talent Lead Consultant',
        'Entreprise': 'HR Path', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82031656.html',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Non précisé',
        'Fit / Notes': 'Consultant HRIS senior (Workday).',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Workday LMS Lead Consultant',
        'Entreprise': 'HR Path', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82031664.html',
        'Contrat': 'CDI', 'Localisation': 'France', 'Remote': 'Non précisé',
        'Fit / Notes': 'Consultant HRIS senior, module LMS (Workday).',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Avant-vente - Business Dev S4HANA System Integration',
        'Entreprise': 'EY', 'Source': 'careers.ey.com',
        'Lien': 'https://careers.ey.com/ey/job/Paris-La-D%C3%A9fense-Avant-vente-Business-Dev-S4HANA-System-Integration-92037/1385667333/',
        'Contrat': 'CDI', 'Localisation': 'Paris La Défense', 'Remote': 'Non précisé',
        'Fit / Notes': 'Avant-vente technique SAP S/4HANA, proche de l\'appel d\'offres infogérance gagné chez ALTI-TCS.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH2.pdf', 'Date trouvée': AUJOURDHUI,
    },

    # ───────────── Offres CSM ─────────────
    {
        'Priorité': '⭐⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Account Manager',
        'Entreprise': 'AssessFirst', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83202761.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Oui (full remote Europe explicite)',
        'Fit / Notes': 'HR Tech (évaluation recrutement), remote confirmé dans le texte.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Customer Success Manager - Expérience Comptable',
        'Entreprise': 'RCA', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/82195678.html',
        'Contrat': 'CDI', 'Localisation': 'Bordeaux', 'Remote': 'Non précisé',
        'Fit / Notes': 'CSM éditeur logiciel comptable.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Customer Success Manager',
        'Entreprise': 'AXIOME ASSOCIES', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83193086.html',
        'Contrat': 'CDI', 'Localisation': 'Montpellier', 'Remote': 'Non précisé',
        'Salaire / TJM': '30-35K€',
        'Fit / Notes': 'CSM générique.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Responsable Déploiement et Performance IA',
        'Entreprise': 'Achil (client anonymisé, SaaS IA conversationnelle)', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83099209.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': 'CSM + IA, rattaché au Head of CS, très bon croisement.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Customer Success / Account Manager - Immobilier',
        'Entreprise': 'Realadvisor', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/customer-success-account-manager-immobilier-teletravail-f69563e7/',
        'Contrat': 'Freelance', 'Localisation': 'Télétravail', 'Remote': 'Oui (télétravail explicite)',
        'Fit / Notes': 'CSM plateforme SaaS immobilier.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Customer Success Manager',
        'Entreprise': 'Realadvisor', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/customer-success-manager-teletravail-8a4833c0/',
        'Contrat': 'Freelance', 'Localisation': 'Télétravail', 'Remote': 'Oui (télétravail explicite)',
        'Fit / Notes': 'CSM plateforme SaaS immobilier, même client que la mission précédente (contenu proche mais titres/descriptions distincts, republication à quelques semaines d\'intervalle plutôt que doublon strict).',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },

    # ───────────── Offres IA ─────────────
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Formateur·rice IA',
        'Entreprise': 'Simplon', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/formateur-rice-ia-bayonne-6742bcda/',
        'Contrat': 'Freelance', 'Localisation': 'Bayonne', 'Remote': 'Non précisé',
        'Fit / Notes': 'Accompagnement IA générative pour demandeurs d\'emploi, local Pays Basque.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },

    # ───────────── Offres PM ─────────────
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'AI Product Manager',
        'Entreprise': 'Client anonymisé (secteur luxe)', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/ai-product-manager-paris-2c63bde7/',
        'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': 'Vision produit IA générative/assistants conversationnels, croisement PM+IA.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_PM_FR.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Owner IA H/F',
        'Entreprise': 'Yunik', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/product-owner-ia-h-f-paris-75-dcba84fc/',
        'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': 'Déploiement/industrialisation IA générative secteur bancaire.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_PM_FR.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Manager Senior',
        'Entreprise': 'Yunik', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/product-manager-senior-paris-75-7f67cfb7/',
        'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': 'Même client que Product Owner IA, 2 postes ouverts en parallèle.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_PM_FR.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Manager - Fulfillment (Order & Dropship)',
        'Entreprise': 'Mirakl', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/product-manager-fulfillment-order-dropship-bordeaux-f7f365fe/',
        'Contrat': 'Freelance', 'Localisation': 'Bordeaux', 'Remote': 'Non précisé',
        'Fit / Notes': 'Scale-up française reconnue, PM confirmé.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_PM_FR.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Manager Senior',
        'Entreprise': 'Sapiens', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/product-manager-senior-paris-716b4ee8/',
        'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': 'Éditeur logiciels assurance.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_PM_FR.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Manager Expérimenté',
        'Entreprise': 'Theodo', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/product-manager-experimente-paris-75-cfe4790a/',
        'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Non précisé',
        'Fit / Notes': 'Agence dev reconnue.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_PM_FR.pdf', 'Date trouvée': AUJOURDHUI,
    },

    # ───────────── Offres USA ─────────────
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Forward Deployed Engineer - EMEA',
        'Entreprise': 'GitLab', 'Source': 'Greenhouse',
        'Lien': 'https://job-boards.greenhouse.io/gitlab/jobs/8522265002',
        'Contrat': 'CDI', 'Localisation': 'Remote Ireland/France/Germany/Netherlands/UK', 'Remote': 'Oui (EMEA explicite, France nommée)',
        'Fit / Notes': "Rôle technique (Python/Go, automatisation infra, DevOps), à la frontière du profil : le pont client-ingénierie et le déploiement rappellent Implementation/Data Migration mais la profondeur code est une vraie lacune à assumer honnêtement en LM.",
        'CV à envoyer': 'Resume_GaetanFRANCOIS_Ashby_EN.pdf', 'Date trouvée': AUJOURDHUI,
        'Onglet': 'Offres USA',
    },

    # ───────────── Pays Basque ─────────────
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Manager - Integrations',
        'Entreprise': 'SD Worx', 'Source': 'careers.sdworx.com',
        'Lien': 'https://careers.sdworx.com/jobs/8266963-product-manager-integrations',
        'Contrat': 'CDI', 'Localisation': 'Multi-site EU dont Bayonne (bureau éligible explicite)', 'Remote': 'Non précisé (poste office-eligible multi-site)',
        'Fit / Notes': "PM sur l'écosystème d'API/intégrations d'un éditeur HR/payroll européen (dont Workday), rôle produit plateforme technique.",
        'CV à envoyer': 'Resume_GaetanFRANCOIS_PM_Platform_EN.pdf', 'Date trouvée': AUJOURDHUI,
        'Onglet': 'Pays Basque',
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Chef de Projet Sage X3 H/F',
        'Entreprise': 'Silkhom (client anonymisé, groupe multi-activités)', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83194074.html',
        'Contrat': 'CDI', 'Localisation': 'Bayonne', 'Remote': 'Hybride (1j télétravail/semaine)',
        'Salaire / TJM': '40-60K€ + prime annuelle jusqu\'à 1,5 mois',
        'Fit / Notes': "Pilotage déploiement ERP Sage X3 : paramétrage, reprise de données, mise en production, formation utilisateurs. Transpose l'expérience SAP/ERP de Gaëtan même si l'outil diffère.",
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
        'Onglet': 'Pays Basque',
    },
    {
        'Priorité': '⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Responsable Projet Aéronautique - Pays Basque H/F',
        'Entreprise': 'Crit (client anonymisé, secteur aéronautique)', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83183892.html',
        'Contrat': 'CDI', 'Localisation': 'Bayonne', 'Remote': 'Non précisé (probablement présentiel, poste industriel)',
        'Fit / Notes': "Chef de projet généraliste (transfert de projets, ROI, pilotage multi-équipes) mais entièrement industriel/manufacturing, aucun volet IT/SI. Fit marginal, nécessiterait une LM qui assume la bascule hors SIRH.",
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
        'Onglet': 'Pays Basque',
    },

    # ───────────── NoRemote ─────────────
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Founding Customer Success Manager',
        'Entreprise': 'Gotam', 'Source': 'mission-freelances.fr',
        'Lien': 'https://www.mission-freelances.fr/missions/founding-customer-success-manager-teletravail-c4e12456/',
        'Contrat': 'Freelance', 'Localisation': 'Télétravail (mention ambiguë)', 'Remote': 'Hybride (la fiche mentionne un "environnement hybride" malgré le champ localité en télétravail)',
        'Fit / Notes': "Lancement marché italien, correspond à la cible Founding CS 0→1 mais le remote est ambigu (marqueur hybride l'emporte sur la mention télétravail, à clarifier avant candidature).",
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Responsable de la Satisfaction Clients',
        'Entreprise': 'Docaposte', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/81110792.html',
        'Contrat': 'CDI', 'Localisation': 'Ivry-sur-Seine', 'Remote': 'Hybride (2j/sem)',
        'Fit / Notes': 'CSM/satisfaction client.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Consultant Implémentation SaaS',
        'Entreprise': 'iAdvize', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83184244.html',
        'Contrat': 'CDI', 'Localisation': 'Nantes', 'Remote': 'Hybride (2j/sem après onboarding)',
        'Salaire / TJM': '40K€',
        'Fit / Notes': 'Implementation Consultant SaaS.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Global Account Manager',
        'Entreprise': 'Malt', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83184948.html',
        'Contrat': 'CDI', 'Localisation': 'Paris', 'Remote': 'Hybride',
        'Fit / Notes': 'Account management, plateforme freelance où Gaëtan a lui-même un profil actif.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Chef de Projet Adoption IA Agentique',
        'Entreprise': 'Seequalis', 'Source': 'HelloWork',
        'Lien': 'https://www.hellowork.com/fr-fr/emplois/83216609.html',
        'Contrat': 'CDI', 'Localisation': 'Courbevoie', 'Remote': 'Hybride',
        'Fit / Notes': 'PM + adoption IA agentique, bon croisement.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Chef de Projet IT RH / Consultant - Transport Aérien',
        'Entreprise': 'Infotel Conseil (client transport aérien)', 'Source': 'free-work.com',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/assistant-chef-de-projet/chef-de-projet-amoa-consultant-transport-aerien',
        'Contrat': 'Freelance', 'Localisation': 'Roissy-en-France', 'Remote': 'Télétravail partiel (présentiel 3j/sem)',
        'Salaire / TJM': '400-550€/j',
        'Fit / Notes': 'Chef de projet IT RH.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'CP / Business Analyst - SAP SuccessFactors (Employee Central)',
        'Entreprise': 'Infotel Conseil (même client transport aérien)', 'Source': 'free-work.com',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/business-analyst/business-analyst-sap-success-factor',
        'Contrat': 'Freelance', 'Localisation': 'Roissy-en-France', 'Remote': 'Télétravail partiel',
        'Salaire / TJM': '400-600€/j, 6 mois renouvelable',
        'Fit / Notes': 'SAP SuccessFactors Employee Central, cœur de cible.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Consultant / Expert IA - Accompagnement & Implémentation Métier',
        'Entreprise': 'Zenith RH', 'Source': 'free-work.com',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/assistant-chef-de-projet/copy-of-pmo-transverse-chef-de-projet-senior-pilotage-si',
        'Contrat': 'Freelance', 'Localisation': 'Paris', 'Remote': 'Télétravail partiel',
        'Durée mission': '6 mois',
        'Fit / Notes': "Conduite du changement IA.",
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Product Owner Confirmé H/F',
        'Entreprise': 'Consort Group (client Centre Régional Football Aquitain)', 'Source': 'free-work.com',
        'Lien': 'https://www.free-work.com/fr/tech-it/job-mission/concepteur-de-base-de-donnee/concepteur-technico-fonctionnel-h-f-1',
        'Contrat': 'CDI', 'Localisation': 'Gironde (33)', 'Remote': 'Télétravail 1-2j/sem',
        'Fit / Notes': 'Product Owner confirmé.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_PM_FR.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Directeur de projets SAP (Paris, Lyon ou Lille)',
        'Entreprise': 'delaware', 'Source': 'carriere.delaware.pro',
        'Lien': 'https://carriere.delaware.pro/jobs/1919274-directeur-de-projets-sap-paris-lyon-ou-lille-h-f-x',
        'Contrat': 'CDI', 'Localisation': 'Paris/Lyon/Lille', 'Remote': 'Hybride',
        'Fit / Notes': 'Chef de projet SAP S/4HANA, bon fit gestion de projet.',
        'CV à envoyer': 'CV_GaetanFRANCOIS_CSM.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Team Leader Manager SAP',
        'Entreprise': 'delaware', 'Source': 'carriere.delaware.pro',
        'Lien': 'https://carriere.delaware.pro/jobs/2019858-team-leader-manager-sap-h-f-x',
        'Contrat': 'CDI', 'Localisation': 'Non précisée', 'Remote': 'Hybride',
        'Fit / Notes': "Encadrement d'équipe SAP.",
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH2.pdf', 'Date trouvée': AUJOURDHUI,
    },
    {
        'Priorité': '⭐⭐⭐', 'Statut': AUJOURDHUI, 'Poste': 'Lead Data & AI',
        'Entreprise': 'delaware', 'Source': 'carriere.delaware.pro',
        'Lien': 'https://carriere.delaware.pro/jobs/7522818-lead-data-ai-h-f-x',
        'Contrat': 'CDI', 'Localisation': 'Non précisée', 'Remote': 'Hybride',
        'Fit / Notes': 'Croisement Data/IA + SAP, différenciant avec le profil formateur IA.',
        'CV à envoyer': 'Resume_GaetanFRANCOIS_SIRH2.pdf', 'Date trouvée': AUJOURDHUI,
    },
]

if __name__ == '__main__':
    ajouter_offres(offres, verbose=True)
